export enum MarginErrorMsgs {
    'DUPLICATED_MARGIN_BRAND' = 'MARGIN_MANAGE.ERROR_MSG.DUPLICATED_MARGIN_BRAND',
    'DUPLICATED_MARGIN_ARTICLE_GROUP' = 'MARGIN_MANAGE.ERROR_MSG.DUPLICATED_MARGIN_ARTICLE_GROUP',
    'INVALID_INDEX_ARTICLE_GROUP' = 'MARGIN_MANAGE.ERROR_MSG.INVALID_INDEX_ARTICLE_GROUP'
};

export const MARGIN_VALUES = [1, 2, 3, 4, 5, 6, 7];