# ************************************************************************
# This is the CZ configuration of Admin application for pre-prod mode.
# 
# Required Common configuration:
# - Application common configuration -
# - Country Code - 
# - Database -
# - Elasticsearch - 
# - ERP - 
# - Caching - 
# - Mail service - 
# - Thread Executor Pool - 
# - Authorization -
# - MDM for creating DVSE user -
# - Media Server -
# - No Proxy For Serbia and CZ we are in Azure -
# - Logging - 
# - Java Melody Monitoring - 
# - Actuator Healthcheck - 
# - Liquibase - 
#
# ************************************************************************
spring.profiles.include: 
  sagadmin,
  wint-pre,
  mdm-prod,
  mail-wt-prod,
  elasticsearch-pre,
  db-pre,
  executor-pool-pre-sb,
  no-liquibase,
  logging-default,
  actuator,
  cache-pre,
  country-sb,
  no-proxy,
  media-server,
  javamelody,
  auth-endpoint-sb-pre

spring.banner.location: classpath:banner/banner_sb.txt
