spring.profiles: analytics-prod-cloud
external:
  webservice:
    analytics:
      url:
        receive: https://analytics.sag-ag.cloud/connectanalytics/receive
sag:
  rest:
    analytics:
      timeout:
        connection-request-timeout: 125000
        connect-timeout: 125000
        read-timeout: 125000
    maxConnPerRoute: 150
    maxConnTotal: 300
