spring.profiles: analytics-prod
external:
  webservice:
    analytics:
      url:
        receive: http://analytics-service-app.apps.sag.services/connectanalytics/receive
        # receive: https://analytics-service-app.apps.sag.services/connectanalytics/receive

sag:
  rest:
    analytics:
      timeout:
        connection-request-timeout: 125000
        connect-timeout: 125000
        read-timeout: 125000
    maxConnPerRoute: 150
    maxConnTotal: 300
