# ************************************************************************
# This is the CH configuration of RESTful application for local mode.
# 
# Required Common configuration:
# - ERP - 
# - Database - 
# - Elasticsearch - 
# - Caching - 
# - Country Code - 
# - Liquibase - 
# - HaynesPro -
# - Media Server - 
# - GTMotive - 
# - Price File Location - 
# - OATS(replace Olyslager) - 
# - Thule - 
# - MDM for DVSE service - 
#
# ************************************************************************
spring.profiles.include:
  ax-pre-cloud,
  db-ch,
  elasticsearch-dev,
  cache-dev,
  country-ch,
  liquibase-ch-dev,
  hp-dev,
  media-server,
  gtmotive-ch-pre,
  price-file-ch,
  oates-pre-ch,
  thule-dev,
  mdm-pre

spring.banner.location: classpath:banner/banner_ch.txt

---
#Authorization server to manage and verify tokens
sag:
  security:
    auth:
      # host: http://localhost:9002
      host: https://ch.bbv-demo.ch/auth-server
      tokenUrl: /oauth/token
      checkTokenUrl: /oauth/check_token
      clientId: eshop-web
      clientSecret: eshop-web-yztAhGpFW

license:
  vin:
    minimumOrder: 0
