# ************************************************************************
# This is the Autonet configuration of DVSE(SOAP) application for local mode.
# 
# Required Common configuration:
# - ERP - 
# - Database - 
# - Elasticsearch
# - Liquibase - 
# - Caching -
# - Country Code - 
# - MDM for DVSE service - 
#
# ************************************************************************
spring.profiles.include: 
  autonet-erp-pre, 
  db-autonet, 
  elasticsearch-dev2,
  no-liquibase, 
  cache-dev, 
  country-autonet,
  mdm-prod

spring.banner.location: classpath:banner/banner_autonet.txt
