-- #3846
ALTER VIEW [dbo].[V_BASKET_HISTORY] AS
SELECT DISTINCT 
    ROW_NUMBER() OVER (ORDER BY BH.ID) AS ID,
    BH.ID AS BASKET_HISTORY_ID, 
    BH.BASKET_NAME,
    BH.GRAND_TOTAL_EXCLUDE_VAT,
    BH.BASKET_JSON,
    BH.UPDATED_DATE,
    BH.ACTIVE,
    BH.ORGANISATION_ID AS ORG_ID,
    ORG.ORG_CODE AS ORG_CODE,
    ORG.SHORTNAME AS ORG_SHORT_NAME,
	(SELECT CASE 
		WHEN (ORG.NAME IS NULL OR ORG.NAME = '')
		THEN CU.FIRST_NAME
		ELSE ORG.NAME
		END) AS CUSTOMER_NAME,
    BH.CREATED_USER_ID,
    CU.FIRST_NAME AS CREATED_FIRST_NAME,
    CU.LAST_NAME AS CREATED_LAST_NAME,
    CONCAT(CU.FIRST_NAME, ' ', CU.LAST_NAME) AS CREATED_FULL_NAME,
    BH.SALES_USER_ID, 
    SU.FIRST_NAME AS SALES_FIRST_NAME,
    SU.LAST_NAME AS SALES_LAST_NAME,
    CONCAT(SU.FIRST_NAME, ' ', SU.LAST_NAME) AS SALES_FULL_NAME,
    BH.CUSTOMER_REF_TEXT
  FROM 
    BASKET_HISTORY BH
    JOIN ESHOP_USER CU ON CU.ID = BH.CREATED_USER_ID
    LEFT JOIN ESHOP_USER SU ON SU.ID = BH.SALES_USER_ID
    JOIN ORGANISATION ORG ON ORG.ID = BH.ORGANISATION_ID
  WHERE BH.ACTIVE = 1

GO
