export enum DiscountItemType {
    OFFER,
    ITEM,
}

export enum DiscountType {
    DISCOUNT_PERCENT,
    DISCOUNT_AMOUNT,
    DISCOUNT_PERCENT_WORK,
    DISCOUNT_AMOUNT_WORK,
    DISCOUNT_PERCENT_ARTICLES,
    DISCOUNT_AMOUNT_ARTICLES,
    ADDITION_PERCENT,
    ADDITION_AMOUNT,
    ADDITION_PERCENT_WORK,
    ADDITION_AMOUNT_WORK,
    ADDITION_PERCENT_ARTICLES,
    ADDITION_AMOUNT_ARTICLES,
    NONE
}