export enum OFFER_STATUS {
    OPEN = 'OPEN',
    MANUALLY_ORDERED = 'MANUALLY_ORDERED',
    ORDERED = 'ORDERED'
}

export enum OFFER_ITEM_TYPE {
    VENDOR_ARTICLE = 'VENDOR_ARTICLE',
    VENDOR_ARTICLE_WITHOUT_VEHICLE = 'VENDOR_ARTICLE_WITHOUT_VEHICLE',
    CLIENT_ARTICLE = 'CLIENT_ARTICLE',
    CLIENT_WORK = 'CLIENT_WORK',
    REMARK = 'REMARK',
    HAYNESPRO_PROVIDER_WORK = 'HAYNESPRO_PROVIDER_WORK'
}
