# ************************************************************************
# This is the AT country configuration of Admin application for local mode.
# 
# Required Common configuration:
# - ERP
# - Database
# - Elasticsearch
# - Liquibase
# - Caching
# - Country Code
# - Media Server
# - Authorization
#
# ************************************************************************
spring.profiles.include: 
  wint-dev,
  db-sb, 
  elasticsearch-dev2,
  no-liquibase, 
  cache-dev, 
  country-sb, 
  media-server,
  auth-endpoint-sb-dev,
  mdm-prod

# https://devops.datenkollektiv.de/banner.txt/index.html Banner Font: doom
spring.banner.location: classpath:banner/banner_sb.txt
