# ************************************************************************
# This is the CH configuration of Admin application for development mode.
# 
# Required Common configuration:
# - Application common configuration -
# - Country Code - 
# - Database -
# - Elasticsearch - 
# - ERP - 
# - Caching - 
# - Mail service - 
# - Thread Executor Pool - 
# - Authorization -
# - MDM for creating DVSE user -
# - Media Server -
# - Proxy -
# - Logging - 
# - Java Melody Monitoring - 
# - Actuator Healthcheck - 
# - Liquibase - 
#
# ************************************************************************
spring.profiles.include: 
  sagadmin, 
  ax-pre-cloud,
  mdm-prod,
  mail-dev,
  elasticsearch-dev,
  db-dev,
  executor-pool,
  no-liquibase,
  logging-dev,
  actuator,
  sba-client-ch-dev,
  cache-dev,
  country-ch,
  no-proxy,
  media-server,
  javamelody,
  auth-endpoint-ch-dev

spring.banner.location: classpath:banner/banner_ch.txt
