# ************************************************************************
# This is the Autonet configuration of OAuth2 application for local mode.
# 
# Required Common configuration:
# - ERP - 
# - Database - 
# - Elasticsearch - 
# - Liquibase - 
# - Caching - 
# - Country Code - 
#
# ************************************************************************
spring.profiles.include: 
  autonet-erp-pre, 
  db-autonet,
  elasticsearch-dev2,
  no-liquibase, 
  cache-dev, 
  country-autonet

spring.banner.location: classpath:banner/banner_autonet.txt
