# ************************************************************************
# This is the AT configuration of OAuth2 application for local mode.
# 
# Required Common configuration:
# - ERP - 
# - Database - 
# - Elasticsearch - 
# - Liquibase - 
# - Caching - 
# - Country Code - 
#
# ************************************************************************
spring.profiles.include: 
  ax-pre-cloud, 
  db-ax-cz, 
  elasticsearch-dev2,
  no-liquibase, 
  cache-dev, 
  country-ax-cz

spring.banner.location: classpath:banner/banner_axcz.txt