CREATE TABLE OAUTH_ACCESS_TOKEN (
  TOKEN_ID VARCHAR(256) DEFAULT NULL,
  TOKEN VARCHAR(MAX),
  AUTHENTICATION_ID VARCHAR(256) DEFAULT NULL,
  USER_NAME VARCHAR(256) DEFAULT NULL,
  CLIENT_ID VARCHAR(256) DEFAULT NULL,
  AUTHENTICATION VARCHAR(MAX),
  REFRESH_TOKEN VARCHAR(MAX) DEFAULT NULL,
  AFFILIATE VARCHAR(256) DEFAULT NULL
);

CREATE TABLE OAUTH_REFRESH_TOKEN (
  TOKEN_ID VARCHAR(256) DEFAULT NULL,
  TOKEN VARCHAR(MAX),
  AUTHENTICATION VARCHAR(MAX)
);
