# ************************************************************************
# This is the CZ configuration of OAuth2 application for Production mode.
# 
# Required Common configuration:
# - Application common configuration - 
# - ERP - 
# - Elasticsearch - 
# - Database - 
# - Thread Executor Pool - 
# - Liquibase - 
# - Logging - 
# - Actuator Healthcheck - 
# - Caching - 
# - Country Code - 
# - No Proxy For Serbia and CZ we are in Azure - 
# - Java Melody Monitoring -
#
# ************************************************************************
spring.profiles.include: 
  sagauth,
  ax-prod-cloud,
  elasticsearch-prod,
  db-prod,
  executor-pool-prod-cz,
  no-liquibase,
  logging-ax-cz-prod,
  actuator,
  cache-prod,
  country-ax-cz,
  no-proxy,
  javamelody

spring.banner.location: classpath:banner/banner_axcz.txt