-- #4178

INSERT INTO ESHOP_PERMISSION(PERMISSION, DESCRIPTION, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, PERMISSION_KEY)
VALUES('OCI', 'Permission to work with oci module', 1, GETDATE(), NULL, NULL, 'OCI');

INSERT INTO ESHOP_FUNCTION( FUNCTION_NAME, DESCRIPTION, RELATIVE_URL)
VALUES('OCI', 'OCI', '/oci**');

DECLARE @oci_perm_id INT = (SELECT ID FROM ESHOP_PERMISSION WHERE PERMISSION = 'OCI');
DECLARE @oci_func_id INT = (SELECT ID FROM ESHOP_FUNCTION WHERE FUNCTION_NAME = 'OCI');

INSERT INTO PERM_FUNCTION(PERM_ID, FUNCTION_ID) VALUES(@oci_perm_id, @oci_func_id);

ALTER TABLE EXTERNAL_USER ADD [LOCK_VIRTUAL_USER] varchar(20) null;

ALTER TABLE [dbo].[CUSTOMER_SETTINGS] ADD [SHOW_OCI_VAT] [bit] NOT NULL DEFAULT (0);

-- #2853
ALTER TABLE CUSTOMER_SETTINGS ADD HOME_BRANCH [varchar](50) NULL;

-- Init Home branch for Derendinger-Swizerland
-- DECLARE @dch_aff_id = (SELECT id FROM ORGANISATION where SHORTNAME='derendinger-ch');
-- UPDATE CUSTOMER_SETTINGS SET HOME_BRANCH='BE' WHERE ID IN (SELECT ORDER_SETTINGS_ID FROM ORGANISATION WHERE parent_id = @dch_aff_id);

-- Add orginal user id when create virtual user
ALTER TABLE [dbo].[ESHOP_USER] ADD [ORIGINAL_USER_ID] [BIGINT];

-- Insert setting for OCI
-- Be carefull, do not insert twice, check before run!
-- DECLARE @dch_affiliate_id INT = (SELECT ID FROM ORGANISATION WHERE SHORTNAME = 'derendinger-ch' AND ORGTYPE_ID = 2);
-- INSERT INTO ORGANISATION_SETTINGS(NAME, ORGANISATION_ID, SETTING_KEY, SETTING_VALUE) VALUES ('Derendinger-Switzerland', @dch_affiliate_id,	'oci_ewb_schema_type', 'Derendinger');
-- INSERT INTO ORGANISATION_SETTINGS(NAME, ORGANISATION_ID, SETTING_KEY, SETTING_VALUE) VALUES ('Derendinger-Switzerland', @dch_affiliate_id,	'oci_vendorid', '2003610');
-- INSERT INTO ORGANISATION_SETTINGS(NAME, ORGANISATION_ID, SETTING_KEY, SETTING_VALUE) VALUES ('Derendinger-Switzerland', @dch_affiliate_id,	'filiale', 'TBE');

ALTER VIEW [dbo].[V_ACTIVE_USER] AS --- ALTER ACTIVE USER PROFILE VIEW
-- for backoffice admin can not view on behalf admin and virtual users in management
SELECT
    U.ID,
    U.USERNAME,
    U.EMAIL,
    CONCAT(U.FIRST_NAME, ' ', U.LAST_NAME) AS FULL_NAME,
    U.PHONE,
    R.NAME AS ROLE_NAME,
    G.NAME AS GROUP_NAME,
    OG.ORGANISATION_ID AS ORG_ID,
    O.PARENT_ID AS ORG_PARENT_ID,
    O.ORG_CODE AS ORG_CODE,
    OP.SHORTNAME AS AFFILIATE,
    O.NAME AS ORG_NAME
FROM
    ESHOP_USER U
    JOIN GROUP_USER GU ON U.ID = GU.USER_ID
    JOIN ESHOP_GROUP G ON GU.GROUP_ID = G.ID
    JOIN GROUP_ROLE GR ON GR.GROUP_ID = G.ID
    JOIN ESHOP_ROLE R  ON GR.ROLE_ID = R.ID
    JOIN ORGANISATION_GROUP OG ON G.ID = OG.GROUP_ID
    JOIN ORGANISATION O ON O.ID = OG.ORGANISATION_ID
    JOIN LOGIN L ON L.USER_ID = U.ID
    JOIN ORGANISATION OP ON O.PARENT_ID = OP.ID
WHERE L.IS_USER_ACTIVE = 1 AND (U.TYPE IS NULL OR (U.TYPE <> 'VIRTUAL_DMS' AND U.TYPE <> 'VIRTUAL_OCI' AND U.TYPE <> 'ON_BEHALF_ADMIN'))
GO
