spring.profiles: mail-prod
# Mail Server properties
spring:
  mail:
    host: smtp.sag-ag.ch
    port: 25
    # username: swissitbridge.test.1210@gmail.com
    # password: swissitbridge
    protocol: smtp
    # tls: true
    # properties.mail.smtp:
    #  auth: true
    #  starttls.enable: true
    #  ssl.trust: smtp.gmail.com
    properties:
      smtp:
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
        starttls.enable: true