
package com.sagag.services.stakis.erp.wsdl.cis;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TMCustomerIdentificationProSvcSoap", targetNamespace = "DVSE.WebApp.CISService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TMCustomerIdentificationProSvcSoap {


    /**
     * 
     * @param password
     * @param clientId
     * @param customerId
     * @param language
     * @param username
     * @return
     *     returns com.sagag.services.stakis.erp.wsdl.cis.OutSession
     */
    @WebMethod(operationName = "GetSession", action = "DVSE.WebApp.CISService/GetSession")
    @WebResult(name = "GetSessionResult", targetNamespace = "DVSE.WebApp.CISService")
    @RequestWrapper(localName = "GetSession", targetNamespace = "DVSE.WebApp.CISService", className = "com.sagag.services.stakis.erp.wsdl.cis.GetSessionRequestBody")
    @ResponseWrapper(localName = "GetSessionResponse", targetNamespace = "DVSE.WebApp.CISService", className = "com.sagag.services.stakis.erp.wsdl.cis.GetSessionResponseBody")
    public OutSession getSession(
        @WebParam(name = "customerId", targetNamespace = "DVSE.WebApp.CISService")
        String customerId,
        @WebParam(name = "username", targetNamespace = "DVSE.WebApp.CISService")
        String username,
        @WebParam(name = "password", targetNamespace = "DVSE.WebApp.CISService")
        String password,
        @WebParam(name = "clientId", targetNamespace = "DVSE.WebApp.CISService")
        Integer clientId,
        @WebParam(name = "language", targetNamespace = "DVSE.WebApp.CISService")
        String language);

    /**
     * 
     * @param query
     * @param pageSize
     * @param language
     * @param sessionId
     * @param pageId
     * @param queryTypeId
     * @return
     *     returns com.sagag.services.stakis.erp.wsdl.cis.OutCustomers
     */
    @WebMethod(operationName = "GetCustomers", action = "DVSE.WebApp.CISService/GetCustomers")
    @WebResult(name = "GetCustomersResult", targetNamespace = "DVSE.WebApp.CISService")
    @RequestWrapper(localName = "GetCustomers", targetNamespace = "DVSE.WebApp.CISService", className = "com.sagag.services.stakis.erp.wsdl.cis.GetCustomersRequestBody")
    @ResponseWrapper(localName = "GetCustomersResponse", targetNamespace = "DVSE.WebApp.CISService", className = "com.sagag.services.stakis.erp.wsdl.cis.GetCustomersResponseBody")
    public OutCustomers getCustomers(
        @WebParam(name = "sessionId", targetNamespace = "DVSE.WebApp.CISService")
        String sessionId,
        @WebParam(name = "query", targetNamespace = "DVSE.WebApp.CISService")
        String query,
        @WebParam(name = "queryTypeId", targetNamespace = "DVSE.WebApp.CISService")
        Integer queryTypeId,
        @WebParam(name = "language", targetNamespace = "DVSE.WebApp.CISService")
        String language,
        @WebParam(name = "pageSize", targetNamespace = "DVSE.WebApp.CISService")
        Integer pageSize,
        @WebParam(name = "pageId", targetNamespace = "DVSE.WebApp.CISService")
        Integer pageId);

    /**
     * 
     * @param customerId
     * @param language
     * @param sessionId
     * @return
     *     returns com.sagag.services.stakis.erp.wsdl.cis.OutCustomer
     */
    @WebMethod(operationName = "GetCustomer", action = "DVSE.WebApp.CISService/GetCustomer")
    @WebResult(name = "GetCustomerResult", targetNamespace = "DVSE.WebApp.CISService")
    @RequestWrapper(localName = "GetCustomer", targetNamespace = "DVSE.WebApp.CISService", className = "com.sagag.services.stakis.erp.wsdl.cis.GetCustomerRequestBody")
    @ResponseWrapper(localName = "GetCustomerResponse", targetNamespace = "DVSE.WebApp.CISService", className = "com.sagag.services.stakis.erp.wsdl.cis.GetCustomerResponseBody")
    public OutCustomer getCustomer(
        @WebParam(name = "sessionId", targetNamespace = "DVSE.WebApp.CISService")
        String sessionId,
        @WebParam(name = "customerId", targetNamespace = "DVSE.WebApp.CISService")
        String customerId,
        @WebParam(name = "language", targetNamespace = "DVSE.WebApp.CISService")
        String language);

    /**
     * 
     * @param customerId
     * @param language
     * @param sessionId
     * @return
     *     returns com.sagag.services.stakis.erp.wsdl.cis.OutVoucherTypes
     */
    @WebMethod(operationName = "GetVoucherTypes", action = "DVSE.WebApp.CISService/GetVoucherTypes")
    @WebResult(name = "GetVoucherTypesResult", targetNamespace = "DVSE.WebApp.CISService")
    @RequestWrapper(localName = "GetVoucherTypes", targetNamespace = "DVSE.WebApp.CISService", className = "com.sagag.services.stakis.erp.wsdl.cis.GetVoucherTypesRequestBody")
    @ResponseWrapper(localName = "GetVoucherTypesResponse", targetNamespace = "DVSE.WebApp.CISService", className = "com.sagag.services.stakis.erp.wsdl.cis.GetVoucherTypesResponseBody")
    public OutVoucherTypes getVoucherTypes(
        @WebParam(name = "sessionId", targetNamespace = "DVSE.WebApp.CISService")
        String sessionId,
        @WebParam(name = "customerId", targetNamespace = "DVSE.WebApp.CISService")
        String customerId,
        @WebParam(name = "language", targetNamespace = "DVSE.WebApp.CISService")
        String language);

    /**
     * 
     * @param filter
     * @param voucherTypeId
     * @param customerId
     * @param pageSize
     * @param language
     * @param sessionId
     * @param pageId
     * @return
     *     returns com.sagag.services.stakis.erp.wsdl.cis.OutVouchers
     */
    @WebMethod(operationName = "GetVouchers", action = "DVSE.WebApp.CISService/GetVouchers")
    @WebResult(name = "GetVouchersResult", targetNamespace = "DVSE.WebApp.CISService")
    @RequestWrapper(localName = "GetVouchers", targetNamespace = "DVSE.WebApp.CISService", className = "com.sagag.services.stakis.erp.wsdl.cis.GetVouchersRequestBody")
    @ResponseWrapper(localName = "GetVouchersResponse", targetNamespace = "DVSE.WebApp.CISService", className = "com.sagag.services.stakis.erp.wsdl.cis.GetVouchersResponseBody")
    public OutVouchers getVouchers(
        @WebParam(name = "sessionId", targetNamespace = "DVSE.WebApp.CISService")
        String sessionId,
        @WebParam(name = "customerId", targetNamespace = "DVSE.WebApp.CISService")
        String customerId,
        @WebParam(name = "filter", targetNamespace = "DVSE.WebApp.CISService")
        Filter filter,
        @WebParam(name = "voucherTypeId", targetNamespace = "DVSE.WebApp.CISService")
        Integer voucherTypeId,
        @WebParam(name = "language", targetNamespace = "DVSE.WebApp.CISService")
        String language,
        @WebParam(name = "pageSize", targetNamespace = "DVSE.WebApp.CISService")
        Integer pageSize,
        @WebParam(name = "pageId", targetNamespace = "DVSE.WebApp.CISService")
        Integer pageId);

    /**
     * 
     * @param voucherTypeId
     * @param voucherId
     * @param customerId
     * @param pageSize
     * @param language
     * @param sessionId
     * @param pageId
     * @return
     *     returns com.sagag.services.stakis.erp.wsdl.cis.OutVoucherDetails
     */
    @WebMethod(operationName = "GetVoucherDetails", action = "DVSE.WebApp.CISService/GetVoucherDetails")
    @WebResult(name = "GetVoucherDetailsResult", targetNamespace = "DVSE.WebApp.CISService")
    @RequestWrapper(localName = "GetVoucherDetails", targetNamespace = "DVSE.WebApp.CISService", className = "com.sagag.services.stakis.erp.wsdl.cis.GetVoucherDetailsRequestBody")
    @ResponseWrapper(localName = "GetVoucherDetailsResponse", targetNamespace = "DVSE.WebApp.CISService", className = "com.sagag.services.stakis.erp.wsdl.cis.GetVoucherDetailsResponseBody")
    public OutVoucherDetails getVoucherDetails(
        @WebParam(name = "sessionId", targetNamespace = "DVSE.WebApp.CISService")
        String sessionId,
        @WebParam(name = "customerId", targetNamespace = "DVSE.WebApp.CISService")
        String customerId,
        @WebParam(name = "voucherId", targetNamespace = "DVSE.WebApp.CISService")
        String voucherId,
        @WebParam(name = "voucherTypeId", targetNamespace = "DVSE.WebApp.CISService")
        Integer voucherTypeId,
        @WebParam(name = "language", targetNamespace = "DVSE.WebApp.CISService")
        String language,
        @WebParam(name = "pageSize", targetNamespace = "DVSE.WebApp.CISService")
        Integer pageSize,
        @WebParam(name = "pageId", targetNamespace = "DVSE.WebApp.CISService")
        Integer pageId);

    /**
     * 
     * @param customerId
     * @param language
     * @param sessionId
     * @return
     *     returns com.sagag.services.stakis.erp.wsdl.cis.OutReturnItemOptions
     */
    @WebMethod(operationName = "GetReturnItemOptions", action = "DVSE.WebApp.CISService/GetReturnItemOptions")
    @WebResult(name = "GetReturnItemOptionsResult", targetNamespace = "DVSE.WebApp.CISService")
    @RequestWrapper(localName = "GetReturnItemOptions", targetNamespace = "DVSE.WebApp.CISService", className = "com.sagag.services.stakis.erp.wsdl.cis.GetReturnItemOptionsRequestBody")
    @ResponseWrapper(localName = "GetReturnItemOptionsResponse", targetNamespace = "DVSE.WebApp.CISService", className = "com.sagag.services.stakis.erp.wsdl.cis.GetReturnItemOptionsResponseBody")
    public OutReturnItemOptions getReturnItemOptions(
        @WebParam(name = "sessionId", targetNamespace = "DVSE.WebApp.CISService")
        String sessionId,
        @WebParam(name = "customerId", targetNamespace = "DVSE.WebApp.CISService")
        String customerId,
        @WebParam(name = "language", targetNamespace = "DVSE.WebApp.CISService")
        String language);

    /**
     * 
     * @param returnableItems
     * @param customerId
     * @param language
     * @param sessionId
     * @return
     *     returns com.sagag.services.stakis.erp.wsdl.cis.BaseResponse
     */
    @WebMethod(operationName = "ReturnItems", action = "DVSE.WebApp.CISService/ReturnItems")
    @WebResult(name = "ReturnItemsResult", targetNamespace = "DVSE.WebApp.CISService")
    @RequestWrapper(localName = "ReturnItems", targetNamespace = "DVSE.WebApp.CISService", className = "com.sagag.services.stakis.erp.wsdl.cis.ReturnItemsRequestBody")
    @ResponseWrapper(localName = "ReturnItemsResponse", targetNamespace = "DVSE.WebApp.CISService", className = "com.sagag.services.stakis.erp.wsdl.cis.ReturnItemsResponseBody")
    public BaseResponse returnItems(
        @WebParam(name = "sessionId", targetNamespace = "DVSE.WebApp.CISService")
        String sessionId,
        @WebParam(name = "customerId", targetNamespace = "DVSE.WebApp.CISService")
        String customerId,
        @WebParam(name = "language", targetNamespace = "DVSE.WebApp.CISService")
        String language,
        @WebParam(name = "returnableItems", targetNamespace = "DVSE.WebApp.CISService")
        ArrayOfReturnItem returnableItems);

    /**
     * 
     * @param voucherId
     * @param language
     * @param sessionId
     * @return
     *     returns com.sagag.services.stakis.erp.wsdl.cis.BaseResponse
     */
    @WebMethod(operationName = "ResetVoucherItemsCanReturnProperty", action = "DVSE.WebApp.CISService/ResetVoucherItemsCanReturnProperty")
    @WebResult(name = "ResetVoucherItemsCanReturnPropertyResult", targetNamespace = "DVSE.WebApp.CISService")
    @RequestWrapper(localName = "ResetVoucherItemsCanReturnProperty", targetNamespace = "DVSE.WebApp.CISService", className = "com.sagag.services.stakis.erp.wsdl.cis.ResetVoucherItemsCanReturnPropertyRequestBody")
    @ResponseWrapper(localName = "ResetVoucherItemsCanReturnPropertyResponse", targetNamespace = "DVSE.WebApp.CISService", className = "com.sagag.services.stakis.erp.wsdl.cis.ResetVoucherItemsCanReturnPropertyResponseBody")
    public BaseResponse resetVoucherItemsCanReturnProperty(
        @WebParam(name = "sessionId", targetNamespace = "DVSE.WebApp.CISService")
        String sessionId,
        @WebParam(name = "voucherId", targetNamespace = "DVSE.WebApp.CISService")
        String voucherId,
        @WebParam(name = "language", targetNamespace = "DVSE.WebApp.CISService")
        String language);

    /**
     * 
     * @param customerId
     * @param pageSize
     * @param language
     * @param sessionId
     * @param pageId
     * @param connectionType
     * @param parentId
     * @return
     *     returns com.sagag.services.stakis.erp.wsdl.cis.OutVouchers
     */
    @WebMethod(operationName = "GetConnectedVouchers", action = "DVSE.WebApp.CISService/GetConnectedVouchers")
    @WebResult(name = "GetConnectedVouchersResult", targetNamespace = "DVSE.WebApp.CISService")
    @RequestWrapper(localName = "GetConnectedVouchers", targetNamespace = "DVSE.WebApp.CISService", className = "com.sagag.services.stakis.erp.wsdl.cis.GetConnectedVouchersRequestBody")
    @ResponseWrapper(localName = "GetConnectedVouchersResponse", targetNamespace = "DVSE.WebApp.CISService", className = "com.sagag.services.stakis.erp.wsdl.cis.GetConnectedVouchersResponseBody")
    public OutVouchers getConnectedVouchers(
        @WebParam(name = "sessionId", targetNamespace = "DVSE.WebApp.CISService")
        String sessionId,
        @WebParam(name = "customerId", targetNamespace = "DVSE.WebApp.CISService")
        String customerId,
        @WebParam(name = "parentId", targetNamespace = "DVSE.WebApp.CISService")
        String parentId,
        @WebParam(name = "connectionType", targetNamespace = "DVSE.WebApp.CISService")
        Integer connectionType,
        @WebParam(name = "language", targetNamespace = "DVSE.WebApp.CISService")
        String language,
        @WebParam(name = "pageSize", targetNamespace = "DVSE.WebApp.CISService")
        Integer pageSize,
        @WebParam(name = "pageId", targetNamespace = "DVSE.WebApp.CISService")
        Integer pageId);

    /**
     * 
     * @param customerId
     * @param language
     * @param sessionId
     * @return
     *     returns com.sagag.services.stakis.erp.wsdl.cis.OutQueryTypes
     */
    @WebMethod(operationName = "GetQueryTypesCustomer", action = "DVSE.WebApp.CISService/GetQueryTypesCustomer")
    @WebResult(name = "GetQueryTypesCustomerResult", targetNamespace = "DVSE.WebApp.CISService")
    @RequestWrapper(localName = "GetQueryTypesCustomer", targetNamespace = "DVSE.WebApp.CISService", className = "com.sagag.services.stakis.erp.wsdl.cis.GetQueryTypesCustomerRequestBody")
    @ResponseWrapper(localName = "GetQueryTypesCustomerResponse", targetNamespace = "DVSE.WebApp.CISService", className = "com.sagag.services.stakis.erp.wsdl.cis.GetQueryTypesCustomerResponseBody")
    public OutQueryTypes getQueryTypesCustomer(
        @WebParam(name = "sessionId", targetNamespace = "DVSE.WebApp.CISService")
        String sessionId,
        @WebParam(name = "customerId", targetNamespace = "DVSE.WebApp.CISService")
        String customerId,
        @WebParam(name = "language", targetNamespace = "DVSE.WebApp.CISService")
        String language);

    /**
     * 
     * @param customerId
     * @param language
     * @param sessionId
     * @return
     *     returns com.sagag.services.stakis.erp.wsdl.cis.OutQueryTypes
     */
    @WebMethod(operationName = "GetQueryTypesVoucher", action = "DVSE.WebApp.CISService/GetQueryTypesVoucher")
    @WebResult(name = "GetQueryTypesVoucherResult", targetNamespace = "DVSE.WebApp.CISService")
    @RequestWrapper(localName = "GetQueryTypesVoucher", targetNamespace = "DVSE.WebApp.CISService", className = "com.sagag.services.stakis.erp.wsdl.cis.GetQueryTypesVoucherRequestBody")
    @ResponseWrapper(localName = "GetQueryTypesVoucherResponse", targetNamespace = "DVSE.WebApp.CISService", className = "com.sagag.services.stakis.erp.wsdl.cis.GetQueryTypesVoucherResponseBody")
    public OutQueryTypes getQueryTypesVoucher(
        @WebParam(name = "sessionId", targetNamespace = "DVSE.WebApp.CISService")
        String sessionId,
        @WebParam(name = "customerId", targetNamespace = "DVSE.WebApp.CISService")
        String customerId,
        @WebParam(name = "language", targetNamespace = "DVSE.WebApp.CISService")
        String language);

    /**
     * 
     * @param filter
     * @param customerId
     * @param pageSize
     * @param language
     * @param sessionId
     * @param pageId
     * @return
     *     returns com.sagag.services.stakis.erp.wsdl.cis.OutInvoices
     */
    @WebMethod(operationName = "GetInvoices", action = "DVSE.WebApp.CISService/GetInvoices")
    @WebResult(name = "GetInvoicesResult", targetNamespace = "DVSE.WebApp.CISService")
    @RequestWrapper(localName = "GetInvoices", targetNamespace = "DVSE.WebApp.CISService", className = "com.sagag.services.stakis.erp.wsdl.cis.GetInvoicesRequestBody")
    @ResponseWrapper(localName = "GetInvoicesResponse", targetNamespace = "DVSE.WebApp.CISService", className = "com.sagag.services.stakis.erp.wsdl.cis.GetInvoicesResponseBody")
    public OutInvoices getInvoices(
        @WebParam(name = "sessionId", targetNamespace = "DVSE.WebApp.CISService")
        String sessionId,
        @WebParam(name = "customerId", targetNamespace = "DVSE.WebApp.CISService")
        String customerId,
        @WebParam(name = "language", targetNamespace = "DVSE.WebApp.CISService")
        String language,
        @WebParam(name = "filter", targetNamespace = "DVSE.WebApp.CISService")
        Filter filter,
        @WebParam(name = "pageSize", targetNamespace = "DVSE.WebApp.CISService")
        Integer pageSize,
        @WebParam(name = "pageId", targetNamespace = "DVSE.WebApp.CISService")
        Integer pageId);

    /**
     * 
     * @param customerId
     * @param language
     * @param sessionId
     * @return
     *     returns com.sagag.services.stakis.erp.wsdl.cis.OutSalesInformation
     */
    @WebMethod(operationName = "GetSalesInformation", action = "DVSE.WebApp.CISService/GetSalesInformation")
    @WebResult(name = "GetSalesInformationResult", targetNamespace = "DVSE.WebApp.CISService")
    @RequestWrapper(localName = "GetSalesInformation", targetNamespace = "DVSE.WebApp.CISService", className = "com.sagag.services.stakis.erp.wsdl.cis.GetSalesInformationRequestBody")
    @ResponseWrapper(localName = "GetSalesInformationResponse", targetNamespace = "DVSE.WebApp.CISService", className = "com.sagag.services.stakis.erp.wsdl.cis.GetSalesInformationResponseBody")
    public OutSalesInformation getSalesInformation(
        @WebParam(name = "sessionId", targetNamespace = "DVSE.WebApp.CISService")
        String sessionId,
        @WebParam(name = "customerId", targetNamespace = "DVSE.WebApp.CISService")
        String customerId,
        @WebParam(name = "language", targetNamespace = "DVSE.WebApp.CISService")
        String language);

    /**
     * 
     * @param customerId
     * @param dateTo
     * @param language
     * @param sessionId
     * @param dateFrom
     * @return
     *     returns com.sagag.services.stakis.erp.wsdl.cis.OutSales
     */
    @WebMethod(operationName = "GetSales", action = "DVSE.WebApp.CISService/GetSales")
    @WebResult(name = "GetSalesResult", targetNamespace = "DVSE.WebApp.CISService")
    @RequestWrapper(localName = "GetSales", targetNamespace = "DVSE.WebApp.CISService", className = "com.sagag.services.stakis.erp.wsdl.cis.GetSalesRequestBody")
    @ResponseWrapper(localName = "GetSalesResponse", targetNamespace = "DVSE.WebApp.CISService", className = "com.sagag.services.stakis.erp.wsdl.cis.GetSalesResponseBody")
    public OutSales getSales(
        @WebParam(name = "sessionId", targetNamespace = "DVSE.WebApp.CISService")
        String sessionId,
        @WebParam(name = "customerId", targetNamespace = "DVSE.WebApp.CISService")
        String customerId,
        @WebParam(name = "language", targetNamespace = "DVSE.WebApp.CISService")
        String language,
        @WebParam(name = "dateFrom", targetNamespace = "DVSE.WebApp.CISService")
        String dateFrom,
        @WebParam(name = "dateTo", targetNamespace = "DVSE.WebApp.CISService")
        String dateTo);

    /**
     * 
     * @param customerId
     * @param language
     * @param sessionId
     * @return
     *     returns com.sagag.services.stakis.erp.wsdl.cis.ArrayOfString
     */
    @WebMethod(operationName = "GetEnabledFunctions", action = "DVSE.WebApp.CISService/GetEnabledFunctions")
    @WebResult(name = "GetEnabledFunctionsResult", targetNamespace = "DVSE.WebApp.CISService")
    @RequestWrapper(localName = "GetEnabledFunctions", targetNamespace = "DVSE.WebApp.CISService", className = "com.sagag.services.stakis.erp.wsdl.cis.GetEnabledFunctionsRequestBody")
    @ResponseWrapper(localName = "GetEnabledFunctionsResponse", targetNamespace = "DVSE.WebApp.CISService", className = "com.sagag.services.stakis.erp.wsdl.cis.GetEnabledFunctionsResponseBody")
    public ArrayOfString getEnabledFunctions(
        @WebParam(name = "sessionId", targetNamespace = "DVSE.WebApp.CISService")
        String sessionId,
        @WebParam(name = "customerId", targetNamespace = "DVSE.WebApp.CISService")
        String customerId,
        @WebParam(name = "language", targetNamespace = "DVSE.WebApp.CISService")
        String language);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetVersion", action = "DVSE.WebApp.CISService/GetVersion")
    @WebResult(name = "GetVersionResult", targetNamespace = "DVSE.WebApp.CISService")
    @RequestWrapper(localName = "GetVersion", targetNamespace = "DVSE.WebApp.CISService", className = "com.sagag.services.stakis.erp.wsdl.cis.GetVersionRequestBody")
    @ResponseWrapper(localName = "GetVersionResponse", targetNamespace = "DVSE.WebApp.CISService", className = "com.sagag.services.stakis.erp.wsdl.cis.GetVersionResponseBody")
    public String getVersion();

}
