export class ErpCustomer {
    id: number;
    nr: number;
    companyId: number;
    shortName: string;
    companyName: string;
    lastName: string;
    name: string;
    active: boolean;
    vatNr: string;
    comment: string;
    languageId: number;
    language: string;
    organisationId: number;
    organisationShort: string;
    addressSalutation: string;
    statusShort: string;
    letterSalutation: string;
    freeDeliveryEndDate: any;
    currencyId: number;
    currency: string;
    oepUvpPrint: boolean;
    sendMethod: number;
    showDiscount: boolean;
    showNetPrice: boolean;
    cashOrCreditTypeCode: string;
    invoiceTypeCode: string;
    sendMethodCode: string;
}
