//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.26 at 09:50:19 AM ICT
//


package com.sagag.services.tools.mdm.wsdl;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.Duration;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.sagag.services.mdm.wsdl package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _GetBackBin_QNAME = new QName("http://schemas.datacontract.org/2004/07/WebServiceV4.GetBack", "GetBackBin");
    private static final QName _GetBackBase_QNAME = new QName("http://schemas.datacontract.org/2004/07/WebServiceV4.GetBack", "GetBackBase");
    private static final QName _GetBackXml_QNAME = new QName("http://schemas.datacontract.org/2004/07/WebServiceV4.GetBack", "GetBackXml");
    private static final QName _AnyType_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "anyType");
    private static final QName _AnyURI_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "anyURI");
    private static final QName _Base64Binary_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "base64Binary");
    private static final QName _Boolean_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "boolean");
    private static final QName _Byte_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "byte");
    private static final QName _DateTime_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "dateTime");
    private static final QName _Decimal_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "decimal");
    private static final QName _Double_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "double");
    private static final QName _Float_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "float");
    private static final QName _Int_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "int");
    private static final QName _Long_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "long");
    private static final QName _QName_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "QName");
    private static final QName _Short_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "short");
    private static final QName _String_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "string");
    private static final QName _UnsignedByte_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedByte");
    private static final QName _UnsignedInt_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedInt");
    private static final QName _UnsignedLong_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedLong");
    private static final QName _UnsignedShort_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedShort");
    private static final QName _Char_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "char");
    private static final QName _Duration_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "duration");
    private static final QName _Guid_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "guid");
    private static final QName _ExecuteBinHead_QNAME = new QName("http://tempuri.org/", "head");
    private static final QName _ExecuteBinData_QNAME = new QName("http://tempuri.org/", "data");
    private static final QName _ExecuteBinResponseExecuteBinResult_QNAME = new QName("http://tempuri.org/", "ExecuteBinResult");
    private static final QName _ExecuteXmlResponseExecuteXmlResult_QNAME = new QName("http://tempuri.org/", "ExecuteXmlResult");
    private static final QName _GetBackBaseMessage_QNAME = new QName("http://schemas.datacontract.org/2004/07/WebServiceV4.GetBack", "Message");
    private static final QName _GetBackXmlData_QNAME = new QName("http://schemas.datacontract.org/2004/07/WebServiceV4.GetBack", "Data");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sagag.services.mdm.wsdl.
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExecuteBin }.
     *
     */
    public ExecuteBin createExecuteBin() {
        return new ExecuteBin();
    }

    /**
     * Create an instance of {@link ExecuteBinResponse }.
     *
     */
    public ExecuteBinResponse createExecuteBinResponse() {
        return new ExecuteBinResponse();
    }

    /**
     * Create an instance of {@link GetBackBin }.
     *
     */
    public GetBackBin createGetBackBin() {
        return new GetBackBin();
    }

    /**
     * Create an instance of {@link ExecuteXml }.
     *
     */
    public ExecuteXml createExecuteXml() {
        return new ExecuteXml();
    }

    /**
     * Create an instance of {@link ExecuteXmlResponse }.
     *
     */
    public ExecuteXmlResponse createExecuteXmlResponse() {
        return new ExecuteXmlResponse();
    }

    /**
     * Create an instance of {@link GetBackXml }.
     *
     */
    public GetBackXml createGetBackXml() {
        return new GetBackXml();
    }

    /**
     * Create an instance of {@link IsAvailable }.
     *
     */
    public IsAvailable createIsAvailable() {
        return new IsAvailable();
    }

    /**
     * Create an instance of {@link IsAvailableResponse }.
     *
     */
    public IsAvailableResponse createIsAvailableResponse() {
        return new IsAvailableResponse();
    }

    /**
     * Create an instance of {@link GetBackBase }.
     *
     */
    public GetBackBase createGetBackBase() {
        return new GetBackBase();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetBackBin }{@code >}}.
     *
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/WebServiceV4.GetBack", name = "GetBackBin")
    public JAXBElement<GetBackBin> createGetBackBin(GetBackBin value) {
        return new JAXBElement<GetBackBin>(_GetBackBin_QNAME, GetBackBin.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetBackBase }{@code >}}.
     *
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/WebServiceV4.GetBack", name = "GetBackBase")
    public JAXBElement<GetBackBase> createGetBackBase(GetBackBase value) {
        return new JAXBElement<GetBackBase>(_GetBackBase_QNAME, GetBackBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetBackXml }{@code >}}.
     *
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/WebServiceV4.GetBack", name = "GetBackXml")
    public JAXBElement<GetBackXml> createGetBackXml(GetBackXml value) {
        return new JAXBElement<GetBackXml>(_GetBackXml_QNAME, GetBackXml.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}.
     *
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "anyType")
    public JAXBElement<Object> createAnyType(Object value) {
        return new JAXBElement<Object>(_AnyType_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}.
     *
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "anyURI")
    public JAXBElement<String> createAnyURI(String value) {
        return new JAXBElement<String>(_AnyURI_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}.
     *
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "base64Binary")
    public JAXBElement<byte[]> createBase64Binary(byte[] value) {
        return new JAXBElement<byte[]>(_Base64Binary_QNAME, byte[].class, null, (value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}.
     *
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "boolean")
    public JAXBElement<Boolean> createBoolean(Boolean value) {
        return new JAXBElement<Boolean>(_Boolean_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}.
     *
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "byte")
    public JAXBElement<Byte> createByte(Byte value) {
        return new JAXBElement<Byte>(_Byte_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}.
     *
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "dateTime")
    public JAXBElement<XMLGregorianCalendar> createDateTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DateTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}.
     *
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "decimal")
    public JAXBElement<BigDecimal> createDecimal(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Decimal_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "double")
    public JAXBElement<Double> createDouble(Double value) {
        return new JAXBElement<Double>(_Double_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "float")
    public JAXBElement<Float> createFloat(Float value) {
        return new JAXBElement<Float>(_Float_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "int")
    public JAXBElement<Integer> createInt(Integer value) {
        return new JAXBElement<Integer>(_Int_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "long")
    public JAXBElement<Long> createLong(Long value) {
        return new JAXBElement<Long>(_Long_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QName }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "QName")
    public JAXBElement<QName> createQName(QName value) {
        return new JAXBElement<QName>(_QName_QNAME, QName.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "short")
    public JAXBElement<Short> createShort(Short value) {
        return new JAXBElement<Short>(_Short_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "string")
    public JAXBElement<String> createString(String value) {
        return new JAXBElement<String>(_String_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "unsignedByte")
    public JAXBElement<Short> createUnsignedByte(Short value) {
        return new JAXBElement<Short>(_UnsignedByte_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "unsignedInt")
    public JAXBElement<Long> createUnsignedInt(Long value) {
        return new JAXBElement<Long>(_UnsignedInt_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "unsignedLong")
    public JAXBElement<BigInteger> createUnsignedLong(BigInteger value) {
        return new JAXBElement<BigInteger>(_UnsignedLong_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "unsignedShort")
    public JAXBElement<Integer> createUnsignedShort(Integer value) {
        return new JAXBElement<Integer>(_UnsignedShort_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "char")
    public JAXBElement<Integer> createChar(Integer value) {
        return new JAXBElement<Integer>(_Char_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Duration }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "duration")
    public JAXBElement<Duration> createDuration(Duration value) {
        return new JAXBElement<Duration>(_Duration_QNAME, Duration.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "guid")
    public JAXBElement<String> createGuid(String value) {
        return new JAXBElement<String>(_Guid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "head", scope = ExecuteBin.class)
    public JAXBElement<byte[]> createExecuteBinHead(byte[] value) {
        return new JAXBElement<byte[]>(_ExecuteBinHead_QNAME, byte[].class, ExecuteBin.class, (value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "data", scope = ExecuteBin.class)
    public JAXBElement<byte[]> createExecuteBinData(byte[] value) {
        return new JAXBElement<byte[]>(_ExecuteBinData_QNAME, byte[].class, ExecuteBin.class, (value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetBackBin }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ExecuteBinResult", scope = ExecuteBinResponse.class)
    public JAXBElement<GetBackBin> createExecuteBinResponseExecuteBinResult(GetBackBin value) {
        return new JAXBElement<GetBackBin>(_ExecuteBinResponseExecuteBinResult_QNAME, GetBackBin.class, ExecuteBinResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "head", scope = ExecuteXml.class)
    public JAXBElement<String> createExecuteXmlHead(String value) {
        return new JAXBElement<String>(_ExecuteBinHead_QNAME, String.class, ExecuteXml.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "data", scope = ExecuteXml.class)
    public JAXBElement<String> createExecuteXmlData(String value) {
        return new JAXBElement<String>(_ExecuteBinData_QNAME, String.class, ExecuteXml.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetBackXml }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ExecuteXmlResult", scope = ExecuteXmlResponse.class)
    public JAXBElement<GetBackXml> createExecuteXmlResponseExecuteXmlResult(GetBackXml value) {
        return new JAXBElement<GetBackXml>(_ExecuteXmlResponseExecuteXmlResult_QNAME, GetBackXml.class, ExecuteXmlResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/WebServiceV4.GetBack", name = "Message", scope = GetBackBase.class)
    public JAXBElement<String> createGetBackBaseMessage(String value) {
        return new JAXBElement<String>(_GetBackBaseMessage_QNAME, String.class, GetBackBase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/WebServiceV4.GetBack", name = "Data", scope = GetBackXml.class)
    public JAXBElement<String> createGetBackXmlData(String value) {
        return new JAXBElement<String>(_GetBackXmlData_QNAME, String.class, GetBackXml.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/WebServiceV4.GetBack", name = "Data", scope = GetBackBin.class)
    public JAXBElement<byte[]> createGetBackBinData(byte[] value) {
        return new JAXBElement<byte[]>(_GetBackXmlData_QNAME, byte[].class, GetBackBin.class, (value));
    }

}
