//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.06.28 at 05:53:09 PM ICT
//


package com.sagag.services.gtmotive.wsdl.vehicle;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.Duration;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;
import java.math.BigDecimal;
import java.math.BigInteger;


/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the com.gtmotive.WSGtVehicleInformationService.wsdl.dto package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation
 * for XML content. The Java representation of XML content can consist of schema derived interfaces
 * and classes representing the binding of schema type definitions, element declarations and model
 * groups. Factory methods for each of these are provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

  private static final QName _ServiceError_QNAME =
      new QName("GtMotive.WSGTI.DistributedServices.Core", "ServiceError");
  private static final QName _AnyType_QNAME =
      new QName("http://schemas.microsoft.com/2003/10/Serialization/", "anyType");
  private static final QName _AnyURI_QNAME =
      new QName("http://schemas.microsoft.com/2003/10/Serialization/", "anyURI");
  private static final QName _Base64Binary_QNAME =
      new QName("http://schemas.microsoft.com/2003/10/Serialization/", "base64Binary");
  private static final QName _Boolean_QNAME =
      new QName("http://schemas.microsoft.com/2003/10/Serialization/", "boolean");
  private static final QName _Byte_QNAME =
      new QName("http://schemas.microsoft.com/2003/10/Serialization/", "byte");
  private static final QName _DateTime_QNAME =
      new QName("http://schemas.microsoft.com/2003/10/Serialization/", "dateTime");
  private static final QName _Decimal_QNAME =
      new QName("http://schemas.microsoft.com/2003/10/Serialization/", "decimal");
  private static final QName _Double_QNAME =
      new QName("http://schemas.microsoft.com/2003/10/Serialization/", "double");
  private static final QName _Float_QNAME =
      new QName("http://schemas.microsoft.com/2003/10/Serialization/", "float");
  private static final QName _Int_QNAME =
      new QName("http://schemas.microsoft.com/2003/10/Serialization/", "int");
  private static final QName _Long_QNAME =
      new QName("http://schemas.microsoft.com/2003/10/Serialization/", "long");
  private static final QName _QName_QNAME =
      new QName("http://schemas.microsoft.com/2003/10/Serialization/", "QName");
  private static final QName _Short_QNAME =
      new QName("http://schemas.microsoft.com/2003/10/Serialization/", "short");
  private static final QName _String_QNAME =
      new QName("http://schemas.microsoft.com/2003/10/Serialization/", "string");
  private static final QName _UnsignedByte_QNAME =
      new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedByte");
  private static final QName _UnsignedInt_QNAME =
      new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedInt");
  private static final QName _UnsignedLong_QNAME =
      new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedLong");
  private static final QName _UnsignedShort_QNAME =
      new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedShort");
  private static final QName _Char_QNAME =
      new QName("http://schemas.microsoft.com/2003/10/Serialization/", "char");
  private static final QName _Duration_QNAME =
      new QName("http://schemas.microsoft.com/2003/10/Serialization/", "duration");
  private static final QName _Guid_QNAME =
      new QName("http://schemas.microsoft.com/2003/10/Serialization/", "guid");
  private static final QName _CreateVehicleInfoStrXmlRequest_QNAME = new QName(
      "GtMotive.WSGTI.DistributedServices.WSGtVehicleInformationService", "strXmlRequest");
  private static final QName _CreateVehicleInfoResponseCreateVehicleInfoResult_QNAME =
      new QName("GtMotive.WSGTI.DistributedServices.WSGtVehicleInformationService",
          "CreateVehicleInfoResult");
  private static final QName _UpdateVehicleInfoResponseUpdateVehicleInfoResult_QNAME =
      new QName("GtMotive.WSGTI.DistributedServices.WSGtVehicleInformationService",
          "UpdateVehicleInfoResult");
  private static final QName _GTUpdateVehicleInfoResponseGTUpdateVehicleInfoResult_QNAME =
      new QName("GtMotive.WSGTI.DistributedServices.WSGtVehicleInformationService",
          "GTUpdateVehicleInfoResult");
  private static final QName _ReadVehicleInfoResponseReadVehicleInfoResult_QNAME = new QName(
      "GtMotive.WSGTI.DistributedServices.WSGtVehicleInformationService", "ReadVehicleInfoResult");
  private static final QName _ListVehicleInfoResponseListVehicleInfoResult_QNAME = new QName(
      "GtMotive.WSGTI.DistributedServices.WSGtVehicleInformationService", "ListVehicleInfoResult");
  private static final QName _GetVinEPCEquipmentResponseGetVinEPCEquipmentResult_QNAME =
      new QName("GtMotive.WSGTI.DistributedServices.WSGtVehicleInformationService",
          "GetVinEPCEquipmentResult");
  private static final QName _NotifyVinEPCResponseNotifyVinEPCResult_QNAME = new QName(
      "GtMotive.WSGTI.DistributedServices.WSGtVehicleInformationService", "NotifyVinEPCResult");
  private static final QName _VinDecoderResponseVinDecoderResult_QNAME = new QName(
      "GtMotive.WSGTI.DistributedServices.WSGtVehicleInformationService", "VinDecoderResult");
  private static final QName _VinDecodificationModeResponseVinDecodificationModeResult_QNAME =
      new QName("GtMotive.WSGTI.DistributedServices.WSGtVehicleInformationService",
          "VinDecodificationModeResult");
  private static final QName _ServiceErrorErrorMessage_QNAME =
      new QName("GtMotive.WSGTI.DistributedServices.Core", "ErrorMessage");

  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes
   * for package: com.gtmotive.WSGtVehicleInformationService.wsdl.dto
   *
   */
  public ObjectFactory() {}

  /**
   * Create an instance of {@link CreateVehicleInfo }
   *
   */
  public CreateVehicleInfo createCreateVehicleInfo() {
    return new CreateVehicleInfo();
  }

  /**
   * Create an instance of {@link CreateVehicleInfoResponse }
   *
   */
  public CreateVehicleInfoResponse createCreateVehicleInfoResponse() {
    return new CreateVehicleInfoResponse();
  }

  /**
   * Create an instance of {@link UpdateVehicleInfo }
   *
   */
  public UpdateVehicleInfo createUpdateVehicleInfo() {
    return new UpdateVehicleInfo();
  }

  /**
   * Create an instance of {@link UpdateVehicleInfoResponse }
   *
   */
  public UpdateVehicleInfoResponse createUpdateVehicleInfoResponse() {
    return new UpdateVehicleInfoResponse();
  }

  /**
   * Create an instance of {@link GTUpdateVehicleInfo }
   *
   */
  public GTUpdateVehicleInfo createGTUpdateVehicleInfo() {
    return new GTUpdateVehicleInfo();
  }

  /**
   * Create an instance of {@link GTUpdateVehicleInfoResponse }
   *
   */
  public GTUpdateVehicleInfoResponse createGTUpdateVehicleInfoResponse() {
    return new GTUpdateVehicleInfoResponse();
  }

  /**
   * Create an instance of {@link ReadVehicleInfo }
   *
   */
  public ReadVehicleInfo createReadVehicleInfo() {
    return new ReadVehicleInfo();
  }

  /**
   * Create an instance of {@link ReadVehicleInfoResponse }
   *
   */
  public ReadVehicleInfoResponse createReadVehicleInfoResponse() {
    return new ReadVehicleInfoResponse();
  }

  /**
   * Create an instance of {@link ListVehicleInfo }
   *
   */
  public ListVehicleInfo createListVehicleInfo() {
    return new ListVehicleInfo();
  }

  /**
   * Create an instance of {@link ListVehicleInfoResponse }
   *
   */
  public ListVehicleInfoResponse createListVehicleInfoResponse() {
    return new ListVehicleInfoResponse();
  }

  /**
   * Create an instance of {@link GetVinEPCEquipment }
   *
   */
  public GetVinEPCEquipment createGetVinEPCEquipment() {
    return new GetVinEPCEquipment();
  }

  /**
   * Create an instance of {@link GetVinEPCEquipmentResponse }
   *
   */
  public GetVinEPCEquipmentResponse createGetVinEPCEquipmentResponse() {
    return new GetVinEPCEquipmentResponse();
  }

  /**
   * Create an instance of {@link NotifyVinEPC }
   *
   */
  public NotifyVinEPC createNotifyVinEPC() {
    return new NotifyVinEPC();
  }

  /**
   * Create an instance of {@link NotifyVinEPCResponse }
   *
   */
  public NotifyVinEPCResponse createNotifyVinEPCResponse() {
    return new NotifyVinEPCResponse();
  }

  /**
   * Create an instance of {@link VinDecoder }
   *
   */
  public VinDecoder createVinDecoder() {
    return new VinDecoder();
  }

  /**
   * Create an instance of {@link VinDecoderResponse }
   *
   */
  public VinDecoderResponse createVinDecoderResponse() {
    return new VinDecoderResponse();
  }

  /**
   * Create an instance of {@link VinDecodificationMode }
   *
   */
  public VinDecodificationMode createVinDecodificationMode() {
    return new VinDecodificationMode();
  }

  /**
   * Create an instance of {@link VinDecodificationModeResponse }
   *
   */
  public VinDecodificationModeResponse createVinDecodificationModeResponse() {
    return new VinDecodificationModeResponse();
  }

  /**
   * Create an instance of {@link ServiceError }
   *
   */
  public ServiceError createServiceError() {
    return new ServiceError();
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link ServiceError }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "GtMotive.WSGTI.DistributedServices.Core", name = "ServiceError")
  public JAXBElement<ServiceError> createServiceError(ServiceError value) {
    return new JAXBElement<ServiceError>(_ServiceError_QNAME, ServiceError.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/",
      name = "anyType")
  public JAXBElement<Object> createAnyType(Object value) {
    return new JAXBElement<Object>(_AnyType_QNAME, Object.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/",
      name = "anyURI")
  public JAXBElement<String> createAnyURI(String value) {
    return new JAXBElement<String>(_AnyURI_QNAME, String.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
   *
   */
  @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/",
      name = "base64Binary")
  public JAXBElement<byte[]> createBase64Binary(byte[] value) {
    return new JAXBElement<byte[]>(_Base64Binary_QNAME, byte[].class, null, (value));
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/",
      name = "boolean")
  public JAXBElement<Boolean> createBoolean(Boolean value) {
    return new JAXBElement<Boolean>(_Boolean_QNAME, Boolean.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "byte")
  public JAXBElement<Byte> createByte(Byte value) {
    return new JAXBElement<Byte>(_Byte_QNAME, Byte.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/",
      name = "dateTime")
  public JAXBElement<XMLGregorianCalendar> createDateTime(XMLGregorianCalendar value) {
    return new JAXBElement<XMLGregorianCalendar>(_DateTime_QNAME, XMLGregorianCalendar.class, null,
        value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/",
      name = "decimal")
  public JAXBElement<BigDecimal> createDecimal(BigDecimal value) {
    return new JAXBElement<BigDecimal>(_Decimal_QNAME, BigDecimal.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/",
      name = "double")
  public JAXBElement<Double> createDouble(Double value) {
    return new JAXBElement<Double>(_Double_QNAME, Double.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "float")
  public JAXBElement<Float> createFloat(Float value) {
    return new JAXBElement<Float>(_Float_QNAME, Float.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "int")
  public JAXBElement<Integer> createInt(Integer value) {
    return new JAXBElement<Integer>(_Int_QNAME, Integer.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "long")
  public JAXBElement<Long> createLong(Long value) {
    return new JAXBElement<Long>(_Long_QNAME, Long.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link QName }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "QName")
  public JAXBElement<QName> createQName(QName value) {
    return new JAXBElement<QName>(_QName_QNAME, QName.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "short")
  public JAXBElement<Short> createShort(Short value) {
    return new JAXBElement<Short>(_Short_QNAME, Short.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/",
      name = "string")
  public JAXBElement<String> createString(String value) {
    return new JAXBElement<String>(_String_QNAME, String.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/",
      name = "unsignedByte")
  public JAXBElement<Short> createUnsignedByte(Short value) {
    return new JAXBElement<Short>(_UnsignedByte_QNAME, Short.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/",
      name = "unsignedInt")
  public JAXBElement<Long> createUnsignedInt(Long value) {
    return new JAXBElement<Long>(_UnsignedInt_QNAME, Long.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/",
      name = "unsignedLong")
  public JAXBElement<BigInteger> createUnsignedLong(BigInteger value) {
    return new JAXBElement<BigInteger>(_UnsignedLong_QNAME, BigInteger.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/",
      name = "unsignedShort")
  public JAXBElement<Integer> createUnsignedShort(Integer value) {
    return new JAXBElement<Integer>(_UnsignedShort_QNAME, Integer.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "char")
  public JAXBElement<Integer> createChar(Integer value) {
    return new JAXBElement<Integer>(_Char_QNAME, Integer.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Duration }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/",
      name = "duration")
  public JAXBElement<Duration> createDuration(Duration value) {
    return new JAXBElement<Duration>(_Duration_QNAME, Duration.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "guid")
  public JAXBElement<String> createGuid(String value) {
    return new JAXBElement<String>(_Guid_QNAME, String.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "GtMotive.WSGTI.DistributedServices.WSGtVehicleInformationService",
      name = "strXmlRequest", scope = CreateVehicleInfo.class)
  public JAXBElement<String> createCreateVehicleInfoStrXmlRequest(String value) {
    return new JAXBElement<String>(_CreateVehicleInfoStrXmlRequest_QNAME, String.class,
        CreateVehicleInfo.class, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "GtMotive.WSGTI.DistributedServices.WSGtVehicleInformationService",
      name = "CreateVehicleInfoResult", scope = CreateVehicleInfoResponse.class)
  public JAXBElement<String> createCreateVehicleInfoResponseCreateVehicleInfoResult(String value) {
    return new JAXBElement<String>(_CreateVehicleInfoResponseCreateVehicleInfoResult_QNAME,
        String.class, CreateVehicleInfoResponse.class, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "GtMotive.WSGTI.DistributedServices.WSGtVehicleInformationService",
      name = "strXmlRequest", scope = UpdateVehicleInfo.class)
  public JAXBElement<String> createUpdateVehicleInfoStrXmlRequest(String value) {
    return new JAXBElement<String>(_CreateVehicleInfoStrXmlRequest_QNAME, String.class,
        UpdateVehicleInfo.class, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "GtMotive.WSGTI.DistributedServices.WSGtVehicleInformationService",
      name = "UpdateVehicleInfoResult", scope = UpdateVehicleInfoResponse.class)
  public JAXBElement<String> createUpdateVehicleInfoResponseUpdateVehicleInfoResult(String value) {
    return new JAXBElement<String>(_UpdateVehicleInfoResponseUpdateVehicleInfoResult_QNAME,
        String.class, UpdateVehicleInfoResponse.class, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "GtMotive.WSGTI.DistributedServices.WSGtVehicleInformationService",
      name = "strXmlRequest", scope = GTUpdateVehicleInfo.class)
  public JAXBElement<String> createGTUpdateVehicleInfoStrXmlRequest(String value) {
    return new JAXBElement<String>(_CreateVehicleInfoStrXmlRequest_QNAME, String.class,
        GTUpdateVehicleInfo.class, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "GtMotive.WSGTI.DistributedServices.WSGtVehicleInformationService",
      name = "GTUpdateVehicleInfoResult", scope = GTUpdateVehicleInfoResponse.class)
  public JAXBElement<String> createGTUpdateVehicleInfoResponseGTUpdateVehicleInfoResult(
      String value) {
    return new JAXBElement<String>(_GTUpdateVehicleInfoResponseGTUpdateVehicleInfoResult_QNAME,
        String.class, GTUpdateVehicleInfoResponse.class, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "GtMotive.WSGTI.DistributedServices.WSGtVehicleInformationService",
      name = "strXmlRequest", scope = ReadVehicleInfo.class)
  public JAXBElement<String> createReadVehicleInfoStrXmlRequest(String value) {
    return new JAXBElement<String>(_CreateVehicleInfoStrXmlRequest_QNAME, String.class,
        ReadVehicleInfo.class, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "GtMotive.WSGTI.DistributedServices.WSGtVehicleInformationService",
      name = "ReadVehicleInfoResult", scope = ReadVehicleInfoResponse.class)
  public JAXBElement<String> createReadVehicleInfoResponseReadVehicleInfoResult(String value) {
    return new JAXBElement<String>(_ReadVehicleInfoResponseReadVehicleInfoResult_QNAME,
        String.class, ReadVehicleInfoResponse.class, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "GtMotive.WSGTI.DistributedServices.WSGtVehicleInformationService",
      name = "strXmlRequest", scope = ListVehicleInfo.class)
  public JAXBElement<String> createListVehicleInfoStrXmlRequest(String value) {
    return new JAXBElement<String>(_CreateVehicleInfoStrXmlRequest_QNAME, String.class,
        ListVehicleInfo.class, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "GtMotive.WSGTI.DistributedServices.WSGtVehicleInformationService",
      name = "ListVehicleInfoResult", scope = ListVehicleInfoResponse.class)
  public JAXBElement<String> createListVehicleInfoResponseListVehicleInfoResult(String value) {
    return new JAXBElement<String>(_ListVehicleInfoResponseListVehicleInfoResult_QNAME,
        String.class, ListVehicleInfoResponse.class, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "GtMotive.WSGTI.DistributedServices.WSGtVehicleInformationService",
      name = "strXmlRequest", scope = GetVinEPCEquipment.class)
  public JAXBElement<String> createGetVinEPCEquipmentStrXmlRequest(String value) {
    return new JAXBElement<String>(_CreateVehicleInfoStrXmlRequest_QNAME, String.class,
        GetVinEPCEquipment.class, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "GtMotive.WSGTI.DistributedServices.WSGtVehicleInformationService",
      name = "GetVinEPCEquipmentResult", scope = GetVinEPCEquipmentResponse.class)
  public JAXBElement<String> createGetVinEPCEquipmentResponseGetVinEPCEquipmentResult(
      String value) {
    return new JAXBElement<String>(_GetVinEPCEquipmentResponseGetVinEPCEquipmentResult_QNAME,
        String.class, GetVinEPCEquipmentResponse.class, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "GtMotive.WSGTI.DistributedServices.WSGtVehicleInformationService",
      name = "strXmlRequest", scope = NotifyVinEPC.class)
  public JAXBElement<String> createNotifyVinEPCStrXmlRequest(String value) {
    return new JAXBElement<String>(_CreateVehicleInfoStrXmlRequest_QNAME, String.class,
        NotifyVinEPC.class, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "GtMotive.WSGTI.DistributedServices.WSGtVehicleInformationService",
      name = "NotifyVinEPCResult", scope = NotifyVinEPCResponse.class)
  public JAXBElement<String> createNotifyVinEPCResponseNotifyVinEPCResult(String value) {
    return new JAXBElement<String>(_NotifyVinEPCResponseNotifyVinEPCResult_QNAME, String.class,
        NotifyVinEPCResponse.class, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "GtMotive.WSGTI.DistributedServices.WSGtVehicleInformationService",
      name = "strXmlRequest", scope = VinDecoder.class)
  public JAXBElement<String> createVinDecoderStrXmlRequest(String value) {
    return new JAXBElement<String>(_CreateVehicleInfoStrXmlRequest_QNAME, String.class,
        VinDecoder.class, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "GtMotive.WSGTI.DistributedServices.WSGtVehicleInformationService",
      name = "VinDecoderResult", scope = VinDecoderResponse.class)
  public JAXBElement<String> createVinDecoderResponseVinDecoderResult(String value) {
    return new JAXBElement<String>(_VinDecoderResponseVinDecoderResult_QNAME, String.class,
        VinDecoderResponse.class, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "GtMotive.WSGTI.DistributedServices.WSGtVehicleInformationService",
      name = "strXmlRequest", scope = VinDecodificationMode.class)
  public JAXBElement<String> createVinDecodificationModeStrXmlRequest(String value) {
    return new JAXBElement<String>(_CreateVehicleInfoStrXmlRequest_QNAME, String.class,
        VinDecodificationMode.class, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "GtMotive.WSGTI.DistributedServices.WSGtVehicleInformationService",
      name = "VinDecodificationModeResult", scope = VinDecodificationModeResponse.class)
  public JAXBElement<String> createVinDecodificationModeResponseVinDecodificationModeResult(
      String value) {
    return new JAXBElement<String>(_VinDecodificationModeResponseVinDecodificationModeResult_QNAME,
        String.class, VinDecodificationModeResponse.class, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
   *
   */
  @XmlElementDecl(namespace = "GtMotive.WSGTI.DistributedServices.Core", name = "ErrorMessage",
      scope = ServiceError.class)
  public JAXBElement<String> createServiceErrorErrorMessage(String value) {
    return new JAXBElement<String>(_ServiceErrorErrorMessage_QNAME, String.class,
        ServiceError.class, value);
  }

}
