//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.06.28 at 05:53:09 PM ICT
//

@javax.xml.bind.annotation.XmlSchema(namespace = "GtMotive.WSGTI.DistributedServices.WSGtVehicleInformationService",
elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.sagag.services.gtmotive.wsdl.vehicle;
