export enum VIN_MODE {
    STANDARD = 'Standard',
    PREMIUM = 'Premium'
}

export enum ARTICLE_SEARCH_MODE {
    ARTICLE_NUMBER = 'ARTICLE_NUMBER',
    ARTICLE_DESC = "ARTICLE_DESC",
    SHOPPING_LIST = "SHOPPING_LIST",
    FREE_TEXT = 'FREE_TEXT',
    ARTICLE_ID = 'ARTICLE_ID',
    DEEP_LINK = 'DEEP_LINK'
}

export enum ARTICLE_FILTER_MODE {
    FREE_TEXT = "FREE_TEXT",
    ARTICLE_DESC = "ARTICLE_DESC",
    ARTICLE_NR = "ARTICLE_NR"
}