--- Migration data from MESSAGE and MESSAGE_LOCATION to MESSAGE_LOCATION_RELATION
INSERT INTO dbo.MESSAGE_LOCATION
SELECT ml.MESSAGE_LOCATION_TYPE_ID, ml.VALUE FROM [dbo].[MESSAGE_LOCATION] ml
join MESSAGE m on m.MESSAGE_LOCATION_ID =  ml.ID ORDER by m.ID desc

DECLARE @MESSAGE_LOCATION_TEMP table(
	r int not null,
	id int not null
)
INSERT into @MESSAGE_LOCATION_TEMP (r, id) SELECT ROW_NUMBER() OVER(ORDER BY ID DESC) AS Rank,ID FROM MESSAGE_LOCATION

DECLARE @MESSAGE_TEMP table(
	r int not null,
	id int not null
)
INSERT into @MESSAGE_TEMP (r, id) SELECT ROW_NUMBER() OVER(ORDER BY ID asc) AS Rank,ID FROM MESSAGE

INSERT INTO [dbo].[MESSAGE_LOCATION_RELATION] (MESSAGE_ID, MESSAGE_LOCATION_ID)
SELECT A.id, B.id
FROM
@MESSAGE_TEMP A
Inner JOIN @MESSAGE_LOCATION_TEMP B on A.r = B.r ORDER by A.r