export enum INFO_TYPE {
    TECHNICAL_INFORMATION = 1,
    GENERAL_INFORMATION = 2,
    INSTALLATION_INFORMATION = 3,
    LABOUR = 4,
    SAFETY_INFORMATION = 5,
    MEASUREMENT_FUNCTIONS = 6,
    DELIVERY = 7,
    OPTIONAL_ACCESSORIES = 8,
    BRIEF_INFORMATION = 9,
    INFORMATION = 90,
    ADD_REC = 'ADD_REC'
}
