# ************************************************************************
# This is the CH configuration of OAuth2 application for Testing mode.
# 
# Required Common configuration:
# - Application common configuration - 
# - ERP - 
# - Elasticsearch - 
# - Database - 
# - Thread Executor Pool - 
# - Liquibase - 
# - Logging - 
# - Actuator Healthcheck - 
# - Caching - 
# - Country Code - 
# - Proxy - 
# - Java Melody Monitoring -
#
# ************************************************************************
spring.profiles.include: 
  sagauth,
  ax-pre-cloud,
  elasticsearch-pre,
  db-pre,
  executor-pool-pre,
  no-liquibase,
  logging-ch-umbpre,
  actuator,
  cache-pre,
  country-ch,
  no-proxy,
  javamelody

spring.banner.location: classpath:banner/banner_ch.txt
