--Add CREATED_DATE for V_MESSAGE
ALTER VIEW V_MESSAGE AS
	SELECT DISTINCT 
        M.ID AS ID,
        M.TITLE AS TITLE,
		T.TYPE AS TYPE,
		A.AREA AS AREA,
		SA.SUB_AREA AS SUB_AREA,
		L.VALUE AS LOCATION_VALUE,
		M.ACTIVE AS ACTIVE,
		CREATED_DATE AS CREATED_DATE
    FROM 
        MESSAGE M
        JOIN MESSAGE_TYPE T ON M.MESSAGE_TYPE_ID = T.ID
		JOIN MESSAGE_SUB_AREA SA ON M.MESSAGE_SUB_AREA_ID=SA.ID
        JOIN MESSAGE_AREA A ON SA.MESSAGE_AREA_ID = A.ID
		JOIN MESSAGE_LOCATION L ON M.MESSAGE_LOCATION_ID = L.ID

-- #3397
update CUSTOMER_SETTINGS set NET_PRICE_VIEW = 1, NET_PRICE_CONFIRM = 1;
update USER_SETTINGS set NET_PRICE_VIEW = 1, NET_PRICE_CONFIRM = 1, CURRENT_STATE_NET_PRICE_VIEW = 1;
		
-- Init marketing email for affiliate
DECLARE @derendingerChId INT = (SELECT ID FROM ORGANISATION WHERE NAME = 'Derendinger-Switzerland');
INSERT INTO ORGANISATION_SETTINGS(NAME,ORGANISATION_ID,SETTING_KEY,SETTING_VALUE) VALUES('Derendinger-Switzerland',@derendingerChId,'marketing_dept_email','marketing@derendinger.ch');

DECLARE @derendingerAtId INT = (SELECT ID FROM ORGANISATION WHERE NAME = 'Derendinger-Austria');
INSERT INTO ORGANISATION_SETTINGS(NAME,ORGANISATION_ID,SETTING_KEY,SETTING_VALUE) VALUES('Derendinger-Austria',@derendingerAtId,'marketing_dept_email','shop@derendinger.at');

DECLARE @technomagChId INT = (SELECT ID FROM ORGANISATION WHERE NAME = 'Technomag-Switzerland');
INSERT INTO ORGANISATION_SETTINGS(NAME,ORGANISATION_ID,SETTING_KEY,SETTING_VALUE) VALUES('Technomag-Switzerland',@technomagChId,'marketing_dept_email','anmeldung@technomag.ch');

DECLARE @matikChId INT = (SELECT ID FROM ORGANISATION WHERE NAME = 'Matik-Switzerland');
INSERT INTO ORGANISATION_SETTINGS(NAME,ORGANISATION_ID,SETTING_KEY,SETTING_VALUE) VALUES('Matik-Switzerland',@matikChId,'marketing_dept_email','anmeldung@matik.ch');

DECLARE @matikAtId INT = (SELECT ID FROM ORGANISATION WHERE NAME = 'Matik-Austria');
INSERT INTO ORGANISATION_SETTINGS(NAME,ORGANISATION_ID,SETTING_KEY,SETTING_VALUE) VALUES('Matik-Austria',@matikAtId,'marketing_dept_email','shop@matik.at');

DECLARE @wbbId INT = (SELECT ID FROM ORGANISATION WHERE NAME = 'Walchli-Bollier-Bulach');
INSERT INTO ORGANISATION_SETTINGS(NAME,ORGANISATION_ID,SETTING_KEY,SETTING_VALUE) VALUES('Walchli-Bollier-Bulach',@wbbId,'marketing_dept_email','info@waelchlibollier.ch');
