-- Init noreply email for affiliate
UPDATE SUPPORTED_AFFILIATE SET NO_REPLY_EMAIL='noreply@derendinger.ch' WHERE SHORT_NAME='derendinger-ch'
UPDATE SUPPORTED_AFFILIATE SET NO_REPLY_EMAIL='noreply@derendinger.at' WHERE SHORT_NAME='derendinger-at'
UPDATE SUPPORTED_AFFILIATE SET NO_REPLY_EMAIL='noreply@technomag.ch' WHERE SHORT_NAME='technomag'
UPDATE SUPPORTED_AFFILIATE SET NO_REPLY_EMAIL='noreply@matik.ch' WHERE SHORT_NAME='matik-ch'
UPDATE SUPPORTED_AFFILIATE SET NO_REPLY_EMAIL='noreply@matik.at' WHERE SHORT_NAME='matik-at'
UPDATE SUPPORTED_AFFILIATE SET NO_REPLY_EMAIL='noreply@waelchlibollier.ch' WHERE SHORT_NAME='wbb'
UPDATE SUPPORTED_AFFILIATE SET NO_REPLY_EMAIL='noreply@remco.be' WHERE SHORT_NAME='rbe'

-- Init data for FEEDBACK_STATUS --
TRUNCATE TABLE dbo.FEEDBACK_STATUS
INSERT INTO dbo.FEEDBACK_STATUS (STATUS_CODE, DESCRIPTION) VALUES('NOT_STARTED', 'Not Started');
INSERT INTO dbo.FEEDBACK_STATUS (STATUS_CODE, DESCRIPTION) VALUES('ASSIGNED', 'Assigned');
INSERT INTO dbo.FEEDBACK_STATUS (STATUS_CODE, DESCRIPTION) VALUES('IN_PROGRESS', 'In Progress');
INSERT INTO dbo.FEEDBACK_STATUS (STATUS_CODE, DESCRIPTION) VALUES('CROSS_CHECKING', 'Cross Checking');
INSERT INTO dbo.FEEDBACK_STATUS (STATUS_CODE, DESCRIPTION) VALUES('DONE', 'Done');

-- Init data for FEEDBACK_TOPIC --
TRUNCATE TABLE dbo.FEEDBACK_TOPIC
INSERT INTO dbo.FEEDBACK_TOPIC (TOPIC_CODE, DESCRIPTION) VALUES('PRICING', 'Pricing');
INSERT INTO dbo.FEEDBACK_TOPIC (TOPIC_CODE, DESCRIPTION) VALUES('EASE_OF_USE', 'Ease of use');
INSERT INTO dbo.FEEDBACK_TOPIC (TOPIC_CODE, DESCRIPTION) VALUES('MISSING_WRONG_DATA', 'Missing/wrong data (vehicle, part, range of goods etc.)');
INSERT INTO dbo.FEEDBACK_TOPIC (TOPIC_CODE, DESCRIPTION) VALUES('LICENSING', 'Licensing (HaynesPro, VIN etc.)');
INSERT INTO dbo.FEEDBACK_TOPIC (TOPIC_CODE, DESCRIPTION) VALUES('SYSTEM_BROWSER_INTERFACES', 'System, Browser, Interfaces');
INSERT INTO dbo.FEEDBACK_TOPIC (TOPIC_CODE, DESCRIPTION) VALUES('PROFILE_SETTINGS', 'Profile, Settings');
INSERT INTO dbo.FEEDBACK_TOPIC (TOPIC_CODE, DESCRIPTION) VALUES('BONUS_MILES_PROGRAM', 'Bonus/Miles Program');
INSERT INTO dbo.FEEDBACK_TOPIC (TOPIC_CODE, DESCRIPTION) VALUES('OTHER', 'Other...');

-- Init data for FEEDBACK_DEPARTMENT --
TRUNCATE TABLE dbo.FEEDBACK_DEPARTMENT
INSERT INTO dbo.FEEDBACK_DEPARTMENT (DEPARTMENT_CODE , DESCRIPTION) VALUES('PRICING_DEPT', 'Pricing');
INSERT INTO dbo.FEEDBACK_DEPARTMENT (DEPARTMENT_CODE , DESCRIPTION) VALUES('DATA_SUPPORT', 'Data issues');
INSERT INTO dbo.FEEDBACK_DEPARTMENT (DEPARTMENT_CODE ,SUPPORTED_AFFILIATE_ID, DESCRIPTION) VALUES('AFFILIATE_BRANCH_DERENDINGER_AT',1, 'Ease of Use, Licensing, Others');
INSERT INTO dbo.FEEDBACK_DEPARTMENT (DEPARTMENT_CODE ,SUPPORTED_AFFILIATE_ID, DESCRIPTION) VALUES('AFFILIATE_BRANCH_MATIK_AT',3, 'Ease of Use, Licensing, Others');
INSERT INTO dbo.FEEDBACK_DEPARTMENT (DEPARTMENT_CODE , DESCRIPTION) VALUES('AFFILIATE_BRANCH_C4S_CH', 'Ease of Use, Licensing, Others');
INSERT INTO dbo.FEEDBACK_DEPARTMENT (DEPARTMENT_CODE , DESCRIPTION) VALUES('TECH_POOL', 'System, Browser, Interfaces');
INSERT INTO dbo.FEEDBACK_DEPARTMENT (DEPARTMENT_CODE , DESCRIPTION) VALUES('SERVICE_DESK', 'Profile, Settings; Bonus Program');

-- Init data for FEEDBACK_TOPIC_DEPARTMENT --
TRUNCATE TABLE dbo.FEEDBACK_TOPIC_DEPARTMENT
INSERT INTO dbo.FEEDBACK_TOPIC_DEPARTMENT (DEPARTMENT_ID, TOPIC_ID) VALUES(1, 1); -- PRICING_DEPT <-> PRICING
INSERT INTO dbo.FEEDBACK_TOPIC_DEPARTMENT (DEPARTMENT_ID, TOPIC_ID) VALUES(2, 3); -- DATA_SUPPORT <-> MISSING_WRONG_DATA

INSERT INTO dbo.FEEDBACK_TOPIC_DEPARTMENT (DEPARTMENT_ID, TOPIC_ID) VALUES(3, 2); -- AFFILIATE_BRANCH <-> EASE_OF_USE
INSERT INTO dbo.FEEDBACK_TOPIC_DEPARTMENT (DEPARTMENT_ID, TOPIC_ID) VALUES(3, 4); -- AFFILIATE_BRANCH <-> LICENSING
INSERT INTO dbo.FEEDBACK_TOPIC_DEPARTMENT (DEPARTMENT_ID, TOPIC_ID) VALUES(3, 8); -- AFFILIATE_BRANCH <-> OTHER
INSERT INTO dbo.FEEDBACK_TOPIC_DEPARTMENT (DEPARTMENT_ID, TOPIC_ID) VALUES(4, 2); -- AFFILIATE_BRANCH <-> EASE_OF_USE
INSERT INTO dbo.FEEDBACK_TOPIC_DEPARTMENT (DEPARTMENT_ID, TOPIC_ID) VALUES(4, 4); -- AFFILIATE_BRANCH <-> LICENSING
INSERT INTO dbo.FEEDBACK_TOPIC_DEPARTMENT (DEPARTMENT_ID, TOPIC_ID) VALUES(4, 8); -- AFFILIATE_BRANCH <-> OTHER
INSERT INTO dbo.FEEDBACK_TOPIC_DEPARTMENT (DEPARTMENT_ID, TOPIC_ID) VALUES(5, 2); -- AFFILIATE_BRANCH <-> EASE_OF_USE
INSERT INTO dbo.FEEDBACK_TOPIC_DEPARTMENT (DEPARTMENT_ID, TOPIC_ID) VALUES(5, 4); -- AFFILIATE_BRANCH <-> LICENSING
INSERT INTO dbo.FEEDBACK_TOPIC_DEPARTMENT (DEPARTMENT_ID, TOPIC_ID) VALUES(5, 8); -- AFFILIATE_BRANCH <-> OTHER

INSERT INTO dbo.FEEDBACK_TOPIC_DEPARTMENT (DEPARTMENT_ID, TOPIC_ID) VALUES(6, 5); -- TECH_POOL <-> SYSTEM_BROWSER_INTERFACES

INSERT INTO dbo.FEEDBACK_TOPIC_DEPARTMENT (DEPARTMENT_ID, TOPIC_ID) VALUES(7, 6); -- SERVICE_DESK <-> PROFILE_SETTINGS
INSERT INTO dbo.FEEDBACK_TOPIC_DEPARTMENT (DEPARTMENT_ID, TOPIC_ID) VALUES(7, 7); -- SERVICE_DESK <-> BONUS_MILES_PROGRAM

-- Init data for FEEDBACK_DEPARTMENT_CONTACT --
TRUNCATE TABLE dbo.FEEDBACK_DEPARTMENT_CONTACT
INSERT INTO dbo.FEEDBACK_DEPARTMENT_CONTACT (DEPARTMENT_ID, [TYPE], VALUE) VALUES(1, 'EMAIL', 'Informatik@sag-austria.at');
INSERT INTO dbo.FEEDBACK_DEPARTMENT_CONTACT (DEPARTMENT_ID, [TYPE], VALUE) VALUES(2, 'EMAIL', 'Informatik@sag-austria.at');
INSERT INTO dbo.FEEDBACK_DEPARTMENT_CONTACT (DEPARTMENT_ID, [TYPE], VALUE) VALUES(3, 'EMAIL', 'Informatik@sag-austria.at');
INSERT INTO dbo.FEEDBACK_DEPARTMENT_CONTACT (DEPARTMENT_ID, [TYPE], VALUE) VALUES(4, 'EMAIL', 'Informatik@sag-austria.at');
INSERT INTO dbo.FEEDBACK_DEPARTMENT_CONTACT (DEPARTMENT_ID, [TYPE], VALUE) VALUES(5, 'EMAIL', 'Informatik@sag-austria.at');
INSERT INTO dbo.FEEDBACK_DEPARTMENT_CONTACT (DEPARTMENT_ID, [TYPE], VALUE) VALUES(6, 'EMAIL', 'Informatik@sag-austria.at');
INSERT INTO dbo.FEEDBACK_DEPARTMENT_CONTACT (DEPARTMENT_ID, [TYPE], VALUE) VALUES(7, 'EMAIL', 'Informatik@sag-austria.at');
