--Prepare bulb, oil, battery permission and functions
UPDATE ESHOP_PERMISSION SET PERMISSION = 'OFFER', DESCRIPTION = 'Permission to work with offer module' WHERE PERMISSION = 'ManageOffer';
UPDATE ESHOP_PERMISSION SET PERMISSION = 'HOME', DESCRIPTION = 'Permission to work with home module' WHERE PERMISSION = 'home';
INSERT INTO ESHOP_PERMISSION(PERMISSION, DESCRIPTION, CREATED_BY, PERMISSION_KEY) VALUES('BULB', 'Permission to work with bulb module', 1, 'BULB');
INSERT INTO ESHOP_PERMISSION(PERMISSION, DESCRIPTION, CREATED_BY, PERMISSION_KEY) VALUES('OIL', 'Permission to work with oil module', 1, 'OIL');
INSERT INTO ESHOP_PERMISSION(PERMISSION, DESCRIPTION, CREATED_BY, PERMISSION_KEY) VALUES('BATTERY', 'Permission to work with oil battery', 1, 'BATTERY');

UPDATE ESHOP_FUNCTION SET FUNCTION_NAME = 'OFFER' WHERE FUNCTION_NAME = 'ManageOffer';
UPDATE ESHOP_FUNCTION SET FUNCTION_NAME = 'OFFER_DMS_API_ADD_CART_TO_OFFER', DESCRIPTION = 'Function to add shopping cart to offer'  WHERE FUNCTION_NAME = 'DmsToOffer';
UPDATE ESHOP_FUNCTION SET FUNCTION_NAME = 'HOME' WHERE FUNCTION_NAME = 'Home';
INSERT INTO ESHOP_FUNCTION(FUNCTION_NAME, DESCRIPTION, RELATIVE_URL) VALUES('BULB_API_SEARCH', 'Function to work with bulb search API at back-end', '/search/bulb**');
INSERT INTO ESHOP_FUNCTION(FUNCTION_NAME, DESCRIPTION, RELATIVE_URL) VALUES('BULB_URL_ACCESS', 'Function to work with bulbs url at front-end', '/bulbs');
INSERT INTO ESHOP_FUNCTION(FUNCTION_NAME, DESCRIPTION, RELATIVE_URL) VALUES('OIL_API_SEARCH', 'Function to work with oil search API at back-end', '/search/oil**');
INSERT INTO ESHOP_FUNCTION(FUNCTION_NAME, DESCRIPTION, RELATIVE_URL) VALUES('OIL_URL_ACCESS', 'Function to work with oil url at front-end', '/oil');
INSERT INTO ESHOP_FUNCTION(FUNCTION_NAME, DESCRIPTION, RELATIVE_URL) VALUES('BATTERY_API_SEARCH', 'Function to work with battery search API at back-end', 'search/battery**');
INSERT INTO ESHOP_FUNCTION(FUNCTION_NAME, DESCRIPTION, RELATIVE_URL) VALUES('BATTERY_URL_ACCESS', 'Function to work with battery url at front-end', '/batteries');

DECLARE @bulbPermissionId INT = (SELECT ID FROM ESHOP_PERMISSION WHERE PERMISSION = 'BULB');
DECLARE @bulbApiSearchFunctionId INT = (SELECT ID FROM ESHOP_FUNCTION WHERE FUNCTION_NAME = 'BULB_API_SEARCH');
DECLARE @bulbUrlAccessFunctionId INT = (SELECT ID FROM ESHOP_FUNCTION WHERE FUNCTION_NAME = 'BULB_URL_ACCESS');
INSERT INTO PERM_FUNCTION(PERM_ID, FUNCTION_ID) VALUES(@bulbPermissionId, @bulbApiSearchFunctionId);
INSERT INTO PERM_FUNCTION(PERM_ID, FUNCTION_ID) VALUES(@bulbPermissionId, @bulbUrlAccessFunctionId);

DECLARE @oilPermissionId INT = (SELECT ID FROM ESHOP_PERMISSION WHERE PERMISSION = 'OIL');
DECLARE @oilApiSearchFunctionId INT = (SELECT ID FROM ESHOP_FUNCTION WHERE FUNCTION_NAME = 'OIL_API_SEARCH');
DECLARE @oilUrlAccessFunctionId INT = (SELECT ID FROM ESHOP_FUNCTION WHERE FUNCTION_NAME = 'OIL_URL_ACCESS');
INSERT INTO PERM_FUNCTION(PERM_ID, FUNCTION_ID) VALUES(@oilPermissionId, @oilApiSearchFunctionId);
INSERT INTO PERM_FUNCTION(PERM_ID, FUNCTION_ID) VALUES(@oilPermissionId, @oilUrlAccessFunctionId);

DECLARE @batteryPermissionId INT = (SELECT ID FROM ESHOP_PERMISSION WHERE PERMISSION = 'BATTERY');
DECLARE @batteryApiSearchFunctionId INT = (SELECT ID FROM ESHOP_FUNCTION WHERE FUNCTION_NAME = 'BATTERY_API_SEARCH');
DECLARE @batteryUrlAccessFunctionId INT = (SELECT ID FROM ESHOP_FUNCTION WHERE FUNCTION_NAME = 'BATTERY_URL_ACCESS');
INSERT INTO PERM_FUNCTION(PERM_ID, FUNCTION_ID) VALUES(@batteryPermissionId, @batteryApiSearchFunctionId);
INSERT INTO PERM_FUNCTION(PERM_ID, FUNCTION_ID) VALUES(@batteryPermissionId, @batteryUrlAccessFunctionId);


--set bulb, oil, battery permission for admin user, normal user
DECLARE @userAdminRoleId INT = (SELECT ID FROM ESHOP_ROLE WHERE NAME = 'USER_ADMIN');
DECLARE @normalUserRoleId INT = (SELECT ID FROM ESHOP_ROLE WHERE NAME = 'NORMAL_USER');

DECLARE @bulbPermissionId INT = (SELECT ID FROM ESHOP_PERMISSION WHERE PERMISSION = 'BULB');
INSERT INTO ROLE_PERMISSION(ROLE_ID, PERM_ID) VALUES(@userAdminRoleId, @bulbPermissionId);
INSERT INTO ROLE_PERMISSION(ROLE_ID, PERM_ID) VALUES(@normalUserRoleId, @bulbPermissionId);

DECLARE @oilPermissionId INT = (SELECT ID FROM ESHOP_PERMISSION WHERE PERMISSION = 'OIL');
INSERT INTO ROLE_PERMISSION(ROLE_ID, PERM_ID) VALUES(@userAdminRoleId, @oilPermissionId);
INSERT INTO ROLE_PERMISSION(ROLE_ID, PERM_ID) VALUES(@normalUserRoleId, @oilPermissionId);

DECLARE @batteryPermissionId INT = (SELECT ID FROM ESHOP_PERMISSION WHERE PERMISSION = 'BATTERY');
INSERT INTO ROLE_PERMISSION(ROLE_ID, PERM_ID) VALUES(@userAdminRoleId, @batteryPermissionId);
INSERT INTO ROLE_PERMISSION(ROLE_ID, PERM_ID) VALUES(@normalUserRoleId, @batteryPermissionId);