spring.profiles: actuator

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health,info,env,scheduledtasks,loggers"
        exclude: "shutdown,threaddump,heapdump"
      cors: 
        allowed-origins: "http://localhost:9001"
        allowed-methods: "GET"
    jmx:
      exposure:
        include: "health,info,env,scheduledtasks,loggers"
        exclude: "shutdown,threaddump,heapdump"
  endpoint:
    health:
      enabled: false
      show-details: always
  health:
    status:
      http-mapping:
        UP: 200
        DOWN: 500
        OUT_OF_SERVICE: 500
        UNKNOWN: 500
      order: DOWN,OUT_OF_SERVICE,UP,UNKNOWN
    diskspace:
      enabled: true
      threshold: 10
    elasticsearch:
      response-timeout: 5000ms
    mail.enabled: false
