spring.profiles: auth-endpoint-autonet-dev

#Authorization server to manage and verify tokens
sag:
  security:
    auth:
      # host: http://localhost:9002
      host: http://autonet.bbv-demo.ch/auth-server
      tokenUrl: /oauth/token
      checkTokenUrl: /oauth/check_token
      clientId: eshop-autonet
      clientSecret: eshop-autonet-yztAhGpFW

