spring.profiles: country-cz

country:
  code: cz
  supported_iso3_countries:
    - AUT
    - CHE
  hashtype: BLCK_VAR
  languages:
    - CS
    - EN
    - DE
  exclude_countries:
  attached_article:
    depot: true
    recycle: false
    vrg: false
    voc: false
  config:
    erp-type: TOP_MOTIVE
    user-loader-mode: ESHOP
    enable-shopping-cart-map-store: true
    enable-local-stock-availability-preferring: false    
    enable-price-discount-promotion: false
    es-external-article-service: default
    category-converter: default
    oauth2-external-authenticator: default
    article-id-mapper: id_pim
    currency: Kč
    default-language: cs
    register-customer-user-setting:
      customer-setting: 
        session-timeout-seconds: 14400
        net-price-view: true
        net-price-confirm: true
      user-setting: 
        language: cs
    sortingOilVehicleInDesc: false