//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.26 at 09:50:19 AM ICT 
//


package com.sagag.services.mdm.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ExecuteXmlResult" type="{http://schemas.datacontract.org/2004/07/WebServiceV4.GetBack}GetBackXml" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "executeXmlResult"
})
@XmlRootElement(name = "ExecuteXmlResponse")
public class ExecuteXmlResponse {

    @XmlElementRef(name = "ExecuteXmlResult", namespace = "http://tempuri.org/", type = JAXBElement.class, required = false)
    protected JAXBElement<GetBackXml> executeXmlResult;

    /**
     * Gets the value of the executeXmlResult property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link GetBackXml }{@code >}
     *     
     */
    public JAXBElement<GetBackXml> getExecuteXmlResult() {
        return executeXmlResult;
    }

    /**
     * Sets the value of the executeXmlResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link GetBackXml }{@code >}
     *     
     */
    public void setExecuteXmlResult(JAXBElement<GetBackXml> value) {
        this.executeXmlResult = value;
    }

}
