export enum DATE_FILTER {
    ALL = 'ALL',
    TODAY = 'TODAY',
    TWO_DAYS = 'TWO_DAYS',
    LAST_WEEK = 'LAST_WEEK',
    LAST_QUATER = 'LAST_QUATER',
    SEVEN_DAYS = 'SEVEN_DAYS',
    LAST_SIX_MONTHS = 'LAST_SIX_MONTHS',
    THIRTY_DAYS = 'THIRTY_DAYS',
    THIRTYONE_DAYS = 'THIRTYONE_DAYS',
    ADD_THIRTYONE_DAYS = 'ADD_THIRTYONE_DAYS'
}
