export enum ESHOP_ROLES {
    SYSTEM_ADMIN = 'SYSTEM_ADMIN',
    GROUP_ADMIN = 'GROUP_ADMIN',
    USER_ADMIN = 'USER_ADMIN',
    SALES_ASSISTANT = 'SALES_ASSISTANT',
    MARKETING_ASSISTANT = 'MARKETING_ASSISTANT',
    NORMAL_USER = 'NORMAL_USER'
}
