spring.profiles: gtmotive-cz-dev

external:
  webservice:
    ## production: info@normauto.ch
    normautoAddress: chau.le@bbv.vn
# GTMotive connection
    gtmotive:
      url: https://estimate.mygtmotive.com/webservice/GtInterfaceWS.asmx
      multilang: true
      accounts:
        cs:
          clientid: SAG_CZ
          userid: ctlgdevcz
          password: FC3306DA3A
          gsId: SGS029700N
        de:
          clientid: SAG_CZ
          userid: ctlgdevde
          password: FC3306DA3A
          gsId: SGS029700N
        en:
          clientid: SAG_CZ
          userid: ctlgdeven
          password: FC3306DA3A
          gsId: SGS029700N
    vehicle:
      url: https://wsgti.gtestimate.com/WSGtVehicleInformationService.svc
      gsId: SGS029700N
      password: FC3306DA3A
      customerId: SAG_CZ
      userId: wsuserdevcz
    gtmotive-main-module:
      url: https://wsgti.gtestimate.com/WSGtService.svc
      accounts:
        cs:
          clientid: SAG_CZ
          userid: wsuserdevcz
          password: FC3306DA3A
          gsId: SGS029700N
        de:
          clientid: SAG_CZ
          userid: wsuserdevde
          password: FC3306DA3A
          gsId: SGS029700N
        en:
          clientid: SAG_CZ
          userid: wsuserdeven
          password: FC3306DA3A
          gsId: SGS029700N
