spring.profiles: gtmotive-ch-prod

external:
  webservice:
    ## production: bestellung@normauto.ch
    normautoAddress: bestellungen@normauto.ch
# GTMotive connection
    gtmotive:
      url: https://estimate.mygtmotive.com/webservice/GtInterfaceWS.asmx
      multilang: true
      accounts:
        de:
          clientid: SAG_CH
          userid: ctlgpro
          password: FC3306DA3A
          gsId: SGS029700N
        fr:
          clientid: SAG_CH
          userid: ctlgprofr
          password: FC3306DA3A
          gsId: SGS029700N
        it:
          clientid: SAG_CH
          userid: ctlgproit
          password: FC3306DA3A
          gsId: SGS029700N
    vehicle:
      url: https://wsgti.gtestimate.com/WSGtVehicleInformationService.svc
      gsId: SGS029700N
      password: FC3306DA3A
      customerId: SAG_CH
      userId: skendallsw
    gtmotive-main-module:
      url: https://wsgti.gtestimate.com/WSGtService.svc
      accounts:
        de:
          clientid: SAG_CH
          userid: wsuserpro
          password: FC3306DA3A
          gsId: SGS029700N
        fr:
          clientid: SAG_CH
          userid: wsuserprofr
          password: FC3306DA3A
          gsId: SGS029700N
        it:
          clientid: SAG_CH
          userid: wsuserproit
          password: FC3306DA3A
          gsId: SGS029700N
