-- Master data for VIN-license
INSERT INTO [dbo].[LICENSE_SETTINGS] (PACK_ID, PACK_NAME, product_Parameters, PACK_ARTICLE_ID, PACK_ARTICLE_NO, PACK_UMAR_ID, QUANTITY, LAST_UPDATE, LAST_UPDATED_BY, TYPE_OF_LICENSE)
VALUES (2, 'VIN-20', 'product_Parameters 2', 1001322974, 'PACK_ARTICLE_NO 2', '', 20, '2018-10-25', 1, 'VIN');
