
/** PLEASE JUST RUN FOR PRO ENV
UPDATE FEEDBACK_DEPARTMENT SET DEPARTMENT_CODE='PRICING' WHERE DEPARTMENT_CODE='PRICING_DEPT';
UPDATE FEEDBACK_DEPARTMENT SET DEPARTMENT_CODE='AFFILIATE_BRANCH_C4S_AT' WHERE DEPARTMENT_CODE='AFFILIATE_BRANCH_C4S_CH';
UPDATE FEEDBACK_DEPARTMENT_CONTACT SET VALUE='data-analysis-pricing@sag-ag.at' WHERE ID = (SELECT FDC.ID FROM FEEDBACK_DEPARTMENT_CONTACT FDC JOIN FEEDBACK_DEPARTMENT FD ON(FDC.DEPARTMENT_ID=FD.ID AND FD.DEPARTMENT_CODE='PRICING'));
UPDATE FEEDBACK_DEPARTMENT_CONTACT SET VALUE='connect4sales@sag-ag.at' WHERE ID = (SELECT FDC.ID FROM FEEDBACK_DEPARTMENT_CONTACT FDC JOIN FEEDBACK_DEPARTMENT FD ON(FDC.DEPARTMENT_ID=FD.ID AND FD.DEPARTMENT_CODE='AFFILIATE_BRANCH_C4S_AT'));
UPDATE FEEDBACK_DEPARTMENT_CONTACT SET VALUE='Informatik@sag-austria.at' WHERE ID = (SELECT FDC.ID FROM FEEDBACK_DEPARTMENT_CONTACT FDC JOIN FEEDBACK_DEPARTMENT FD ON(FDC.DEPARTMENT_ID=FD.ID AND FD.DEPARTMENT_CODE='AFFILIATE_BRANCH_DERENDINGER_AT'));
UPDATE FEEDBACK_DEPARTMENT_CONTACT SET VALUE='Informatik@sag-austria.at' WHERE ID = (SELECT FDC.ID FROM FEEDBACK_DEPARTMENT_CONTACT FDC JOIN FEEDBACK_DEPARTMENT FD ON(FDC.DEPARTMENT_ID=FD.ID AND FD.DEPARTMENT_CODE='AFFILIATE_BRANCH_MATIK_AT'));
UPDATE FEEDBACK_DEPARTMENT_CONTACT SET VALUE='dataconnect@sag-ag.at' WHERE ID = (SELECT FDC.ID FROM FEEDBACK_DEPARTMENT_CONTACT FDC JOIN FEEDBACK_DEPARTMENT FD ON(FDC.DEPARTMENT_ID=FD.ID AND FD.DEPARTMENT_CODE='DATA_SUPPORT'));
UPDATE FEEDBACK_DEPARTMENT_CONTACT SET VALUE='hotline@sag-ag.at' WHERE ID = (SELECT FDC.ID FROM FEEDBACK_DEPARTMENT_CONTACT FDC JOIN FEEDBACK_DEPARTMENT FD ON(FDC.DEPARTMENT_ID=FD.ID AND FD.DEPARTMENT_CODE='TECH_POOL'));
UPDATE FEEDBACK_DEPARTMENT_CONTACT SET VALUE='servicedesk@sag-ag.at' WHERE ID = (SELECT FDC.ID FROM FEEDBACK_DEPARTMENT_CONTACT FDC JOIN FEEDBACK_DEPARTMENT FD ON(FDC.DEPARTMENT_ID=FD.ID AND FD.DEPARTMENT_CODE='SERVICE_DESK'));

ALTER TABLE dbo.FEEDBACK DROP CONSTRAINT FK_TOPIC_ID;
TRUNCATE TABLE dbo.FEEDBACK_TOPIC;
INSERT INTO dbo.FEEDBACK_TOPIC (TOPIC_CODE, DESCRIPTION) VALUES('PRICING', 'Pricing');
INSERT INTO dbo.FEEDBACK_TOPIC (TOPIC_CODE, DESCRIPTION) VALUES('ORDERS_AVAILABILITY', 'Orders, Availability');
INSERT INTO dbo.FEEDBACK_TOPIC (TOPIC_CODE, DESCRIPTION) VALUES('EASE_OF_USE', 'Ease of use');
INSERT INTO dbo.FEEDBACK_TOPIC (TOPIC_CODE, DESCRIPTION) VALUES('MISSING_WRONG_DATA', 'Missing/wrong data (vehicle, part, range of goods etc.)');
INSERT INTO dbo.FEEDBACK_TOPIC (TOPIC_CODE, DESCRIPTION) VALUES('LICENSING', 'Licensing (HaynesPro, VIN etc.)');
INSERT INTO dbo.FEEDBACK_TOPIC (TOPIC_CODE, DESCRIPTION) VALUES('SYSTEM_BROWSER_INTERFACES', 'System, Browser, Interfaces');
INSERT INTO dbo.FEEDBACK_TOPIC (TOPIC_CODE, DESCRIPTION) VALUES('PROFILE_SETTINGS', 'Profile, Settings');
INSERT INTO dbo.FEEDBACK_TOPIC (TOPIC_CODE, DESCRIPTION) VALUES('BONUS_MILES_PROGRAM', 'Bonus/Miles Program');
INSERT INTO dbo.FEEDBACK_TOPIC (TOPIC_CODE, DESCRIPTION) VALUES('OTHER', 'Other...');
ALTER TABLE dbo.FEEDBACK ADD CONSTRAINT FK_TOPIC_ID FOREIGN KEY (TOPIC_ID) REFERENCES dbo.FEEDBACK_TOPIC (ID);

DECLARE @orderAvailabilityTopicId INT = (SELECT ID FROM FEEDBACK_TOPIC WHERE TOPIC_CODE = 'ORDERS_AVAILABILITY');
DECLARE @ddatAffbranchId INT = (SELECT ID FROM FEEDBACK_DEPARTMENT WHERE DEPARTMENT_CODE = 'AFFILIATE_BRANCH_DERENDINGER_AT');
DECLARE @matikatAffbranchId INT = (SELECT ID FROM FEEDBACK_DEPARTMENT WHERE DEPARTMENT_CODE = 'AFFILIATE_BRANCH_MATIK_AT');
DECLARE @c4satAffbranchId INT = (SELECT ID FROM FEEDBACK_DEPARTMENT WHERE DEPARTMENT_CODE = 'AFFILIATE_BRANCH_C4S_AT');
INSERT INTO FEEDBACK_TOPIC_DEPARTMENT (DEPARTMENT_ID, TOPIC_ID) VALUES(@ddatAffbranchId, @orderAvailabilityTopicId);
INSERT INTO FEEDBACK_TOPIC_DEPARTMENT (DEPARTMENT_ID, TOPIC_ID) VALUES(@matikatAffbranchId, @orderAvailabilityTopicId);
INSERT INTO FEEDBACK_TOPIC_DEPARTMENT (DEPARTMENT_ID, TOPIC_ID) VALUES(@c4satAffbranchId, @orderAvailabilityTopicId);


TRUNCATE TABLE dbo.FEEDBACK_TOPIC_DEPARTMENT
DECLARE @deptDDAT INT = (SELECT  ID FROM FEEDBACK_DEPARTMENT WHERE DEPARTMENT_CODE='AFFILIATE_BRANCH_DERENDINGER_AT');
DECLARE @deptMAT INT = (SELECT  ID FROM FEEDBACK_DEPARTMENT WHERE DEPARTMENT_CODE='AFFILIATE_BRANCH_MATIK_AT');
DECLARE @deptC4SAT INT = (SELECT  ID FROM FEEDBACK_DEPARTMENT WHERE DEPARTMENT_CODE='AFFILIATE_BRANCH_C4S_AT');
DECLARE @deptTechPool INT = (SELECT  ID FROM FEEDBACK_DEPARTMENT WHERE DEPARTMENT_CODE='TECH_POOL');
DECLARE @deptServiceDesk INT = (SELECT  ID FROM FEEDBACK_DEPARTMENT WHERE DEPARTMENT_CODE='SERVICE_DESK');

DECLARE @topicPricing INT = (SELECT  ID FROM FEEDBACK_TOPIC WHERE TOPIC_CODE='PRICING');
DECLARE @deptPricing INT = (SELECT  ID FROM FEEDBACK_DEPARTMENT WHERE DEPARTMENT_CODE='PRICING');
INSERT INTO dbo.FEEDBACK_TOPIC_DEPARTMENT (TOPIC_ID, DEPARTMENT_ID) VALUES(@topicPricing, @deptPricing);

DECLARE @topicOrderAvai INT = (SELECT  ID FROM FEEDBACK_TOPIC WHERE TOPIC_CODE='ORDERS_AVAILABILITY');
INSERT INTO dbo.FEEDBACK_TOPIC_DEPARTMENT (TOPIC_ID, DEPARTMENT_ID) VALUES(@topicOrderAvai, @deptDDAT);
INSERT INTO dbo.FEEDBACK_TOPIC_DEPARTMENT (TOPIC_ID, DEPARTMENT_ID) VALUES(@topicOrderAvai, @deptMAT);
INSERT INTO dbo.FEEDBACK_TOPIC_DEPARTMENT (TOPIC_ID, DEPARTMENT_ID) VALUES(@topicOrderAvai, @deptC4SAT);

DECLARE @topicEaseOfUse INT = (SELECT  ID FROM FEEDBACK_TOPIC WHERE TOPIC_CODE='EASE_OF_USE');
INSERT INTO dbo.FEEDBACK_TOPIC_DEPARTMENT (TOPIC_ID, DEPARTMENT_ID) VALUES(@topicEaseOfUse, @deptDDAT);
INSERT INTO dbo.FEEDBACK_TOPIC_DEPARTMENT (TOPIC_ID, DEPARTMENT_ID) VALUES(@topicEaseOfUse, @deptMAT);
INSERT INTO dbo.FEEDBACK_TOPIC_DEPARTMENT (TOPIC_ID, DEPARTMENT_ID) VALUES(@topicEaseOfUse, @deptC4SAT);

DECLARE @topicOther INT = (SELECT  ID FROM FEEDBACK_TOPIC WHERE TOPIC_CODE='OTHER');
INSERT INTO dbo.FEEDBACK_TOPIC_DEPARTMENT (TOPIC_ID, DEPARTMENT_ID) VALUES(@topicOther, @deptDDAT);
INSERT INTO dbo.FEEDBACK_TOPIC_DEPARTMENT (TOPIC_ID, DEPARTMENT_ID) VALUES(@topicOther, @deptMAT);
INSERT INTO dbo.FEEDBACK_TOPIC_DEPARTMENT (TOPIC_ID, DEPARTMENT_ID) VALUES(@topicOther, @deptC4SAT);

DECLARE @topicDataIssue INT = (SELECT  ID FROM FEEDBACK_TOPIC WHERE TOPIC_CODE='MISSING_WRONG_DATA');
DECLARE @deptDataSupport INT = (SELECT  ID FROM FEEDBACK_DEPARTMENT WHERE DEPARTMENT_CODE='DATA_SUPPORT');
INSERT INTO dbo.FEEDBACK_TOPIC_DEPARTMENT (TOPIC_ID, DEPARTMENT_ID) VALUES(@topicDataIssue, @deptDataSupport);

DECLARE @topicSystemBrowserInterface INT = (SELECT  ID FROM FEEDBACK_TOPIC WHERE TOPIC_CODE='SYSTEM_BROWSER_INTERFACES');
INSERT INTO dbo.FEEDBACK_TOPIC_DEPARTMENT (TOPIC_ID, DEPARTMENT_ID) VALUES(@topicSystemBrowserInterface, @deptTechPool);

DECLARE @topicLicense INT = (SELECT  ID FROM FEEDBACK_TOPIC WHERE TOPIC_CODE='LICENSING');
INSERT INTO dbo.FEEDBACK_TOPIC_DEPARTMENT (TOPIC_ID, DEPARTMENT_ID) VALUES(@topicLicense, @deptTechPool);

DECLARE @topicProfileSetting INT = (SELECT  ID FROM FEEDBACK_TOPIC WHERE TOPIC_CODE='PROFILE_SETTINGS');
INSERT INTO dbo.FEEDBACK_TOPIC_DEPARTMENT (TOPIC_ID, DEPARTMENT_ID) VALUES(@topicProfileSetting, @deptServiceDesk);

DECLARE @topicBonusMilesProgram INT = (SELECT  ID FROM FEEDBACK_TOPIC WHERE TOPIC_CODE='BONUS_MILES_PROGRAM');
INSERT INTO dbo.FEEDBACK_TOPIC_DEPARTMENT (TOPIC_ID, DEPARTMENT_ID) VALUES(@topicBonusMilesProgram, @deptServiceDesk);

