# ************************************************************************
# This is the SB configuration of OAuth2 application for Development mode.
# 
# Required Common configuration:
# - Application common configuration - 
# - ERP - 
# - Elasticsearch - 
# - Database - 
# - Thread Executor Pool - 
# - Liquibase - 
# - Logging - 
# - Actuator Healthcheck - 
# - Caching - 
# - Country Code - 
# - Proxy - 
# - Java Melody Monitoring -
#
# ************************************************************************
spring.profiles.include: 
  sagauth,
  wint-dev,
  elasticsearch-dev,
  db-dev,
  executor-pool,
  no-liquibase,
  logging-sb-dev,
  actuator,
  cache-dev,
  country-sb,
  no-proxy,
  javamelody

spring.banner.location: classpath:banner/banner_sb.txt
