export enum RETURN_REASON {
    DEFECT = 'DEFECT',
    INCORRECT_FEED_LINE = 'INCORRECT_FEED_LINE',
    FALSE_ARTICLE = 'FALSE_ARTICLE',
    WRONG_AMOUNT = 'WRONG_AMOUNT',
    SELECTION = 'SELECTION',
    NOT_USED = 'NOT_USED',
    SUPPLIER_CALLBACK = 'SUPPLIER_CALLBACK',
    ALTERNATIVE = 'ALTERNATIVE',
    AIS_RETOUR = 'AIS_RETOUR',
    REPAIR = 'REPAIR',
}