USE [ax]
--GO
/*
DROP TABLE [dbo].[ORGANISATION_GROUP]
DROP TABLE [dbo].[GROUP_USER]
DROP TABLE [dbo].[GROUP_ROLE]
DROP TABLE [dbo].[ROLE_PERMISSION]
DROP TABLE [dbo].[PERM_FUNCTION]
DROP TABLE [dbo].[ORGANISATION_ADDRESS]
DROP TABLE [dbo].[ESHOP_PERMISSION]
DROP TABLE [dbo].[ESHOP_GROUP]
DROP TABLE [dbo].[USER_ARTICLE_HISTORY]
DROP TABLE [dbo].[USER_VEHICLE_HISTORY]
DROP TABLE [dbo].[USER_ORDER_HISTORY]
DROP TABLE [dbo].[ARTICLE_HISTORY]
DROP TABLE [dbo].[VEHICLE_HISTORY]
DROP TABLE [dbo].[ORDER_HISTORY]
DROP TABLE [dbo].[BASKET_HISTORY]
DROP TABLE [dbo].[ORDER_STATUS]
DROP TABLE [dbo].[ORDER_TYPE]
DROP TABLE [dbo].[LOGIN]
DROP TABLE [dbo].[ESHOP_USER]
DROP TABLE [dbo].[ESHOP_ROLE]
DROP TABLE [dbo].[ROLE_TYPE]
DROP TABLE [dbo].[ESHOP_FUNCTION]
DROP TABLE [dbo].[ADDRESS]
DROP TABLE [dbo].[ADDRESS_TYPE]
DROP TABLE [dbo].[ORGANISATION]
DROP TABLE [dbo].[ORGANISATION_TYPE]
DROP TABLE [dbo].[ORGANISATION_SETTINGS]
DROP TABLE [dbo].[CUSTOMER_SETTINGS]
DROP TABLE [dbo].[ALLOCATION_TYPE]
DROP TABLE [dbo].[PAYMENT_METHOD]
DROP TABLE [dbo].[DELIVERY_TYPE]
DROP TABLE [dbo].[COLLECTIVE_DELIVERY]
DROP TABLE [dbo].[COUPON_CONDITIONS]
DROP TABLE [dbo].[LANGUAGES]
DROP TABLE [dbo].[SALUTATION]
DROP TABLE [dbo].[COUPON_USE_LOG]
DROP TABLE [dbo].[ESHOP_CART_ITEM]
DROP TABLE [dbo].[VIN_LOGGING]
DROP TABLE [dbo].[BUSINESS_LOG]
DROP TABLE [dbo].[EXTERNAL_ORGANISATION]
DROP TABLE [dbo].[EXTERNAL_USER]
DROP TABLE [dbo].[ESHOP_RELEASE]
*/
/****** Object:  Table [dbo].[ADDRESS]    Script Date: 7/4/2017 12:04:18 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[ADDRESS](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [LINE1] [varchar](150) NULL,
    [LINE2] [varchar](50) NULL,
    [LINE3] [varchar](50) NULL,
    [COUNTRYISO] [char](3) NULL,
    [STATE] [varchar](50) NULL,
    [CITY] [varchar](50) NULL,
    [ZIPCODE] [varchar](10) NULL,
    [ADDRESS_TYPE_ID] [int] NULL,
 CONSTRAINT [PK_ADDRESS] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[ADDRESS_TYPE]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[ADDRESS_TYPE](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [TYPE] [varchar](45) NULL,
    [DESCRIPTION] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[ALLOCATION_TYPE]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[ALLOCATION_TYPE](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [TYPE] [varchar](50) NOT NULL,
    [DESC_CODE] [varchar](255) NOT NULL,
    [DESCRIPTION] [varchar](255) NULL,
 CONSTRAINT [PK_ALLOCATION_TYPE] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[ARTICLE_HISTORY]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[ARTICLE_HISTORY](
    [ID] [bigint] IDENTITY(1,1) NOT NULL,
    [ART_NUMBER] [varchar](50) NULL,
    [ART_ID] [varchar](50) NULL,
    [ART_SAG_SYS_ID] [varchar](50) NULL,
    [MANUFACTURE] [varchar](255) NULL,
    [ART_IMG] [varchar](255) NULL,
    [VEHICLE_INFO] [varchar](255) NULL,
    [GROSS_PRICE] [decimal](18, 2) NULL,
    [MENGE] [int] NULL,
    [DELIVERY_INFO] [varchar](255) NULL,
    [REFERENCE] [varchar](255) NULL,
 CONSTRAINT [PK_ARTICLE_HISTORY] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[BASKET_HISTORY]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[BASKET_HISTORY](
    [ID] [bigint] IDENTITY(1,1) NOT NULL,
    [ART_ID_SAG_SYS] [varchar](50) NULL,
    [ART_UMAR_ID] [varchar](50) NULL,
    [PRICE] [decimal](18, 2) NULL,
    [QUANTITY] [int] NULL,
    [TOTAL] [decimal](18, 2) NULL,
    [VEHICLE_ID] [varchar](50) NULL,
    [PRODUCT] [varchar](255) NULL,
    [MANUFACTURE] [varchar](255) NULL,
    [ART_IMAGE] [varchar](255) NULL,
    [POSITION] [varchar](255) NULL,
    [MENGE] [int] NULL,
    [AVAILABILITY] [varchar](50) NULL,
    [ORDER_ID] [int] NOT NULL,
    [USER_ID] [bigint] NOT NULL,
 CONSTRAINT [PK_BASKET_HISTORY] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[COLLECTIVE_DELIVERY]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[COLLECTIVE_DELIVERY](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [TYPE] [varchar](max) NOT NULL,
    [DESC_CODE] [varchar](255) NOT NULL,
    [DESCRIPTION] [varchar](max) NULL,
 CONSTRAINT [PK_COLLECTIVE_DELIVERY] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[COUPON_CONDITIONS]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[COUPON_CONDITIONS](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [COUPON_CODE] [varchar](12) NOT NULL,
    [DATE_START] [datetime] NOT NULL,
    [DATE_END] [datetime] NOT NULL,
    [USAGE_COUNT] [int] NOT NULL,
    [USED_COUNT] [int] NOT NULL,
    [AMOUNT] [decimal](18, 2) NOT NULL,
    [PERCENTAGE] [int] NULL,
    [DISCOUNT_ARTICLE_ID] [bigint] NOT NULL,
    [MINIMUM_ORDER_AMOUNT] [decimal](18, 2) NOT NULL,
    [MAXIMUM_DISCOUNT] [decimal](18, 2) NULL,
    [BULK_QUANTITY_TRIGGER] [int] NULL,
    [BULK_QUANTITY_ARTICLE_ID] [bigint] NULL,
    [COUNTRY] [varchar](2) NULL,
    [AFFILIATE] [varchar](255) NOT NULL,
    [CUSTOMER_GROUP] [varchar](255) NULL,
    [CUSTOMER_NR] [bigint] NULL,
    [ARTICLE_CATEGORIES] [varchar](255) NULL,
    [ARTICLE_ID] [varchar](255) NULL,
    [BRANDS] [varchar](255) NULL,
    [UPDATED_BY] [varchar](255) NOT NULL,
    [DATE_OF_LAST_UPDATE] [datetime] NOT NULL,
    [CREATED_BY] [varchar](255) NOT NULL,
    [DATE_OF_CREATION] [datetime] NOT NULL,
    [UMAR_ID] [bigint] NOT NULL,
 CONSTRAINT [PK_COUPON_CONDITIONS] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [COUPON_CONDITIONS_COUPON_CODE_UNIQUE] UNIQUE NONCLUSTERED 
(
    [COUPON_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[COUPON_USE_LOG]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[COUPON_USE_LOG](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [COUPONS_CODE] [varchar](12) NULL,
    [DATE_USED] [datetime] NOT NULL,
    [USAGE_COUNT_REMAINDER] [int] NOT NULL,
    [AMOUNT_APPLIED] [decimal](18, 2) NULL,
    [DISCOUNT_ARTICLE_ID] [bigint] NOT NULL,
    [CUSTOMER_NR] [varchar](20) NULL,
    [USER_ID] [varchar](255) NOT NULL,
    [ORDER_CONFIRMATION_ID] [bigint] NULL,
    [ORDER_ID] [bigint] NULL,
    [COUNTRY_MATCH] [varchar](2) NULL,
    [AFFILIATE_MATCH] [varchar](255) NULL,
    [ARTICLE_CATEGORIES] [varchar](255) NULL,
    [ARTICLE_ID_MATCH] [varchar](255) NULL,
    [BRANDS_MATCH] [varchar](255) NULL,
    [UMAR_ID] [bigint] NOT NULL,
 CONSTRAINT [PK_COUPON_USE_LOG] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[CUSTOMER_SETTINGS]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[CUSTOMER_SETTINGS](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [ALLOCATION_ID] [int] NOT NULL,
    [PAYMENT_METHOD] [int] NOT NULL,
    [DELIVERY_ID] [int] NOT NULL,
    [COLLECTIVE_DELIVERY_ID] [int] NOT NULL,
    [NET_PRICE_VIEW] [bit] NOT NULL,
    [NET_PRICE_CONFIRM] [bit] NOT NULL,
    [VIEW_BILLING] [bit] NOT NULL,
    [ADDRESS_ID] [bit] NOT NULL,
    [USE_DEFAULT_SETTING] [bit] NOT NULL,
    [EMAIL_NOTIFICATION_ORDER] [bit] NOT NULL,
    [BILLING_ADDRESS_ID] [varchar](19) NULL,
    [DELIVERY_ADDRESS_ID] [varchar](19) NULL,
    [INVOICE_ID] [int] NOT NULL,
    [ALLOW_NET_PRICE_CHANGED] [bit] NOT NULL,
    [INVOICE_TYPE] [int] NOT NULL,
    [SHOW_DISCOUNT] [bit] NOT NULL,
    [SESSION_TIMEOUT_SECONDS] [int] NOT NULL,
 CONSTRAINT [PK_ORG_ORDER_SETTINGS] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[DELIVERY_TYPE]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[DELIVERY_TYPE](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [TYPE] [varchar](50) NOT NULL,
    [DESC_CODE] [varchar](255) NOT NULL,
    [DESCRIPTION] [varchar](255) NULL,
 CONSTRAINT [PK_DELIVERY_TYPE] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[ESHOP_CART_ITEM]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING OFF
--GO
CREATE TABLE [dbo].[ESHOP_CART_ITEM](
    [ID] [bigint] IDENTITY(1,1) NOT NULL,
    [CART_KEY] [varchar](300) NOT NULL,
    [USER_NAME] [varchar](255) NOT NULL,
    [CUSTOMER_NR] [bigint] NULL,
    [QUANTITY] [int] NULL,
    [ARTICLE_JSON] [varchar](max) NOT NULL,
    [ADDED_TIME] [datetime] NOT NULL,
    [CATEGORY_JSON] [varchar](max) NULL,
    [VEHICLE_JSON] [varchar](max) NULL,
    [ITEM_DESC] [varchar](max) NULL,
    [ITEM_TYPE] [varchar](50) NULL,
    [CHILD_JSON] [varchar](max) NULL
 CONSTRAINT [PK_ESHOP_CART_ITEM] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]; 

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[ESHOP_FUNCTION]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[ESHOP_FUNCTION](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [FUNCTION_NAME] [varchar](45) NULL,
    [DESCRIPTION] [varchar](255) NULL,
    [RELATIVE_URL] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[ESHOP_GROUP]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[ESHOP_GROUP](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [NAME] [varchar](45) NULL,
    [DESCRIPTION] [varchar](255) NULL,
    [ORG_CODE] [varchar](20) NULL,
    [ROLE_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [GROUP_ID_UNIQUE] UNIQUE NONCLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[ESHOP_PERMISSION]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[ESHOP_PERMISSION](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [PERMISSION] [varchar](45) NULL,
    [DESCRIPTION] [varchar](255) NULL,
    [CREATED_BY] [varchar](45) NULL,
    [CREATED_DATE] [datetime] NULL,
    [MODIFIED_BY] [varchar](45) NULL,
    [MODIFIED_DATE] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [RIGHTS_ID_UNIQUE] UNIQUE NONCLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[ESHOP_ROLE]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[ESHOP_ROLE](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [NAME] [varchar](45) NULL,
    [ROLE_TYPE_ID] [int] NOT NULL,
    [DESCRIPTION] [varchar](255) NULL,
 CONSTRAINT [PK_ESHOP_ROLE] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[ESHOP_USER]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[ESHOP_USER](
    [ID] [bigint] IDENTITY(1,1) NOT NULL,
    [SALUTATION] [int] NULL,
    [FIRST_NAME] [varchar](45) NULL,
    [LAST_NAME] [varchar](45) NULL,
    [EMAIL] [varchar](255) NULL,
    [USERNAME] [varchar](255) NULL,
    [PHONE] [varchar](45) NULL,
    [LANGUAGE] [int] NULL,
    [TYPE] [varchar](45) NULL,
    [HOURLY_RATE] [int] NULL,
    [EMAIL_CONFIRMATION] [bit] NULL,
    [NEWSLETTER] [bit] NULL,
    [SETTING] [int] NULL,
    [AGE] [int] NULL,
    [VAT_CONFIRM] [bit] NULL,
 CONSTRAINT [PK_ESHOP_USER] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [USERS_ID_UNIQUE] UNIQUE NONCLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[EXTERNAL_ORGANISATION]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[EXTERNAL_ORGANISATION](
    [ID] [bigint] IDENTITY(1,1) NOT NULL,
    [ORG_ID] [int] NOT NULL,
    [EXTERNAL_CUSTOMER_ID] [varchar](255) NOT NULL,
    [EXTERNAL_APP] [varchar](255) NOT NULL,
    [EXTERNAL_CUSTOMER_NAME] [varchar](255) NULL,
 CONSTRAINT [EXTERNAL_ORGANISATION_PK] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[EXTERNAL_USER]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[EXTERNAL_USER](
    [ID] [bigint] IDENTITY(1,1) NOT NULL,
    [ESHOP_USER_ID] [bigint] NOT NULL,
    [USERNAME] [varchar](255) NOT NULL,
    [PASSWORD] [varchar](255) NOT NULL,
    [EXTERNAL_APP] [varchar](255) NOT NULL,
    [ACTIVE] [bit] NOT NULL,
    [CREATED_DATE] [datetime] NOT NULL,
 CONSTRAINT [EXTERNAL_USER_PK] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[GROUP_ROLE]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
CREATE TABLE [dbo].[GROUP_ROLE](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [GROUP_ID] [int] NOT NULL,
    [ROLE_ID] [int] NOT NULL,
 CONSTRAINT [PK_GROUP_ROLE] PRIMARY KEY CLUSTERED 
(
    [GROUP_ID] ASC,
    [ROLE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
/****** Object:  Table [dbo].[GROUP_USER]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
CREATE TABLE [dbo].[GROUP_USER](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [GROUP_ID] [int] NOT NULL,
    [USER_ID] [bigint] NOT NULL,
 CONSTRAINT [PK_GROUP_USER] PRIMARY KEY CLUSTERED 
(
    [ID] ASC,
    [GROUP_ID] ASC,
    [USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
/****** Object:  Table [dbo].[INVOICE_TYPE]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[INVOICE_TYPE](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [INVOICE_TYPE_CODE] [varchar](50) NOT NULL,
    [INVOICE_TYPE_NAME] [varchar](50) NOT NULL,
    [INVOICE_TYPE_DESC] [varchar](255) NULL,
 CONSTRAINT [PK_INVOICE_TYPE] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[LANGUAGES]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[LANGUAGES](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [LANGCODE] [varchar](255) NULL,
    [LANGISO] [varchar](255) NULL,
    [DESCRIPTION] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[LICENSE]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[LICENSE](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [TYPE_OF_LICENSE] [char](50) NOT NULL,
    [PACK_ID] [bigint] NOT NULL,
    [PACK_NAME] [char](50) NOT NULL,
    [CUSTOMER_NR] [bigint] NOT NULL,
    [USER_ID] [bigint] NOT NULL,
    [BEGIN_DATE] [datetime] NOT NULL,
    [END_DATE] [datetime] NOT NULL,
    [QUANTITY] [int] NOT NULL,
    [QUANTITY_USED] [int] NOT NULL,
    [LAST_USED] [datetime] NULL,
    [LAST_UPDATE] [datetime] NOT NULL,
    [LAST_UPDATED_BY] [bigint] NOT NULL,
 CONSTRAINT [LICENSE_PK] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[LICENSE_SETTINGS]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[LICENSE_SETTINGS](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [PACK_ID] [bigint] NOT NULL,
    [PACK_NAME] [char](50) NOT NULL,
    [PRODUCT_PARAMETERS] [nvarchar](100) NOT NULL,
    [PACK_ARTICLE_ID] [bigint] NOT NULL,
    [PACK_ARTICLE_NO] [char](50) NOT NULL,
    [PACK_UMAR_ID] [bigint] NOT NULL,
    [QUANTITY] [int] NOT NULL,
    [LAST_UPDATE] [datetime] NOT NULL,
    [LAST_UPDATED_BY] [bigint] NOT NULL,
 CONSTRAINT [LICENSE_SETTINGS_PK] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
    [PACK_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[LOGIN]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[LOGIN](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [PASSWORD] [varchar](255) NULL,
    [USER_ID] [bigint] NOT NULL,
    [IS_USER_ACTIVE] [bit] NOT NULL,
    [hash_type] [varchar](255) NULL,
 CONSTRAINT [PK_LOGIN] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [LOGIN_ID_UNIQUE] UNIQUE NONCLUSTERED 
(
    [USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[MIGRATION_ESHOP_USER]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[MIGRATION_ESHOP_USER](
    [ID] [bigint] IDENTITY(1,1) NOT NULL,
    [USER_ID] [bigint] NOT NULL,
    [SALUTATION] [int] NULL,
    [FIRST_NAME] [varchar](255) NULL,
    [LAST_NAME] [varchar](255) NULL,
    [EMAIL] [varchar](255) NULL,
    [USERNAME] [varchar](255) NULL,
    [PHONE] [varchar](45) NULL,
    [LANGUAGE] [int] NULL,
    [TYPE] [varchar](45) NULL,
    [HOURLY_RATE] [decimal](19, 0) NULL,
    [EMAIL_CONFIRMATION] [bit] NULL,
    [NEWSLETTER] [bit] NULL,
    [NET_PRICE_VIEW] [bit] NULL,
    [NET_PRICE_CONFIRM] [bit] NULL,
    [DEFAULT_SETTING] [bit] NULL,
    [SETTING] [int] NULL,
    [AGE] [int] NULL,
    [ORGANISATION_ID] [varchar](50) NULL,
    [PASSWORD] [varchar](255) NULL,
    [VAT_CONFIRM] [bit] NOT NULL,
    [USER_ROLE] [varchar](50) NULL,
    [NEW_USER_ID] [bigint] NULL,
    [IS_MIGRATED] [bit] NOT NULL,
    [HAS_PARTNER_PROGRAM] [bit] NOT NULL,
 CONSTRAINT [PK_MIGRATION_ESHOP_USER] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[MIGRATION_LICENSE]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[MIGRATION_LICENSE](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [USER_ID] [bigint] NOT NULL,
    [TYPE_OF_LICENSE] [char](50) NOT NULL,
    [PACK_ID] [bigint] NOT NULL,
    [PACK_NAME] [char](50) NOT NULL,
    [CUSTOMER_NR] [bigint] NOT NULL,
    [BEGIN_DATE] [datetime] NOT NULL,
    [END_DATE] [datetime] NOT NULL,
    [QUANTITY] [int] NOT NULL,
    [QUANTITY_USED] [int] NOT NULL,
    [LAST_USED] [datetime] NULL,
    [LAST_UPDATE] [datetime] NOT NULL,
    [LAST_UPDATED_BY] [char](50) NOT NULL,
    [IS_MIGRATED] [bit] NOT NULL,
    [NEW_USER_ID] [bigint] NULL,
 CONSTRAINT [MIGRATE_LICENSE_PK] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[MIGRATION_ORGANISATION]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[MIGRATION_ORGANISATION](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [ORG_CODE] [varchar](20) NULL,
    [ORG_ID] [int] NOT NULL,
    [COMPANY_NAME] [varchar](150) NULL,
    [CUSTOMER_NAME] [varchar](255) NULL,
    [IS_MIGRATED] [bit] NOT NULL,
 CONSTRAINT [PK_MIGRATION_ORGANISATION] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[OAUTH_ACCESS_TOKEN]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[OAUTH_ACCESS_TOKEN](
    [TOKEN_ID] [varchar](256) NULL,
    [TOKEN] [varchar](max) NULL,
    [AUTHENTICATION_ID] [varchar](256) NULL,
    [USER_NAME] [varchar](256) NOT NULL,
    [CLIENT_ID] [varchar](256) NULL,
    [AUTHENTICATION] [varchar](max) NULL,
    [REFRESH_TOKEN] [varchar](max) NULL,
 CONSTRAINT [UC_USER_NAME] UNIQUE NONCLUSTERED 
(
    [USER_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[OAUTH_REFRESH_TOKEN]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[OAUTH_REFRESH_TOKEN](
    [TOKEN_ID] [varchar](256) NULL,
    [TOKEN] [varchar](max) NULL,
    [AUTHENTICATION] [varchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[ORDER_HISTORY]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[ORDER_HISTORY](
    [ID] [bigint] IDENTITY(1,1) NOT NULL,
    [ORDER_NUMBER] [varchar](50) NULL,
    [TRANS_NUMBER] [varchar](50) NULL,
    [USER_ID] [bigint] NULL,
    [CUSTOMER_NUMBER] [bigint] NOT NULL,
    [ORDER_INFO_JSON] [varchar](max) NULL,
    [ERP_ORDER_DETAIL_URL] [varchar](255) NULL,
    [SALE_ID] [bigint] NULL,
 CONSTRAINT [PK_ORDER_HISTORY] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[ORDER_STATUS]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[ORDER_STATUS](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [ORDER_STATUS] [varchar](50) NOT NULL,
    [DESC_CODE] [varchar](50) NOT NULL,
    [DESCRIPTION] [varchar](255) NULL,
 CONSTRAINT [PK_ORDER_STATUS] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[ORDER_TYPE]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[ORDER_TYPE](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [ORDER_TYPE] [varchar](50) NOT NULL,
    [DESC_CODE] [varchar](255) NOT NULL,
    [DESCRIPTION] [varchar](255) NULL,
 CONSTRAINT [PK_ORDER_TYPE] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[ORGANISATION]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[ORGANISATION](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [NAME] [varchar](150) NULL,
    [ORG_CODE] [varchar](20) NULL,
    [ORGTYPE_ID] [int] NOT NULL,
    [PARENT_ID] [int] NOT NULL,
    [DESCRIPTION] [varchar](255) NULL,
    [SHORTNAME] [varchar](45) NULL,
    [ORDER_SETTINGS_ID] [int] NULL,
 CONSTRAINT [PK_ORGANISATION] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UK_chd15mrfx7slue9vae2rvjs0i] UNIQUE NONCLUSTERED 
(
    [ORG_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[ORGANISATION_ADDRESS]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
CREATE TABLE [dbo].[ORGANISATION_ADDRESS](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [ORGANISATION_ID] [int] NOT NULL,
    [ADDRESS_ID] [int] NOT NULL,
 CONSTRAINT [PK_ORGANISATION_ADDRESS] PRIMARY KEY CLUSTERED 
(
    [ORGANISATION_ID] ASC,
    [ADDRESS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
/****** Object:  Table [dbo].[ORGANISATION_GROUP]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
CREATE TABLE [dbo].[ORGANISATION_GROUP](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [GROUP_ID] [int] NOT NULL,
    [ORGANISATION_ID] [int] NOT NULL,
 CONSTRAINT [PK_ORGANISATION_GROUP] PRIMARY KEY CLUSTERED 
(
    [ID] ASC,
    [GROUP_ID] ASC,
    [ORGANISATION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
/****** Object:  Table [dbo].[ORGANISATION_SETTINGS]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[ORGANISATION_SETTINGS](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [NAME] [varchar](50) NOT NULL,
    [ORGANISATION_ID] [int] NOT NULL,
    [SETTING_KEY] [varchar](255) NOT NULL,
    [SETTING_VALUE] [varchar](255) NULL,
 CONSTRAINT [PK_SETTINGS] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[ORGANISATION_TYPE]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[ORGANISATION_TYPE](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [NAME] [varchar](45) NULL,
    [LEVEL] [int] NULL,
    [DESCRIPTION] [varchar](255) NULL,
 CONSTRAINT [PK_ORGANISATION_TYPE] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [ORGTYPE_ID_UNIQUE] UNIQUE NONCLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [ORGTYPE_LEVEL_UNIQUE] UNIQUE NONCLUSTERED 
(
    [LEVEL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[PAYMENT_METHOD]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[PAYMENT_METHOD](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [PAY_METHOD] [varchar](50) NOT NULL,
    [DESC_CODE] [varchar](255) NOT NULL,
    [DESCRIPTION] [varchar](255) NULL,
 CONSTRAINT [PK_PAYMENT_METHOD] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[PERM_FUNCTION]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
CREATE TABLE [dbo].[PERM_FUNCTION](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [PERM_ID] [int] NOT NULL,
    [FUNCTION_ID] [int] NOT NULL,
 CONSTRAINT [PK_PERM_FUNCTION] PRIMARY KEY CLUSTERED 
(
    [PERM_ID] ASC,
    [FUNCTION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
/****** Object:  Table [dbo].[ROLE_PERMISSION]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
CREATE TABLE [dbo].[ROLE_PERMISSION](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [ROLE_ID] [int] NOT NULL,
    [PERM_ID] [int] NOT NULL,
 CONSTRAINT [PK_ROLE_PERMISSION] PRIMARY KEY CLUSTERED 
(
    [ROLE_ID] ASC,
    [PERM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
/****** Object:  Table [dbo].[ROLE_TYPE]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[ROLE_TYPE](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [NAME] [varchar](45) NULL,
    [DESCRIPTION] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [ID_UNIQUE] UNIQUE NONCLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[SALUTATION]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[SALUTATION](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [CODE] [varchar](50) NULL,
    [DESCRIPTION] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[USER_ARTICLE_HISTORY]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
CREATE TABLE [dbo].[USER_ARTICLE_HISTORY](
    [ID] [bigint] IDENTITY(1,1) NOT NULL,
    [USER_ID] [bigint] NOT NULL,
    [ART_HISTORY_ID] [bigint] NOT NULL,
 CONSTRAINT [PK_USER_ARTICLE_HISTORY] PRIMARY KEY CLUSTERED 
(
    [USER_ID] ASC,
    [ART_HISTORY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
/****** Object:  Table [dbo].[USER_ORDER_HISTORY]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
CREATE TABLE [dbo].[USER_ORDER_HISTORY](
    [ID] [bigint] IDENTITY(1,1) NOT NULL,
    [USER_ID] [bigint] NOT NULL,
    [ORDER_ID] [bigint] NOT NULL,
 CONSTRAINT [PK_USER_ORDER_HISTORY_1] PRIMARY KEY CLUSTERED 
(
    [USER_ID] ASC,
    [ORDER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
/****** Object:  Table [dbo].[USER_SETTINGS]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[USER_SETTINGS](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [ALLOCATION_ID] [int] NOT NULL,
    [PAYMENT_METHOD] [int] NOT NULL,
    [DELIVERY_ID] [int] NOT NULL,
    [COLLECTIVE_DELIVERY_ID] [int] NOT NULL,
    [NET_PRICE_VIEW] [bit] NOT NULL,
    [NET_PRICE_CONFIRM] [bit] NOT NULL,
    [VIEW_BILLING] [bit] NOT NULL,
    [ADDRESS_ID] [bit] NOT NULL,
    [USE_DEFAULT_SETTING] [bit] NOT NULL,
    [EMAIL_NOTIFICATION_ORDER] [bit] NOT NULL,
    [BILLING_ADDRESS_ID] [varchar](19) NULL,
    [DELIVERY_ADDRESS_ID] [varchar](19) NULL,
    [INVOICE_TYPE] [int] NOT NULL,
    [SHOW_DISCOUNT] [bit] NOT NULL,
    [SHOW_HAPPY_POINTS] [bit] NOT NULL,
    [ACCEPT_HAPPY_POINT_TERM] [bit] NULL,
    [SALE_ON_BEHALF_OF] [bit] NOT NULL,
 CONSTRAINT [PK_USER_SETTINGS] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[USER_VEHICLE_HISTORY]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
CREATE TABLE [dbo].[USER_VEHICLE_HISTORY](
    [ID] [bigint] IDENTITY(1,1) NOT NULL,
    [USER_ID] [bigint] NOT NULL,
    [VEH_HISTORY_ID] [bigint] NOT NULL,
    [SELECT_DATE] [datetime] NULL,
 CONSTRAINT [PK_USER_VEHICLE_HISTORY] PRIMARY KEY CLUSTERED 
(
    [USER_ID] ASC,
    [VEH_HISTORY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
/****** Object:  Table [dbo].[VEHICLE_HISTORY]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[VEHICLE_HISTORY](
    [ID] [bigint] IDENTITY(1,1) NOT NULL,
    [VEH_ID] [varchar](50) NOT NULL,
    [VEH_MAKE] [varchar](50) NOT NULL,
    [VEH_MODEL] [varchar](50) NOT NULL,
    [VEH_TYPE] [varchar](50) NOT NULL,
    [VEH_NAME] [varchar](255) NULL,
    [VEH_INFO] [varchar](255) NULL,
    [VEH_VIN] [varchar](50) NULL,
    [ID_SAG] [varchar](19) NULL,
    [ID_SAG_MAKE] [varchar](19) NULL,
    [ID_SAG_MODEL] [varchar](19) NULL,
 CONSTRAINT [PK_VEHICLE_HISTORY] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
/****** Object:  Table [dbo].[VIN_LOGGING]    Script Date: 7/4/2017 12:04:20 PM ******/
SET ANSI_NULLS ON
--GO
SET QUOTED_IDENTIFIER ON
--GO
SET ANSI_PADDING ON
--GO
CREATE TABLE [dbo].[VIN_LOGGING](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [VIN] [varchar](17) NOT NULL,
    [CUSTOMER_ID] [bigint] NOT NULL,
    [ESTIMATE_ID] [varchar](255) NULL,
    [VEHICLE_ID] [varchar](255) NULL,
    [DATE_OF_LOG_ENTRY] [datetime] NOT NULL,
    [USER_ID] [bigint] NOT NULL,
    [STATUS] [int] NULL,
    [ERROR_CODE] [int] NULL,
 CONSTRAINT [PK_VIN_LOGGING] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--GO
SET ANSI_PADDING OFF
--GO
ALTER TABLE [dbo].[ADDRESS] ADD  DEFAULT (NULL) FOR [LINE1]
--GO
ALTER TABLE [dbo].[ADDRESS] ADD  DEFAULT (NULL) FOR [LINE2]
--GO
ALTER TABLE [dbo].[ADDRESS] ADD  DEFAULT (NULL) FOR [LINE3]
--GO
ALTER TABLE [dbo].[ADDRESS] ADD  DEFAULT (NULL) FOR [COUNTRYISO]
--GO
ALTER TABLE [dbo].[ADDRESS] ADD  DEFAULT (NULL) FOR [STATE]
--GO
ALTER TABLE [dbo].[ADDRESS] ADD  DEFAULT (NULL) FOR [CITY]
--GO
ALTER TABLE [dbo].[ADDRESS] ADD  DEFAULT (NULL) FOR [ZIPCODE]
--GO
ALTER TABLE [dbo].[COUPON_CONDITIONS] ADD  DEFAULT ((0)) FOR [UMAR_ID]
--GO
ALTER TABLE [dbo].[COUPON_USE_LOG] ADD  DEFAULT ((0)) FOR [UMAR_ID]
--GO
ALTER TABLE [dbo].[CUSTOMER_SETTINGS] ADD  DEFAULT ((1)) FOR [NET_PRICE_VIEW]
--GO
ALTER TABLE [dbo].[CUSTOMER_SETTINGS] ADD  DEFAULT ((1)) FOR [NET_PRICE_CONFIRM]
--GO
ALTER TABLE [dbo].[CUSTOMER_SETTINGS] ADD  DEFAULT ((1)) FOR [VIEW_BILLING]
--GO
ALTER TABLE [dbo].[CUSTOMER_SETTINGS] ADD  DEFAULT ((1)) FOR [ADDRESS_ID]
--GO
ALTER TABLE [dbo].[CUSTOMER_SETTINGS] ADD  DEFAULT ((1)) FOR [USE_DEFAULT_SETTING]
--GO
ALTER TABLE [dbo].[CUSTOMER_SETTINGS] ADD  DEFAULT ((0)) FOR [EMAIL_NOTIFICATION_ORDER]
--GO
ALTER TABLE [dbo].[CUSTOMER_SETTINGS] ADD  DEFAULT ((1)) FOR [INVOICE_ID]
--GO
ALTER TABLE [dbo].[CUSTOMER_SETTINGS] ADD  DEFAULT ((1)) FOR [ALLOW_NET_PRICE_CHANGED]
--GO
ALTER TABLE [dbo].[CUSTOMER_SETTINGS] ADD  DEFAULT ((1)) FOR [INVOICE_TYPE]
--GO
ALTER TABLE [dbo].[CUSTOMER_SETTINGS] ADD  DEFAULT ((1)) FOR [SHOW_DISCOUNT]
--GO
ALTER TABLE [dbo].[CUSTOMER_SETTINGS] ADD  DEFAULT ((3600)) FOR [SESSION_TIMEOUT_SECONDS]
--GO
ALTER TABLE [dbo].[ESHOP_CART_ITEM] ADD  DEFAULT ((1)) FOR [QUANTITY]
--GO
ALTER TABLE [dbo].[ESHOP_CART_ITEM] ADD  DEFAULT (getdate()) FOR [ADDED_TIME]
--GO
ALTER TABLE [dbo].[ESHOP_FUNCTION] ADD  DEFAULT (NULL) FOR [FUNCTION_NAME]
--GO
ALTER TABLE [dbo].[ESHOP_GROUP] ADD  DEFAULT (NULL) FOR [NAME]
--GO
ALTER TABLE [dbo].[ESHOP_GROUP] ADD  DEFAULT ('000000') FOR [ORG_CODE]
--GO
ALTER TABLE [dbo].[ESHOP_GROUP] ADD  DEFAULT ((6)) FOR [ROLE_ID]
--GO
ALTER TABLE [dbo].[ESHOP_PERMISSION] ADD  DEFAULT (NULL) FOR [PERMISSION]
--GO
ALTER TABLE [dbo].[ESHOP_PERMISSION] ADD  CONSTRAINT [DF_ESHOP_PERMISSION_CREATED_DATE]  DEFAULT (getdate()) FOR [CREATED_DATE]
--GO
ALTER TABLE [dbo].[ESHOP_ROLE] ADD  DEFAULT (NULL) FOR [NAME]
--GO
ALTER TABLE [dbo].[ESHOP_USER] ADD  CONSTRAINT [DF__ESHOP_USE__FIRST__412EB0B6]  DEFAULT (NULL) FOR [FIRST_NAME]
--GO
ALTER TABLE [dbo].[ESHOP_USER] ADD  CONSTRAINT [DF__ESHOP_USE__LAST___4222D4EF]  DEFAULT (NULL) FOR [LAST_NAME]
--GO
ALTER TABLE [dbo].[ESHOP_USER] ADD  CONSTRAINT [DF__ESHOP_USE__USER___4316F928]  DEFAULT (NULL) FOR [EMAIL]
--GO
ALTER TABLE [dbo].[ESHOP_USER] ADD  DEFAULT ((0)) FOR [HOURLY_RATE]
--GO
ALTER TABLE [dbo].[ESHOP_USER] ADD  DEFAULT ((1)) FOR [VAT_CONFIRM]
--GO
ALTER TABLE [dbo].[EXTERNAL_ORGANISATION] ADD  DEFAULT ('DVSE') FOR [EXTERNAL_APP]
--GO
ALTER TABLE [dbo].[EXTERNAL_ORGANISATION] ADD  DEFAULT (NULL) FOR [EXTERNAL_CUSTOMER_NAME]
--GO
ALTER TABLE [dbo].[EXTERNAL_USER] ADD  DEFAULT ('DVSE') FOR [EXTERNAL_APP]
--GO
ALTER TABLE [dbo].[EXTERNAL_USER] ADD  DEFAULT ((0)) FOR [ACTIVE]
--GO
ALTER TABLE [dbo].[EXTERNAL_USER] ADD  DEFAULT (getdate()) FOR [CREATED_DATE]
--GO
ALTER TABLE [dbo].[LOGIN] ADD  CONSTRAINT [DF_LOGIN_PASSWORD]  DEFAULT (NULL) FOR [PASSWORD]
--GO
ALTER TABLE [dbo].[LOGIN] ADD  DEFAULT ((1)) FOR [IS_USER_ACTIVE]
--GO
ALTER TABLE [dbo].[MIGRATION_ESHOP_USER] ADD  DEFAULT ((1)) FOR [VAT_CONFIRM]
--GO
ALTER TABLE [dbo].[MIGRATION_ESHOP_USER] ADD  DEFAULT ((0)) FOR [IS_MIGRATED]
--GO
ALTER TABLE [dbo].[MIGRATION_ESHOP_USER] ADD  DEFAULT ((0)) FOR [HAS_PARTNER_PROGRAM]
--GO
ALTER TABLE [dbo].[MIGRATION_LICENSE] ADD  DEFAULT ((0)) FOR [USER_ID]
--GO
ALTER TABLE [dbo].[MIGRATION_LICENSE] ADD  DEFAULT ((0)) FOR [IS_MIGRATED]
--GO
ALTER TABLE [dbo].[MIGRATION_ORGANISATION] ADD  DEFAULT ((0)) FOR [IS_MIGRATED]
--GO
ALTER TABLE [dbo].[OAUTH_ACCESS_TOKEN] ADD  DEFAULT (NULL) FOR [TOKEN_ID]
--GO
ALTER TABLE [dbo].[OAUTH_ACCESS_TOKEN] ADD  DEFAULT (NULL) FOR [AUTHENTICATION_ID]
--GO
ALTER TABLE [dbo].[OAUTH_ACCESS_TOKEN] ADD  DEFAULT (NULL) FOR [USER_NAME]
--GO
ALTER TABLE [dbo].[OAUTH_ACCESS_TOKEN] ADD  DEFAULT (NULL) FOR [CLIENT_ID]
--GO
ALTER TABLE [dbo].[OAUTH_ACCESS_TOKEN] ADD  DEFAULT (NULL) FOR [REFRESH_TOKEN]

ALTER TABLE [dbo].[OAUTH_ACCESS_TOKEN] ADD UNIQUE (USER_NAME)
--GO
ALTER TABLE [dbo].[OAUTH_REFRESH_TOKEN] ADD  DEFAULT (NULL) FOR [TOKEN_ID]
--GO
ALTER TABLE [dbo].[ORDER_HISTORY] ADD  DEFAULT (NULL) FOR [ERP_ORDER_DETAIL_URL]
--GO
ALTER TABLE [dbo].[ORGANISATION] ADD  CONSTRAINT [DF_ORGANISATION_NAME]  DEFAULT (NULL) FOR [NAME]
--GO
ALTER TABLE [dbo].[ORGANISATION] ADD  CONSTRAINT [DF_ORGANISATION_ORGTY]  DEFAULT (NULL) FOR [ORGTYPE_ID]
--GO
ALTER TABLE [dbo].[ORGANISATION] ADD  CONSTRAINT [DF_ORGANISATION_PARENT]  DEFAULT (NULL) FOR [PARENT_ID]
--GO
ALTER TABLE [dbo].[ORGANISATION_SETTINGS] ADD  DEFAULT (NULL) FOR [SETTING_VALUE]
--GO
ALTER TABLE [dbo].[ORGANISATION_TYPE] ADD  CONSTRAINT [DF_ORGANISAT_LEVEL]  DEFAULT (NULL) FOR [LEVEL]
--GO
ALTER TABLE [dbo].[ROLE_TYPE] ADD  DEFAULT (NULL) FOR [NAME]
--GO
ALTER TABLE [dbo].[USER] ADD  DEFAULT ((0)) FOR [ACTIVATED]
--GO
ALTER TABLE [dbo].[USER] ADD  DEFAULT (NULL) FOR [ACTIVATIONKEY]
--GO
ALTER TABLE [dbo].[USER] ADD  DEFAULT (NULL) FOR [RESETPASSWORDKEY]
--GO
ALTER TABLE [dbo].[USER_SETTINGS] ADD  DEFAULT ((1)) FOR [NET_PRICE_VIEW]
--GO
ALTER TABLE [dbo].[USER_SETTINGS] ADD  DEFAULT ((1)) FOR [NET_PRICE_CONFIRM]
--GO
ALTER TABLE [dbo].[USER_SETTINGS] ADD  DEFAULT ((1)) FOR [VIEW_BILLING]
--GO
ALTER TABLE [dbo].[USER_SETTINGS] ADD  DEFAULT ((1)) FOR [ADDRESS_ID]
--GO
ALTER TABLE [dbo].[USER_SETTINGS] ADD  DEFAULT ((1)) FOR [USE_DEFAULT_SETTING]
--GO
ALTER TABLE [dbo].[USER_SETTINGS] ADD  DEFAULT ((0)) FOR [EMAIL_NOTIFICATION_ORDER]
--GO
ALTER TABLE [dbo].[USER_SETTINGS] ADD  DEFAULT ((1)) FOR [INVOICE_TYPE]
--GO
ALTER TABLE [dbo].[USER_SETTINGS] ADD  DEFAULT ((1)) FOR [SHOW_DISCOUNT]
--GO
ALTER TABLE [dbo].[USER_SETTINGS] ADD  DEFAULT ((0)) FOR [SHOW_HAPPY_POINTS]
--GO
ALTER TABLE [dbo].[USER_SETTINGS] ADD  DEFAULT ((0)) FOR [ACCEPT_HAPPY_POINT_TERM]
--GO
ALTER TABLE [dbo].[USER_SETTINGS] ADD  DEFAULT ((0)) FOR [SALE_ON_BEHALF_OF]
--GO
ALTER TABLE [dbo].[USER_VEHICLE_HISTORY] ADD  CONSTRAINT [DF_USER_VEHICLE_HISTORY_SELECT_DATE]  DEFAULT (getdate()) FOR [SELECT_DATE]
--GO
ALTER TABLE [dbo].[VIN_LOGGING] ADD  CONSTRAINT [DF_VIN_LOGGING_DATE_OF_LOG_ENTRY]  DEFAULT (getdate()) FOR [DATE_OF_LOG_ENTRY]
--GO
ALTER TABLE [dbo].[ADDRESS]  WITH CHECK ADD  CONSTRAINT [FK_ADDRESS_ADDRESSTYPE] FOREIGN KEY([ADDRESS_TYPE_ID])
REFERENCES [dbo].[ADDRESS_TYPE] ([ID])
--GO
ALTER TABLE [dbo].[ADDRESS] CHECK CONSTRAINT [FK_ADDRESS_ADDRESSTYPE]
--GO
ALTER TABLE [dbo].[COUPON_USE_LOG]  WITH NOCHECK ADD  CONSTRAINT [FK_COUPON_USE_LOG_CUSTOMER_NR] FOREIGN KEY([CUSTOMER_NR])
REFERENCES [dbo].[ORGANISATION] ([ORG_CODE])
NOT FOR REPLICATION 
--GO
ALTER TABLE [dbo].[COUPON_USE_LOG] NOCHECK CONSTRAINT [FK_COUPON_USE_LOG_CUSTOMER_NR]
--GO
ALTER TABLE [dbo].[CUSTOMER_SETTINGS]  WITH CHECK ADD  CONSTRAINT [FK_ORG_ORDER_SETTINGS_ALLOCATION_TYPE] FOREIGN KEY([ALLOCATION_ID])
REFERENCES [dbo].[ALLOCATION_TYPE] ([ID])
--GO
ALTER TABLE [dbo].[CUSTOMER_SETTINGS] CHECK CONSTRAINT [FK_ORG_ORDER_SETTINGS_ALLOCATION_TYPE]
--GO
ALTER TABLE [dbo].[CUSTOMER_SETTINGS]  WITH CHECK ADD  CONSTRAINT [FK_ORG_ORDER_SETTINGS_COLLECTIVE_DELIVERY] FOREIGN KEY([COLLECTIVE_DELIVERY_ID])
REFERENCES [dbo].[COLLECTIVE_DELIVERY] ([ID])
--GO
ALTER TABLE [dbo].[CUSTOMER_SETTINGS] CHECK CONSTRAINT [FK_ORG_ORDER_SETTINGS_COLLECTIVE_DELIVERY]
--GO
ALTER TABLE [dbo].[CUSTOMER_SETTINGS]  WITH CHECK ADD  CONSTRAINT [FK_ORG_ORDER_SETTINGS_DELIVERY_TYPE] FOREIGN KEY([DELIVERY_ID])
REFERENCES [dbo].[DELIVERY_TYPE] ([ID])
--GO
ALTER TABLE [dbo].[CUSTOMER_SETTINGS] CHECK CONSTRAINT [FK_ORG_ORDER_SETTINGS_DELIVERY_TYPE]
--GO
ALTER TABLE [dbo].[CUSTOMER_SETTINGS]  WITH CHECK ADD  CONSTRAINT [FK_ORG_ORDER_SETTINGS_PAYMENT_METHOD] FOREIGN KEY([PAYMENT_METHOD])
REFERENCES [dbo].[PAYMENT_METHOD] ([ID])
--GO
ALTER TABLE [dbo].[CUSTOMER_SETTINGS] CHECK CONSTRAINT [FK_ORG_ORDER_SETTINGS_PAYMENT_METHOD]
--GO
ALTER TABLE [dbo].[CUSTOMER_SETTINGS]  WITH CHECK ADD  CONSTRAINT [FK_ORG_ORDER_SETTINGS_INVOICE_TYPE] FOREIGN KEY([INVOICE_TYPE])
REFERENCES [dbo].[INVOICE_TYPE] ([ID])
--GO
ALTER TABLE [dbo].[CUSTOMER_SETTINGS] CHECK CONSTRAINT [FK_ORG_ORDER_SETTINGS_INVOICE_TYPE]
--GO
ALTER TABLE [dbo].[ESHOP_ROLE]  WITH CHECK ADD  CONSTRAINT [FK_ESHOP_ROLE_ROLE_TYPE] FOREIGN KEY([ROLE_TYPE_ID])
REFERENCES [dbo].[ROLE_TYPE] ([ID])
--GO
ALTER TABLE [dbo].[ESHOP_ROLE] CHECK CONSTRAINT [FK_ESHOP_ROLE_ROLE_TYPE]
--GO
ALTER TABLE [dbo].[ESHOP_USER]  WITH CHECK ADD  CONSTRAINT [FK_ESHOP_USER_LANGUAGE] FOREIGN KEY([LANGUAGE])
REFERENCES [dbo].[LANGUAGES] ([ID])
--GO
ALTER TABLE [dbo].[ESHOP_USER] CHECK CONSTRAINT [FK_ESHOP_USER_LANGUAGE]
--GO
ALTER TABLE [dbo].[ESHOP_USER]  WITH CHECK ADD  CONSTRAINT [FK_ESHOP_USER_SALUTATION] FOREIGN KEY([SALUTATION])
REFERENCES [dbo].[SALUTATION] ([ID])
--GO
ALTER TABLE [dbo].[ESHOP_USER] CHECK CONSTRAINT [FK_ESHOP_USER_SALUTATION]
--GO
ALTER TABLE [dbo].[ESHOP_USER]  WITH CHECK ADD  CONSTRAINT [FK_ESHOP_USER_SETTINGS] FOREIGN KEY([SETTING])
REFERENCES [dbo].[USER_SETTINGS] ([ID])
--GO
ALTER TABLE [dbo].[GROUP_ROLE]  WITH CHECK ADD  CONSTRAINT [FK_GROUP_ROLE_ESHOP_ROLE] FOREIGN KEY([ROLE_ID])
REFERENCES [dbo].[ESHOP_ROLE] ([ID])
--GO
ALTER TABLE [dbo].[GROUP_ROLE] CHECK CONSTRAINT [FK_GROUP_ROLE_ESHOP_ROLE]
--GO
ALTER TABLE [dbo].[GROUP_ROLE]  WITH CHECK ADD  CONSTRAINT [FK_GROUP_ROLE_ESHOPGROUP] FOREIGN KEY([GROUP_ID])
REFERENCES [dbo].[ESHOP_GROUP] ([ID])
--GO
ALTER TABLE [dbo].[GROUP_ROLE] CHECK CONSTRAINT [FK_GROUP_ROLE_ESHOPGROUP]
--GO
ALTER TABLE [dbo].[GROUP_USER]  WITH CHECK ADD  CONSTRAINT [FK_GROUP_ID_USER_ID] FOREIGN KEY([GROUP_ID])
REFERENCES [dbo].[ESHOP_GROUP] ([ID])
--GO
ALTER TABLE [dbo].[GROUP_USER] CHECK CONSTRAINT [FK_GROUP_ID_USER_ID]
--GO
ALTER TABLE [dbo].[GROUP_USER]  WITH CHECK ADD  CONSTRAINT [FK_USER_ID_GROUP_ID] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[ESHOP_USER] ([ID])
--GO
ALTER TABLE [dbo].[GROUP_USER] CHECK CONSTRAINT [FK_USER_ID_GROUP_ID]
--GO
ALTER TABLE [dbo].[LICENSE]  WITH CHECK ADD  CONSTRAINT [FK_LICENSE_PACK_ID] FOREIGN KEY([PACK_ID])
REFERENCES [dbo].[LICENSE_SETTINGS] ([PACK_ID])
--GO
ALTER TABLE [dbo].[LICENSE] CHECK CONSTRAINT [FK_LICENSE_PACK_ID]
--GO
ALTER TABLE [dbo].[LOGIN]  WITH CHECK ADD  CONSTRAINT [FK_LOGIN_ESHOP_USER] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[ESHOP_USER] ([ID])
--GO
ALTER TABLE [dbo].[LOGIN] CHECK CONSTRAINT [FK_LOGIN_ESHOP_USER]
--GO
ALTER TABLE [dbo].[ORDER_HISTORY]  WITH CHECK ADD  CONSTRAINT [FK_ORDER_HISTORY_ESHOP_USER] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[ESHOP_USER] ([ID])
--GO
ALTER TABLE [dbo].[ORDER_HISTORY] CHECK CONSTRAINT [FK_ORDER_HISTORY_ESHOP_USER]
--GO
ALTER TABLE [dbo].[ORGANISATION]  WITH CHECK ADD  CONSTRAINT [FK_ORGANISATION_ORG_ORDER_SETTINGS] FOREIGN KEY([ORDER_SETTINGS_ID])
REFERENCES [dbo].[CUSTOMER_SETTINGS] ([ID])
--GO
ALTER TABLE [dbo].[ORGANISATION] CHECK CONSTRAINT [FK_ORGANISATION_ORG_ORDER_SETTINGS]
--GO
ALTER TABLE [dbo].[ORGANISATION]  WITH CHECK ADD  CONSTRAINT [FK_ORGANISATION_ORGTYPE] FOREIGN KEY([ORGTYPE_ID])
REFERENCES [dbo].[ORGANISATION_TYPE] ([ID])
--GO
ALTER TABLE [dbo].[ORGANISATION] CHECK CONSTRAINT [FK_ORGANISATION_ORGTYPE]
--GO
ALTER TABLE [dbo].[ORGANISATION_ADDRESS]  WITH CHECK ADD  CONSTRAINT [FK_ORGANISATION_ADDRESS_ADDRESS] FOREIGN KEY([ADDRESS_ID])
REFERENCES [dbo].[ADDRESS] ([ID])
--GO
ALTER TABLE [dbo].[ORGANISATION_ADDRESS] CHECK CONSTRAINT [FK_ORGANISATION_ADDRESS_ADDRESS]
--GO
ALTER TABLE [dbo].[ORGANISATION_ADDRESS]  WITH CHECK ADD  CONSTRAINT [FK_ORGANISATION_ADDRESS_ORGANISATION] FOREIGN KEY([ORGANISATION_ID])
REFERENCES [dbo].[ORGANISATION] ([ID])
--GO
ALTER TABLE [dbo].[ORGANISATION_ADDRESS] CHECK CONSTRAINT [FK_ORGANISATION_ADDRESS_ORGANISATION]
--GO
ALTER TABLE [dbo].[ORGANISATION_GROUP]  WITH CHECK ADD  CONSTRAINT [FK_ORGANISATION_GROUP_ESHOPGROUP] FOREIGN KEY([GROUP_ID])
REFERENCES [dbo].[ESHOP_GROUP] ([ID])
--GO
ALTER TABLE [dbo].[ORGANISATION_GROUP] CHECK CONSTRAINT [FK_ORGANISATION_GROUP_ESHOPGROUP]
--GO
ALTER TABLE [dbo].[ORGANISATION_GROUP]  WITH CHECK ADD  CONSTRAINT [FK_ORGANISATION_GROUP_ORGANISATION] FOREIGN KEY([ORGANISATION_ID])
REFERENCES [dbo].[ORGANISATION] ([ID])
--GO
ALTER TABLE [dbo].[ORGANISATION_GROUP] CHECK CONSTRAINT [FK_ORGANISATION_GROUP_ORGANISATION]
--GO
ALTER TABLE [dbo].[ORGANISATION_SETTINGS]  WITH CHECK ADD  CONSTRAINT [FK_ORGANISATION_SETTINGS_ORGANISATION_ID] FOREIGN KEY([ORGANISATION_ID])
REFERENCES [dbo].[ORGANISATION] ([ID])
--GO
ALTER TABLE [dbo].[ORGANISATION_SETTINGS] CHECK CONSTRAINT [FK_ORGANISATION_SETTINGS_ORGANISATION_ID]
--GO
ALTER TABLE [dbo].[PERM_FUNCTION]  WITH CHECK ADD  CONSTRAINT [FK_FUNCTION_PERM_ID] FOREIGN KEY([PERM_ID])
REFERENCES [dbo].[ESHOP_PERMISSION] ([ID])
--GO
ALTER TABLE [dbo].[PERM_FUNCTION] CHECK CONSTRAINT [FK_FUNCTION_PERM_ID]
--GO
ALTER TABLE [dbo].[PERM_FUNCTION]  WITH CHECK ADD  CONSTRAINT [FK_PERM_FUNCTION_ID] FOREIGN KEY([FUNCTION_ID])
REFERENCES [dbo].[ESHOP_FUNCTION] ([ID])
--GO
ALTER TABLE [dbo].[PERM_FUNCTION] CHECK CONSTRAINT [FK_PERM_FUNCTION_ID]
--GO
ALTER TABLE [dbo].[ROLE_PERMISSION]  WITH CHECK ADD  CONSTRAINT [FK_ROLE_PERMISSION_ESHOP_PERMISSION] FOREIGN KEY([PERM_ID])
REFERENCES [dbo].[ESHOP_PERMISSION] ([ID])
--GO
ALTER TABLE [dbo].[ROLE_PERMISSION] CHECK CONSTRAINT [FK_ROLE_PERMISSION_ESHOP_PERMISSION]
--GO
ALTER TABLE [dbo].[ROLE_PERMISSION]  WITH CHECK ADD  CONSTRAINT [FK_ROLE_PERMISSION_ESHOP_ROLE] FOREIGN KEY([ROLE_ID])
REFERENCES [dbo].[ESHOP_ROLE] ([ID])
--GO
ALTER TABLE [dbo].[ROLE_PERMISSION] CHECK CONSTRAINT [FK_ROLE_PERMISSION_ESHOP_ROLE]
--GO
ALTER TABLE [dbo].[USER_ARTICLE_HISTORY]  WITH CHECK ADD  CONSTRAINT [FK_USER_ARTICLE_HISTORY_ARTICLE_HISTORY] FOREIGN KEY([ART_HISTORY_ID])
REFERENCES [dbo].[ARTICLE_HISTORY] ([ID])
--GO
ALTER TABLE [dbo].[USER_ARTICLE_HISTORY] CHECK CONSTRAINT [FK_USER_ARTICLE_HISTORY_ARTICLE_HISTORY]
--GO
ALTER TABLE [dbo].[USER_ARTICLE_HISTORY]  WITH CHECK ADD  CONSTRAINT [FK_USER_ARTICLE_HISTORY_ESHOP_USER] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[ESHOP_USER] ([ID])
--GO
ALTER TABLE [dbo].[USER_ARTICLE_HISTORY] CHECK CONSTRAINT [FK_USER_ARTICLE_HISTORY_ESHOP_USER]
--GO
ALTER TABLE [dbo].[USER_ORDER_HISTORY]  WITH CHECK ADD  CONSTRAINT [FK_USER_ORDER_HISTORY_ESHOP_USER] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[ESHOP_USER] ([ID])
--GO
ALTER TABLE [dbo].[USER_ORDER_HISTORY] CHECK CONSTRAINT [FK_USER_ORDER_HISTORY_ESHOP_USER]
--GO
ALTER TABLE [dbo].[USER_ORDER_HISTORY]  WITH CHECK ADD  CONSTRAINT [FK_USER_ORDER_HISTORY_ORDER_HISTORY] FOREIGN KEY([ORDER_ID])
REFERENCES [dbo].[ORDER_HISTORY] ([ID])
--GO
ALTER TABLE [dbo].[USER_ORDER_HISTORY] CHECK CONSTRAINT [FK_USER_ORDER_HISTORY_ORDER_HISTORY]
--GO
ALTER TABLE [dbo].[USER_SETTINGS]  WITH CHECK ADD  CONSTRAINT [FK_USER_SETTINGS_ALLOCATION_TYPE] FOREIGN KEY([ALLOCATION_ID])
REFERENCES [dbo].[ALLOCATION_TYPE] ([ID])
--GO
ALTER TABLE [dbo].[USER_SETTINGS] CHECK CONSTRAINT [FK_USER_SETTINGS_ALLOCATION_TYPE]
--GO
ALTER TABLE [dbo].[USER_SETTINGS]  WITH CHECK ADD  CONSTRAINT [FK_USER_SETTINGS_COLLECTIVE_DELIVERY] FOREIGN KEY([COLLECTIVE_DELIVERY_ID])
REFERENCES [dbo].[COLLECTIVE_DELIVERY] ([ID])
--GO
ALTER TABLE [dbo].[USER_SETTINGS] CHECK CONSTRAINT [FK_USER_SETTINGS_COLLECTIVE_DELIVERY]
--GO
ALTER TABLE [dbo].[USER_SETTINGS]  WITH CHECK ADD  CONSTRAINT [FK_USER_SETTINGS_DELIVERY_TYPE] FOREIGN KEY([DELIVERY_ID])
REFERENCES [dbo].[DELIVERY_TYPE] ([ID])
--GO
ALTER TABLE [dbo].[USER_SETTINGS] CHECK CONSTRAINT [FK_USER_SETTINGS_DELIVERY_TYPE]
--GO
ALTER TABLE [dbo].[USER_SETTINGS]  WITH CHECK ADD  CONSTRAINT [FK_USER_SETTINGS_PAYMENT_METHOD] FOREIGN KEY([PAYMENT_METHOD])
REFERENCES [dbo].[PAYMENT_METHOD] ([ID])
--GO
ALTER TABLE [dbo].[USER_SETTINGS] CHECK CONSTRAINT [FK_USER_SETTINGS_PAYMENT_METHOD]
--GO
ALTER TABLE [dbo].[USER_SETTINGS]  WITH CHECK ADD  CONSTRAINT [FK_USER_SETTINGS_INVOICE_TYPE] FOREIGN KEY([INVOICE_TYPE])
REFERENCES [dbo].[INVOICE_TYPE] ([ID])
--GO
ALTER TABLE [dbo].[USER_SETTINGS] CHECK CONSTRAINT [FK_USER_SETTINGS_INVOICE_TYPE]
--GO
ALTER TABLE [dbo].[USER_VEHICLE_HISTORY]  WITH CHECK ADD  CONSTRAINT [FK_USER_VEHICLE_HISTORY_ESHOP_USER] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[ESHOP_USER] ([ID])
--GO
ALTER TABLE [dbo].[USER_VEHICLE_HISTORY] CHECK CONSTRAINT [FK_USER_VEHICLE_HISTORY_ESHOP_USER]
--GO
ALTER TABLE [dbo].[USER_VEHICLE_HISTORY]  WITH CHECK ADD  CONSTRAINT [FK_USER_VEHICLE_HISTORY_VEHICLE_HISTORY] FOREIGN KEY([VEH_HISTORY_ID])
REFERENCES [dbo].[VEHICLE_HISTORY] ([ID])
--GO
ALTER TABLE [dbo].[USER_VEHICLE_HISTORY] CHECK CONSTRAINT [FK_USER_VEHICLE_HISTORY_VEHICLE_HISTORY]
--GO
ALTER TABLE [dbo].[VIN_LOGGING]  WITH CHECK ADD  CONSTRAINT [FK_VIN_LOGGING_ID] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[ESHOP_USER] ([ID])
--GO
ALTER TABLE [dbo].[VIN_LOGGING] CHECK CONSTRAINT [FK_VIN_LOGGING_ID]
--GO

ALTER TABLE ORDER_HISTORY ALTER COLUMN ERP_ORDER_DETAIL_URL [varchar](max);
--GO

-- Basket History
DROP TABLE [dbo].[BASKET_HISTORY]
CREATE TABLE [dbo].[BASKET_HISTORY](
    [ID] [bigint] IDENTITY(1,1) NOT NULL,
    [BASKET_NAME] [varchar] (255) NOT NULL,
    [ORGANISATION_ID] [INT]  NOT NULL,
    [CREATED_USER_ID] [bigint] NOT NULL,
    [SALES_USER_ID] [bigint] DEFAULT NULL,
    [GRAND_TOTAL_EXCLUDE_VAT] [decimal] (10, 2) NOT NULL DEFAULT 0,
    [BASKET_JSON] [varchar] (max) NOT NULL,
    [UPDATED_DATE] [datetime] DEFAULT getdate(),
 CONSTRAINT [PK_BASKET_HISTORY] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

-- Rename SHOW_HAPPY_POINTS -> HAS_PARTNER_PROGRAM_VIEW
-- Rename ACCEPT_HAPPY_POINT_TERM -> HAS_PARTNER_PROGRAM_LOGIN
sp_RENAME 'USER_SETTINGS.SHOW_HAPPY_POINTS' , 'HAS_PARTNER_PROGRAM_VIEW', 'COLUMN'
sp_RENAME 'USER_SETTINGS.ACCEPT_HAPPY_POINT_TERM' , 'HAS_PARTNER_PROGRAM_LOGIN', 'COLUMN'

-- #1522: Performance 
-- CREATE INDEX ON TABLE USER_VEHICLE_HISTORY (USER_ID, VEH_HISTORY_ID)
CREATE INDEX IDX_USER_VEHICLE_HISTORY_USER_ID ON [dbo].[USER_VEHICLE_HISTORY] (USER_ID);
CREATE INDEX IDX_USER_VEHICLE_HISTORY_VEH_HISTORY_ID ON [dbo].[USER_VEHICLE_HISTORY] (VEH_HISTORY_ID);
CREATE INDEX IDX_USER_VEHICLE_HISTORY_USER_VEHICLE ON [dbo].[USER_VEHICLE_HISTORY] (USER_ID, VEH_HISTORY_ID);
CREATE INDEX IDX_USER_VEHICLE_HISTORY_ID ON [dbo].[USER_VEHICLE_HISTORY] (ID);

-- CREATE INDEX ON TABLE VEHICLE_HISTORY (ID, VEH_ID)
CREATE INDEX IDX_VEHICLE_HISTORY_ID ON [dbo].[VEHICLE_HISTORY] (ID);
CREATE INDEX IDX_VEHICLE_HISTORY_VEH_ID ON [dbo].[VEHICLE_HISTORY] (VEH_ID);

-- CREATE INDEX ON TABLE LICENSE(CUSTOMER_NR, TYPE_OF_LICENSE)
CREATE INDEX IDX_LICENSE_VEH_CUSTOMER_NR ON [dbo].[LICENSE] (CUSTOMER_NR);
CREATE INDEX IDX_LICENSE_VEH_CUSTOMER_NR_TYPE_OF_LICENSE ON [dbo].[LICENSE] (CUSTOMER_NR, TYPE_OF_LICENSE);
CREATE INDEX IDX_LICENSE_VEH_TYPE_OF_LICENSE ON [dbo].[LICENSE] (TYPE_OF_LICENSE);

-- CREATE INDEX ON TABLE LICENSE_SETTINGS(TYPE_OF_LICENSE)
CREATE INDEX IDX_LICENSE_SETTINGS_ID ON [dbo].[LICENSE_SETTINGS] (ID);
CREATE INDEX IDX_LICENSE_SETTINGS_TYPE_OF_LICENSE ON [dbo].[LICENSE_SETTINGS] (TYPE_OF_LICENSE);

-- ADD more columns to ORDER_HISTORY to improve performance for recent order histories - # 1691
ALTER TABLE [dbo].[ORDER_HISTORY] ADD [CREATED_DATE] DATETIME NOT NULL DEFAULT (getdate());
ALTER TABLE [dbo].[ORDER_HISTORY] ADD [SALE_NAME] VARCHAR(150) NULL;
ALTER TABLE [dbo].[ORDER_HISTORY] ADD [TOTAL] FLOAT NOT NULL DEFAULT ((0));
-- CREATE INDEX for ORDER_HISTORY table
CREATE INDEX IDX_ORDER_HISTORY_ID ON [dbo].[ORDER_HISTORY] (ID);
CREATE INDEX IDX_ORDER_HISTORY_SALE_ID ON [dbo].[ORDER_HISTORY] (SALE_ID);
CREATE INDEX IDX_ORDER_HISTORY_CUSTOMER_NUMBER ON [dbo].[ORDER_HISTORY] (CUSTOMER_NUMBER);
CREATE INDEX IDX_ORDER_HISTORY_USER_ID ON [dbo].[ORDER_HISTORY] (USER_ID);
CREATE INDEX IDX_ORDER_HISTORY_SALE_ID_CUSTOMER_NUMBER ON [dbo].[ORDER_HISTORY] (SALE_ID, CUSTOMER_NUMBER);
-- CREATE INDEX for ORGANISATION (ORG_CODE, PARENT_ID, SHORTNAME)
CREATE INDEX IDX_ORGANISATION_ID ON [dbo].[ORGANISATION] (ID);
CREATE INDEX IDX_ORGANISATION_ORG_CODE ON [dbo].[ORGANISATION] (ORG_CODE);
CREATE INDEX IDX_ORGANISATION_PARENT_ID ON [dbo].[ORGANISATION] (PARENT_ID);
CREATE INDEX IDX_ORGANISATION_SHORTNAME ON [dbo].[ORGANISATION] (SHORTNAME);
CREATE INDEX IDX_ORGANISATION_ORG_CODE_PARENT_ID ON [dbo].[ORGANISATION] (ORG_CODE, PARENT_ID);

-- ADD SHOW_RECOMMENDED_RETAIL_PRICE COLUMN INTO USER_SETTING TABLE
ALTER TABLE [dbo].[USER_SETTINGS] ADD [SHOW_RECOMMENDED_RETAIL_PRICE] BIT NOT NULL DEFAULT ((0));

-- LOG USER SIGN IN DATETIME
ALTER TABLE [dbo].[ESHOP_USER] ADD [SIGN_IN_DATE] [DATETIME] NULL;
ALTER TABLE [dbo].[ESHOP_USER] ADD DEFAULT (GETDATE()) FOR [SIGN_IN_DATE];

-- SUPPORT RELEASE VERSION
CREATE TABLE [dbo].[ESHOP_RELEASE](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [RELEASE_BUILD] [VARCHAR](20) NULL,
    [RELEASE_VERSION] [VARCHAR](20) NULL,
    [RELEASE_DATE] [DATETIME] NULL
)

ALTER TABLE [dbo].[ESHOP_RELEASE] ADD DEFAULT (GETDATE()) FOR [RELEASE_DATE];

ALTER TABLE [dbo].[ESHOP_USER] DROP COLUMN [AGE];

-- #1964: Change username, impact to shopping cart
ALTER TABLE [ESHOP_CART_ITEM] ADD [USER_ID] [VARCHAR](20) NULL;

-- Perf: create INDEX on ESHOP_CART_ITEM table
CREATE INDEX INX_ESHOP_CART_ITEM_USER_NAME ON [dbo].[ESHOP_CART_ITEM] (USER_NAME);
CREATE INDEX INX_ESHOP_CART_ITEM_CART_KEY ON [dbo].[ESHOP_CART_ITEM] (CART_KEY);
CREATE INDEX INX_ESHOP_CART_ITEM_ID ON [dbo].[ESHOP_CART_ITEM] (ID);
CREATE INDEX INX_ESHOP_CART_ITEM_USER_ID ON [dbo].[ESHOP_CART_ITEM] (USER_ID);
CREATE INDEX INX_ESHOP_CART_ITEM_CUSTOMER_NR ON [dbo].[ESHOP_CART_ITEM] (CUSTOMER_NR);
CREATE INDEX INX_ESHOP_CART_ITEM_USER_ID_CUSTOMER_NR ON [dbo].[ESHOP_CART_ITEM] (USER_ID, CUSTOMER_NR);

--- DROP COLUMNS ORG_CODE AND ROLE_ID
ALTER TABLE [dbo].[ESHOP_GROUP] DROP COLUMN [ORG_CODE];
ALTER TABLE [dbo].[ESHOP_GROUP] DROP COLUMN [ROLE_ID];

-- ADD ACTIVE COLUMN INTO BASKET_HISTORY TABLE
ALTER TABLE [dbo].[BASKET_HISTORY] ADD [ACTIVE] BIT NOT NULL DEFAULT ((1));


--Offer module tables Start

CREATE TABLE [dbo].[OFFER_PERSON](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[ORGANISATION_ID] [int] NOT NULL,
	[TYPE] [varchar](50) NOT NULL,
	[STATUS] [varchar](50) NOT NULL,
	[FIRST_NAME] [varchar](100) NULL,
    [LAST_NAME] [varchar](100) NULL,
    [EMAIL] [varchar](255) NULL,
    [LANGUAGE_ID] [int] NOT NULL,
    [HOURLY_RATE] [decimal](19, 0) NULL,
    [CREATED_USER_ID] [bigint] NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_USER_ID] [bigint] NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[TECSTATE] [varchar](8) NOT NULL DEFAULT 'ACTIVE',
	[VERSION] [int] NOT NULL DEFAULT 1
	CONSTRAINT [PK_OFFER_PERSON] PRIMARY KEY CLUSTERED
	([ID] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
ALTER TABLE [dbo].[OFFER_PERSON]  WITH CHECK ADD  CONSTRAINT [FK_OFFER_PERSON_LANGUAGE] FOREIGN KEY([LANGUAGE_ID]) REFERENCES [dbo].[LANGUAGES] ([ID]);
ALTER TABLE [dbo].[OFFER_PERSON]  WITH CHECK ADD  CONSTRAINT [FK_OFFER_PERSON_CREATED_USER_ID] FOREIGN KEY([CREATED_USER_ID]) REFERENCES [dbo].[ESHOP_USER] ([ID]);
ALTER TABLE [dbo].[OFFER_PERSON]  WITH CHECK ADD  CONSTRAINT [FK_OFFER_PERSON_MODIFIED_USER_ID] FOREIGN KEY([MODIFIED_USER_ID]) REFERENCES [dbo].[ESHOP_USER] ([ID]);
ALTER TABLE [dbo].[OFFER_PERSON]  WITH CHECK ADD  CONSTRAINT [FK_OFFER_PERSON_ORGANISATION_ID] FOREIGN KEY([ORGANISATION_ID]) REFERENCES [dbo].[ORGANISATION] ([ID]);

CREATE TABLE [dbo].[OFFER_ADDRESS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[PERSON_ID] [bigint] NOT NULL,
	[LINE1] [varchar](150) NULL,
	[LINE2] [varchar](50) NULL,
	[LINE3] [varchar](50) NULL,
	[COUNTRYISO] [varchar](3) NOT NULL,
	[STATE] [varchar](50) NULL,
    [CITY] [varchar](50) NULL,
    [ZIPCODE] [varchar](10) NULL,
	[CREATED_USER_ID] [bigint] NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_USER_ID] [bigint] NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[TECSTATE] [varchar](8) NOT NULL DEFAULT 'ACTIVE',
	[ERP_ID] [varchar](19) NULL,
	[TYPE] [varchar](20) NOT NULL,
	[PO_BOX] [varchar](50) NULL,
	[VERSION] [int] NOT NULL DEFAULT 1
CONSTRAINT [PK_OFFER_ADDRESS] PRIMARY KEY CLUSTERED
([ID] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
ALTER TABLE [dbo].[OFFER_ADDRESS]  WITH CHECK ADD  CONSTRAINT [FK_OFFER_ADDRESS_CREATED_USER_ID] FOREIGN KEY([CREATED_USER_ID]) REFERENCES [dbo].[ESHOP_USER] ([ID]);
ALTER TABLE [dbo].[OFFER_ADDRESS]  WITH CHECK ADD  CONSTRAINT [FK_OFFER_ADDRESS_MODIFIED_USER_ID] FOREIGN KEY([MODIFIED_USER_ID]) REFERENCES [dbo].[ESHOP_USER] ([ID]);
ALTER TABLE [dbo].[OFFER_ADDRESS]  WITH CHECK ADD  CONSTRAINT [FK_OFFER_PERSON_ID] FOREIGN KEY(PERSON_ID) REFERENCES [dbo].[OFFER_PERSON] ([ID]);

CREATE TABLE [dbo].[CURRENCY](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ISO_CODE] [varchar](3) NOT NULL,
	[DESCRIPTION] [varchar](50) NULL
	CONSTRAINT [PK_CURRENCY] PRIMARY KEY CLUSTERED
	([ID] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE [dbo].[OFFER](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[OFFER_NUMBER] [varchar](10) NULL,
	--[VENDOR_ID] [varchar](50) NULL,
	[CLIENT_ID] [int] NULL,
	[OWNER_ID] [bigint] NOT NULL,
	[STATUS] [varchar](50) NOT NULL,
    [OFFER_DATE] [datetime] NOT NULL,
    [RECIPIENT_ID] [bigint] NOT NULL,
	[RECIPIENT_ADDRESS_ID] [bigint] NOT NULL,
	[TOTAL_GROSS_PRICE] [decimal](18, 2) NOT NULL,
	[DELIVERY_DATE] [datetime] NULL,
	[REMARK] [varchar](200) NULL,
	[DELIVERY_LOCATION] [varchar](50) NULL,
	[CREATED_USER_ID] [bigint] NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_USER_ID] [bigint] NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[TECSTATE] [varchar](8) NOT NULL DEFAULT 'ACTIVE',
	[CURRENCY_ID] [int] NULL,
	[VAT] [decimal](18, 2) NOT NULL,
	[TYPE] [varchar](10) NOT NULL,
	[ALT_OFFER_PRICE_USED] [bit] NOT NULL DEFAULT 0,
	[VERSION] [int] NOT NULL DEFAULT 1
CONSTRAINT [PK_OFFER] PRIMARY KEY CLUSTERED
([ID] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
ALTER TABLE [dbo].[OFFER]  WITH CHECK ADD  CONSTRAINT [FK_OFFER_RECIPIENT_ADDRESS] FOREIGN KEY([RECIPIENT_ADDRESS_ID]) REFERENCES [dbo].[OFFER_ADDRESS] ([ID]);
ALTER TABLE [dbo].[OFFER]  WITH CHECK ADD  CONSTRAINT [FK_OFFER_CREATED_USER_ID] FOREIGN KEY([CREATED_USER_ID]) REFERENCES [dbo].[ESHOP_USER] ([ID]);
ALTER TABLE [dbo].[OFFER]  WITH CHECK ADD  CONSTRAINT [FK_OFFER_MODIFIED_USER_ID] FOREIGN KEY([MODIFIED_USER_ID]) REFERENCES [dbo].[ESHOP_USER] ([ID]);
ALTER TABLE [dbo].[OFFER]  WITH CHECK ADD  CONSTRAINT [FK_OFFER_CLIENT_ID] FOREIGN KEY([CLIENT_ID]) REFERENCES [dbo].[ORGANISATION] ([ID]);
ALTER TABLE [dbo].[OFFER]  WITH CHECK ADD  CONSTRAINT [FK_OFFER_OWNER_ID] FOREIGN KEY([OWNER_ID]) REFERENCES [dbo].[ESHOP_USER] ([ID]);
ALTER TABLE [dbo].[OFFER]  WITH CHECK ADD  CONSTRAINT [FK_OFFER_RECIPIENT_ID] FOREIGN KEY([RECIPIENT_ID]) REFERENCES [dbo].[OFFER_PERSON] ([ID]);
ALTER TABLE [dbo].[OFFER]  WITH CHECK ADD  CONSTRAINT [FK_OFFER_CURRENCY_ID] FOREIGN KEY([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY] ([ID]);


CREATE TABLE [dbo].[SHOP_ARTICLE] (
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[ORGANISATION_ID] [int] NOT NULL,
	[TYPE] [varchar](12) NOT NULL, --ARTICLE, WORK
	[ARTICLE_NUMBER] [varchar](50) NOT NULL,
	[NAME] [varchar](100) NULL,
	[DESCRIPTION] [varchar](500) NULL,
	[AMOUNT] [decimal](18,3) NOT NULL DEFAULT 0,
	[PRICE] [decimal](18, 3) NOT NULL,
	[CREATED_USER_ID] [bigint] NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_USER_ID] [bigint] NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[TECSTATE] [varchar](8) NOT NULL DEFAULT 'ACTIVE',
	[CURRENCY_ID] [int] NULL,
	[VERSION] [int] NOT NULL DEFAULT 1
	CONSTRAINT [PK_SHOP_ARTICLE] PRIMARY KEY CLUSTERED
	([ID] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
	CONSTRAINT [UN_ARTICLE_NUMBER] UNIQUE (ARTICLE_NUMBER)
) ON [PRIMARY];
ALTER TABLE [dbo].[SHOP_ARTICLE]  WITH CHECK ADD  CONSTRAINT [FK_SHOP_ARTICLE_ORGANISATION] FOREIGN KEY([ORGANISATION_ID]) REFERENCES [dbo].[ORGANISATION] ([ID]);
ALTER TABLE [dbo].[SHOP_ARTICLE]  WITH CHECK ADD  CONSTRAINT [FK_SHOP_ARTICLE_CREATED_USER_ID] FOREIGN KEY([CREATED_USER_ID]) REFERENCES [dbo].[ESHOP_USER] ([ID]);
ALTER TABLE [dbo].[SHOP_ARTICLE]  WITH CHECK ADD  CONSTRAINT [FK_SHOP_ARTICLE_MODIFIED_USER_ID] FOREIGN KEY([MODIFIED_USER_ID]) REFERENCES [dbo].[ESHOP_USER] ([ID]);
ALTER TABLE [dbo].[SHOP_ARTICLE]  WITH CHECK ADD  CONSTRAINT [FK_SHOP_ARTICLE_CURRENCY_ID] FOREIGN KEY([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY] ([ID]);

CREATE TABLE [dbo].[OFFER_POSITION](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[OFFER_ID] [bigint] NOT NULL,
	[TYPE] [varchar](50) NOT NULL,
	[UMSART_ID] [varchar](19) NULL,
	[SHOP_ARTICLE_ID] [bigint] NULL,
	[ARTICLE_NUMBER] [varchar](50) NULL,
    [ARTICLE_DESCRIPTION] [varchar](256) NULL,
    [VEHICLE_ID] [varchar](19) NULL,
	[VEHICLE_DESCRIPTION] [varchar](50) NULL,
	[CALCULATED] [datetime] NOT NULL,
	[SEQUENCE] [int] NOT NULL,
	[CONTEXT] [varchar](10) NULL,
	[QUANTITY] [decimal](18,2) NULL,
	[UOM_ISO] [varchar](3)  NULL,
	[CURRENCY_ID] [int] NULL,
	[GROSS_PRICE] [decimal](18,2) NULL,
	[NET_PRICE] [decimal](18,2) NULL,
	[TOTAL_GROSS_PRICE] [decimal](18,2) NULL,
	[REMARK] [varchar](200) NULL,
	[ACTION_TYPE] [varchar](15) NULL, --ADDITION_AMOUNT,ADDITION_PERCENT, DISCOUNT_AMOUNT,DISCOUNT_PERCENT
	[DELIVERY_TYPE_ID] [int] NULL,
	[DELIVERY_DATE] [datetime] NULL,
	[CREATED_USER_ID] [bigint] NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_USER_ID] [bigint] NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[TECSTATE] [varchar](8) NOT NULL DEFAULT 'ACTIVE',
	[MAKE_ID] [varchar](19) NULL, --Used to identify the vehicle as with Shopping basket
	[MODEL_ID] [varchar](19) NULL, --Used to identify the vehicle as with Shopping basket
	[ACTION_VALUE] [decimal](18,3) DEFAULT 0,
	[VEHICLE_BOM_ID] [varchar](19) NULL,
	[VEHICLE_BOM_DESCRIPTION] [varchar](50) NULL,
	[ARTICLE_ENHANCED_DESCRIPTION] [varchar](50) NULL, --Use "product_addon" or take from SHOPARTICLE
	[PRICED_UNIT] [varchar](3) NULL,
	[CATALOG_PATH] [varchar](50) NULL,
	[VEHICLE_TYPE_CODE] [varchar](10) NULL,
	[PRICED_QUANTITY] [decimal](18,2) NULL,
	[VERSION] [int] NOT NULL DEFAULT 1
CONSTRAINT [PK_OFFER_POSITION] PRIMARY KEY CLUSTERED
([ID] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
ALTER TABLE [dbo].[OFFER_POSITION]  WITH CHECK ADD  CONSTRAINT [FK_OFFER_POSITION_PERSON] FOREIGN KEY([OFFER_ID]) REFERENCES [dbo].[OFFER] ([ID]);
ALTER TABLE [dbo].[OFFER_POSITION]  WITH CHECK ADD  CONSTRAINT [FK_SHOP_ARTICLE] FOREIGN KEY([SHOP_ARTICLE_ID]) REFERENCES [dbo].[SHOP_ARTICLE] ([ID]);
ALTER TABLE [dbo].[OFFER_POSITION]  WITH CHECK ADD  CONSTRAINT [FK_OFFER_POSITION_CREATED_USER_ID] FOREIGN KEY([CREATED_USER_ID]) REFERENCES [dbo].[ESHOP_USER] ([ID]);
ALTER TABLE [dbo].[OFFER_POSITION]  WITH CHECK ADD  CONSTRAINT [FK_OFFER_POSITION_MODIFIED_USER_ID] FOREIGN KEY([MODIFIED_USER_ID]) REFERENCES [dbo].[ESHOP_USER] ([ID]);
ALTER TABLE [dbo].[OFFER_POSITION]  WITH CHECK ADD  CONSTRAINT [FK_OFFER_POSITION_DELIVERY_TYPE_ID] FOREIGN KEY([DELIVERY_TYPE_ID]) REFERENCES [dbo].[DELIVERY_TYPE] ([ID]);
ALTER TABLE [dbo].[OFFER_POSITION]  WITH CHECK ADD  CONSTRAINT [FK_OFFER_POSITION_CURRENCY_ID] FOREIGN KEY([CURRENCY_ID]) REFERENCES [dbo].[CURRENCY] ([ID]);

-- CREATE INDEX
CREATE INDEX IDX_OFFER_VEHICLE_DESC ON [dbo].[OFFER_POSITION] (OFFER_ID, VEHICLE_DESCRIPTION);

CREATE TABLE [dbo].[OFFER_PERSON_PROPERTY](
	[PERSON_ID] [bigint] NOT NULL,
	[TYPE] [varchar](50) NOT NULL,
	[VALUE] [varchar](255) NOT NULL,
	CONSTRAINT [PK_OFFER_PERSON_PROPERTY] PRIMARY KEY CLUSTERED
	([PERSON_ID], [TYPE] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
ALTER TABLE [dbo].[OFFER_PERSON_PROPERTY]  WITH CHECK ADD  CONSTRAINT [FK_OFFER_PERSON_PERSON_PROPERTY] FOREIGN KEY([PERSON_ID])
REFERENCES [dbo].[OFFER_PERSON] ([ID]);
--Offer module tables end

ALTER TABLE [ESHOP_RELEASE] ADD [RELEASE_BRANCH] [VARCHAR](20) NULL,

ALTER TABLE [OFFER_PERSON] ADD [OFFER_COMPANY_NAME] [VARCHAR](100) NULL

ALTER TABLE [OFFER] ALTER COLUMN RECIPIENT_ID [bigint] NULL;
ALTER TABLE [OFFER] ALTER COLUMN RECIPIENT_ADDRESS_ID [bigint] NULL;
ALTER TABLE [SALUTATION] ADD [TYPE] [VARCHAR](10) NULL

-- Increase length of VEHICLE_DESCRIPTION in OFFER_POSITION
ALTER TABLE [dbo].[OFFER_POSITION] ALTER COLUMN VEHICLE_DESCRIPTION VARCHAR(255);

-- Update property of ACTION_TYPE to NOT NULL
ALTER TABLE OFFER_POSITION ALTER COLUMN ACTION_TYPE [VARCHAR](30)  NOT NULL;

-- Create view offer
CREATE VIEW VIEW_OFFER AS
		SELECT DISTINCT
		o.ID,
		o.OWNER_ID,
		o.CLIENT_ID AS ORGANISATION_ID,
		o.OFFER_NUMBER,
		(SELECT
			CASE WHEN (operson.OFFER_COMPANY_NAME IS NULL OR operson.OFFER_COMPANY_NAME='')
			THEN CONCAT(operson.FIRST_NAME, ' ', operson.LAST_NAME)
			ELSE operson.OFFER_COMPANY_NAME
			END
		WHERE operson.TECSTATE = 'ACTIVE')
		AS CUSTOMER_NAME,
		e.USERNAME AS OWNER_USERNAME,
		o.REMARK,
		o.OFFER_DATE,
		o.STATUS,
		(SELECT
			STUFF((SELECT ';' + t2.VEHICLE_DESCRIPTION
				FROM OFFER_POSITION t2
				WHERE t1.ID = t2.OFFER_ID
				AND t2.TECSTATE = 'ACTIVE'
				AND t2.VEHICLE_DESCRIPTION IS NOT NULL AND t2.VEHICLE_DESCRIPTION <> ''
				FOR XML PATH('')), 1, 1, '')
			FROM OFFER t1
			WHERE ID = o.ID
			GROUP BY ID) AS VEHICLE_DESCRIPTIONS,
		o.TOTAL_GROSS_PRICE
	FROM OFFER o
	LEFT JOIN OFFER_POSITION op
	ON op.OFFER_ID = o.ID
	LEFT JOIN OFFER_PERSON operson
	ON operson.ID = o.RECIPIENT_ID
	JOIN ESHOP_USER e
	ON e.ID = o.OWNER_ID
	WHERE o.TECSTATE = 'ACTIVE'
	AND (op.TECSTATE = 'ACTIVE' OR op.TECSTATE IS NULL);

-- Create view offer person
CREATE VIEW VIEW_OFFER_PERSON AS
	SELECT DISTINCT
		o.ID,
		o.ORGANISATION_ID,
		(SELECT
			CASE WHEN (o.OFFER_COMPANY_NAME IS NULL OR o.OFFER_COMPANY_NAME='')
			THEN CONCAT(o.FIRST_NAME, ' ', o.LAST_NAME)
			ELSE o.OFFER_COMPANY_NAME
			END)
		AS DISPLAY_NAME,
		COALESCE(o.OFFER_COMPANY_NAME,'') AS COMPANY_NAME,
		COALESCE(o.FIRST_NAME,'') AS FIRST_NAME,
		COALESCE(o.LAST_NAME,'') AS LAST_NAME,
		COALESCE(oa.LINE1,'') AS LINE1,
		COALESCE(oa.ZIPCODE,'') AS ZIPCODE,
		COALESCE(oa.CITY,'') AS CITY,
		COALESCE((SELECT VALUE FROM OFFER_PERSON_PROPERTY WHERE PERSON_ID=o.ID and TYPE='PHONE'), '') AS PHONE,
		COALESCE((SELECT VALUE FROM OFFER_PERSON_PROPERTY WHERE PERSON_ID=o.ID and TYPE='FAX'), '') AS FAX,
		COALESCE((SELECT VALUE FROM OFFER_PERSON_PROPERTY WHERE PERSON_ID=o.ID and TYPE='SALUTATION'), '') AS SALUTATION,
		COALESCE(o.EMAIL,'') AS EMAIL
		FROM OFFER_PERSON o
		LEFT JOIN OFFER_ADDRESS oa
		ON oa.PERSON_ID = o.ID
	WHERE o.TECSTATE = 'ACTIVE' AND o.STATUS = 'ACTIVE';

-- Add columns for OFFER POSITION
ALTER TABLE [dbo].[OFFER_POSITION] ADD CONNECT_VEHICLE_ID VARCHAR(50);

--- START #2294: update permission
ALTER TABLE ROLE_PERMISSION DROP CONSTRAINT FK_ROLE_PERMISSION_ESHOP_PERMISSION;
CREATE TABLE [dbo].[GROUP_PERMISSION](
    [ID] bigint IDENTITY(1,1) NOT NULL,
    [GROUP_ID] bigint NOT NULL,
    [PERM_ID] bigint NOT NULL,
    [ALLOWED] bit NOT NULL DEFAULT 1;
 PRIMARY KEY CLUSTERED
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

-- ADD UNIQUE CONSTRAINT FOR COMPOUND KEY GROUP_ID and PERM_ID
ALTER TABLE [dbo].[GROUP_PERMISSION] ADD CONSTRAINT [UC_GROUP_PERMISSION] UNIQUE ([GROUP_ID], [PERM_ID]);
-- CHANGE COLUMN TYPE OF CREATED_BY AND MODIFIED_BY IN ESHOP_PERMISSION
ALTER TABLE [dbo].[ESHOP_PERMISSION] ALTER COLUMN [CREATED_BY] [BIGINT];
ALTER TABLE [dbo].[ESHOP_PERMISSION] ALTER COLUMN [MODIFIED_BY] [BIGINT];
-- CREATE INDEX
CREATE INDEX IDX_GROUP_PERMISSION_ID ON [dbo].[GROUP_PERMISSION] (ID);
CREATE INDEX IDX_GROUP_PERMISSION_GROUP_ID_PERM_ID ON [dbo].[GROUP_PERMISSION] (GROUP_ID, PERM_ID);
--- END #2294: update permission

--- CREATE ORGANISATION_PROPERTY
CREATE TABLE [dbo].[ORGANISATION_PROPERTY](
	[ID] bigint IDENTITY(1,1) NOT NULL,
	[ORGANISATION_ID] [bigint] NOT NULL,
	[TYPE] [varchar](50) NOT NULL,
	[VALUE] [varchar](255) NOT NULL,
	CONSTRAINT [PK_ORGANISATION_PROPERTY] PRIMARY KEY CLUSTERED
	([ORGANISATION_ID], [TYPE] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

--- CREATE ACTIVE USER PROFILE VIEW
CREATE VIEW V_ACTIVE_USER AS
    SELECT
        U.ID,
        U.USERNAME,
        U.EMAIL,
        CONCAT(U.FIRST_NAME, ' ', U.LAST_NAME) AS FULL_NAME,
        U.PHONE,
        R.NAME AS ROLE_NAME,
        G.NAME AS GROUP_NAME,
        OG.ORGANISATION_ID AS ORG_ID,
        O.PARENT_ID AS ORG_PARENT_ID,
        O.ORG_CODE AS ORG_CODE,
        OP.SHORTNAME AS AFFILIATE,
        O.NAME AS ORG_NAME
    FROM
        ESHOP_USER U
        JOIN GROUP_USER GU ON U.ID = GU.USER_ID
        JOIN ESHOP_GROUP G ON GU.GROUP_ID = G.ID
        JOIN GROUP_ROLE GR ON GR.GROUP_ID = G.ID
        JOIN ESHOP_ROLE R  ON GR.ROLE_ID = R.ID
        JOIN ORGANISATION_GROUP OG ON G.ID = OG.GROUP_ID
        JOIN ORGANISATION O ON O.ID = OG.ORGANISATION_ID
        JOIN LOGIN L ON L.USER_ID = U.ID
        JOIN ORGANISATION OP ON O.PARENT_ID = OP.ID
    WHERE L.IS_USER_ACTIVE = 1 ;

-- ADD net price state for user setting
ALTER TABLE [dbo].[USER_SETTINGS] ADD CURRENT_STATE_NET_PRICE_VIEW [bit]  DEFAULT ((0));

--- CREATE ORDER HISTORY VIEW
CREATE VIEW V_ORDER_HISTORY AS
		SELECT DISTINCT
		o.ID,
		o.CUSTOMER_NUMBER,
		org.NAME AS CUSTOMER_NAME,
		o.ORDER_NUMBER,
		o.TOTAL AS TOTAL_PRICE,
		o.CREATED_DATE,
		o.SALE_NAME,
		o.SALE_ID,
		org.PARENT_ID AS AFFILIATE_ID,
		o.CLOSED_DATE,
		o.TYPE,
		o.AX_PROCESS_STATUS,
		o.WORK_IDS,
		o.ERP_ORDER_DETAIL_URL AS AX_ORDER_URL
	FROM ORDER_HISTORY o
	LEFT JOIN ORGANISATION org
	ON o.CUSTOMER_NUMBER = org.ORG_CODE
	WHERE o.ORDER_NUMBER IS NOT NULL AND o.SALE_ID IS NOT NULL

-- Add PERMISSION_KEY column
ALTER TABLE ESHOP_PERMISSION ADD PERMISSION_KEY varchar (255)

-- View User Detail
CREATE VIEW V_USER_DETAIL AS
  SELECT DISTINCT 
    ROW_NUMBER() OVER (ORDER BY U.ID) AS ID,
    U.ID AS USER_ID, 
    U.USERNAME AS USER_NAME, 
    U.EMAIL AS USER_EMAIL,
    U.FIRST_NAME AS FIRST_NAME,
    U.LAST_NAME AS LAST_NAME,
    U.PHONE AS TELEPHONE,
    US.ID AS USER_SETTING_ID,
    US.SALE_ON_BEHALF_OF AS SALE_ON_BEHALF_OF,
    R.ID AS ROLE_ID, 
    R.NAME AS ROLE_NAME, 
    G.ID AS GROUP_ID, 
    G.NAME AS GROUP_NAME, 
    OG.ORGANISATION_ID AS ORG_ID, 
    O.PARENT_ID AS ORG_PARENT_ID, 
    O.ORG_CODE AS ORG_CODE, 
    O.SHORTNAME AS ORG_SHORT_NAME,
    O.NAME AS ORG_NAME,
    O.ORDER_SETTINGS_ID AS ORG_SETTINGS_ID,
    SL.CODE AS SALUT_CODE,
    L.FIRST_LOGIN_DATE AS FIRST_LOGIN_DATE,
    U.SIGN_IN_DATE AS LAST_LOGIN_DATE
  from 
  	ESHOP_USER U
    JOIN GROUP_USER GU ON U.ID = GU.USER_ID
    JOIN ESHOP_GROUP G ON GU.GROUP_ID = G.ID
    JOIN GROUP_ROLE GR ON GR.GROUP_ID = G.ID
    JOIN ESHOP_ROLE R  ON GR.ROLE_ID = R.ID
    JOIN ORGANISATION_GROUP OG ON G.ID = OG.GROUP_ID
    JOIN ORGANISATION O ON O.ID = OG.ORGANISATION_ID
    JOIN LOGIN L ON L.USER_ID = U.ID
    JOIN USER_SETTINGS US ON US.ID = U.SETTING
    JOIN SALUTATION SL ON SL.ID = U.SALUTATION
  WHERE L.IS_USER_ACTIVE = 1;
    
-- INDEX ON [dbo].[ESHOP_USER]
CREATE INDEX IDX_ESHOP_USER_LANGUAGE ON [dbo].[ESHOP_USER] (LANGUAGE);
CREATE INDEX IDX_ESHOP_USER_USERNAME ON [dbo].[ESHOP_USER] (USERNAME);
CREATE INDEX IDX_ESHOP_USER_SETTING ON [dbo].[ESHOP_USER] (SETTING);
CREATE INDEX IDX_ESHOP_USER_EMAIL ON [dbo].[ESHOP_USER] (EMAIL);

-- INDEX ON [dbo].[LANGUAGES]
CREATE INDEX IDX_LANGUAGES_LANGISO ON [dbo].[LANGUAGES] (LANGISO);

-- INDEX ON [dbo].[AAD_ACCOUNTS]
CREATE INDEX IDX_AAD_ACCOUNTS_PRIMARY_CONTACT_EMAIL ON [dbo].[AAD_ACCOUNTS] (PRIMARY_CONTACT_EMAIL);
CREATE INDEX IDX_AAD_ACCOUNTS_PERMIT_GROUP ON [dbo].[AAD_ACCOUNTS] (PERMIT_GROUP);

-- Remove UN_ARTICLE_NUMBER CONSTRAINT
ALTER TABLE [dbo].[SHOP_ARTICLE] DROP CONSTRAINT UN_ARTICLE_NUMBER;

-- ADD ORDER_DISPLAY Column
ALTER TABLE PAYMENT_METHOD ADD ORDER_DISPLAY int DEFAULT 0;

-- View V_BASKET_HISTORY
CREATE VIEW V_BASKET_HISTORY AS
  SELECT DISTINCT 
    ROW_NUMBER() OVER (ORDER BY BH.ID) AS ID,
    BH.ID AS BASKET_HISTORY_ID, 
    BH.BASKET_NAME,
    BH.GRAND_TOTAL_EXCLUDE_VAT,
    BH.BASKET_JSON,
    BH.UPDATED_DATE,
    BH.ACTIVE,
    BH.ORGANISATION_ID AS ORG_ID,
    ORG.ORG_CODE AS ORG_CODE,
    ORG.SHORTNAME AS ORG_SHORT_NAME,
    BH.CREATED_USER_ID,
    CU.FIRST_NAME AS CREATED_FIRST_NAME,
    CU.LAST_NAME AS CREATED_LAST_NAME,
    CONCAT(CU.FIRST_NAME, ' ', CU.LAST_NAME) AS CREATED_FULL_NAME,
    BH.SALES_USER_ID, 
    SU.FIRST_NAME AS SALES_FIRST_NAME,
    SU.LAST_NAME AS SALES_LAST_NAME,
    CONCAT(SU.FIRST_NAME, ' ', SU.LAST_NAME) AS SALES_FULL_NAME
  FROM 
    BASKET_HISTORY BH
    JOIN ESHOP_USER CU ON CU.ID = BH.CREATED_USER_ID
    JOIN ESHOP_USER SU ON SU.ID = BH.SALES_USER_ID
    JOIN ORGANISATION ORG ON ORG.ID = BH.ORGANISATION_ID
  WHERE BH.ACTIVE = 1

-- Create V_USER_EXPORT
CREATE VIEW V_USER_EXPORT AS
	SELECT DISTINCT
	ROW_NUMBER() OVER (ORDER BY VU.USER_ID) AS ID,
	VU.ID AS USER_ID,
	VU.ORG_CODE AS ORG_CODE,
	EO.EXTERNAL_CUSTOMER_NAME AS EXTERNAL_CUSTOMER_NAME,
	EU.USERNAME AS EXTERNAL_USER_NAME,
	VU.USER_NAME AS USER_NAME,
	VU.FIRST_NAME AS FIRST_NAME,
	VU.LAST_NAME AS LAST_NAME,
	VU.USER_EMAIL AS USER_EMAIL,
	A.ZIPCODE AS ZIPCODE,
	OP.SHORTNAME AS ORG_PARENT_SHORT_NAME,
	VU.FIRST_LOGIN_DATE AS FIRST_LOGIN_DATE,
	VU.LAST_LOGIN_DATE AS LAST_LOGIN_DATE

	FROM V_USER_DETAIL VU
	JOIN ORGANISATION OP ON VU.ORG_PARENT_ID=OP.ID
	LEFT JOIN EXTERNAL_ORGANISATION EO ON EO.ORG_ID=VU.ORG_ID
	LEFT JOIN ORGANISATION_ADDRESS OA ON OA.ORGANISATION_ID = VU.ORG_ID
	LEFT JOIN ADDRESS A ON A.ID=OA.ADDRESS_ID
	LEFT JOIN ADDRESS_TYPE AT ON (A.ADDRESS_TYPE_ID = AT.ID AND AT.TYPE='DEFAULT')
	LEFT JOIN EXTERNAL_USER EU ON EU.ESHOP_USER_ID = VU.USER_ID
-- #2671
ALTER TABLE [dbo].[EXTERNAL_ORGANISATION] ADD UNIQUE (EXTERNAL_CUSTOMER_NAME)
ALTER TABLE [dbo].[EXTERNAL_USER] ADD UNIQUE (USERNAME)

ALTER TABLE [LOGIN] ADD [LAST_ON_BEHALF_OF_DATE] [DATETIME] NULL;

-- Add FIRST_LOGIN_DATE
ALTER TABLE [LOGIN] ADD [FIRST_LOGIN_DATE] [datetime];

-- #2946 allow two decimal
DROP INDEX [dbo].[OFFER_PERSON].[IDX_OFFER_PERSON_HOURLY_RATE];
ALTER TABLE [dbo].[ESHOP_USER] ALTER COLUMN HOURLY_RATE [decimal](10, 2) NULL;
ALTER TABLE [dbo].[MIGRATION_ESHOP_USER] ALTER COLUMN HOURLY_RATE [decimal](10, 2) NULL;
ALTER TABLE [dbo].[OFFER_PERSON] ALTER COLUMN HOURLY_RATE [decimal](10, 2) NULL;

-- #2981: add closed date to ORDER HISTORY
ALTER TABLE ORDER_HISTORY ADD COLUMN CLOSED_DATE datetime NULL;
ALTER TABLE ORDER_HISTORY ADD TYPE varchar(20) NULL;
ALTER TABLE ORDER_HISTORY ADD AX_PROCESS_STATUS varchar(20) NULL;
ALTER TABLE ORDER_HISTORY ADD WORK_IDS varchar(1000) NULL;

-- Message schema
--Create MESSAGE_ACCESS_RIGHT table
CREATE TABLE [dbo].[MESSAGE_ACCESS_RIGHT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_GROUP] [varchar](50) NOT NULL,
	[USER_GROUP_KEY] [varchar](50) NOT NULL,
	[MESSAGE_ROLE_TYPE_ID] [int] NOT NULL,
	[DESCRIPTION] [varchar](200) NULL,
 CONSTRAINT [PK_MESSAGE_ACCESS_RIGHT] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--Create MESSAGE_ROLE_TYPE table
CREATE TABLE [dbo].[MESSAGE_ROLE_TYPE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ROLE_TYPE] [varchar](50) NOT NULL,
	[DESCRIPTION] [varchar](200) NULL,
 CONSTRAINT [PK_MESSAGE_ROLE_TYPE] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--Create MESSAGE_ACCESS_RIGHT _ROLE table
CREATE TABLE [dbo].[MESSAGE_ACCESS_RIGHT_ROLE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MESSAGE_ACCESS_RIGHT_ID] [int] NOT NULL,
	[ESHOP_ROLE_ID] [int] NOT NULL,
 CONSTRAINT [PK_MESSAGE_ACCESS_RIGHT _ROLE] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--Create MESSAGE_STYLE table
CREATE TABLE [dbo].[MESSAGE_STYLE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[STYLE] [varchar](50) NOT NULL,
	[DESCRIPTION] [varchar](200) NULL,
 CONSTRAINT [PK_MESSAGE_STYLE] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--Create MESSAGE_TYPE table
CREATE TABLE [dbo].[MESSAGE_TYPE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TYPE] [varchar](50) NOT NULL,
	[DESCRIPTION] [varchar](200) NULL,
 CONSTRAINT [PK_MESSAGE_TYPE] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--Create MESSAGE_AREA table
CREATE TABLE [dbo].[MESSAGE_AREA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AREA] [varchar](200) NOT NULL,
	[AUTH] [bit] NOT NULL DEFAULT 0,
	[DESCRIPTION] [varchar](200) NULL,
 CONSTRAINT [PK_MESSAGE_AREA] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--Create MESSAGE_SUB_AREA table
CREATE TABLE [dbo].[MESSAGE_SUB_AREA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SUB_AREA] [varchar](50) NOT NULL,
	[SORT] [smallint] NOT NULL,
	[MESSAGE_AREA_ID] [int] NOT NULL,
	[DESCRIPTION] [varchar](200) NULL,
 CONSTRAINT [PK_MESSAGE_SUB_AREA] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--Create MESSAGE_LOCATION_TYPE table
CREATE TABLE [dbo].[MESSAGE_LOCATION_TYPE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[LOCATION_TYPE] [varchar](50) NOT NULL,
	[DESCRIPTION] [varchar](200) NULL,
 CONSTRAINT [PK_MESSAGE_LOCATION_TYPE] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--Create MESSAGE_LOCATION table
CREATE TABLE [dbo].[MESSAGE_LOCATION](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MESSAGE_LOCATION_TYPE_ID] [int] NOT NULL,
	[VALUE] [varchar](50) NOT NULL,
 CONSTRAINT [PK_MESSAGE_LOCATION] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--Create MESSAGE_VISIBILITY table
CREATE TABLE [dbo].[MESSAGE_VISIBILITY](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[VISIBILITY] [varchar](200) NOT NULL,
	[DESCRIPTION] [varchar](200) NULL,
 CONSTRAINT [PK_MESSAGE_VISIBILITY] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--Create MESSAGE table
CREATE TABLE [dbo].[MESSAGE](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TITLE] [varchar](200) NOT NULL,
	[MESSAGE_LOCATION_ID] [int] NOT NULL,
	[MESSAGE_ACCESS_RIGHT_ID] [int] NOT NULL,
	[MESSAGE_TYPE_ID] [int] NOT NULL,
	[MESSAGE_SUB_AREA_ID] [int] NOT NULL,
	[MESSAGE_STYLE_ID] [int] NOT NULL,
	[MESSAGE_VISIBILITY_ID] [int] NOT NULL,
	[ACTIVE] [bit] NOT NULL,
	[DATE_VALID_FROM] [datetime] NOT NULL,
	[DATE_VALID_TO] [datetime] NOT NULL,
	[CREATED_USER_ID] [bigint] NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_USER_ID] [bigint] NULL,
	[MODIFIED_DATE] [datetime] NULL,
 CONSTRAINT [PK_MESSAGE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--Create MESSAGE_LANGUAGE table
CREATE TABLE [dbo].[MESSAGE_LANGUAGE](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[MESSAGE_ID] [bigint] NOT NULL,
	[LANG_ISO] [varchar](10) NOT NULL,
	[CONTENT] [varchar](max) NOT NULL,
 CONSTRAINT [PK_MESSAGE_LANGUAGE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

--- MESSAGE #2763
CREATE TABLE [dbo].[MESSAGE_HIDING](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[USER_ID] [bigint] NOT NULL,
	[MESSAGE_ID] [bigint] NOT NULL,
	CONSTRAINT [PK_MESSAGE_HIDING] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

--- Create MESSAGE_ACCESS_RIGHT_AREA table
CREATE TABLE [dbo].[MESSAGE_ACCESS_RIGHT_AREA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MESSAGE_ACCESS_RIGHT_ID] [int] NOT NULL,
	[MESSAGE_AREA_ID] [int] NOT NULL,
 CONSTRAINT [PK_MESSAGE_ACCESS_RIGHT_AREA] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--- Create MESSAGE_LOCATION_TYPE_ROLE_TYPE table
CREATE TABLE [dbo].[MESSAGE_LOCATION_TYPE_ROLE_TYPE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MESSAGE_LOCATION_TYPE_ID] [int] NOT NULL,
	[MESSAGE_ROLE_TYPE_ID] [int] NOT NULL,
 CONSTRAINT [PK_MESSAGE_LOCATION_TYPE_ROLE_TYPE] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--- CREATE V_MESSAGE VIEW
CREATE VIEW V_MESSAGE AS
	SELECT DISTINCT 
        M.ID AS ID,
        M.TITLE AS TITLE,
		T.TYPE AS TYPE,
		A.AREA AS AREA,
		SA.SUB_AREA AS SUB_AREA,
		L.VALUE AS LOCATION_VALUE,
		M.ACTIVE AS ACTIVE
    FROM 
        MESSAGE M
        JOIN MESSAGE_TYPE T ON M.MESSAGE_TYPE_ID = T.ID
		JOIN MESSAGE_SUB_AREA SA ON M.MESSAGE_SUB_AREA_ID=SA.ID
        JOIN MESSAGE_AREA A ON SA.MESSAGE_AREA_ID = A.ID
		JOIN MESSAGE_LOCATION L ON M.MESSAGE_LOCATION_ID = L.ID

--- Update column rules for TYPE column in ORDER HISTORY
ALTER TABLE ORDER_HISTORY ALTER COLUMN TYPE NOT NULL

-- Add setting for option of showing classic/tree category
ALTER TABLE [dbo].[USER_SETTINGS] ADD [CLASSIC_CATEGORY_VIEW] [bit] DEFAULT ((1));