USE axch;
SET IDENTITY_INSERT axch.dbo.DELIVERY_TYPE OFF;
GO
SET IDENTITY_INSERT axch.dbo.INVOICE_TYPE OFF;
GO
SET IDENTITY_INSERT axch.dbo.ALLOCATION_TYPE OFF;
GO
SET IDENTITY_INSERT axch.dbo.COLLECTIVE_DELIVERY OFF;
GO
SET IDENTITY_INSERT axch.dbo.PAYMENT_METHOD OFF;
GO
SET IDENTITY_INSERT axch.dbo.CUSTOMER_SETTINGS OFF;
GO
SET IDENTITY_INSERT axch.dbo.USER_SETTINGS OFF;
GO
SET IDENTITY_INSERT axch.dbo.ADDRESS_TYPE OFF;
GO
SET IDENTITY_INSERT axch.dbo.ADDRESS OFF;
GO
SET IDENTITY_INSERT axch.dbo.ORGANISATION_TYPE OFF;
GO
SET IDENTITY_INSERT axch.dbo.ORGANISATION OFF;
GO
SET IDENTITY_INSERT axch.dbo.ORGANISATION_ADDRESS OFF;
GO
SET IDENTITY_INSERT axch.dbo.ORGANISATION_SETTINGS OFF;
GO
SET IDENTITY_INSERT axch.dbo.ROLE_TYPE OFF;
GO
SET IDENTITY_INSERT axch.dbo.ESHOP_ROLE OFF;
GO
SET IDENTITY_INSERT axch.dbo.LANGUAGES OFF;
GO
SET IDENTITY_INSERT axch.dbo.SALUTATION OFF;
GO
SET IDENTITY_INSERT axch.dbo.ESHOP_USER OFF;
GO
SET IDENTITY_INSERT axch.dbo.ESHOP_GROUP OFF;
GO
SET IDENTITY_INSERT axch.dbo.ORGANISATION_GROUP OFF;
GO
SET IDENTITY_INSERT axch.dbo.ORGANISATION_PROPERTY OFF;
GO
SET IDENTITY_INSERT axch.dbo.GROUP_ROLE OFF;
GO
SET IDENTITY_INSERT axch.dbo.GROUP_USER OFF;
GO
SET IDENTITY_INSERT axch.dbo.LICENSE_SETTINGS OFF;
GO
SET IDENTITY_INSERT axch.dbo.LICENSE OFF;
GO
SET IDENTITY_INSERT axch.dbo.LOGIN OFF;
GO
SET IDENTITY_INSERT axch.dbo.ORDER_HISTORY OFF;
GO
SET IDENTITY_INSERT axch.dbo.USER_ORDER_HISTORY OFF;
GO
SET IDENTITY_INSERT axch.dbo.PASSWORD_RESET_TOKEN OFF;
GO
SET IDENTITY_INSERT axch.dbo.ARTICLE_HISTORY OFF;
GO
SET IDENTITY_INSERT axch.dbo.USER_ARTICLE_HISTORY OFF;
GO
SET IDENTITY_INSERT axch.dbo.VIN_LOGGING OFF;
GO
SET IDENTITY_INSERT axch.dbo.VEHICLE_HISTORY OFF;
GO
SET IDENTITY_INSERT axch.dbo.USER_VEHICLE_HISTORY OFF;
GO
SET IDENTITY_INSERT axch.dbo.ESHOP_PERMISSION OFF;
GO
SET IDENTITY_INSERT axch.dbo.ROLE_PERMISSION OFF;
GO
SET IDENTITY_INSERT axch.dbo.ESHOP_FUNCTION OFF;
GO
SET IDENTITY_INSERT axch.dbo.PERM_FUNCTION OFF;
GO
SET IDENTITY_INSERT axch.dbo.AAD_ACCOUNTS OFF;
GO
SET IDENTITY_INSERT axch.dbo.BASKET_HISTORY OFF;
GO
SET IDENTITY_INSERT axch.dbo.COUNTRY OFF;
GO
SET IDENTITY_INSERT axch.dbo.COUPON_CONDITIONS OFF;
GO
SET IDENTITY_INSERT axch.dbo.COUPON_USE_LOG OFF;
GO
SET IDENTITY_INSERT axch.dbo.CURRENCY OFF;
GO
SET IDENTITY_INSERT axch.dbo.ESHOP_CART_ITEM OFF;
GO
SET IDENTITY_INSERT axch.dbo.ESHOP_RELEASE OFF;
GO
SET IDENTITY_INSERT axch.dbo.EXTERNAL_ORGANISATION OFF;
GO
SET IDENTITY_INSERT axch.dbo.EXTERNAL_USER OFF;
GO
SET IDENTITY_INSERT axch.dbo.GROUP_PERMISSION OFF;
GO
SET IDENTITY_INSERT axch.dbo.MAPPING_USER_ID_EBL_CONNECT OFF;
GO
SET IDENTITY_INSERT axch.dbo.MESSAGE OFF;
GO
SET IDENTITY_INSERT axch.dbo.MESSAGE_ACCESS_RIGHT OFF;
GO
SET IDENTITY_INSERT axch.dbo.MESSAGE_ACCESS_RIGHT_AREA OFF;
GO
SET IDENTITY_INSERT axch.dbo.MESSAGE_ACCESS_RIGHT_ROLE OFF;
GO
SET IDENTITY_INSERT axch.dbo.MESSAGE_AREA OFF;
GO
SET IDENTITY_INSERT axch.dbo.MESSAGE_HIDING OFF;
GO
SET IDENTITY_INSERT axch.dbo.MESSAGE_LANGUAGE OFF;
GO
SET IDENTITY_INSERT axch.dbo.MESSAGE_LOCATION OFF;
GO
SET IDENTITY_INSERT axch.dbo.MESSAGE_LOCATION_TYPE OFF;
GO
SET IDENTITY_INSERT axch.dbo.MESSAGE_LOCATION_TYPE_ROLE_TYPE OFF;
GO
SET IDENTITY_INSERT axch.dbo.MESSAGE_ROLE_TYPE OFF;
GO
SET IDENTITY_INSERT axch.dbo.MESSAGE_STYLE OFF;
GO
SET IDENTITY_INSERT axch.dbo.MESSAGE_SUB_AREA OFF;
GO
SET IDENTITY_INSERT axch.dbo.MESSAGE_TYPE OFF;
GO
SET IDENTITY_INSERT axch.dbo.MESSAGE_VISIBILITY OFF;
GO
SET IDENTITY_INSERT axch.dbo.MIGRATION_ORGANISATION OFF;
GO
SET IDENTITY_INSERT axch.dbo.OFFER OFF;
GO
SET IDENTITY_INSERT axch.dbo.OFFER_ADDRESS OFF;
GO
SET IDENTITY_INSERT axch.dbo.OFFER_PERSON OFF;
GO
SET IDENTITY_INSERT axch.dbo.OFFER_POSITION OFF;
GO
SET IDENTITY_INSERT axch.dbo.ORDER_STATUS OFF;
GO
SET IDENTITY_INSERT axch.dbo.ORDER_TYPE OFF;
GO
SET IDENTITY_INSERT axch.dbo.PAYMENT_TYPE OFF;
GO
SET IDENTITY_INSERT axch.dbo.SHOP_ARTICLE OFF;
GO
SET IDENTITY_INSERT axch.dbo.[STATE] OFF;
GO
SET IDENTITY_INSERT axch.dbo.SUPPORTED_AFFILIATE OFF;
GO
SET IDENTITY_INSERT axch.dbo.TOUR_TIME OFF;
GO
SET IDENTITY_INSERT axch.dbo.FEEDBACK_DEPARTMENT OFF;
GO
SET IDENTITY_INSERT axch.dbo.FEEDBACK_DEPARTMENT_CONTACT OFF;
GO
SET IDENTITY_INSERT axch.dbo.FEEDBACK_STATUS OFF;
GO
SET IDENTITY_INSERT axch.dbo.FEEDBACK_TOPIC OFF;
GO
SET IDENTITY_INSERT axch.dbo.FEEDBACK_TOPIC_DEPARTMENT OFF;
GO
SET IDENTITY_INSERT axch.dbo.FEEDBACK OFF;
GO
SET IDENTITY_INSERT axch.dbo.RETURN_ORDER_REASON OFF;
GO
SET IDENTITY_INSERT axch.dbo.DELIVERY_TYPE ON;
INSERT INTO axch.dbo.DELIVERY_TYPE(ID, [TYPE], DESC_CODE, DESCRIPTION) SELECT ID, [TYPE], DESC_CODE, DESCRIPTION FROM sag.dbo.DELIVERY_TYPE;
SET IDENTITY_INSERT axch.dbo.DELIVERY_TYPE OFF;
GO
SET IDENTITY_INSERT axch.dbo.INVOICE_TYPE ON;
INSERT INTO axch.dbo.INVOICE_TYPE(ID, INVOICE_TYPE_CODE, INVOICE_TYPE_NAME, INVOICE_TYPE_DESC) SELECT ID, INVOICE_TYPE_CODE, INVOICE_TYPE_NAME, INVOICE_TYPE_DESC FROM sag.dbo.INVOICE_TYPE;
SET IDENTITY_INSERT axch.dbo.INVOICE_TYPE OFF;
GO
SET IDENTITY_INSERT axch.dbo.ALLOCATION_TYPE ON;
INSERT INTO axch.dbo.ALLOCATION_TYPE(ID, [TYPE], DESC_CODE, DESCRIPTION) SELECT ID, [TYPE], DESC_CODE, DESCRIPTION FROM sag.dbo.ALLOCATION_TYPE;
SET IDENTITY_INSERT axch.dbo.ALLOCATION_TYPE OFF;
GO
SET IDENTITY_INSERT axch.dbo.COLLECTIVE_DELIVERY ON;
INSERT INTO axch.dbo.COLLECTIVE_DELIVERY(ID, [TYPE], DESC_CODE, DESCRIPTION) SELECT ID, [TYPE], DESC_CODE, DESCRIPTION FROM sag.dbo.COLLECTIVE_DELIVERY;
SET IDENTITY_INSERT axch.dbo.COLLECTIVE_DELIVERY OFF;
GO
SET IDENTITY_INSERT axch.dbo.PAYMENT_METHOD ON;
INSERT INTO axch.dbo.PAYMENT_METHOD(ID, PAY_METHOD, DESC_CODE, DESCRIPTION, ORDER_DISPLAY) SELECT ID, PAY_METHOD, DESC_CODE, DESCRIPTION, 0 FROM sag.dbo.PAYMENT_METHOD;
SET IDENTITY_INSERT axch.dbo.PAYMENT_METHOD OFF;
GO
SET IDENTITY_INSERT axch.dbo.CUSTOMER_SETTINGS ON;
INSERT INTO axch.dbo.CUSTOMER_SETTINGS(ID, ALLOCATION_ID, PAYMENT_METHOD, DELIVERY_ID, COLLECTIVE_DELIVERY_ID, NET_PRICE_VIEW, NET_PRICE_CONFIRM, VIEW_BILLING, ADDRESS_ID, USE_DEFAULT_SETTING, EMAIL_NOTIFICATION_ORDER, BILLING_ADDRESS_ID, DELIVERY_ADDRESS_ID, INVOICE_ID, ALLOW_NET_PRICE_CHANGED, INVOICE_TYPE, SHOW_DISCOUNT, SESSION_TIMEOUT_SECONDS) SELECT ID, ALLOCATION_ID, PAYMENT_METHOD, DELIVERY_ID, COLLECTIVE_DELIVERY_ID, NET_PRICE_VIEW, NET_PRICE_CONFIRM, VIEW_BILLING, ADDRESS_ID, USE_DEFAULT_SETTING, EMAIL_NOTIFICATION_ORDER, BILLING_ADDRESS_ID, DELIVERY_ADDRESS_ID, INVOICE_ID, ALLOW_NET_PRICE_CHANGED, INVOICE_TYPE, SHOW_DISCOUNT, SESSION_TIMEOUT_SECONDS FROM sag.dbo.CUSTOMER_SETTINGS;
SET IDENTITY_INSERT axch.dbo.CUSTOMER_SETTINGS OFF;
GO
SET IDENTITY_INSERT axch.dbo.USER_SETTINGS ON;
INSERT INTO axch.dbo.USER_SETTINGS(ID, ALLOCATION_ID, PAYMENT_METHOD, DELIVERY_ID, COLLECTIVE_DELIVERY_ID, NET_PRICE_VIEW, NET_PRICE_CONFIRM, VIEW_BILLING, ADDRESS_ID, USE_DEFAULT_SETTING, EMAIL_NOTIFICATION_ORDER, BILLING_ADDRESS_ID, DELIVERY_ADDRESS_ID, INVOICE_TYPE, SHOW_DISCOUNT, SHOW_HAPPY_POINTS, ACCEPT_HAPPY_POINT_TERM, SALE_ON_BEHALF_OF, SHOW_RECOMMENDED_RETAIL_PRICE, CURRENT_STATE_NET_PRICE_VIEW, CLASSIC_CATEGORY_VIEW) SELECT ID, ALLOCATION_ID, PAYMENT_METHOD, DELIVERY_ID, COLLECTIVE_DELIVERY_ID, NET_PRICE_VIEW, NET_PRICE_CONFIRM, VIEW_BILLING, ADDRESS_ID, 1, EMAIL_NOTIFICATION_ORDER, BILLING_ADDRESS_ID, DELIVERY_ADDRESS_ID, INVOICE_TYPE, SHOW_DISCOUNT, 0, 0, SALE_ON_BEHALF_OF, 0, CURRENT_STATE_NET_PRICE_VIEW, CLASSIC_CATEGORY_VIEW FROM sag.dbo.USER_SETTINGS;
SET IDENTITY_INSERT axch.dbo.USER_SETTINGS OFF;
GO
SET IDENTITY_INSERT axch.dbo.ADDRESS_TYPE ON;
INSERT INTO axch.dbo.ADDRESS_TYPE(ID, [TYPE], DESCRIPTION) SELECT ID, [TYPE], DESCRIPTION FROM sag.dbo.ADDRESS_TYPE;
SET IDENTITY_INSERT axch.dbo.ADDRESS_TYPE OFF;
GO
SET IDENTITY_INSERT axch.dbo.ADDRESS ON;
INSERT INTO axch.dbo.ADDRESS(ID, LINE1, LINE2, LINE3, COUNTRYISO, [STATE], CITY, ZIPCODE, ADDRESS_TYPE_ID) SELECT ID, LINE1, LINE2, LINE3, COUNTRYISO, [STATE], CITY, ZIPCODE, ADDRESS_TYPE_ID FROM sag.dbo.ADDRESS;
SET IDENTITY_INSERT axch.dbo.ADDRESS OFF;
GO
SET IDENTITY_INSERT axch.dbo.ORGANISATION_TYPE ON;
INSERT INTO axch.dbo.ORGANISATION_TYPE(ID, NAME, [LEVEL], DESCRIPTION) SELECT ID, NAME, [LEVEL], DESCRIPTION FROM sag.dbo.ORGANISATION_TYPE;
SET IDENTITY_INSERT axch.dbo.ORGANISATION_TYPE OFF;
GO
SET IDENTITY_INSERT axch.dbo.ORGANISATION ON;
INSERT INTO axch.dbo.ORGANISATION(ID, NAME, ORG_CODE, ORGTYPE_ID, PARENT_ID, DESCRIPTION, SHORTNAME, ORDER_SETTINGS_ID) SELECT ID, NAME, ORG_CODE, ORGTYPE_ID, PARENT_ID, DESCRIPTION, SHORTNAME, ORDER_SETTINGS_ID FROM sag.dbo.ORGANISATION;
SET IDENTITY_INSERT axch.dbo.ORGANISATION OFF;
GO
SET IDENTITY_INSERT axch.dbo.ORGANISATION_ADDRESS ON;
INSERT INTO axch.dbo.ORGANISATION_ADDRESS(ID, ORGANISATION_ID, ADDRESS_ID) SELECT ID, ORGANISATION_ID, ADDRESS_ID FROM sag.dbo.ORGANISATION_ADDRESS;
SET IDENTITY_INSERT axch.dbo.ORGANISATION_ADDRESS OFF;
GO
SET IDENTITY_INSERT axch.dbo.ORGANISATION_SETTINGS ON;
INSERT INTO axch.dbo.ORGANISATION_SETTINGS(ID, NAME, ORGANISATION_ID, SETTING_KEY, SETTING_VALUE) SELECT ID, NAME, ORGANISATION_ID, SETTING_KEY, SETTING_VALUE FROM sag.dbo.ORGANISATION_SETTINGS;
SET IDENTITY_INSERT axch.dbo.ORGANISATION_SETTINGS OFF;
GO
SET IDENTITY_INSERT axch.dbo.ROLE_TYPE ON;
INSERT INTO axch.dbo.ROLE_TYPE(ID, NAME, DESCRIPTION) SELECT ID, NAME, DESCRIPTION FROM sag.dbo.ROLE_TYPE;
SET IDENTITY_INSERT axch.dbo.ROLE_TYPE OFF;
GO
SET IDENTITY_INSERT axch.dbo.ESHOP_ROLE ON;
INSERT INTO axch.dbo.ESHOP_ROLE(ID, NAME, ROLE_TYPE_ID, DESCRIPTION) SELECT ID, NAME, ROLE_TYPE_ID, DESCRIPTION FROM sag.dbo.ESHOP_ROLE;
SET IDENTITY_INSERT axch.dbo.ESHOP_ROLE OFF;
GO
SET IDENTITY_INSERT axch.dbo.LANGUAGES ON;
INSERT INTO axch.dbo.LANGUAGES(ID, LANGCODE, LANGISO, DESCRIPTION) SELECT ID, LANGCODE, LANGISO, DESCRIPTION FROM sag.dbo.LANGUAGES;
SET IDENTITY_INSERT axch.dbo.LANGUAGES OFF;
GO
SET IDENTITY_INSERT axch.dbo.SALUTATION ON;
INSERT INTO axch.dbo.SALUTATION(ID, CODE, DESCRIPTION, [TYPE]) SELECT ID, CODE, DESCRIPTION, [TYPE] FROM sag.dbo.SALUTATION;
SET IDENTITY_INSERT axch.dbo.SALUTATION OFF;
GO
SET IDENTITY_INSERT axch.dbo.ESHOP_USER ON;
INSERT INTO axch.dbo.ESHOP_USER(ID, SALUTATION, FIRST_NAME, LAST_NAME, EMAIL, USERNAME, PHONE, [LANGUAGE], [TYPE], HOURLY_RATE, EMAIL_CONFIRMATION, NEWSLETTER, SETTING, VAT_CONFIRM, SIGN_IN_DATE, FAX) SELECT ID, SALUTATION, FIRST_NAME, LAST_NAME, EMAIL, USERNAME, PHONE, [LANGUAGE], [TYPE], HOURLY_RATE, EMAIL_CONFIRMATION, NEWSLETTER, SETTING, VAT_CONFIRM, SIGN_IN_DATE, FAX FROM sag.dbo.ESHOP_USER;
SET IDENTITY_INSERT axch.dbo.ESHOP_USER OFF;
GO
SET IDENTITY_INSERT axch.dbo.ESHOP_GROUP ON;
INSERT INTO axch.dbo.ESHOP_GROUP(ID, NAME, DESCRIPTION, ORG_CODE, ROLE_ID) SELECT ID, NAME, DESCRIPTION, ORG_CODE, ROLE_ID FROM sag.dbo.ESHOP_GROUP;
SET IDENTITY_INSERT axch.dbo.ESHOP_GROUP OFF;
GO
SET IDENTITY_INSERT axch.dbo.ORGANISATION_GROUP ON;
INSERT INTO axch.dbo.ORGANISATION_GROUP(ID, GROUP_ID, ORGANISATION_ID) SELECT ID, GROUP_ID, ORGANISATION_ID FROM sag.dbo.ORGANISATION_GROUP;
SET IDENTITY_INSERT axch.dbo.ORGANISATION_GROUP OFF;
GO
SET IDENTITY_INSERT axch.dbo.ORGANISATION_PROPERTY ON;
INSERT INTO axch.dbo.ORGANISATION_PROPERTY(ID, ORGANISATION_ID, [TYPE], VALUE) SELECT ID, ORGANISATION_ID, [TYPE], VALUE FROM sag.dbo.ORGANISATION_PROPERTY;
SET IDENTITY_INSERT axch.dbo.ORGANISATION_PROPERTY OFF;
GO
SET IDENTITY_INSERT axch.dbo.GROUP_ROLE ON;
INSERT INTO axch.dbo.GROUP_ROLE(ID, GROUP_ID, ROLE_ID) SELECT ID, GROUP_ID, ROLE_ID FROM sag.dbo.GROUP_ROLE;
SET IDENTITY_INSERT axch.dbo.GROUP_ROLE OFF;
GO
SET IDENTITY_INSERT axch.dbo.GROUP_USER ON;
INSERT INTO axch.dbo.GROUP_USER(ID, GROUP_ID, USER_ID) SELECT ID, GROUP_ID, USER_ID FROM sag.dbo.GROUP_USER;
SET IDENTITY_INSERT axch.dbo.GROUP_USER OFF;
GO
SET IDENTITY_INSERT axch.dbo.LICENSE_SETTINGS ON;
INSERT INTO axch.dbo.LICENSE_SETTINGS(ID, PACK_ID, PACK_NAME, PRODUCT_PARAMETERS, PACK_ARTICLE_ID, PACK_ARTICLE_NO, PACK_UMAR_ID, QUANTITY, LAST_UPDATE, LAST_UPDATED_BY, TYPE_OF_LICENSE) SELECT ID, PACK_ID, PACK_NAME, PRODUCT_PARAMETERS, PACK_ARTICLE_ID, PACK_ARTICLE_NO, PACK_UMAR_ID, QUANTITY, LAST_UPDATE, LAST_UPDATED_BY, TYPE_OF_LICENSE FROM sag.dbo.LICENSE_SETTINGS;
SET IDENTITY_INSERT axch.dbo.LICENSE_SETTINGS OFF;
GO
SET IDENTITY_INSERT axch.dbo.LICENSE ON;
INSERT INTO axch.dbo.LICENSE(ID, TYPE_OF_LICENSE, PACK_ID, PACK_NAME, CUSTOMER_NR, USER_ID, BEGIN_DATE, END_DATE, QUANTITY, QUANTITY_USED, LAST_USED, LAST_UPDATE, LAST_UPDATED_BY) SELECT ID, TYPE_OF_LICENSE, PACK_ID, PACK_NAME, CUSTOMER_NR, USER_ID, BEGIN_DATE, END_DATE, QUANTITY, QUANTITY_USED, LAST_USED, LAST_UPDATE, LAST_UPDATED_BY FROM sag.dbo.LICENSE;
SET IDENTITY_INSERT axch.dbo.LICENSE OFF;
GO
SET IDENTITY_INSERT axch.dbo.LOGIN ON;
INSERT INTO axch.dbo.LOGIN(ID, PASSWORD, USER_ID, IS_USER_ACTIVE, hash_type, LAST_ON_BEHALF_OF_DATE, FIRST_LOGIN_DATE) SELECT ID, PASSWORD, USER_ID, IS_USER_ACTIVE, hash_type, LAST_ON_BEHALF_OF_DATE, FIRST_LOGIN_DATE FROM sag.dbo.LOGIN;
SET IDENTITY_INSERT axch.dbo.LOGIN OFF;
GO
SET IDENTITY_INSERT axch.dbo.ORDER_HISTORY ON;
INSERT INTO axch.dbo.ORDER_HISTORY(ID, ORDER_NUMBER, TRANS_NUMBER, USER_ID, CUSTOMER_NUMBER, ORDER_INFO_JSON, ERP_ORDER_DETAIL_URL, SALE_ID, CREATED_DATE, SALE_NAME, TOTAL, CLOSED_DATE, [TYPE], AX_PROCESS_STATUS, WORK_IDS, ORDER_STATE) SELECT ID, ORDER_NUMBER, TRANS_NUMBER, USER_ID, CUSTOMER_NUMBER, ORDER_INFO_JSON, ERP_ORDER_DETAIL_URL, SALE_ID, CREATED_DATE, SALE_NAME, TOTAL, NULL, NULL, NULL, NULL, ORDER_STATE FROM sag.dbo.ORDER_HISTORY;
SET IDENTITY_INSERT axch.dbo.ORDER_HISTORY OFF;
GO
SET IDENTITY_INSERT axch.dbo.USER_ORDER_HISTORY ON;
INSERT INTO axch.dbo.USER_ORDER_HISTORY(ID, USER_ID, ORDER_ID) SELECT ID, USER_ID, ORDER_ID FROM sag.dbo.USER_ORDER_HISTORY;
SET IDENTITY_INSERT axch.dbo.USER_ORDER_HISTORY OFF;
GO
SET IDENTITY_INSERT axch.dbo.ARTICLE_HISTORY ON;
INSERT INTO axch.dbo.ARTICLE_HISTORY(ID, ART_NUMBER, ART_ID, ART_SAG_SYS_ID, MANUFACTURE, ART_IMG, VEHICLE_INFO, GROSS_PRICE, MENGE, DELIVERY_INFO, REFERENCE) SELECT ID, ART_NUMBER, ART_ID, ART_SAG_SYS_ID, MANUFACTURE, ART_IMG, VEHICLE_INFO, GROSS_PRICE, MENGE, DELIVERY_INFO, REFERENCE FROM sag.dbo.ARTICLE_HISTORY;
SET IDENTITY_INSERT axch.dbo.ARTICLE_HISTORY OFF;
GO
SET IDENTITY_INSERT axch.dbo.USER_ARTICLE_HISTORY ON;
INSERT INTO axch.dbo.USER_ARTICLE_HISTORY(ID, USER_ID, ART_HISTORY_ID) SELECT ID, USER_ID, ART_HISTORY_ID FROM sag.dbo.USER_ARTICLE_HISTORY;
SET IDENTITY_INSERT axch.dbo.USER_ARTICLE_HISTORY OFF;
GO
SET IDENTITY_INSERT axch.dbo.VIN_LOGGING ON;
INSERT INTO axch.dbo.VIN_LOGGING(ID, VIN, CUSTOMER_ID, ESTIMATE_ID, VEHICLE_ID, DATE_OF_LOG_ENTRY, USER_ID, STATUS, ERROR_CODE) SELECT ID, VIN, CUSTOMER_ID, ESTIMATE_ID, VEHICLE_ID, DATE_OF_LOG_ENTRY, USER_ID, STATUS, ERROR_CODE FROM sag.dbo.VIN_LOGGING;
SET IDENTITY_INSERT axch.dbo.VIN_LOGGING OFF;
GO
SET IDENTITY_INSERT axch.dbo.VEHICLE_HISTORY ON;
INSERT INTO axch.dbo.VEHICLE_HISTORY(ID, VEH_ID, VEH_MAKE, VEH_MODEL, VEH_TYPE, VEH_NAME, VEH_INFO, VEH_VIN, ID_SAG, ID_SAG_MAKE, ID_SAG_MODEL) SELECT ID, VEH_ID, VEH_MAKE, VEH_MODEL, VEH_TYPE, VEH_NAME, VEH_INFO, VEH_VIN, ID_SAG, ID_SAG_MAKE, ID_SAG_MODEL FROM sag.dbo.VEHICLE_HISTORY;
SET IDENTITY_INSERT axch.dbo.VEHICLE_HISTORY OFF;
GO
SET IDENTITY_INSERT axch.dbo.USER_VEHICLE_HISTORY ON;
INSERT INTO axch.dbo.USER_VEHICLE_HISTORY(ID, USER_ID, VEH_HISTORY_ID, SELECT_DATE) SELECT ID, USER_ID, VEH_HISTORY_ID, SELECT_DATE FROM sag.dbo.USER_VEHICLE_HISTORY;
SET IDENTITY_INSERT axch.dbo.USER_VEHICLE_HISTORY OFF;
GO
SET IDENTITY_INSERT axch.dbo.ESHOP_PERMISSION ON;
INSERT INTO axch.dbo.ESHOP_PERMISSION(ID, PERMISSION, DESCRIPTION, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, PERMISSION_KEY) SELECT ID, PERMISSION, DESCRIPTION, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, PERMISSION_KEY FROM sag.dbo.ESHOP_PERMISSION;
SET IDENTITY_INSERT axch.dbo.ESHOP_PERMISSION OFF;
GO
SET IDENTITY_INSERT axch.dbo.ROLE_PERMISSION ON;
INSERT INTO axch.dbo.ROLE_PERMISSION(ID, ROLE_ID, PERM_ID) SELECT ID, ROLE_ID, PERM_ID FROM sag.dbo.ROLE_PERMISSION;
SET IDENTITY_INSERT axch.dbo.ROLE_PERMISSION OFF;
GO
SET IDENTITY_INSERT axch.dbo.ESHOP_FUNCTION ON;
INSERT INTO axch.dbo.ESHOP_FUNCTION(ID, FUNCTION_NAME, DESCRIPTION, RELATIVE_URL) SELECT ID, FUNCTION_NAME, DESCRIPTION, RELATIVE_URL FROM sag.dbo.ESHOP_FUNCTION;
SET IDENTITY_INSERT axch.dbo.ESHOP_FUNCTION OFF;
GO
SET IDENTITY_INSERT axch.dbo.PERM_FUNCTION ON;
INSERT INTO axch.dbo.PERM_FUNCTION(ID, PERM_ID, FUNCTION_ID) SELECT ID, PERM_ID, FUNCTION_ID FROM sag.dbo.PERM_FUNCTION;
SET IDENTITY_INSERT axch.dbo.PERM_FUNCTION OFF;
GO
SET IDENTITY_INSERT axch.dbo.AAD_ACCOUNTS ON;
INSERT INTO axch.dbo.AAD_ACCOUNTS(ID, FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) SELECT ID, FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP FROM sag.dbo.AAD_ACCOUNTS;
SET IDENTITY_INSERT axch.dbo.AAD_ACCOUNTS OFF;
GO
SET IDENTITY_INSERT axch.dbo.BASKET_HISTORY ON;
INSERT INTO axch.dbo.BASKET_HISTORY(ID, BASKET_NAME, ORGANISATION_ID, CREATED_USER_ID, SALES_USER_ID, GRAND_TOTAL_EXCLUDE_VAT, BASKET_JSON, UPDATED_DATE, ACTIVE, CUSTOMER_REF_TEXT) SELECT ID, BASKET_NAME, ORGANISATION_ID, CREATED_USER_ID, SALES_USER_ID, GRAND_TOTAL_EXCLUDE_VAT, BASKET_JSON, UPDATED_DATE, ACTIVE, CUSTOMER_REF_TEXT FROM sag.dbo.BASKET_HISTORY;
SET IDENTITY_INSERT axch.dbo.BASKET_HISTORY OFF;
GO
SET IDENTITY_INSERT axch.dbo.COUNTRY ON;
INSERT INTO axch.dbo.COUNTRY(ID, CODE, SHORT_NAME, FULL_NAME) SELECT ID, CODE, SHORT_NAME, FULL_NAME FROM sag.dbo.COUNTRY;
SET IDENTITY_INSERT axch.dbo.COUNTRY OFF;
GO
SET IDENTITY_INSERT axch.dbo.COUPON_CONDITIONS ON;
INSERT INTO axch.dbo.COUPON_CONDITIONS(ID, COUPON_CODE, DATE_START, DATE_END, USAGE_COUNT, USED_COUNT, AMOUNT, PERCENTAGE, DISCOUNT_ARTICLE_ID, MINIMUM_ORDER_AMOUNT, MAXIMUM_DISCOUNT, BULK_QUANTITY_TRIGGER, BULK_QUANTITY_ARTICLE_ID, COUNTRY, AFFILIATE, CUSTOMER_GROUP, CUSTOMER_NR, ARTICLE_CATEGORIES, ARTICLE_ID, BRANDS, UPDATED_BY, DATE_OF_LAST_UPDATE, CREATED_BY, DATE_OF_CREATION, UMAR_ID) SELECT ID, COUPON_CODE, DATE_START, DATE_END, USAGE_COUNT, USED_COUNT, AMOUNT, PERCENTAGE, DISCOUNT_ARTICLE_ID, MINIMUM_ORDER_AMOUNT, MAXIMUM_DISCOUNT, BULK_QUANTITY_TRIGGER, BULK_QUANTITY_ARTICLE_ID, COUNTRY, AFFILIATE, CUSTOMER_GROUP, CUSTOMER_NR, ARTICLE_CATEGORIES, ARTICLE_ID, BRANDS, UPDATED_BY, DATE_OF_LAST_UPDATE, CREATED_BY, DATE_OF_CREATION, UMAR_ID FROM sag.dbo.COUPON_CONDITIONS;
SET IDENTITY_INSERT axch.dbo.COUPON_CONDITIONS OFF;
GO
SET IDENTITY_INSERT axch.dbo.COUPON_USE_LOG ON;
INSERT INTO axch.dbo.COUPON_USE_LOG(ID, COUPONS_CODE, DATE_USED, USAGE_COUNT_REMAINDER, AMOUNT_APPLIED, DISCOUNT_ARTICLE_ID, CUSTOMER_NR, USER_ID, ORDER_CONFIRMATION_ID, ORDER_ID, COUNTRY_MATCH, AFFILIATE_MATCH, ARTICLE_CATEGORIES, ARTICLE_ID_MATCH, BRANDS_MATCH, UMAR_ID) SELECT ID, COUPONS_CODE, DATE_USED, USAGE_COUNT_REMAINDER, AMOUNT_APPLIED, DISCOUNT_ARTICLE_ID, CUSTOMER_NR, USER_ID, ORDER_CONFIRMATION_ID, ORDER_ID, COUNTRY_MATCH, AFFILIATE_MATCH, ARTICLE_CATEGORIES, ARTICLE_ID_MATCH, BRANDS_MATCH, UMAR_ID FROM sag.dbo.COUPON_USE_LOG;
SET IDENTITY_INSERT axch.dbo.COUPON_USE_LOG OFF;
GO
SET IDENTITY_INSERT axch.dbo.CURRENCY ON;
INSERT INTO axch.dbo.CURRENCY(ID, ISO_CODE, DESCRIPTION) SELECT ID, ISO_CODE, DESCRIPTION FROM sag.dbo.CURRENCY;
SET IDENTITY_INSERT axch.dbo.CURRENCY OFF;
GO
SET IDENTITY_INSERT axch.dbo.ESHOP_CART_ITEM ON;
INSERT INTO axch.dbo.ESHOP_CART_ITEM(ID, CART_KEY, USER_NAME, CUSTOMER_NR, QUANTITY, ARTICLE_JSON, ADDED_TIME, CATEGORY_JSON, VEHICLE_JSON, ITEM_DESC, ITEM_TYPE, CHILD_JSON, USER_ID) SELECT ID, CART_KEY, USER_NAME, CUSTOMER_NR, QUANTITY, ARTICLE_JSON, ADDED_TIME, CATEGORY_JSON, VEHICLE_JSON, ITEM_DESC, ITEM_TYPE, CHILD_JSON, USER_ID FROM sag.dbo.ESHOP_CART_ITEM;
SET IDENTITY_INSERT axch.dbo.ESHOP_CART_ITEM OFF;
GO
SET IDENTITY_INSERT axch.dbo.ESHOP_RELEASE ON;
INSERT INTO axch.dbo.ESHOP_RELEASE(ID, RELEASE_BUILD, RELEASE_VERSION, RELEASE_DATE) SELECT ID, RELEASE_BUILD, RELEASE_VERSION, RELEASE_DATE FROM sag.dbo.ESHOP_RELEASE;
SET IDENTITY_INSERT axch.dbo.ESHOP_RELEASE OFF;
GO
SET IDENTITY_INSERT axch.dbo.EXTERNAL_ORGANISATION ON;
INSERT INTO axch.dbo.EXTERNAL_ORGANISATION(ID, ORG_ID, EXTERNAL_CUSTOMER_ID, EXTERNAL_APP, EXTERNAL_CUSTOMER_NAME) SELECT ID, ORG_ID, EXTERNAL_CUSTOMER_ID, EXTERNAL_APP, EXTERNAL_CUSTOMER_NAME FROM sag.dbo.EXTERNAL_ORGANISATION;
SET IDENTITY_INSERT axch.dbo.EXTERNAL_ORGANISATION OFF;
GO
SET IDENTITY_INSERT axch.dbo.EXTERNAL_USER ON;
INSERT INTO axch.dbo.EXTERNAL_USER(ID, ESHOP_USER_ID, USERNAME, PASSWORD, EXTERNAL_APP, ACTIVE, CREATED_DATE) SELECT ID, ESHOP_USER_ID, USERNAME, PASSWORD, EXTERNAL_APP, ACTIVE, CREATED_DATE FROM sag.dbo.EXTERNAL_USER;
SET IDENTITY_INSERT axch.dbo.EXTERNAL_USER OFF;
GO
SET IDENTITY_INSERT axch.dbo.GROUP_PERMISSION ON;
INSERT INTO axch.dbo.GROUP_PERMISSION(ID, GROUP_ID, PERM_ID, ALLOWED) SELECT ID, GROUP_ID, PERM_ID, ALLOWED FROM sag.dbo.GROUP_PERMISSION;
SET IDENTITY_INSERT axch.dbo.GROUP_PERMISSION OFF;
GO
SET IDENTITY_INSERT axch.dbo.MESSAGE ON;
INSERT INTO axch.dbo.MESSAGE(ID, TITLE, MESSAGE_LOCATION_ID, MESSAGE_ACCESS_RIGHT_ID, MESSAGE_TYPE_ID, MESSAGE_SUB_AREA_ID, MESSAGE_STYLE_ID, MESSAGE_VISIBILITY_ID, ACTIVE, DATE_VALID_FROM, DATE_VALID_TO, CREATED_USER_ID, CREATED_DATE, MODIFIED_USER_ID, MODIFIED_DATE) SELECT ID, TITLE, MESSAGE_LOCATION_ID, MESSAGE_ACCESS_RIGHT_ID, MESSAGE_TYPE_ID, MESSAGE_SUB_AREA_ID, MESSAGE_STYLE_ID, MESSAGE_VISIBILITY_ID, ACTIVE, DATE_VALID_FROM, DATE_VALID_TO, CREATED_USER_ID, CREATED_DATE, MODIFIED_USER_ID, MODIFIED_DATE FROM sag.dbo.MESSAGE;
SET IDENTITY_INSERT axch.dbo.MESSAGE OFF;
GO
SET IDENTITY_INSERT axch.dbo.MESSAGE_ACCESS_RIGHT ON;
INSERT INTO axch.dbo.MESSAGE_ACCESS_RIGHT(ID, USER_GROUP, USER_GROUP_KEY, MESSAGE_ROLE_TYPE_ID, DESCRIPTION) SELECT ID, USER_GROUP, USER_GROUP_KEY, MESSAGE_ROLE_TYPE_ID, DESCRIPTION FROM sag.dbo.MESSAGE_ACCESS_RIGHT;
SET IDENTITY_INSERT axch.dbo.MESSAGE_ACCESS_RIGHT OFF;
GO
SET IDENTITY_INSERT axch.dbo.MESSAGE_ACCESS_RIGHT_AREA ON;
INSERT INTO axch.dbo.MESSAGE_ACCESS_RIGHT_AREA(ID, MESSAGE_ACCESS_RIGHT_ID, MESSAGE_AREA_ID) SELECT ID, MESSAGE_ACCESS_RIGHT_ID, MESSAGE_AREA_ID FROM sag.dbo.MESSAGE_ACCESS_RIGHT_AREA;
SET IDENTITY_INSERT axch.dbo.MESSAGE_ACCESS_RIGHT_AREA OFF;
GO
SET IDENTITY_INSERT axch.dbo.MESSAGE_ACCESS_RIGHT_ROLE ON;
INSERT INTO axch.dbo.MESSAGE_ACCESS_RIGHT_ROLE(ID, MESSAGE_ACCESS_RIGHT_ID, ESHOP_ROLE_ID) SELECT ID, MESSAGE_ACCESS_RIGHT_ID, ESHOP_ROLE_ID FROM sag.dbo.MESSAGE_ACCESS_RIGHT_ROLE;
SET IDENTITY_INSERT axch.dbo.MESSAGE_ACCESS_RIGHT_ROLE OFF;
GO
SET IDENTITY_INSERT axch.dbo.MESSAGE_AREA ON;
INSERT INTO axch.dbo.MESSAGE_AREA(ID, AREA, AUTH, DESCRIPTION) SELECT ID, AREA, AUTH, DESCRIPTION FROM sag.dbo.MESSAGE_AREA;
SET IDENTITY_INSERT axch.dbo.MESSAGE_AREA OFF;
GO
SET IDENTITY_INSERT axch.dbo.MESSAGE_HIDING ON;
INSERT INTO axch.dbo.MESSAGE_HIDING(ID, USER_ID, MESSAGE_ID) SELECT ID, USER_ID, MESSAGE_ID FROM sag.dbo.MESSAGE_HIDING;
SET IDENTITY_INSERT axch.dbo.MESSAGE_HIDING OFF;
GO
SET IDENTITY_INSERT axch.dbo.MESSAGE_LANGUAGE ON;
INSERT INTO axch.dbo.MESSAGE_LANGUAGE(ID, MESSAGE_ID, LANG_ISO, CONTENT) SELECT ID, MESSAGE_ID, LANG_ISO, CONTENT FROM sag.dbo.MESSAGE_LANGUAGE;
SET IDENTITY_INSERT axch.dbo.MESSAGE_LANGUAGE OFF;
GO
SET IDENTITY_INSERT axch.dbo.MESSAGE_LOCATION ON;
INSERT INTO axch.dbo.MESSAGE_LOCATION(ID, MESSAGE_LOCATION_TYPE_ID, VALUE) SELECT ID, MESSAGE_LOCATION_TYPE_ID, VALUE FROM sag.dbo.MESSAGE_LOCATION;
SET IDENTITY_INSERT axch.dbo.MESSAGE_LOCATION OFF;
GO
SET IDENTITY_INSERT axch.dbo.MESSAGE_LOCATION_TYPE ON;
INSERT INTO axch.dbo.MESSAGE_LOCATION_TYPE(ID, LOCATION_TYPE, DESCRIPTION) SELECT ID, LOCATION_TYPE, DESCRIPTION FROM sag.dbo.MESSAGE_LOCATION_TYPE;
SET IDENTITY_INSERT axch.dbo.MESSAGE_LOCATION_TYPE OFF;
GO
SET IDENTITY_INSERT axch.dbo.MESSAGE_LOCATION_TYPE_ROLE_TYPE ON;
INSERT INTO axch.dbo.MESSAGE_LOCATION_TYPE_ROLE_TYPE(ID, MESSAGE_LOCATION_TYPE_ID, MESSAGE_ROLE_TYPE_ID) SELECT ID, MESSAGE_LOCATION_TYPE_ID, MESSAGE_ROLE_TYPE_ID FROM sag.dbo.MESSAGE_LOCATION_TYPE_ROLE_TYPE;
SET IDENTITY_INSERT axch.dbo.MESSAGE_LOCATION_TYPE_ROLE_TYPE OFF;
GO
SET IDENTITY_INSERT axch.dbo.MESSAGE_ROLE_TYPE ON;
INSERT INTO axch.dbo.MESSAGE_ROLE_TYPE(ID, ROLE_TYPE, DESCRIPTION) SELECT ID, ROLE_TYPE, DESCRIPTION FROM sag.dbo.MESSAGE_ROLE_TYPE;
SET IDENTITY_INSERT axch.dbo.MESSAGE_ROLE_TYPE OFF;
GO
SET IDENTITY_INSERT axch.dbo.MESSAGE_STYLE ON;
INSERT INTO axch.dbo.MESSAGE_STYLE(ID, [STYLE], DESCRIPTION) SELECT ID, [STYLE], DESCRIPTION FROM sag.dbo.MESSAGE_STYLE;
SET IDENTITY_INSERT axch.dbo.MESSAGE_STYLE OFF;
GO
SET IDENTITY_INSERT axch.dbo.MESSAGE_SUB_AREA ON;
INSERT INTO axch.dbo.MESSAGE_SUB_AREA(ID, SUB_AREA, SORT, MESSAGE_AREA_ID, DESCRIPTION) SELECT ID, SUB_AREA, SORT, MESSAGE_AREA_ID, DESCRIPTION FROM sag.dbo.MESSAGE_SUB_AREA;
SET IDENTITY_INSERT axch.dbo.MESSAGE_SUB_AREA OFF;
GO
SET IDENTITY_INSERT axch.dbo.MESSAGE_TYPE ON;
INSERT INTO axch.dbo.MESSAGE_TYPE(ID, [TYPE], DESCRIPTION) SELECT ID, [TYPE], DESCRIPTION FROM sag.dbo.MESSAGE_TYPE;
SET IDENTITY_INSERT axch.dbo.MESSAGE_TYPE OFF;
GO
SET IDENTITY_INSERT axch.dbo.MESSAGE_VISIBILITY ON;
INSERT INTO axch.dbo.MESSAGE_VISIBILITY(ID, VISIBILITY, DESCRIPTION) SELECT ID, VISIBILITY, DESCRIPTION FROM sag.dbo.MESSAGE_VISIBILITY;
SET IDENTITY_INSERT axch.dbo.MESSAGE_VISIBILITY OFF;
GO
SET IDENTITY_INSERT axch.dbo.MIGRATION_ORGANISATION ON;
INSERT INTO axch.dbo.MIGRATION_ORGANISATION(ID, ORG_CODE, ORG_ID, COMPANY_NAME, CUSTOMER_NAME, IS_MIGRATED) SELECT ID, ORG_CODE, ORG_ID, COMPANY_NAME, CUSTOMER_NAME, IS_MIGRATED FROM sag.dbo.MIGRATION_ORGANISATION;
SET IDENTITY_INSERT axch.dbo.MIGRATION_ORGANISATION OFF;
GO
INSERT INTO axch.dbo.OAUTH_ACCESS_TOKEN(TOKEN_ID, TOKEN, AUTHENTICATION_ID, USER_NAME, CLIENT_ID, AUTHENTICATION, REFRESH_TOKEN) SELECT TOKEN_ID, TOKEN, AUTHENTICATION_ID, USER_NAME, CLIENT_ID, AUTHENTICATION, REFRESH_TOKEN FROM sag.dbo.OAUTH_ACCESS_TOKEN;
GO
INSERT INTO axch.dbo.OAUTH_REFRESH_TOKEN(TOKEN_ID, TOKEN, AUTHENTICATION) SELECT TOKEN_ID, TOKEN, AUTHENTICATION FROM sag.dbo.OAUTH_REFRESH_TOKEN;
GO
SET IDENTITY_INSERT axch.dbo.OFFER ON;
INSERT INTO axch.dbo.OFFER(ID, OFFER_NUMBER, CLIENT_ID, OWNER_ID, STATUS, OFFER_DATE, RECIPIENT_ID, RECIPIENT_ADDRESS_ID, TOTAL_GROSS_PRICE, DELIVERY_DATE, REMARK, DELIVERY_LOCATION, CREATED_USER_ID, CREATED_DATE, MODIFIED_USER_ID, MODIFIED_DATE, TECSTATE, CURRENCY_ID, VAT, [TYPE], ALT_OFFER_PRICE_USED, VERSION) SELECT ID, OFFER_NUMBER, CLIENT_ID, OWNER_ID, STATUS, OFFER_DATE, RECIPIENT_ID, RECIPIENT_ADDRESS_ID, TOTAL_GROSS_PRICE, DELIVERY_DATE, REMARK, DELIVERY_LOCATION, CREATED_USER_ID, CREATED_DATE, MODIFIED_USER_ID, MODIFIED_DATE, TECSTATE, CURRENCY_ID, VAT, [TYPE], ALT_OFFER_PRICE_USED, VERSION FROM sag.dbo.OFFER;
SET IDENTITY_INSERT axch.dbo.OFFER OFF;
GO
SET IDENTITY_INSERT axch.dbo.OFFER_ADDRESS ON;
INSERT INTO axch.dbo.OFFER_ADDRESS(ID, PERSON_ID, LINE1, LINE2, LINE3, COUNTRYISO, [STATE], CITY, ZIPCODE, CREATED_USER_ID, CREATED_DATE, MODIFIED_USER_ID, MODIFIED_DATE, TECSTATE, ERP_ID, [TYPE], PO_BOX, VERSION) SELECT ID, PERSON_ID, LINE1, LINE2, LINE3, COUNTRYISO, [STATE], CITY, ZIPCODE, CREATED_USER_ID, CREATED_DATE, MODIFIED_USER_ID, MODIFIED_DATE, TECSTATE, ERP_ID, [TYPE], PO_BOX, VERSION FROM sag.dbo.OFFER_ADDRESS;
SET IDENTITY_INSERT axch.dbo.OFFER_ADDRESS OFF;
GO
SET IDENTITY_INSERT axch.dbo.OFFER_PERSON ON;
INSERT INTO axch.dbo.OFFER_PERSON(ID, ORGANISATION_ID, [TYPE], STATUS, FIRST_NAME, LAST_NAME, EMAIL, LANGUAGE_ID, HOURLY_RATE, CREATED_USER_ID, CREATED_DATE, MODIFIED_USER_ID, MODIFIED_DATE, TECSTATE, VERSION, OFFER_COMPANY_NAME) SELECT ID, ORGANISATION_ID, [TYPE], STATUS, FIRST_NAME, LAST_NAME, EMAIL, LANGUAGE_ID, HOURLY_RATE, CREATED_USER_ID, CREATED_DATE, MODIFIED_USER_ID, MODIFIED_DATE, TECSTATE, VERSION, OFFER_COMPANY_NAME FROM sag.dbo.OFFER_PERSON;
SET IDENTITY_INSERT axch.dbo.OFFER_PERSON OFF;
GO
INSERT INTO axch.dbo.OFFER_PERSON_PROPERTY(PERSON_ID, [TYPE], VALUE) SELECT PERSON_ID, [TYPE], VALUE FROM sag.dbo.OFFER_PERSON_PROPERTY;
GO
SET IDENTITY_INSERT axch.dbo.OFFER_POSITION ON;
INSERT INTO axch.dbo.OFFER_POSITION(ID, OFFER_ID, [TYPE], UMSART_ID, SHOP_ARTICLE_ID, ARTICLE_NUMBER, ARTICLE_DESCRIPTION, VEHICLE_ID, VEHICLE_DESCRIPTION, CALCULATED, [SEQUENCE], CONTEXT, QUANTITY, UOM_ISO, CURRENCY_ID, GROSS_PRICE, NET_PRICE, TOTAL_GROSS_PRICE, REMARK, ACTION_TYPE, DELIVERY_TYPE_ID, DELIVERY_DATE, CREATED_USER_ID, CREATED_DATE, MODIFIED_USER_ID, MODIFIED_DATE, TECSTATE, MAKE_ID, MODEL_ID, ACTION_VALUE, VEHICLE_BOM_ID, VEHICLE_BOM_DESCRIPTION, ARTICLE_ENHANCED_DESCRIPTION, PRICED_UNIT, CATALOG_PATH, VEHICLE_TYPE_CODE, PRICED_QUANTITY, VERSION, CONNECT_VEHICLE_ID, SAGSYS_ID) SELECT ID, OFFER_ID, [TYPE], UMSART_ID, SHOP_ARTICLE_ID, ARTICLE_NUMBER, ARTICLE_DESCRIPTION, VEHICLE_ID, VEHICLE_DESCRIPTION, CALCULATED, [SEQUENCE], CONTEXT, QUANTITY, UOM_ISO, CURRENCY_ID, GROSS_PRICE, NET_PRICE, TOTAL_GROSS_PRICE, REMARK, ACTION_TYPE, DELIVERY_TYPE_ID, DELIVERY_DATE, CREATED_USER_ID, CREATED_DATE, MODIFIED_USER_ID, MODIFIED_DATE, TECSTATE, MAKE_ID, MODEL_ID, ACTION_VALUE, VEHICLE_BOM_ID, VEHICLE_BOM_DESCRIPTION, ARTICLE_ENHANCED_DESCRIPTION, PRICED_UNIT, CATALOG_PATH, VEHICLE_TYPE_CODE, PRICED_QUANTITY, VERSION, CONNECT_VEHICLE_ID, SAGSYS_ID FROM sag.dbo.OFFER_POSITION;
SET IDENTITY_INSERT axch.dbo.OFFER_POSITION OFF;
GO
SET IDENTITY_INSERT axch.dbo.ORDER_STATUS ON;
INSERT INTO axch.dbo.ORDER_STATUS(ID, ORDER_STATUS, DESC_CODE, DESCRIPTION) SELECT ID, ORDER_STATUS, DESC_CODE, DESCRIPTION FROM sag.dbo.ORDER_STATUS;
SET IDENTITY_INSERT axch.dbo.ORDER_STATUS OFF;
GO
SET IDENTITY_INSERT axch.dbo.ORDER_TYPE ON;
INSERT INTO axch.dbo.ORDER_TYPE(ID, ORDER_TYPE, DESC_CODE, DESCRIPTION) SELECT ID, ORDER_TYPE, DESC_CODE, DESCRIPTION FROM sag.dbo.ORDER_TYPE;
SET IDENTITY_INSERT axch.dbo.ORDER_TYPE OFF;
GO
SET IDENTITY_INSERT axch.dbo.SHOP_ARTICLE ON;
INSERT INTO axch.dbo.SHOP_ARTICLE(ID, ORGANISATION_ID, [TYPE], ARTICLE_NUMBER, NAME, DESCRIPTION, AMOUNT, PRICE, CREATED_USER_ID, CREATED_DATE, MODIFIED_USER_ID, MODIFIED_DATE, TECSTATE, CURRENCY_ID, VERSION) SELECT ID, ORGANISATION_ID, [TYPE], ARTICLE_NUMBER, NAME, DESCRIPTION, AMOUNT, PRICE, CREATED_USER_ID, CREATED_DATE, MODIFIED_USER_ID, MODIFIED_DATE, TECSTATE, CURRENCY_ID, VERSION FROM sag.dbo.SHOP_ARTICLE;
SET IDENTITY_INSERT axch.dbo.SHOP_ARTICLE OFF;
GO
SET IDENTITY_INSERT axch.dbo.SUPPORTED_AFFILIATE ON;
INSERT INTO axch.dbo.SUPPORTED_AFFILIATE(ID, SHORT_NAME, COMPANY_NAME, DESCRIPTION, COUNTRY_ID, UPDATED_DATE, ES_SHORT_NAME, SALES_ORIGIN_ID, SHOW_PFAND_ARTICLE, LOGO_LINK) SELECT ID, SHORT_NAME, COMPANY_NAME, DESCRIPTION, COUNTRY_ID, UPDATED_DATE, ES_SHORT_NAME, SALES_ORIGIN_ID, 0, NULL FROM sag.dbo.SUPPORTED_AFFILIATE;
SET IDENTITY_INSERT axch.dbo.SUPPORTED_AFFILIATE OFF;
GO
SET IDENTITY_INSERT axch.dbo.FEEDBACK_DEPARTMENT ON;
INSERT INTO axch.dbo.FEEDBACK_DEPARTMENT(ID, DEPARTMENT_CODE, DESCRIPTION, SUPPORTED_AFFILIATE_ID) SELECT ID, DEPARTMENT_CODE, DESCRIPTION, SUPPORTED_AFFILIATE_ID FROM sag.dbo.FEEDBACK_DEPARTMENT;
SET IDENTITY_INSERT axch.dbo.FEEDBACK_DEPARTMENT OFF;
GO
SET IDENTITY_INSERT axch.dbo.FEEDBACK_DEPARTMENT_CONTACT ON;
INSERT INTO axch.dbo.FEEDBACK_DEPARTMENT_CONTACT(ID, DEPARTMENT_ID, TYPE, VALUE) SELECT ID, DEPARTMENT_ID, TYPE, VALUE FROM sag.dbo.FEEDBACK_DEPARTMENT_CONTACT;
SET IDENTITY_INSERT axch.dbo.FEEDBACK_DEPARTMENT_CONTACT OFF;
GO
SET IDENTITY_INSERT axch.dbo.FEEDBACK_STATUS ON;
INSERT INTO axch.dbo.FEEDBACK_STATUS(ID, STATUS_CODE, DESCRIPTION) SELECT ID, STATUS_CODE, DESCRIPTION FROM sag.dbo.FEEDBACK_STATUS;
SET IDENTITY_INSERT axch.dbo.FEEDBACK_STATUS OFF;
GO
SET IDENTITY_INSERT axch.dbo.FEEDBACK_TOPIC ON;
INSERT INTO axch.dbo.FEEDBACK_TOPIC(ID, TOPIC_CODE, DESCRIPTION) SELECT ID, TOPIC_CODE, DESCRIPTION FROM sag.dbo.FEEDBACK_TOPIC;
SET IDENTITY_INSERT axch.dbo.FEEDBACK_TOPIC OFF;
GO
SET IDENTITY_INSERT axch.dbo.FEEDBACK_TOPIC_DEPARTMENT ON;
INSERT INTO axch.dbo.FEEDBACK_TOPIC_DEPARTMENT(ID, TOPIC_ID, DEPARTMENT_ID) SELECT ID, TOPIC_ID, DEPARTMENT_ID FROM sag.dbo.FEEDBACK_TOPIC_DEPARTMENT;
SET IDENTITY_INSERT axch.dbo.FEEDBACK_TOPIC_DEPARTMENT OFF;
GO
SET IDENTITY_INSERT axch.dbo.FEEDBACK ON;
INSERT INTO axch.dbo.FEEDBACK(ID, USER_ID, SALES_ID, STATUS_ID, TOPIC_ID, ORG_ID, USER_INFORMATION, TECHNICAL_INFORMATION, FEEDBACK_MESSAGE, CREATED_DATE, CREATED_USER_ID, MODIFIED_DATE, MODIFIED_USER_ID, CUSTOMER_CONTACT, SOURCE) SELECT ID, USER_ID, SALES_ID, STATUS_ID, TOPIC_ID, ORG_ID, USER_INFORMATION, TECHNICAL_INFORMATION, FEEDBACK_MESSAGE, CREATED_DATE, CREATED_USER_ID, MODIFIED_DATE, MODIFIED_USER_ID, CUSTOMER_CONTACT, SOURCE FROM sag.dbo.FEEDBACK;
SET IDENTITY_INSERT axch.dbo.FEEDBACK OFF;
GO
