# ************************************************************************
# This is the Autonet configuration of RESTful application for Development mode.
# 
# Required Common configuration:
# - Application common configuration - 
# - ERP - 
# - Incentive - 
# - GTMotive - 
# - MDM for DVSE service - 
# - Mail service - 
# - Elasticsearch - 
# - Database - 
# - Thread Executor Pool - 
# - Logging - 
# - Actuator Healthcheck - 
# - Caching - 
# - Country Code - 
# - Analytics - 
# - Liquibase - 
# - Proxy - 
# - Media Server - 
# - Java Melody Monitoring - 
#
# ************************************************************************
spring.profiles.include: 
  sagrest,
  autonet-erp-pre,
  incentive-dev,
  gtmotive-ch-pre,
  mdm-prod,
  mail-dev,
  elasticsearch-dev,
  db-dev,
  executor-pool,
  logging-autonet-dev,
  actuator,
  cache-autonet,
  country-autonet,
  analytics-pre-cloud,
  liquibase-autonet-dev,
  no-proxy,
  media-server,
  javamelody

spring.banner.location: classpath:banner/banner_autonet.txt

---
#Authorization server to manage and verify tokens
sag:
  security:
    auth:
      # host: http://localhost:9002
      host: http://autonet.bbv-demo.ch/auth-server
      tokenUrl: /oauth/token
      checkTokenUrl: /oauth/check_token
      clientId: autonet-rest
      clientSecret: autonet-rest-yztAhGpFW

license:
  vin:
    minimumOrder: 150
