# ************************************************************************
# This is the CZ configuration of RESTful application for Pre-Prod mode.
# 
# Required Common configuration:
# - Application common configuration - 
# - ERP - 
# - Incentive - 
# - HaynesPro Endpoint - 
# - GTMotive - 
# - MDM for DVSE service - 
# - OATS(replace Olyslager) - 
# - Mail service - 
# - Elasticsearch - 
# - Database - 
# - Thread Executor Pool - 
# - Logging - 
# - Actuator Healthcheck - 
# - Caching - 
# - Country Code - 
# - Analytics - 
# - Liquibase - 
# - No Proxy For Serbia and CZ we are in Azure - 
# - Media Server - 
# - Price File Location - 
# - Java Melody Monitoring - 
# - Thule - 
#
# ************************************************************************
spring.profiles.include: 
  sagrest,
  stakis-erp-pre,
  incentive-dev,
  hp-pre,
  gtmotive-cz-pre,
  mdm-pre,
  unicat-pre,
  unicat-callback-pre,
  oates-prod-cz,
  mail-prod,
  elasticsearch-pre,
  db-pre,
  executor-pool,
  logging-cz-pre,
  actuator,
  cache-pre,
  country-cz,
  analytics-pre-cloud,
  no-liquibase,
  no-proxy,
  media-server,
  price-file-cz,
  javamelody,
  thule-pre,
  recommend-art-cz-pre

---
#Authorization server to manage and verify tokens
sag:
  security:
    auth:
      # host: http://localhost:9002
      # host: https://preconnect2.sag.services/auth-server-st
      host: http://localhost:8080/auth-server-st
      tokenUrl: /oauth/token
      checkTokenUrl: /oauth/check_token
      clientId: eshop-web
      clientSecret: eshop-web-yztAhGpFW

license:
  vin:
    minimumOrder: 600
