CREATE TABLE [dbo].[MAPPING_USER_ID_EBL_CONNECT] (
    [ID] [bigint] IDENTITY(1,1) NOT NULL,
    [EBL_USER_ID] [bigint] NOT NULL,
    [CONNECT_USER_ID] [bigint] NOT NULL,
    [EBL_ORG_ID] [bigint] NOT NULL,
    [CONNECT_ORG_ID] [int] NOT NULL
)

-- SHOP ARTICLE START
-- Shop Article modified columns
ALTER TABLE [dbo].[SHOP_ARTICLE] ALTER COLUMN DESCRIPTION VARCHAR(8000);
ALTER TABLE [dbo].[SHOP_ARTICLE] ALTER COLUMN NAME VARCHAR(8000);
ALTER TABLE [dbo].[SHOP_ARTICLE] ALTER COLUMN AMOUNT DECIMAL(18, 10) NULL;
ALTER TABLE [dbo].[SHOP_ARTICLE] ALTER COLUMN PRICE DECIMAL(18, 10) NULL;
ALTER TABLE [dbo].[SHOP_ARTICLE] ALTER COLUMN CREATED_USER_ID BIGINT NULL;
ALTER TABLE [dbo].[SHOP_ARTICLE] ALTER COLUMN CREATED_DATE DATETIME NULL;
ALTER TABLE [dbo].[SHOP_ARTICLE] ALTER COLUMN TECSTATE VARCHAR(8) NULL;
ALTER TABLE [dbo].[SHOP_ARTICLE] ALTER COLUMN VERSION INT NULL;

-- Shop Article Index
CREATE INDEX IDX_SHOP_ARTICLE_ID ON [dbo].[SHOP_ARTICLE] (ID);
CREATE INDEX IDX_SHOP_ARTICLE_ORG_ID ON [dbo].[SHOP_ARTICLE] (ORGANISATION_ID);
CREATE INDEX IDX_SHOP_ARTICLE_TYPE ON [dbo].[SHOP_ARTICLE] (TYPE);
CREATE INDEX IDX_SHOP_ARTICLE_ARTICLE_NUMBER ON [dbo].[SHOP_ARTICLE] (ARTICLE_NUMBER);
CREATE INDEX IDX_SHOP_ARTICLE_AMOUNT ON [dbo].[SHOP_ARTICLE] (AMOUNT);
CREATE INDEX IDX_SHOP_ARTICLE_PRICE ON [dbo].[SHOP_ARTICLE] (PRICE);
CREATE INDEX IDX_SHOP_ARTICLE_TECSTATE ON [dbo].[SHOP_ARTICLE] (TECSTATE);
CREATE INDEX IDX_SHOP_ARTICLE_VERSION ON [dbo].[SHOP_ARTICLE] (VERSION);

-- Shop Article constraint
-- Optional ALTER TABLE [dbo].[SHOP_ARTICLE] DROP CONSTRAINT [UN_ARTICLE_NUMBER];
ALTER TABLE [dbo].[SHOP_ARTICLE] DROP CONSTRAINT [FK_SHOP_ARTICLE_ORGANISATION];
ALTER TABLE [dbo].[SHOP_ARTICLE] DROP CONSTRAINT [FK_SHOP_ARTICLE_CREATED_USER_ID];
ALTER TABLE [dbo].[SHOP_ARTICLE] DROP CONSTRAINT [FK_SHOP_ARTICLE_MODIFIED_USER_ID];
ALTER TABLE [dbo].[SHOP_ARTICLE] DROP CONSTRAINT [FK_SHOP_ARTICLE_CURRENCY_ID];
ALTER TABLE [dbo].[OFFER_POSITION] DROP CONSTRAINT [FK_SHOP_ARTICLE];
-- SHOP ARTICLE END

-- OFFER_PERSON START
ALTER TABLE [dbo].[OFFER_PERSON] ALTER COLUMN CREATED_USER_ID BIGINT NULL;
ALTER TABLE [dbo].[OFFER_PERSON] ALTER COLUMN CREATED_DATE DATETIME NULL;

-- Offer Person Index
CREATE INDEX IDX_OFFER_PERSON_ID ON [dbo].[OFFER_PERSON] (ID);
CREATE INDEX IDX_OFFER_PERSON_ORGANISATION_ID ON [dbo].[OFFER_PERSON] (ORGANISATION_ID);
CREATE INDEX IDX_OFFER_PERSON_TYPE ON [dbo].[OFFER_PERSON] (TYPE);
CREATE INDEX IDX_OFFER_PERSON_STATUS ON [dbo].[OFFER_PERSON] (STATUS);
CREATE INDEX IDX_OFFER_PERSON_FIRST_NAME ON [dbo].[OFFER_PERSON] (FIRST_NAME);
CREATE INDEX IDX_OFFER_PERSON_LAST_NAME ON [dbo].[OFFER_PERSON] (LAST_NAME);
CREATE INDEX IDX_OFFER_PERSON_EMAIL ON [dbo].[OFFER_PERSON] (EMAIL);
CREATE INDEX IDX_OFFER_PERSON_LANGUAGE_ID ON [dbo].[OFFER_PERSON] (LANGUAGE_ID);
CREATE INDEX IDX_OFFER_PERSON_HOURLY_RATE ON [dbo].[OFFER_PERSON] (HOURLY_RATE);
CREATE INDEX IDX_OFFER_PERSON_OFFER_COMPANY_NAME ON [dbo].[OFFER_PERSON] (OFFER_COMPANY_NAME);

-- Offer Person constraint
ALTER TABLE [dbo].[OFFER_PERSON] DROP CONSTRAINT [FK_OFFER_PERSON_LANGUAGE];
ALTER TABLE [dbo].[OFFER_PERSON] DROP CONSTRAINT [FK_OFFER_PERSON_CREATED_USER_ID];
ALTER TABLE [dbo].[OFFER_PERSON] DROP CONSTRAINT [FK_OFFER_PERSON_MODIFIED_USER_ID];
ALTER TABLE [dbo].[OFFER_PERSON] DROP CONSTRAINT [FK_OFFER_PERSON_ORGANISATION_ID];
-- OFFER_PERSON END

-- OFFER_PERSON_PROPERTY START
-- Offer Person Property modified columns
SET IDENTITY_INSERT OFFER_PERSON_PROPERTY ON
SET IDENTITY_INSERT OFFER_PERSON_PROPERTY OFF
ALTER TABLE [dbo].[OFFER_PERSON_PROPERTY] ALTER COLUMN VALUE VARCHAR(8000);

-- Offer Person Property Index
CREATE INDEX IDX_OFFER_PERSON_PROPERTY_PERSON_ID ON [dbo].[OFFER_PERSON_PROPERTY] (PERSON_ID);
CREATE INDEX IDX_OFFER_PERSON_PROPERTY_TYPE ON [dbo].[OFFER_PERSON_PROPERTY] (TYPE);

-- Offer Person Property constraint
ALTER TABLE [dbo].[OFFER_PERSON_PROPERTY] DROP CONSTRAINT [FK_OFFER_PERSON_PERSON_PROPERTY];
-- OFFER_PERSON_PROPERTY END

-- OFFER ADDRESS START
-- Offer Address index
CREATE INDEX IDX_OFFER_ADDRESS_ID ON [dbo].[OFFER_ADDRESS] (ID);
CREATE INDEX IDX_OFFER_ADDRESS_PERSON_ID ON [dbo].[OFFER_ADDRESS] (PERSON_ID);

-- Offer Address constraint
ALTER TABLE [dbo].[OFFER_ADDRESS] DROP CONSTRAINT [FK_OFFER_ADDRESS_CREATED_USER_ID];
ALTER TABLE [dbo].[OFFER_ADDRESS] DROP CONSTRAINT [FK_OFFER_ADDRESS_MODIFIED_USER_ID];
ALTER TABLE [dbo].[OFFER_ADDRESS] DROP CONSTRAINT [FK_OFFER_PERSON_ID];
-- OFFER ADDRESS END

-- OFFER START

ALTER TABLE [dbo].[OFFER] ALTER COLUMN TOTAL_GROSS_PRICE DECIMAL(18,10) NULL;
ALTER TABLE [dbo].[OFFER] ALTER COLUMN RECIPIENT_ID BIGINT NULL;
ALTER TABLE [dbo].[OFFER] ALTER COLUMN RECIPIENT_ADDRESS_ID BIGINT NULL;
ALTER TABLE [dbo].[OFFER] ALTER COLUMN REMARK VARCHAR(8000);
ALTER TABLE [dbo].[OFFER] ALTER COLUMN DELIVERY_DATE DATETIME2;
ALTER TABLE [dbo].[OFFER] ALTER COLUMN OFFER_DATE DATETIME2;
ALTER TABLE [dbo].[OFFER] ALTER COLUMN CREATED_DATE DATETIME2;
ALTER TABLE [dbo].[OFFER] ALTER COLUMN MODIFIED_DATE DATETIME2;

-- Offer index

-- Offer constraint
ALTER TABLE [dbo].[OFFER] DROP CONSTRAINT [FK_OFFER_RECIPIENT_ID];
ALTER TABLE [dbo].[OFFER] DROP CONSTRAINT [FK_OFFER_RECIPIENT_ADDRESS];
ALTER TABLE [dbo].[OFFER] DROP CONSTRAINT [FK_OFFER_CREATED_USER_ID];
ALTER TABLE [dbo].[OFFER] DROP CONSTRAINT [FK_OFFER_MODIFIED_USER_ID];
ALTER TABLE [dbo].[OFFER] DROP CONSTRAINT [FK_OFFER_CLIENT_ID];
ALTER TABLE [dbo].[OFFER] DROP CONSTRAINT [FK_OFFER_OWNER_ID];
ALTER TABLE [dbo].[OFFER] DROP CONSTRAINT [FK_OFFER_CURRENCY_ID];
-- OFFER END

-- OFFER POSITION START

ALTER TABLE [dbo].[OFFER_POSITION] ALTER COLUMN ARTICLE_DESCRIPTION VARCHAR(500);
ALTER TABLE [dbo].[OFFER_POSITION] ALTER COLUMN VEHICLE_DESCRIPTION VARCHAR(500);
ALTER TABLE [dbo].[OFFER_POSITION] ALTER COLUMN VEHICLE_BOM_DESCRIPTION VARCHAR(500);
ALTER TABLE [dbo].[OFFER_POSITION] ALTER COLUMN ARTICLE_ENHANCED_DESCRIPTION VARCHAR(500);
ALTER TABLE [dbo].[OFFER_POSITION] ALTER COLUMN PRICED_UNIT VARCHAR(500);
ALTER TABLE [dbo].[OFFER_POSITION] ALTER COLUMN CATALOG_PATH VARCHAR(500);
ALTER TABLE [dbo].[OFFER_POSITION] ALTER COLUMN VEHICLE_TYPE_CODE VARCHAR(500);
ALTER TABLE [dbo].[OFFER_POSITION] ALTER COLUMN REMARK VARCHAR(500);
ALTER TABLE [dbo].[OFFER_POSITION] ALTER COLUMN DELIVERY_DATE DATETIME2;
ALTER TABLE [dbo].[OFFER_POSITION] ALTER COLUMN CREATED_DATE DATETIME2;
ALTER TABLE [dbo].[OFFER_POSITION] ALTER COLUMN MODIFIED_DATE DATETIME2;

ALTER TABLE [dbo].[OFFER_POSITION] ALTER COLUMN MAKE_ID VARCHAR(100);
ALTER TABLE [dbo].[OFFER_POSITION] ALTER COLUMN MODEL_ID VARCHAR(100);
ALTER TABLE [dbo].[OFFER_POSITION] ALTER COLUMN VEHICLE_BOM_ID VARCHAR(100);
ALTER TABLE [dbo].[OFFER_POSITION] ALTER COLUMN CONTEXT VARCHAR(50);
ALTER TABLE [dbo].[OFFER_POSITION] ALTER COLUMN ACTION_TYPE VARCHAR(50);
-- Offer Position index

-- Offer Position constraint
ALTER TABLE [dbo].[OFFER_POSITION] DROP CONSTRAINT [FK_OFFER_POSITION_PERSON];
ALTER TABLE [dbo].[OFFER_POSITION] DROP CONSTRAINT [FK_SHOP_ARTICLE];
ALTER TABLE [dbo].[OFFER_POSITION] DROP CONSTRAINT [FK_OFFER_POSITION_CREATED_USER_ID];
ALTER TABLE [dbo].[OFFER_POSITION] DROP CONSTRAINT [FK_OFFER_POSITION_MODIFIED_USER_ID];
ALTER TABLE [dbo].[OFFER_POSITION] DROP CONSTRAINT [FK_OFFER_POSITION_DELIVERY_TYPE_ID];
ALTER TABLE [dbo].[OFFER_POSITION] DROP CONSTRAINT [FK_OFFER_POSITION_CURRENCY_ID];

-- OFFER POSITION END

-- Add columns
ALTER TABLE [dbo].[OFFER_POSITION] ADD CONNECT_VEHICLE_ID VARCHAR(50);
ALTER TABLE [dbo].[OFFER_POSITION] ADD SAGSYS_ID VARCHAR(19);

--- Query to update default email for register virtual user
UPDATE ESHOP_USER SET EMAIL='noReply@sag-austria.at', PHONE= ' '  WHERE USERNAME LIKE 'Agent-%' AND LAST_NAME = 'Agent' AND TYPE= 'ON_BEHALF_ADMIN';
