USE SHOP;
-- ADDRESS START

-- Query to get person address of offer person from EBL system.
SELECT * FROM SHOP.ADDRESS sa
  INNER JOIN SHOP.ORGANISATION_ADDRESS oa ON oa.ADDRESS_ID = sa.ID
  INNER JOIN SHOP.ORGANISATIONLINK ol ON ol.CLIENT_ID = oa.ORGANISATION_ID
  INNER JOIN SHOP.LOGIN_ROLEASSIGNMENT ra ON ra.ORGANISATION_ID = ol.CLIENT_ID
  WHERE ra.PERSON_ID = personId;

-- ADDRESS END

SELECT * FROM SHOP.ORGANISATION o
  INNER JOIN SHOP.ORGANISATIONLINK ol ON ol.CLIENT_ID = o.ID
  INNER JOIN SHOP.LOGIN_ROLEASSIGNMENT ra ON ra.ORGANISATION_ID = ol.CLIENT_ID
  INNER JOIN SHOP.PERSON P ON P.ID = ra.PERSON_ID
  WHERE o.TYPE='FINALCUSTOMER' AND P.ID = :personId