//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.29 at 10:18:58 AM ICT 
//


package com.sagag.services.dvse.wsdl.dvse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AvailableState complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AvailableState"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AvailState" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="AvailDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AvailIconUrl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AvailableState", propOrder = {
    "availState",
    "availDescription",
    "availIconUrl"
})
public class AvailableState {

    @XmlElement(name = "AvailState")
    protected int availState;
    @XmlElement(name = "AvailDescription")
    protected String availDescription;
    @XmlElement(name = "AvailIconUrl")
    protected String availIconUrl;

    /**
     * Gets the value of the availState property.
     * 
     */
    public int getAvailState() {
        return availState;
    }

    /**
     * Sets the value of the availState property.
     * 
     */
    public void setAvailState(int value) {
        this.availState = value;
    }

    /**
     * Gets the value of the availDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvailDescription() {
        return availDescription;
    }

    /**
     * Sets the value of the availDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvailDescription(String value) {
        this.availDescription = value;
    }

    /**
     * Gets the value of the availIconUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvailIconUrl() {
        return availIconUrl;
    }

    /**
     * Sets the value of the availIconUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvailIconUrl(String value) {
        this.availIconUrl = value;
    }

}
