//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.29 at 10:18:58 AM ICT
//


package com.sagag.services.dvse.wsdl.dvse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetBackItems complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="GetBackItems"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{DVSE}BaseGetBack"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Items" type="{DVSE}ArrayOfItem" minOccurs="0"/&gt;
 *         &lt;element name="ResponseLimit" type="{DVSE}ResponseLimit" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetBackItems", propOrder = {
    "items",
    "responseLimit"
})
public class GetBackItems extends BaseGetBack {

    @XmlElement(name = "Items")
    protected ArrayOfItem items;
    @XmlElement(name = "ResponseLimit")
    protected ResponseLimit responseLimit;

    /**
     * Gets the value of the items property.
     *
     * @return
     *     possible object is
     *     {@link ArrayOfItem }
     *
     */
    public ArrayOfItem getItems() {
        return items;
    }

    /**
     * Sets the value of the items property.
     *
     * @param value
     *     allowed object is
     *     {@link ArrayOfItem }
     *
     */
    public void setItems(ArrayOfItem value) {
        this.items = value;
    }

    /**
     * Gets the value of the responseLimit property.
     *
     * @return
     *     possible object is
     *     {@link ResponseLimit }
     *
     */
    public ResponseLimit getResponseLimit() {
        return responseLimit;
    }

    /**
     * Sets the value of the responseLimit property.
     *
     * @param value
     *     allowed object is
     *     {@link ResponseLimit }
     *
     */
    public void setResponseLimit(ResponseLimit value) {
        this.responseLimit = value;
    }

}
