//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.29 at 10:18:58 AM ICT 
//


package com.sagag.services.dvse.wsdl.dvse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for InstalledItemInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InstalledItemInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="IsAlreadyBuiltIn" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Mileage" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="DateBuiltIn" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InstalledItemInfo", propOrder = {
    "isAlreadyBuiltIn",
    "mileage",
    "dateBuiltIn"
})
public class InstalledItemInfo {

    @XmlElement(name = "IsAlreadyBuiltIn")
    protected boolean isAlreadyBuiltIn;
    @XmlElement(name = "Mileage", required = true, type = Integer.class, nillable = true)
    protected Integer mileage;
    @XmlElement(name = "DateBuiltIn", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateBuiltIn;

    /**
     * Gets the value of the isAlreadyBuiltIn property.
     * 
     */
    public boolean isIsAlreadyBuiltIn() {
        return isAlreadyBuiltIn;
    }

    /**
     * Sets the value of the isAlreadyBuiltIn property.
     * 
     */
    public void setIsAlreadyBuiltIn(boolean value) {
        this.isAlreadyBuiltIn = value;
    }

    /**
     * Gets the value of the mileage property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMileage() {
        return mileage;
    }

    /**
     * Sets the value of the mileage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMileage(Integer value) {
        this.mileage = value;
    }

    /**
     * Gets the value of the dateBuiltIn property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateBuiltIn() {
        return dateBuiltIn;
    }

    /**
     * Sets the value of the dateBuiltIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateBuiltIn(XMLGregorianCalendar value) {
        this.dateBuiltIn = value;
    }

}
