//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.29 at 10:18:58 AM ICT
//


package com.sagag.services.dvse.wsdl.dvse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Item complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Item"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{DVSE}ItemBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Warehouses" type="{DVSE}ArrayOfWarehouse" minOccurs="0"/&gt;
 *         &lt;element name="Prices" type="{DVSE}ArrayOfPrice" minOccurs="0"/&gt;
 *         &lt;element name="Quantities" type="{DVSE}ArrayOfQuantity" minOccurs="0"/&gt;
 *         &lt;element name="AlternativeItems" type="{DVSE}ArrayOfItem" minOccurs="0"/&gt;
 *         &lt;element name="ReplacementItems" type="{DVSE}ArrayOfItem" minOccurs="0"/&gt;
 *         &lt;element name="AccessoryItems" type="{DVSE}ArrayOfItem" minOccurs="0"/&gt;
 *         &lt;element name="SuggestionItems" type="{DVSE}ArrayOfItem" minOccurs="0"/&gt;
 *         &lt;element name="LinkedItems" type="{DVSE}ArrayOfItem" minOccurs="0"/&gt;
 *         &lt;element name="ObligatedItems" type="{DVSE}ArrayOfItem" minOccurs="0"/&gt;
 *         &lt;element name="InstalledItemInfo" type="{DVSE}InstalledItemInfo" minOccurs="0"/&gt;
 *         &lt;element name="AvailState" type="{DVSE}AvailableState" minOccurs="0"/&gt;
 *         &lt;element name="AdditionalArticleInformation" type="{DVSE}ArrayOfItemInfo" minOccurs="0"/&gt;
 *         &lt;element name="ItemOrder" type="{DVSE}ItemOrder" minOccurs="0"/&gt;
 *         &lt;element name="HasActionPrice" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="ShipmentModes" type="{DVSE}ArrayOfShipmentMode" minOccurs="0"/&gt;
 *         &lt;element name="ArticleActions" type="{DVSE}ArrayOfArticleAction" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Item", propOrder = {
    "warehouses",
    "prices",
    "quantities",
    "alternativeItems",
    "replacementItems",
    "accessoryItems",
    "suggestionItems",
    "linkedItems",
    "obligatedItems",
    "installedItemInfo",
    "availState",
    "additionalArticleInformation",
    "itemOrder",
    "hasActionPrice",
    "shipmentModes",
    "articleActions"
})
public class Item extends ItemBase {

    @XmlElement(name = "Warehouses")
    protected ArrayOfWarehouse warehouses;
    @XmlElement(name = "Prices")
    protected ArrayOfPrice prices;
    @XmlElement(name = "Quantities")
    protected ArrayOfQuantity quantities;
    @XmlElement(name = "AlternativeItems")
    protected ArrayOfItem alternativeItems;
    @XmlElement(name = "ReplacementItems")
    protected ArrayOfItem replacementItems;
    @XmlElement(name = "AccessoryItems")
    protected ArrayOfItem accessoryItems;
    @XmlElement(name = "SuggestionItems")
    protected ArrayOfItem suggestionItems;
    @XmlElement(name = "LinkedItems")
    protected ArrayOfItem linkedItems;
    @XmlElement(name = "ObligatedItems")
    protected ArrayOfItem obligatedItems;
    @XmlElement(name = "InstalledItemInfo")
    protected InstalledItemInfo installedItemInfo;
    @XmlElement(name = "AvailState")
    protected AvailableState availState;
    @XmlElement(name = "AdditionalArticleInformation")
    protected ArrayOfItemInfo additionalArticleInformation;
    @XmlElement(name = "ItemOrder")
    protected ItemOrder itemOrder;
    @XmlElement(name = "HasActionPrice")
    protected boolean hasActionPrice;
    @XmlElement(name = "ShipmentModes")
    protected ArrayOfShipmentMode shipmentModes;
    @XmlElement(name = "ArticleActions")
    protected ArrayOfArticleAction articleActions;

    /**
     * Gets the value of the warehouses property.
     *
     * @return
     *     possible object is
     *     {@link ArrayOfWarehouse }
     *
     */
    public ArrayOfWarehouse getWarehouses() {
        return warehouses;
    }

    /**
     * Sets the value of the warehouses property.
     *
     * @param value
     *     allowed object is
     *     {@link ArrayOfWarehouse }
     *
     */
    public void setWarehouses(ArrayOfWarehouse value) {
        this.warehouses = value;
    }

    /**
     * Gets the value of the prices property.
     *
     * @return
     *     possible object is
     *     {@link ArrayOfPrice }
     *
     */
    public ArrayOfPrice getPrices() {
        return prices;
    }

    /**
     * Sets the value of the prices property.
     *
     * @param value
     *     allowed object is
     *     {@link ArrayOfPrice }
     *
     */
    public void setPrices(ArrayOfPrice value) {
        this.prices = value;
    }

    /**
     * Gets the value of the quantities property.
     *
     * @return
     *     possible object is
     *     {@link ArrayOfQuantity }
     *
     */
    public ArrayOfQuantity getQuantities() {
        return quantities;
    }

    /**
     * Sets the value of the quantities property.
     *
     * @param value
     *     allowed object is
     *     {@link ArrayOfQuantity }
     *
     */
    public void setQuantities(ArrayOfQuantity value) {
        this.quantities = value;
    }

    /**
     * Gets the value of the alternativeItems property.
     *
     * @return
     *     possible object is
     *     {@link ArrayOfItem }
     *
     */
    public ArrayOfItem getAlternativeItems() {
        return alternativeItems;
    }

    /**
     * Sets the value of the alternativeItems property.
     *
     * @param value
     *     allowed object is
     *     {@link ArrayOfItem }
     *
     */
    public void setAlternativeItems(ArrayOfItem value) {
        this.alternativeItems = value;
    }

    /**
     * Gets the value of the replacementItems property.
     *
     * @return
     *     possible object is
     *     {@link ArrayOfItem }
     *
     */
    public ArrayOfItem getReplacementItems() {
        return replacementItems;
    }

    /**
     * Sets the value of the replacementItems property.
     *
     * @param value
     *     allowed object is
     *     {@link ArrayOfItem }
     *
     */
    public void setReplacementItems(ArrayOfItem value) {
        this.replacementItems = value;
    }

    /**
     * Gets the value of the accessoryItems property.
     *
     * @return
     *     possible object is
     *     {@link ArrayOfItem }
     *
     */
    public ArrayOfItem getAccessoryItems() {
        return accessoryItems;
    }

    /**
     * Sets the value of the accessoryItems property.
     *
     * @param value
     *     allowed object is
     *     {@link ArrayOfItem }
     *
     */
    public void setAccessoryItems(ArrayOfItem value) {
        this.accessoryItems = value;
    }

    /**
     * Gets the value of the suggestionItems property.
     *
     * @return
     *     possible object is
     *     {@link ArrayOfItem }
     *
     */
    public ArrayOfItem getSuggestionItems() {
        return suggestionItems;
    }

    /**
     * Sets the value of the suggestionItems property.
     *
     * @param value
     *     allowed object is
     *     {@link ArrayOfItem }
     *
     */
    public void setSuggestionItems(ArrayOfItem value) {
        this.suggestionItems = value;
    }

    /**
     * Gets the value of the linkedItems property.
     *
     * @return
     *     possible object is
     *     {@link ArrayOfItem }
     *
     */
    public ArrayOfItem getLinkedItems() {
        return linkedItems;
    }

    /**
     * Sets the value of the linkedItems property.
     *
     * @param value
     *     allowed object is
     *     {@link ArrayOfItem }
     *
     */
    public void setLinkedItems(ArrayOfItem value) {
        this.linkedItems = value;
    }

    /**
     * Gets the value of the obligatedItems property.
     *
     * @return
     *     possible object is
     *     {@link ArrayOfItem }
     *
     */
    public ArrayOfItem getObligatedItems() {
        return obligatedItems;
    }

    /**
     * Sets the value of the obligatedItems property.
     *
     * @param value
     *     allowed object is
     *     {@link ArrayOfItem }
     *
     */
    public void setObligatedItems(ArrayOfItem value) {
        this.obligatedItems = value;
    }

    /**
     * Gets the value of the installedItemInfo property.
     *
     * @return
     *     possible object is
     *     {@link InstalledItemInfo }
     *
     */
    public InstalledItemInfo getInstalledItemInfo() {
        return installedItemInfo;
    }

    /**
     * Sets the value of the installedItemInfo property.
     *
     * @param value
     *     allowed object is
     *     {@link InstalledItemInfo }
     *
     */
    public void setInstalledItemInfo(InstalledItemInfo value) {
        this.installedItemInfo = value;
    }

    /**
     * Gets the value of the availState property.
     *
     * @return
     *     possible object is
     *     {@link AvailableState }
     *
     */
    public AvailableState getAvailState() {
        return availState;
    }

    /**
     * Sets the value of the availState property.
     *
     * @param value
     *     allowed object is
     *     {@link AvailableState }
     *
     */
    public void setAvailState(AvailableState value) {
        this.availState = value;
    }

    /**
     * Gets the value of the additionalArticleInformation property.
     *
     * @return
     *     possible object is
     *     {@link ArrayOfItemInfo }
     *
     */
    public ArrayOfItemInfo getAdditionalArticleInformation() {
        return additionalArticleInformation;
    }

    /**
     * Sets the value of the additionalArticleInformation property.
     *
     * @param value
     *     allowed object is
     *     {@link ArrayOfItemInfo }
     *
     */
    public void setAdditionalArticleInformation(ArrayOfItemInfo value) {
        this.additionalArticleInformation = value;
    }

    /**
     * Gets the value of the itemOrder property.
     *
     * @return
     *     possible object is
     *     {@link ItemOrder }
     *
     */
    public ItemOrder getItemOrder() {
        return itemOrder;
    }

    /**
     * Sets the value of the itemOrder property.
     *
     * @param value
     *     allowed object is
     *     {@link ItemOrder }
     *
     */
    public void setItemOrder(ItemOrder value) {
        this.itemOrder = value;
    }

    /**
     * Gets the value of the hasActionPrice property.
     *
     */
    public boolean isHasActionPrice() {
        return hasActionPrice;
    }

    /**
     * Sets the value of the hasActionPrice property.
     *
     */
    public void setHasActionPrice(boolean value) {
        this.hasActionPrice = value;
    }

    /**
     * Gets the value of the shipmentModes property.
     *
     * @return
     *     possible object is
     *     {@link ArrayOfShipmentMode }
     *
     */
    public ArrayOfShipmentMode getShipmentModes() {
        return shipmentModes;
    }

    /**
     * Sets the value of the shipmentModes property.
     *
     * @param value
     *     allowed object is
     *     {@link ArrayOfShipmentMode }
     *
     */
    public void setShipmentModes(ArrayOfShipmentMode value) {
        this.shipmentModes = value;
    }

    /**
     * Gets the value of the articleActions property.
     *
     * @return
     *     possible object is
     *     {@link ArrayOfArticleAction }
     *
     */
    public ArrayOfArticleAction getArticleActions() {
        return articleActions;
    }

    /**
     * Sets the value of the articleActions property.
     *
     * @param value
     *     allowed object is
     *     {@link ArrayOfArticleAction }
     *
     */
    public void setArticleActions(ArrayOfArticleAction value) {
        this.articleActions = value;
    }

}
