//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.29 at 10:18:58 AM ICT 
//


package com.sagag.services.dvse.wsdl.dvse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ItemBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ItemBase"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="WholesalerArticleNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SupplierName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SupplierId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="SupplierArticleNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RequestedQuantity" type="{DVSE}Quantity" minOccurs="0"/&gt;
 *         &lt;element name="Memo" type="{DVSE}ArrayOfString" minOccurs="0"/&gt;
 *         &lt;element name="TecDocTypes" type="{DVSE}ArrayOfTecDocType" minOccurs="0"/&gt;
 *         &lt;element name="GenericArticles" type="{DVSE}ArrayOfGenericArticle" minOccurs="0"/&gt;
 *         &lt;element name="EAN" type="{DVSE}ArrayOfString" minOccurs="0"/&gt;
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FlagPackedForSelfService" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
 *         &lt;element name="FlagMaterialLabelingObligation" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
 *         &lt;element name="FlagExchangePart" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
 *         &lt;element name="FlagAccessory" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
 *         &lt;element name="ArticleStatus" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="ExtendedDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReferenceNumbers" type="{DVSE}ArrayOfString" minOccurs="0"/&gt;
 *         &lt;element name="UtilityNumbers" type="{DVSE}ArrayOfString" minOccurs="0"/&gt;
 *         &lt;element name="Criteria" type="{DVSE}ArrayOfCriterion" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItemBase", propOrder = {
    "wholesalerArticleNumber",
    "supplierName",
    "supplierId",
    "supplierArticleNumber",
    "requestedQuantity",
    "memo",
    "tecDocTypes",
    "genericArticles",
    "ean",
    "description",
    "flagPackedForSelfService",
    "flagMaterialLabelingObligation",
    "flagExchangePart",
    "flagAccessory",
    "articleStatus",
    "extendedDescription",
    "referenceNumbers",
    "utilityNumbers",
    "criteria"
})
@XmlSeeAlso({
    Item.class
})
public class ItemBase {

    @XmlElement(name = "WholesalerArticleNumber")
    protected String wholesalerArticleNumber;
    @XmlElement(name = "SupplierName")
    protected String supplierName;
    @XmlElement(name = "SupplierId")
    protected int supplierId;
    @XmlElement(name = "SupplierArticleNumber")
    protected String supplierArticleNumber;
    @XmlElement(name = "RequestedQuantity")
    protected Quantity requestedQuantity;
    @XmlElement(name = "Memo")
    protected ArrayOfString memo;
    @XmlElement(name = "TecDocTypes")
    protected ArrayOfTecDocType tecDocTypes;
    @XmlElement(name = "GenericArticles")
    protected ArrayOfGenericArticle genericArticles;
    @XmlElement(name = "EAN")
    protected ArrayOfString ean;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "FlagPackedForSelfService")
    @XmlSchemaType(name = "unsignedByte")
    protected short flagPackedForSelfService;
    @XmlElement(name = "FlagMaterialLabelingObligation")
    @XmlSchemaType(name = "unsignedByte")
    protected short flagMaterialLabelingObligation;
    @XmlElement(name = "FlagExchangePart")
    @XmlSchemaType(name = "unsignedByte")
    protected short flagExchangePart;
    @XmlElement(name = "FlagAccessory")
    @XmlSchemaType(name = "unsignedByte")
    protected short flagAccessory;
    @XmlElement(name = "ArticleStatus")
    protected int articleStatus;
    @XmlElement(name = "ExtendedDescription")
    protected String extendedDescription;
    @XmlElement(name = "ReferenceNumbers")
    protected ArrayOfString referenceNumbers;
    @XmlElement(name = "UtilityNumbers")
    protected ArrayOfString utilityNumbers;
    @XmlElement(name = "Criteria")
    protected ArrayOfCriterion criteria;

    /**
     * Gets the value of the wholesalerArticleNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWholesalerArticleNumber() {
        return wholesalerArticleNumber;
    }

    /**
     * Sets the value of the wholesalerArticleNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWholesalerArticleNumber(String value) {
        this.wholesalerArticleNumber = value;
    }

    /**
     * Gets the value of the supplierName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * Sets the value of the supplierName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierName(String value) {
        this.supplierName = value;
    }

    /**
     * Gets the value of the supplierId property.
     * 
     */
    public int getSupplierId() {
        return supplierId;
    }

    /**
     * Sets the value of the supplierId property.
     * 
     */
    public void setSupplierId(int value) {
        this.supplierId = value;
    }

    /**
     * Gets the value of the supplierArticleNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierArticleNumber() {
        return supplierArticleNumber;
    }

    /**
     * Sets the value of the supplierArticleNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierArticleNumber(String value) {
        this.supplierArticleNumber = value;
    }

    /**
     * Gets the value of the requestedQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link Quantity }
     *     
     */
    public Quantity getRequestedQuantity() {
        return requestedQuantity;
    }

    /**
     * Sets the value of the requestedQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quantity }
     *     
     */
    public void setRequestedQuantity(Quantity value) {
        this.requestedQuantity = value;
    }

    /**
     * Gets the value of the memo property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfString }
     *     
     */
    public ArrayOfString getMemo() {
        return memo;
    }

    /**
     * Sets the value of the memo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfString }
     *     
     */
    public void setMemo(ArrayOfString value) {
        this.memo = value;
    }

    /**
     * Gets the value of the tecDocTypes property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfTecDocType }
     *     
     */
    public ArrayOfTecDocType getTecDocTypes() {
        return tecDocTypes;
    }

    /**
     * Sets the value of the tecDocTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfTecDocType }
     *     
     */
    public void setTecDocTypes(ArrayOfTecDocType value) {
        this.tecDocTypes = value;
    }

    /**
     * Gets the value of the genericArticles property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfGenericArticle }
     *     
     */
    public ArrayOfGenericArticle getGenericArticles() {
        return genericArticles;
    }

    /**
     * Sets the value of the genericArticles property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfGenericArticle }
     *     
     */
    public void setGenericArticles(ArrayOfGenericArticle value) {
        this.genericArticles = value;
    }

    /**
     * Gets the value of the ean property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfString }
     *     
     */
    public ArrayOfString getEAN() {
        return ean;
    }

    /**
     * Sets the value of the ean property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfString }
     *     
     */
    public void setEAN(ArrayOfString value) {
        this.ean = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the flagPackedForSelfService property.
     * 
     */
    public short getFlagPackedForSelfService() {
        return flagPackedForSelfService;
    }

    /**
     * Sets the value of the flagPackedForSelfService property.
     * 
     */
    public void setFlagPackedForSelfService(short value) {
        this.flagPackedForSelfService = value;
    }

    /**
     * Gets the value of the flagMaterialLabelingObligation property.
     * 
     */
    public short getFlagMaterialLabelingObligation() {
        return flagMaterialLabelingObligation;
    }

    /**
     * Sets the value of the flagMaterialLabelingObligation property.
     * 
     */
    public void setFlagMaterialLabelingObligation(short value) {
        this.flagMaterialLabelingObligation = value;
    }

    /**
     * Gets the value of the flagExchangePart property.
     * 
     */
    public short getFlagExchangePart() {
        return flagExchangePart;
    }

    /**
     * Sets the value of the flagExchangePart property.
     * 
     */
    public void setFlagExchangePart(short value) {
        this.flagExchangePart = value;
    }

    /**
     * Gets the value of the flagAccessory property.
     * 
     */
    public short getFlagAccessory() {
        return flagAccessory;
    }

    /**
     * Sets the value of the flagAccessory property.
     * 
     */
    public void setFlagAccessory(short value) {
        this.flagAccessory = value;
    }

    /**
     * Gets the value of the articleStatus property.
     * 
     */
    public int getArticleStatus() {
        return articleStatus;
    }

    /**
     * Sets the value of the articleStatus property.
     * 
     */
    public void setArticleStatus(int value) {
        this.articleStatus = value;
    }

    /**
     * Gets the value of the extendedDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtendedDescription() {
        return extendedDescription;
    }

    /**
     * Sets the value of the extendedDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtendedDescription(String value) {
        this.extendedDescription = value;
    }

    /**
     * Gets the value of the referenceNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfString }
     *     
     */
    public ArrayOfString getReferenceNumbers() {
        return referenceNumbers;
    }

    /**
     * Sets the value of the referenceNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfString }
     *     
     */
    public void setReferenceNumbers(ArrayOfString value) {
        this.referenceNumbers = value;
    }

    /**
     * Gets the value of the utilityNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfString }
     *     
     */
    public ArrayOfString getUtilityNumbers() {
        return utilityNumbers;
    }

    /**
     * Sets the value of the utilityNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfString }
     *     
     */
    public void setUtilityNumbers(ArrayOfString value) {
        this.utilityNumbers = value;
    }

    /**
     * Gets the value of the criteria property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfCriterion }
     *     
     */
    public ArrayOfCriterion getCriteria() {
        return criteria;
    }

    /**
     * Sets the value of the criteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfCriterion }
     *     
     */
    public void setCriteria(ArrayOfCriterion value) {
        this.criteria = value;
    }

}
