//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.29 at 10:18:58 AM ICT 
//


package com.sagag.services.dvse.wsdl.dvse;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sagag.services.dvse.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sagag.services.dvse.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetArticleInformation }
     * 
     */
    public GetArticleInformation createGetArticleInformation() {
        return new GetArticleInformation();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link ArrayOfItem }
     * 
     */
    public ArrayOfItem createArrayOfItem() {
        return new ArrayOfItem();
    }

    /**
     * Create an instance of {@link ResponseLimit }
     * 
     */
    public ResponseLimit createResponseLimit() {
        return new ResponseLimit();
    }

    /**
     * Create an instance of {@link GetArticleInformationResponse }
     * 
     */
    public GetArticleInformationResponse createGetArticleInformationResponse() {
        return new GetArticleInformationResponse();
    }

    /**
     * Create an instance of {@link GetBackItems }
     * 
     */
    public GetBackItems createGetBackItems() {
        return new GetBackItems();
    }

    /**
     * Create an instance of {@link SendOrder }
     * 
     */
    public SendOrder createSendOrder() {
        return new SendOrder();
    }

    /**
     * Create an instance of {@link Order }
     * 
     */
    public Order createOrder() {
        return new Order();
    }

    /**
     * Create an instance of {@link SendOrderResponse }
     * 
     */
    public SendOrderResponse createSendOrderResponse() {
        return new SendOrderResponse();
    }

    /**
     * Create an instance of {@link GetBackOrder }
     * 
     */
    public GetBackOrder createGetBackOrder() {
        return new GetBackOrder();
    }

    /**
     * Create an instance of {@link GetBillingModes }
     * 
     */
    public GetBillingModes createGetBillingModes() {
        return new GetBillingModes();
    }

    /**
     * Create an instance of {@link GetBillingModesResponse }
     * 
     */
    public GetBillingModesResponse createGetBillingModesResponse() {
        return new GetBillingModesResponse();
    }

    /**
     * Create an instance of {@link GetBackBillingModes }
     * 
     */
    public GetBackBillingModes createGetBackBillingModes() {
        return new GetBackBillingModes();
    }

    /**
     * Create an instance of {@link GetWarehouses }
     * 
     */
    public GetWarehouses createGetWarehouses() {
        return new GetWarehouses();
    }

    /**
     * Create an instance of {@link GetWarehousesResponse }
     * 
     */
    public GetWarehousesResponse createGetWarehousesResponse() {
        return new GetWarehousesResponse();
    }

    /**
     * Create an instance of {@link GetBackWarehouses }
     * 
     */
    public GetBackWarehouses createGetBackWarehouses() {
        return new GetBackWarehouses();
    }

    /**
     * Create an instance of {@link GetPaymentModes }
     * 
     */
    public GetPaymentModes createGetPaymentModes() {
        return new GetPaymentModes();
    }

    /**
     * Create an instance of {@link GetPaymentModesResponse }
     * 
     */
    public GetPaymentModesResponse createGetPaymentModesResponse() {
        return new GetPaymentModesResponse();
    }

    /**
     * Create an instance of {@link GetBackPaymentModes }
     * 
     */
    public GetBackPaymentModes createGetBackPaymentModes() {
        return new GetBackPaymentModes();
    }

    /**
     * Create an instance of {@link GetShipmentModes }
     * 
     */
    public GetShipmentModes createGetShipmentModes() {
        return new GetShipmentModes();
    }

    /**
     * Create an instance of {@link GetShipmentModesResponse }
     * 
     */
    public GetShipmentModesResponse createGetShipmentModesResponse() {
        return new GetShipmentModesResponse();
    }

    /**
     * Create an instance of {@link GetBackShipmentModes }
     * 
     */
    public GetBackShipmentModes createGetBackShipmentModes() {
        return new GetBackShipmentModes();
    }

    /**
     * Create an instance of {@link GetTours }
     * 
     */
    public GetTours createGetTours() {
        return new GetTours();
    }

    /**
     * Create an instance of {@link GetToursResponse }
     * 
     */
    public GetToursResponse createGetToursResponse() {
        return new GetToursResponse();
    }

    /**
     * Create an instance of {@link GetBackTours }
     * 
     */
    public GetBackTours createGetBackTours() {
        return new GetBackTours();
    }

    /**
     * Create an instance of {@link GetDeliveryAddresses }
     * 
     */
    public GetDeliveryAddresses createGetDeliveryAddresses() {
        return new GetDeliveryAddresses();
    }

    /**
     * Create an instance of {@link GetDeliveryAddressesResponse }
     * 
     */
    public GetDeliveryAddressesResponse createGetDeliveryAddressesResponse() {
        return new GetDeliveryAddressesResponse();
    }

    /**
     * Create an instance of {@link GetBackDeliveryAddresses }
     * 
     */
    public GetBackDeliveryAddresses createGetBackDeliveryAddresses() {
        return new GetBackDeliveryAddresses();
    }

    /**
     * Create an instance of {@link SendOrderDocument }
     * 
     */
    public SendOrderDocument createSendOrderDocument() {
        return new SendOrderDocument();
    }

    /**
     * Create an instance of {@link SendOrderDocumentResponse }
     * 
     */
    public SendOrderDocumentResponse createSendOrderDocumentResponse() {
        return new SendOrderDocumentResponse();
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link ItemBase }
     * 
     */
    public ItemBase createItemBase() {
        return new ItemBase();
    }

    /**
     * Create an instance of {@link Quantity }
     * 
     */
    public Quantity createQuantity() {
        return new Quantity();
    }

    /**
     * Create an instance of {@link AvailableState }
     * 
     */
    public AvailableState createAvailableState() {
        return new AvailableState();
    }

    /**
     * Create an instance of {@link ArrayOfString }
     * 
     */
    public ArrayOfString createArrayOfString() {
        return new ArrayOfString();
    }

    /**
     * Create an instance of {@link Tour }
     * 
     */
    public Tour createTour() {
        return new Tour();
    }

    /**
     * Create an instance of {@link ArrayOfTecDocType }
     * 
     */
    public ArrayOfTecDocType createArrayOfTecDocType() {
        return new ArrayOfTecDocType();
    }

    /**
     * Create an instance of {@link TecDocType }
     * 
     */
    public TecDocType createTecDocType() {
        return new TecDocType();
    }

    /**
     * Create an instance of {@link ArrayOfGenericArticle }
     * 
     */
    public ArrayOfGenericArticle createArrayOfGenericArticle() {
        return new ArrayOfGenericArticle();
    }

    /**
     * Create an instance of {@link GenericArticle }
     * 
     */
    public GenericArticle createGenericArticle() {
        return new GenericArticle();
    }

    /**
     * Create an instance of {@link ArrayOfCriterion }
     * 
     */
    public ArrayOfCriterion createArrayOfCriterion() {
        return new ArrayOfCriterion();
    }

    /**
     * Create an instance of {@link Criterion }
     * 
     */
    public Criterion createCriterion() {
        return new Criterion();
    }

    /**
     * Create an instance of {@link ArrayOfWarehouse }
     * 
     */
    public ArrayOfWarehouse createArrayOfWarehouse() {
        return new ArrayOfWarehouse();
    }

    /**
     * Create an instance of {@link Warehouse }
     * 
     */
    public Warehouse createWarehouse() {
        return new Warehouse();
    }

    /**
     * Create an instance of {@link ArrayOfQuantity }
     * 
     */
    public ArrayOfQuantity createArrayOfQuantity() {
        return new ArrayOfQuantity();
    }

    /**
     * Create an instance of {@link ArrayOfPrice }
     * 
     */
    public ArrayOfPrice createArrayOfPrice() {
        return new ArrayOfPrice();
    }

    /**
     * Create an instance of {@link Price }
     * 
     */
    public Price createPrice() {
        return new Price();
    }

    /**
     * Create an instance of {@link InstalledItemInfo }
     * 
     */
    public InstalledItemInfo createInstalledItemInfo() {
        return new InstalledItemInfo();
    }

    /**
     * Create an instance of {@link ArrayOfItemInfo }
     * 
     */
    public ArrayOfItemInfo createArrayOfItemInfo() {
        return new ArrayOfItemInfo();
    }

    /**
     * Create an instance of {@link ItemInfo }
     * 
     */
    public ItemInfo createItemInfo() {
        return new ItemInfo();
    }

    /**
     * Create an instance of {@link ItemOrder }
     * 
     */
    public ItemOrder createItemOrder() {
        return new ItemOrder();
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link ArrayOfShipmentMode }
     * 
     */
    public ArrayOfShipmentMode createArrayOfShipmentMode() {
        return new ArrayOfShipmentMode();
    }

    /**
     * Create an instance of {@link ShipmentMode }
     * 
     */
    public ShipmentMode createShipmentMode() {
        return new ShipmentMode();
    }

    /**
     * Create an instance of {@link ArrayOfArticleAction }
     * 
     */
    public ArrayOfArticleAction createArrayOfArticleAction() {
        return new ArrayOfArticleAction();
    }

    /**
     * Create an instance of {@link ArticleAction }
     * 
     */
    public ArticleAction createArticleAction() {
        return new ArticleAction();
    }

    /**
     * Create an instance of {@link BaseGetBack }
     * 
     */
    public BaseGetBack createBaseGetBack() {
        return new BaseGetBack();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link ArrayOfBillingMode }
     * 
     */
    public ArrayOfBillingMode createArrayOfBillingMode() {
        return new ArrayOfBillingMode();
    }

    /**
     * Create an instance of {@link BillingMode }
     * 
     */
    public BillingMode createBillingMode() {
        return new BillingMode();
    }

    /**
     * Create an instance of {@link ArrayOfPaymentMode }
     * 
     */
    public ArrayOfPaymentMode createArrayOfPaymentMode() {
        return new ArrayOfPaymentMode();
    }

    /**
     * Create an instance of {@link PaymentMode }
     * 
     */
    public PaymentMode createPaymentMode() {
        return new PaymentMode();
    }

    /**
     * Create an instance of {@link ArrayOfTour }
     * 
     */
    public ArrayOfTour createArrayOfTour() {
        return new ArrayOfTour();
    }

    /**
     * Create an instance of {@link ArrayOfAddress }
     * 
     */
    public ArrayOfAddress createArrayOfAddress() {
        return new ArrayOfAddress();
    }

}
