//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.29 at 10:18:58 AM ICT 
//


package com.sagag.services.dvse.wsdl.dvse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResponseLimit complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResponseLimit"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="IsResponseBounded" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="ResponseMax" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="NumberOfRequestedItems" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResponseLimit", propOrder = {
    "isResponseBounded",
    "responseMax",
    "numberOfRequestedItems"
})
public class ResponseLimit {

    @XmlElement(name = "IsResponseBounded")
    protected boolean isResponseBounded;
    @XmlElement(name = "ResponseMax", required = true, type = Integer.class, nillable = true)
    protected Integer responseMax;
    @XmlElement(name = "NumberOfRequestedItems")
    protected int numberOfRequestedItems;

    /**
     * Gets the value of the isResponseBounded property.
     * 
     */
    public boolean isIsResponseBounded() {
        return isResponseBounded;
    }

    /**
     * Sets the value of the isResponseBounded property.
     * 
     */
    public void setIsResponseBounded(boolean value) {
        this.isResponseBounded = value;
    }

    /**
     * Gets the value of the responseMax property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getResponseMax() {
        return responseMax;
    }

    /**
     * Sets the value of the responseMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setResponseMax(Integer value) {
        this.responseMax = value;
    }

    /**
     * Gets the value of the numberOfRequestedItems property.
     * 
     */
    public int getNumberOfRequestedItems() {
        return numberOfRequestedItems;
    }

    /**
     * Sets the value of the numberOfRequestedItems property.
     * 
     */
    public void setNumberOfRequestedItems(int value) {
        this.numberOfRequestedItems = value;
    }

}
