//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.29 at 10:18:58 AM ICT 
//


package com.sagag.services.dvse.wsdl.dvse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TecDocType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TecDocType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TecDocTypeId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="TecDocModelId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="TecDocManufacturerId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="VehicleType" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="VIN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FullDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DateFrom" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="DateTo" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="KwFrom" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="KwTo" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="HpFrom" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="HpTo" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="CcmTax" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="CcmTech" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Liter" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="CylinderNumber" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="ABS" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="VehicleMode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EngineMode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DriveType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ASR" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="BreakSystem" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FuelType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CatalystType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TransmissionType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BodyType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="KeyNumbers" type="{DVSE}ArrayOfString" minOccurs="0"/&gt;
 *         &lt;element name="EngineCodes" type="{DVSE}ArrayOfString" minOccurs="0"/&gt;
 *         &lt;element name="PlateNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TecDocType", propOrder = {
    "tecDocTypeId",
    "tecDocModelId",
    "tecDocManufacturerId",
    "vehicleType",
    "vin",
    "description",
    "fullDescription",
    "dateFrom",
    "dateTo",
    "kwFrom",
    "kwTo",
    "hpFrom",
    "hpTo",
    "ccmTax",
    "ccmTech",
    "liter",
    "cylinderNumber",
    "abs",
    "vehicleMode",
    "engineMode",
    "driveType",
    "asr",
    "breakSystem",
    "fuelType",
    "catalystType",
    "transmissionType",
    "bodyType",
    "keyNumbers",
    "engineCodes",
    "plateNumber"
})
public class TecDocType {

    @XmlElement(name = "TecDocTypeId")
    protected int tecDocTypeId;
    @XmlElement(name = "TecDocModelId")
    protected int tecDocModelId;
    @XmlElement(name = "TecDocManufacturerId")
    protected int tecDocManufacturerId;
    @XmlElement(name = "VehicleType")
    protected int vehicleType;
    @XmlElement(name = "VIN")
    protected String vin;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "FullDescription")
    protected String fullDescription;
    @XmlElement(name = "DateFrom")
    protected int dateFrom;
    @XmlElement(name = "DateTo")
    protected int dateTo;
    @XmlElement(name = "KwFrom")
    protected int kwFrom;
    @XmlElement(name = "KwTo")
    protected int kwTo;
    @XmlElement(name = "HpFrom")
    protected int hpFrom;
    @XmlElement(name = "HpTo")
    protected int hpTo;
    @XmlElement(name = "CcmTax")
    protected int ccmTax;
    @XmlElement(name = "CcmTech")
    protected int ccmTech;
    @XmlElement(name = "Liter")
    protected int liter;
    @XmlElement(name = "CylinderNumber")
    protected int cylinderNumber;
    @XmlElement(name = "ABS")
    protected int abs;
    @XmlElement(name = "VehicleMode")
    protected String vehicleMode;
    @XmlElement(name = "EngineMode")
    protected String engineMode;
    @XmlElement(name = "DriveType")
    protected String driveType;
    @XmlElement(name = "ASR")
    protected int asr;
    @XmlElement(name = "BreakSystem")
    protected String breakSystem;
    @XmlElement(name = "FuelType")
    protected String fuelType;
    @XmlElement(name = "CatalystType")
    protected String catalystType;
    @XmlElement(name = "TransmissionType")
    protected String transmissionType;
    @XmlElement(name = "BodyType")
    protected String bodyType;
    @XmlElement(name = "KeyNumbers")
    protected ArrayOfString keyNumbers;
    @XmlElement(name = "EngineCodes")
    protected ArrayOfString engineCodes;
    @XmlElement(name = "PlateNumber")
    protected String plateNumber;

    /**
     * Gets the value of the tecDocTypeId property.
     * 
     */
    public int getTecDocTypeId() {
        return tecDocTypeId;
    }

    /**
     * Sets the value of the tecDocTypeId property.
     * 
     */
    public void setTecDocTypeId(int value) {
        this.tecDocTypeId = value;
    }

    /**
     * Gets the value of the tecDocModelId property.
     * 
     */
    public int getTecDocModelId() {
        return tecDocModelId;
    }

    /**
     * Sets the value of the tecDocModelId property.
     * 
     */
    public void setTecDocModelId(int value) {
        this.tecDocModelId = value;
    }

    /**
     * Gets the value of the tecDocManufacturerId property.
     * 
     */
    public int getTecDocManufacturerId() {
        return tecDocManufacturerId;
    }

    /**
     * Sets the value of the tecDocManufacturerId property.
     * 
     */
    public void setTecDocManufacturerId(int value) {
        this.tecDocManufacturerId = value;
    }

    /**
     * Gets the value of the vehicleType property.
     * 
     */
    public int getVehicleType() {
        return vehicleType;
    }

    /**
     * Sets the value of the vehicleType property.
     * 
     */
    public void setVehicleType(int value) {
        this.vehicleType = value;
    }

    /**
     * Gets the value of the vin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVIN() {
        return vin;
    }

    /**
     * Sets the value of the vin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVIN(String value) {
        this.vin = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the fullDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullDescription() {
        return fullDescription;
    }

    /**
     * Sets the value of the fullDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullDescription(String value) {
        this.fullDescription = value;
    }

    /**
     * Gets the value of the dateFrom property.
     * 
     */
    public int getDateFrom() {
        return dateFrom;
    }

    /**
     * Sets the value of the dateFrom property.
     * 
     */
    public void setDateFrom(int value) {
        this.dateFrom = value;
    }

    /**
     * Gets the value of the dateTo property.
     * 
     */
    public int getDateTo() {
        return dateTo;
    }

    /**
     * Sets the value of the dateTo property.
     * 
     */
    public void setDateTo(int value) {
        this.dateTo = value;
    }

    /**
     * Gets the value of the kwFrom property.
     * 
     */
    public int getKwFrom() {
        return kwFrom;
    }

    /**
     * Sets the value of the kwFrom property.
     * 
     */
    public void setKwFrom(int value) {
        this.kwFrom = value;
    }

    /**
     * Gets the value of the kwTo property.
     * 
     */
    public int getKwTo() {
        return kwTo;
    }

    /**
     * Sets the value of the kwTo property.
     * 
     */
    public void setKwTo(int value) {
        this.kwTo = value;
    }

    /**
     * Gets the value of the hpFrom property.
     * 
     */
    public int getHpFrom() {
        return hpFrom;
    }

    /**
     * Sets the value of the hpFrom property.
     * 
     */
    public void setHpFrom(int value) {
        this.hpFrom = value;
    }

    /**
     * Gets the value of the hpTo property.
     * 
     */
    public int getHpTo() {
        return hpTo;
    }

    /**
     * Sets the value of the hpTo property.
     * 
     */
    public void setHpTo(int value) {
        this.hpTo = value;
    }

    /**
     * Gets the value of the ccmTax property.
     * 
     */
    public int getCcmTax() {
        return ccmTax;
    }

    /**
     * Sets the value of the ccmTax property.
     * 
     */
    public void setCcmTax(int value) {
        this.ccmTax = value;
    }

    /**
     * Gets the value of the ccmTech property.
     * 
     */
    public int getCcmTech() {
        return ccmTech;
    }

    /**
     * Sets the value of the ccmTech property.
     * 
     */
    public void setCcmTech(int value) {
        this.ccmTech = value;
    }

    /**
     * Gets the value of the liter property.
     * 
     */
    public int getLiter() {
        return liter;
    }

    /**
     * Sets the value of the liter property.
     * 
     */
    public void setLiter(int value) {
        this.liter = value;
    }

    /**
     * Gets the value of the cylinderNumber property.
     * 
     */
    public int getCylinderNumber() {
        return cylinderNumber;
    }

    /**
     * Sets the value of the cylinderNumber property.
     * 
     */
    public void setCylinderNumber(int value) {
        this.cylinderNumber = value;
    }

    /**
     * Gets the value of the abs property.
     * 
     */
    public int getABS() {
        return abs;
    }

    /**
     * Sets the value of the abs property.
     * 
     */
    public void setABS(int value) {
        this.abs = value;
    }

    /**
     * Gets the value of the vehicleMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleMode() {
        return vehicleMode;
    }

    /**
     * Sets the value of the vehicleMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleMode(String value) {
        this.vehicleMode = value;
    }

    /**
     * Gets the value of the engineMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEngineMode() {
        return engineMode;
    }

    /**
     * Sets the value of the engineMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEngineMode(String value) {
        this.engineMode = value;
    }

    /**
     * Gets the value of the driveType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriveType() {
        return driveType;
    }

    /**
     * Sets the value of the driveType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriveType(String value) {
        this.driveType = value;
    }

    /**
     * Gets the value of the asr property.
     * 
     */
    public int getASR() {
        return asr;
    }

    /**
     * Sets the value of the asr property.
     * 
     */
    public void setASR(int value) {
        this.asr = value;
    }

    /**
     * Gets the value of the breakSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBreakSystem() {
        return breakSystem;
    }

    /**
     * Sets the value of the breakSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBreakSystem(String value) {
        this.breakSystem = value;
    }

    /**
     * Gets the value of the fuelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFuelType() {
        return fuelType;
    }

    /**
     * Sets the value of the fuelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFuelType(String value) {
        this.fuelType = value;
    }

    /**
     * Gets the value of the catalystType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatalystType() {
        return catalystType;
    }

    /**
     * Sets the value of the catalystType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatalystType(String value) {
        this.catalystType = value;
    }

    /**
     * Gets the value of the transmissionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransmissionType() {
        return transmissionType;
    }

    /**
     * Sets the value of the transmissionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransmissionType(String value) {
        this.transmissionType = value;
    }

    /**
     * Gets the value of the bodyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBodyType() {
        return bodyType;
    }

    /**
     * Sets the value of the bodyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBodyType(String value) {
        this.bodyType = value;
    }

    /**
     * Gets the value of the keyNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfString }
     *     
     */
    public ArrayOfString getKeyNumbers() {
        return keyNumbers;
    }

    /**
     * Sets the value of the keyNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfString }
     *     
     */
    public void setKeyNumbers(ArrayOfString value) {
        this.keyNumbers = value;
    }

    /**
     * Gets the value of the engineCodes property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfString }
     *     
     */
    public ArrayOfString getEngineCodes() {
        return engineCodes;
    }

    /**
     * Sets the value of the engineCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfString }
     *     
     */
    public void setEngineCodes(ArrayOfString value) {
        this.engineCodes = value;
    }

    /**
     * Gets the value of the plateNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlateNumber() {
        return plateNumber;
    }

    /**
     * Sets the value of the plateNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlateNumber(String value) {
        this.plateNumber = value;
    }

}
