package com.sagag.services.tools.support;

public enum SagUserErrorCode {

  NOT_FOUND_USER, WRONG_FORMAT_PASSWORD,
  INVALID_AFFILIATE, INVALID_COMPANY_NAME,
  INVALID_CUSTOMER_NR,
  INVALID_ORGANISATION_TYPE, INVALID_ADMIN_ROLE,
  INVALID_USER_ROLE, INVALID_POST_CODE,
  INVALID_USER_NAME, INVALID_SUR_NAME,
  INVALID_EMAIL, INVALID_USERNAME_IN_CUSTOMER,
  INVALID_USERNAME_IN_AFFILIATE, INVALID_SALUTATION,
  INVALID_DELIVERY_METHOD, INVALID_GROUP,
  INVALID_CUSTOMER, CUSTOMER_INACTIVE, SEND_MAIL_FAILED,
  NOT_FOUND_EMAIL_ADDRESS, MULTIPLE_MAIL_ADDRESSES, NOT_AUTHORIZED_USER,
  INVALID_EXTERNAL_ORGANISATION, NOT_FOUND_ORGANISATION,
  CREATE_MDM_USER_FAILED, NOT_FOUND_USER_ON_BEHALF,
  DUPLICATED_USERNAME_IN_AFFILIATE
}
