export const MAX_INFO_LENGTH = 60;
export const APP_SUB_ORDER_BASKET = 'APP_SUB_ORDER_BASKET';

export const FAVORITE_BROADCAST_EVENT = {
    ADD_ARTICLE: 'ADD_ARTICLE',
    EDIT_ARTICLE: 'EDIT_ARTICLE',
    REMOVE_ARTICLE: 'REMOVE_ARTICLE',
    ADD_LEAF: 'ADD_LEAF',
    EDIT_LEAF: 'EDIT_LEAF',
    REMOVE_LEAF: 'REMOVE_LEAF',
    TOGGLE_STATUS_ARTICLE: 'TOGGLE_STATUS_ARTICLE',
    TOGGLE_STATUS_LEAF: 'TOGGLE_STATUS_LEAF',
    UPDATE_SEARCH_ARTICLE_HISTORY: 'UPDATE_SEARCH_ARTICLE_HISTORY',
    EDIT_LEAF_COMMENT: 'EDIT_LEAF_COMMENT',
    TOGGLE_STATUS_VEHICLE: 'TOGGLE_STATUS_VEHICLE',
    ADD_VEHICLE: 'ADD_VEHICLE',
    EDIT_VEHICLE: 'EDIT_VEHICLE',
    REMOVE_VEHICLE: 'REMOVE_VEHICLE'
};

export const FAVORITE_PROCESS_TYPE = {
    LEAF_NODE: 'LEAF_NODE',
    ARTICLE: 'ARTICLE',
    VEHICLE: 'VEHICLE'
};

export const FAVORITE_SEARCH_TYPE = {
    'ALL': 'ALL',
    'ARTICLE': 'ARTICLE'
};

export const INFO_TYPE_MAP = {
    TEXT: 'TEXT',
    IMAGE: 'IMAGE',
    LINK: 'LINK'
}

export const NONVEHICLE = 'NONVEHICLE';
export const OTHER_SUPPLIERS_NAME = 'Other suppliers';
export const APP_VAT_CONFIRM = 'app.vat.confirm';
