select * from AAD_ACCOUNTS where PRIMARY_CONTACT_EMAIL like '%simon%';
select * from AAD_ACCOUNTS where PRIMARY_CONTACT_EMAIL like '%bharani%';
select * from AAD_ACCOUNTS where PRIMARY_CONTACT_EMAIL like '%philipp%';
select * from AAD_ACCOUNTS where PRIMARY_CONTACT_EMAIL like '%lefkothea%';

INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Simon', 'Kendall', 'Simon.Kendall@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Bharani', 'Kumar', 'Bharani.Kumar@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Philipp', 'Grueter', 'Philipp.Grueter@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Lefkothea', 'Karlou', 'Lefkothea.Karlou@sag-ag.ch', 9999, 'Female', '30DA', 'SALES');

-- Lila TEST team
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Charalampos', 'Tampasis', 'Charalampos.Tampasis@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Anastasia', 'Herodotou', 'Anastasia.Herodotou@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Maria', 'Roumelioti', 'Maria.Roumelioti@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');

-- From Simon email
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Peiman', 'Safiari', 'Peiman.Safiari@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Vladimir', 'Sokol', 'Vladimir.Sokol@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Eugen', 'Ruppen', 'Eugen.Ruppen@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Katharina', 'Luppe', 'Katharina.Luppe@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Markus', 'Brenner', 'Markus.Brenner@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Matthias', 'Rohrbach', 'Matthias.Rohrbach@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Stephan', 'Simeoni', 'Stephan.Simeoni@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Michael', 'vonSpreckelsen', 'Michael.vonSpreckelsen@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Daniel', 'Blumer', 'Daniel.Blumer@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Christoph', 'Kohler', 'christoph.kohler@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Thomas', 'Goeckeritz', 'thomas.goeckeritz@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Juergen', 'Steffen', 'Juergen.steffen@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Ext', 'Pecn', 'ext_pecn@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');

INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Sandro', 'Piffaretti', 'sandro.piffaretti@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Joel', 'Souchon', 'Joel.Souchon@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Birgit', 'Weische', 'Birgit.Weische@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Bruno', 'Weidenthaler', 'bruno.weidenthaler@sag-austria.at', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Philipp', 'Stähly', 'Philipp.Staehly@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Philippe', 'Thiemann', 'Philippe.Thiemann@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Stefan', 'Thönen', 'Stefan.Thoenen@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Henning', 'Kaess', 'Henning.Kaess@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Peter', 'Rusterholz', 'Peter.Rusterholz@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Kurt', 'Schnyder', 'Kurt.Schnyder@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');

INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Michael', 'vonSpreckelsen', 'Michael.vonSpreckelsen@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Thomas', 'Weigel', 'Thomas.Weigel@gws.ms', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Julian', 'Goblirsch', 'Julian.Goblirsch@gws.ms', 9999, 'Male', '30DA', 'SALES');

-- From Phillip
-- in PROD
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Primus', 'Jauch', 'Primus.Jauch@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Daniel', 'Pecnik', 'Daniel.Pecnik@gws.ms', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Müller', 'Julian', 'Julian.Mueller@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Kendall', 'Rex', 'rex.kendall@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');

-- in PREPROD
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Eugen', 'Ruppen', 'Eugen.Ruppen@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Susann', 'Hug', 'Susann.Hug@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Dalibor', 'Zecevic', 'Dalibor.Zecevic@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Christoph', 'Kohler', 'christoph.kohler@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Stephan', 'Simeoni', 'Stephan.Simeoni@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Primus', 'Jauch', 'Primus.Jauch@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Julian', 'Mueller', 'Julian.Mueller@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Rex', 'Kendall', 'Rex.Kendall@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Kendall', 'Rex', 'rex.kendall@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');

-- Sokol Vladimir Vladimir.Sokol@sag-ag.ch (NOK - assign permission)
INSERT INTO GROUP_USER (USER_ID, GROUP_ID) VALUES (15014,3);
-- Luppe Katharina Katharina.Luppe@sag-ag.ch (NOK - assign permission)
INSERT INTO GROUP_USER (USER_ID, GROUP_ID) VALUES (15103,3);
-- Krstic Dusko Dusko.Krstic@sag-ag.ch (NOK - assign permission)
INSERT INTO GROUP_USER (USER_ID, GROUP_ID) VALUES (15104,3);

-- Truong: TEST Account
INSERT INTO [dbo].[AAD_ACCOUNTS] (FIRST_NAME, LAST_NAME, PRIMARY_CONTACT_EMAIL, PERSONAL_NUMBER, GENDER, LEGAL_ENTITY_ID, PERMIT_GROUP) VALUES ('Connect', 'Business DEV', 'sys-ws-connect-dev@sag-ag.ch', 9999, 'Male', '30DA', 'SALES');

