GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_AAD_ACCOUNTS_PERMIT_GROUP]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_AAD_ACCOUNTS_PERMIT_GROUP] ON [dbo].[AAD_ACCOUNTS]
(
	[PERMIT_GROUP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_AAD_ACCOUNTS_PRIMARY_CONTACT_EMAIL]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_AAD_ACCOUNTS_PRIMARY_CONTACT_EMAIL] ON [dbo].[AAD_ACCOUNTS]
(
	[PRIMARY_CONTACT_EMAIL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_COUNTRY_CODE]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_COUNTRY_CODE] ON [dbo].[COUNTRY]
(
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [INX_ESHOP_CART_ITEM_CART_KEY]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [INX_ESHOP_CART_ITEM_CART_KEY] ON [dbo].[ESHOP_CART_ITEM]
(
	[CART_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [INX_ESHOP_CART_ITEM_CUSTOMER_NR]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [INX_ESHOP_CART_ITEM_CUSTOMER_NR] ON [dbo].[ESHOP_CART_ITEM]
(
	[CUSTOMER_NR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
GO
/****** Object:  Index [INX_ESHOP_CART_ITEM_ID]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [INX_ESHOP_CART_ITEM_ID] ON [dbo].[ESHOP_CART_ITEM]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [INX_ESHOP_CART_ITEM_USER_ID]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [INX_ESHOP_CART_ITEM_USER_ID] ON [dbo].[ESHOP_CART_ITEM]
(
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [INX_ESHOP_CART_ITEM_USER_ID_CUSTOMER_NR]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [INX_ESHOP_CART_ITEM_USER_ID_CUSTOMER_NR] ON [dbo].[ESHOP_CART_ITEM]
(
	[USER_ID] ASC,
	[CUSTOMER_NR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [INX_ESHOP_CART_ITEM_USER_NAME]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [INX_ESHOP_CART_ITEM_USER_NAME] ON [dbo].[ESHOP_CART_ITEM]
(
	[USER_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_ESHOP_USER_EMAIL]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_ESHOP_USER_EMAIL] ON [dbo].[ESHOP_USER]
(
	[EMAIL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDX_ESHOP_USER_LANGUAGE]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_ESHOP_USER_LANGUAGE] ON [dbo].[ESHOP_USER]
(
	[LANGUAGE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDX_ESHOP_USER_SETTING]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_ESHOP_USER_SETTING] ON [dbo].[ESHOP_USER]
(
	[SETTING] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_ESHOP_USER_USERNAME]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_ESHOP_USER_USERNAME] ON [dbo].[ESHOP_USER]
(
	[USERNAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDX_EXTERNAL_ESHOP_USER_ID]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_EXTERNAL_ESHOP_USER_ID] ON [dbo].[EXTERNAL_USER]
(
	[ESHOP_USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDX_FINAL_CUSTOMER_ORDER_ORG_ID]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_FINAL_CUSTOMER_ORDER_ORG_ID] ON [dbo].[FINAL_CUSTOMER_ORDER]
(
	[ORG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDX_FINAL_CUSTOMER_ORDER_USER_ID]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_FINAL_CUSTOMER_ORDER_USER_ID] ON [dbo].[FINAL_CUSTOMER_ORDER]
(
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDX_FINAL_CUSTOMER_ORDER_ITEM_FINAL_CUSTOMER_ORDER_ID]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_FINAL_CUSTOMER_ORDER_ITEM_FINAL_CUSTOMER_ORDER_ID] ON [dbo].[FINAL_CUSTOMER_ORDER_ITEM]
(
	[FINAL_CUSTOMER_ORDER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDX_GROUP_USER_ID]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_GROUP_USER_ID] ON [dbo].[GROUP_USER]
(
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDX_INVOICE_HISTORY_CREATED_DATE]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_INVOICE_HISTORY_CREATED_DATE] ON [dbo].[INVOICE_HISTORY]
(
	[CREATED_DATE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDX_INVOICE_HISTORY_CUSTOMER_NR]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_INVOICE_HISTORY_CUSTOMER_NR] ON [dbo].[INVOICE_HISTORY]
(
	[CUSTOMER_NR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDX_INVOICE_HISTORY_INVOICE_NR]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_INVOICE_HISTORY_INVOICE_NR] ON [dbo].[INVOICE_HISTORY]
(
	[INVOICE_NR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_INVOICE_TYPE_NAME]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_INVOICE_TYPE_NAME] ON [dbo].[INVOICE_TYPE]
(
	[INVOICE_TYPE_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_LANGUAGES_LANGISO]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_LANGUAGES_LANGISO] ON [dbo].[LANGUAGES]
(
	[LANGISO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDX_LICENSE_VEH_CUSTOMER_NR]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_LICENSE_VEH_CUSTOMER_NR] ON [dbo].[LICENSE]
(
	[CUSTOMER_NR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_LICENSE_VEH_CUSTOMER_NR_TYPE_OF_LICENSE]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_LICENSE_VEH_CUSTOMER_NR_TYPE_OF_LICENSE] ON [dbo].[LICENSE]
(
	[CUSTOMER_NR] ASC,
	[TYPE_OF_LICENSE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_LICENSE_VEH_TYPE_OF_LICENSE]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_LICENSE_VEH_TYPE_OF_LICENSE] ON [dbo].[LICENSE]
(
	[TYPE_OF_LICENSE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_LICENSE_SETTINGS_TYPE_OF_LICENSE]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_LICENSE_SETTINGS_TYPE_OF_LICENSE] ON [dbo].[LICENSE_SETTINGS]
(
	[TYPE_OF_LICENSE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_OAUTH_ACCESS_TOKEN_AUTHENTICATION_ID]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_OAUTH_ACCESS_TOKEN_AUTHENTICATION_ID] ON [dbo].[OAUTH_ACCESS_TOKEN]
(
	[AUTHENTICATION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_OAUTH_ACCESS_TOKEN_TOKEN_ID]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_OAUTH_ACCESS_TOKEN_TOKEN_ID] ON [dbo].[OAUTH_ACCESS_TOKEN]
(
	[TOKEN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDX_OFFER_ADDRESS_ID]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_OFFER_ADDRESS_ID] ON [dbo].[OFFER_ADDRESS]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDX_OFFER_ADDRESS_PERSON_ID]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_OFFER_ADDRESS_PERSON_ID] ON [dbo].[OFFER_ADDRESS]
(
	[PERSON_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_OFFER_PERSON_EMAIL]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_OFFER_PERSON_EMAIL] ON [dbo].[OFFER_PERSON]
(
	[EMAIL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_OFFER_PERSON_FIRST_NAME]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_OFFER_PERSON_FIRST_NAME] ON [dbo].[OFFER_PERSON]
(
	[FIRST_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDX_OFFER_PERSON_ID]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_OFFER_PERSON_ID] ON [dbo].[OFFER_PERSON]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDX_OFFER_PERSON_LANGUAGE_ID]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_OFFER_PERSON_LANGUAGE_ID] ON [dbo].[OFFER_PERSON]
(
	[LANGUAGE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_OFFER_PERSON_LAST_NAME]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_OFFER_PERSON_LAST_NAME] ON [dbo].[OFFER_PERSON]
(
	[LAST_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_OFFER_PERSON_OFFER_COMPANY_NAME]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_OFFER_PERSON_OFFER_COMPANY_NAME] ON [dbo].[OFFER_PERSON]
(
	[OFFER_COMPANY_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDX_OFFER_PERSON_ORGANISATION_ID]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_OFFER_PERSON_ORGANISATION_ID] ON [dbo].[OFFER_PERSON]
(
	[ORGANISATION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_OFFER_PERSON_STATUS]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_OFFER_PERSON_STATUS] ON [dbo].[OFFER_PERSON]
(
	[STATUS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_OFFER_PERSON_TYPE]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_OFFER_PERSON_TYPE] ON [dbo].[OFFER_PERSON]
(
	[TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDX_OFFER_PERSON_PROPERTY_PERSON_ID]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_OFFER_PERSON_PROPERTY_PERSON_ID] ON [dbo].[OFFER_PERSON_PROPERTY]
(
	[PERSON_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_OFFER_PERSON_PROPERTY_TYPE]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_OFFER_PERSON_PROPERTY_TYPE] ON [dbo].[OFFER_PERSON_PROPERTY]
(
	[TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDX_OFFER_POSITION_OFFER_ID]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_OFFER_POSITION_OFFER_ID] ON [dbo].[OFFER_POSITION]
(
	[OFFER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_OFFER_VEHICLE_DESC]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_OFFER_VEHICLE_DESC] ON [dbo].[OFFER_POSITION]
(
	[OFFER_ID] ASC,
	[VEHICLE_DESCRIPTION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDX_ORDER_HISTORY_CUSTOMER_NUMBER]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_ORDER_HISTORY_CUSTOMER_NUMBER] ON [dbo].[ORDER_HISTORY]
(
	[CUSTOMER_NUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDX_ORDER_HISTORY_FINAL_CUSTOMER_ORDER_ID]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_ORDER_HISTORY_FINAL_CUSTOMER_ORDER_ID] ON [dbo].[ORDER_HISTORY]
(
	[FINAL_CUSTOMER_ORDER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDX_ORDER_HISTORY_GOODS_RECEIVER_ID]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_ORDER_HISTORY_GOODS_RECEIVER_ID] ON [dbo].[ORDER_HISTORY]
(
	[GOODS_RECEIVER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_ORDER_HISTORY_ORDER_NUMBER]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_ORDER_HISTORY_ORDER_NUMBER] ON [dbo].[ORDER_HISTORY]
(
	[ORDER_NUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDX_ORDER_HISTORY_SALE_ID]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_ORDER_HISTORY_SALE_ID] ON [dbo].[ORDER_HISTORY]
(
	[SALE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDX_ORDER_HISTORY_SALE_ID_CUSTOMER_NUMBER]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_ORDER_HISTORY_SALE_ID_CUSTOMER_NUMBER] ON [dbo].[ORDER_HISTORY]
(
	[SALE_ID] ASC,
	[CUSTOMER_NUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDX_ORDER_HISTORY_USER_ID]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_ORDER_HISTORY_USER_ID] ON [dbo].[ORDER_HISTORY]
(
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_ORGANISATION_NAME]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_ORGANISATION_NAME] ON [dbo].[ORGANISATION]
(
	[NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_ORGANISATION_ORG_CODE]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_ORGANISATION_ORG_CODE] ON [dbo].[ORGANISATION]
(
	[ORG_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_ORGANISATION_ORG_CODE_PARENT_ID]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_ORGANISATION_ORG_CODE_PARENT_ID] ON [dbo].[ORGANISATION]
(
	[ORG_CODE] ASC,
	[PARENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDX_ORGANISATION_PARENT_ID]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_ORGANISATION_PARENT_ID] ON [dbo].[ORGANISATION]
(
	[PARENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDX_ORGANISATION_SETTINGS_ID]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_ORGANISATION_SETTINGS_ID] ON [dbo].[ORGANISATION]
(
	[ORDER_SETTINGS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_ORGANISATION_SHORTNAME]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_ORGANISATION_SHORTNAME] ON [dbo].[ORGANISATION]
(
	[SHORTNAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDX_ORGANISATION_GROUP_ID]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_ORGANISATION_GROUP_ID] ON [dbo].[ORGANISATION_GROUP]
(
	[GROUP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDX_SHOP_ARTICLE_AMOUNT]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_SHOP_ARTICLE_AMOUNT] ON [dbo].[SHOP_ARTICLE]
(
	[AMOUNT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_SHOP_ARTICLE_ARTICLE_NUMBER]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_SHOP_ARTICLE_ARTICLE_NUMBER] ON [dbo].[SHOP_ARTICLE]
(
	[ARTICLE_NUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDX_SHOP_ARTICLE_ORG_ID]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_SHOP_ARTICLE_ORG_ID] ON [dbo].[SHOP_ARTICLE]
(
	[ORGANISATION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDX_SHOP_ARTICLE_PRICE]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_SHOP_ARTICLE_PRICE] ON [dbo].[SHOP_ARTICLE]
(
	[PRICE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_SHOP_ARTICLE_TECSTATE]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_SHOP_ARTICLE_TECSTATE] ON [dbo].[SHOP_ARTICLE]
(
	[TECSTATE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_SHOP_ARTICLE_TYPE]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_SHOP_ARTICLE_TYPE] ON [dbo].[SHOP_ARTICLE]
(
	[TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDX_SHOP_ARTICLE_VERSION]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_SHOP_ARTICLE_VERSION] ON [dbo].[SHOP_ARTICLE]
(
	[VERSION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_SUPPORTED_AFFILIATE_COMPANY_NAME]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_SUPPORTED_AFFILIATE_COMPANY_NAME] ON [dbo].[SUPPORTED_AFFILIATE]
(
	[COMPANY_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDX_SUPPORTED_AFFILIATE_COUNTRY_ID]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_SUPPORTED_AFFILIATE_COUNTRY_ID] ON [dbo].[SUPPORTED_AFFILIATE]
(
	[COUNTRY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDX_SUPPORTED_AFFILIATE_ID]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_SUPPORTED_AFFILIATE_ID] ON [dbo].[SUPPORTED_AFFILIATE]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_SUPPORTED_AFFILIATE_SHORT_NAME]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_SUPPORTED_AFFILIATE_SHORT_NAME] ON [dbo].[SUPPORTED_AFFILIATE]
(
	[SHORT_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_TOUR_TIME_BRANCH_ID]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_TOUR_TIME_BRANCH_ID] ON [dbo].[TOUR_TIME]
(
	[BRANCH_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_TOUR_TIME_CUST_NR]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_TOUR_TIME_CUST_NR] ON [dbo].[TOUR_TIME]
(
	[CUSTOMER_NUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_USER_VEH_HISTORY]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_USER_VEH_HISTORY] ON [dbo].[USER_VEHICLE_HISTORY]
(
	[USER_ID] ASC,
	[VEH_HISTORY_ID] ASC,
	[SEARCH_TERM] ASC,
	[FROM_SOURCE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IDX_VEHICLE_HISTORY_ID]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_VEHICLE_HISTORY_ID] ON [dbo].[VEHICLE_HISTORY]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_VEHICLE_HISTORY_VEH_ID]    Script Date: 4/7/2021 5:39:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_VEHICLE_HISTORY_VEH_ID] ON [dbo].[VEHICLE_HISTORY]
(
	[VEH_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO