CREATE TABLE sag.dbo.MIGRATION_EBL_ORGANISATION (
  ID BIGINT NOT NULL,
  ERPNUMBER BIGINT NOT NULL,
  ERPINSTANCE varchar(50),
  [TYPE] varchar(50),
  ORGANISATIONID varchar(50),
  NAME varchar(100),
  STATUS varchar(50),
  DISTRIBUTIONSET varchar(19),
  UC_ID varchar(19),
  DC varchar(50),
  UM_ID varchar(19),
  DM varchar(50),
  VERSION varchar(10),
  TECSTATE varchar(50),
  COUNTRYISO varchar(3),
  NEW_ID BIGINT,
  COMPANY_NAME VARCHAR(5,0)
  IS_MIGRATED [bit] NOT NULL default 0
)

CREATE TABLE MIGRATION_EBL_PERSON (
  ID BIGINT NOT NULL,
  "TYPE" VARCHAR(50),
  STATUS VARCHAR(50),
  FIRSTNAME VARCHAR(100),
  LASTNAME VARCHAR(100),
  EMAIL VARCHAR(255),
  LANGISO VARCHAR(3),
  UC_ID BIGINT,
  DC DATETIME DEFAULT GETDATE(),
  UM_ID BIGINT,
  DM DATETIME,
  VERSION INT DEFAULT 1,
  TECSTATE VARCHAR(50) DEFAULT 'ACTIVE',
  AFFILIATE varchar(50),
  IS_MIGRATED [bit] NOT NULL default 0
)

CREATE TABLE MIGRATION_EBL_LOGIN (
  ID BIGINT NOT NULL,
  PERSON_ID BIGINT NOT NULL,
  ORGANISATION_ID BIGINT NOT NULL,
  ACCESSPOINT_ID BIGINT NOT NULL,
  USERNAME VARCHAR(50),
  PASSWORDHASH VARCHAR(50),
  UC_ID BIGINT NULL,
  DC DATETIME DEFAULT GETDATE() ,
  UM_ID BIGINT NULL,
  DM DATETIME NULL,
  VERSION BIGINT NULL DEFAULT 1 ,
  TECSTATE VARCHAR(50) DEFAULT 'ACTIVE' ,
  LASTLOGIN DATETIME NULL,
  PASSWORDCHANGEREQUIRED BIGINT NULL DEFAULT 0 ,
  STATUS VARCHAR(31) DEFAULT 'ACTIVE' ,
  HASHTYPE VARCHAR(50)
)

CREATE TABLE MIGRATION_EBL_LOGIN_ROLEASSIGNMENT (
  ID BIGINT NOT NULL IDENTITY(1,1),
  "ROLE" VARCHAR(50),
  PERSON_ID BIGINT NOT NULL,
  ORGANISATION_ID BIGINT NOT NULL,
  LOGIN_ID BIGINT NOT NULL
) 

CREATE TABLE MIGRATION_EBL_ORGANISATION_PROPERTY (
  ID BIGINT NOT NULL IDENTITY(1,1),
  ORGANISATION_ID BIGINT NOT NULL,
  "TYPE" VARCHAR(50),
  VALUE VARCHAR(255)
)

CREATE TABLE MIGRATION_EBL_PERSON_PROPERTY (
  ID BIGINT NOT NULL IDENTITY(1,1),
  PERSON_ID BIGINT NOT NULL,
  "TYPE" VARCHAR(50),
  VALUE VARCHAR(255)
)

