USE [ax]

--GO
CREATE TABLE [dbo].[PAYMENT_TYPE](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [CODE] [varchar](50) NULL,
    [DESCRIPTION] [varchar](255) NULL,
PRIMARY KEY CLUSTERED
([ID] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY]) ON [PRIMARY];

--GO
CREATE TABLE [dbo].[COUNTRY](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [CODE] [varchar](50) NULL,
    [SHORT_NAME] [varchar](255) NULL,
    [FULL_NAME] [varchar](500) NULL,
PRIMARY KEY CLUSTERED
([ID] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY]) ON [PRIMARY];

--GO
CREATE TABLE [dbo].[STATE](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [CODE] [varchar](50) NULL,
    [DESCRIPTION] [varchar](255) NULL,
PRIMARY KEY CLUSTERED
([ID] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY]) ON [PRIMARY];

-- CREATE AAD Accounts with SALE guys list
CREATE TABLE [dbo].[AAD_ACCOUNTS](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [FIRST_NAME] [varchar](255) NULL,
    [LAST_NAME] [varchar](255) NULL,
    [PRIMARY_CONTACT_EMAIL] [varchar](255) NULL,
    [PERSONAL_NUMBER] [smallint] NULL,
    [GENDER] [varchar](10) NULL,
    [LEGAL_ENTITY_ID] [varchar](10) NULL,
    [PERMIT_GROUP] [varchar](10) NULL,
PRIMARY KEY CLUSTERED
([ID] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY]) ON [PRIMARY];

-- MOVE THIS FROM MASTER
ALTER TABLE [dbo].[LICENSE_SETTINGS] ADD [TYPE_OF_LICENSE] [char](50) NULL;

-- SUPPORTED AFFILIATE
CREATE TABLE [dbo].[SUPPORTED_AFFILIATE](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [SHORT_NAME] [varchar](50) NULL,
    [COMPANY_NAME] [varchar](255) NULL,
    [DESCRIPTION] [varchar](500) NULL,
    [COUNTRY_ID] [int] NOT NULL,
    [UPDATED_DATE] datetime NOT NULL DEFAULT getdate(),
PRIMARY KEY CLUSTERED
([ID] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY]) ON [PRIMARY];

-- CREATE INDEX ON TABLE SUPPORTED_AFFILIATE (ID, SHORT_NAME, COMPANY_NAME, COUNTRY_ID)
CREATE INDEX IDX_SUPPORTED_AFFILIATE_ID ON [dbo].[SUPPORTED_AFFILIATE] (ID);
CREATE INDEX IDX_SUPPORTED_AFFILIATE_SHORT_NAME ON [dbo].[SUPPORTED_AFFILIATE] (SHORT_NAME);
CREATE INDEX IDX_SUPPORTED_AFFILIATE_COMPANY_NAME ON [dbo].[SUPPORTED_AFFILIATE] (COMPANY_NAME);
CREATE INDEX IDX_SUPPORTED_AFFILIATE_COUNTRY_ID ON [dbo].[SUPPORTED_AFFILIATE] (COUNTRY_ID);

-- CREATE INDEX ON TABLE COUNTRY (ID, CODE)
CREATE INDEX IDX_COUNTRY_ID ON [dbo].[COUNTRY] (ID);
CREATE INDEX IDX_COUNTRY_CODE ON [dbo].[COUNTRY] (CODE);

-- Add more columns for SUPPORTED_AFFILIATE
ALTER TABLE [dbo].[SUPPORTED_AFFILIATE] ADD [ES_SHORT_NAME] [char](50) NULL;
ALTER TABLE [dbo].[SUPPORTED_AFFILIATE] ADD [SALES_ORIGIN_ID] [char](50) NULL;

ALTER TABLE MIGRATION_DVSE_CUSTOMERS ADD PASSANT_NAME VARCHAR(255) NULL
ALTER TABLE MIGRATION_DVSE_CUSTOMERS ADD SALE_GROUP VARCHAR(255) NULL
ALTER TABLE MIGRATION_DVSE_CUSTOMERS ADD CUSTOMER_GROUP VARCHAR(255) NULL
ALTER TABLE MIGRATION_DVSE_CUSTOMERS ADD SEND_METHOD VARCHAR(255) NULL;

-- ADD more column CREATED_DATE in AAD_ACCOUNTS for tracking
ALTER TABLE [dbo].[AAD_ACCOUNTS] ADD CREATED_DATE datetime NULL;
ALTER TABLE [dbo].[AAD_ACCOUNTS] ADD DEFAULT (getdate()) FOR [CREATED_DATE];

-- Support Tour time table
CREATE TABLE [dbo].[TOUR_TIME](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [CUSTOMER_NUMBER] [varchar](20) NOT NULL,
    [BRANCH_ID] [varchar](20) NULL,
    [TOUR_NAME] [varchar](255) NULL
PRIMARY KEY CLUSTERED
([ID] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY]) ON [PRIMARY];

CREATE INDEX IDX_TOUR_TIME_CUST_NR ON [dbo].[TOUR_TIME] (CUSTOMER_NUMBER);
CREATE INDEX IDX_TOUR_TIME_BRANCH_ID ON [dbo].[TOUR_TIME] (BRANCH_ID);

-- forgot password
-- auto-generated definition
CREATE TABLE PASSWORD_RESET_TOKEN
(
  ID          BIGINT IDENTITY
    CONSTRAINT PASSWORD_RESET_TOKEN_ID_pk
    PRIMARY KEY,
  token       VARCHAR(6),
  expiry_date DATETIME,
  USER_ID     BIGINT
    CONSTRAINT PASSWORD_RESET_TOKEN_ESHOP_USER_ID_fk
    REFERENCES ESHOP_USER
)
GO
CREATE UNIQUE INDEX PASSWORD_RESET_TOKEN_ID_uindex
  ON PASSWORD_RESET_TOKEN (ID)
GO
ALTER TABLE [dbo].[PASSWORD_RESET_TOKEN] ADD hash_username_code VARCHAR(255) NULL


-- Add more colums for SUPPORT_AFFILIATE
ALTER TABLE [dbo].[SUPPORTED_AFFILIATE] ADD [SHOW_PFAND_ARTICLE] bit DEFAULT 0;
ALTER TABLE [dbo].[SUPPORTED_AFFILIATE] ADD [LOGO_LINK] VARCHAR(255) NULL;