/** PLEASE JUST RUN FOR PRO ENV
ALTER TABLE dbo.FEEDBACK DROP CONSTRAINT FK_USER_ID;
ALTER TABLE dbo.FEEDBACK DROP CONSTRAINT FK_SALES_ID;
ALTER TABLE dbo.FEEDBACK DROP CONSTRAINT FK_ORG_ID;
ALTER TABLE dbo.FEEDBACK DROP CONSTRAINT FK_STATUS_ID;
ALTER TABLE dbo.FEEDBACK DROP CONSTRAINT FK_TOPIC_ID;
ALTER TABLE dbo.FEEDBACK_DEPARTMENT_CONTACT DROP CONSTRAINT FK_DEPARTMENT_ID;


TRUNCATE TABLE dbo.FEEDBACK_TOPIC;
INSERT INTO dbo.FEEDBACK_TOPIC (TOPIC_CODE, DESCRIPTION) VALUES('PRICING', 'Pricing');
INSERT INTO dbo.FEEDBACK_TOPIC (TOPIC_CODE, DESCRIPTION) VALUES('ORDERS_AVAILABILITY', 'Orders, Availability');
INSERT INTO dbo.FEEDBACK_TOPIC (TOPIC_CODE, DESCRIPTION) VALUES('EASE_OF_USE', 'Ease of use');
INSERT INTO dbo.FEEDBACK_TOPIC (TOPIC_CODE, DESCRIPTION) VALUES('MISSING_WRONG_DATA', 'Missing/wrong data (vehicle, part, range of goods etc.)');
INSERT INTO dbo.FEEDBACK_TOPIC (TOPIC_CODE, DESCRIPTION) VALUES('LICENSING', 'Licensing (HaynesPro, VIN etc.)');
INSERT INTO dbo.FEEDBACK_TOPIC (TOPIC_CODE, DESCRIPTION) VALUES('SYSTEM_BROWSER_INTERFACES', 'System, Browser, Interfaces');
INSERT INTO dbo.FEEDBACK_TOPIC (TOPIC_CODE, DESCRIPTION) VALUES('PROFILE_SETTINGS', 'Profile, Settings');
INSERT INTO dbo.FEEDBACK_TOPIC (TOPIC_CODE, DESCRIPTION) VALUES('OTHER', 'Other...');


TRUNCATE TABLE dbo.FEEDBACK_DEPARTMENT;
INSERT INTO dbo.FEEDBACK_DEPARTMENT (DEPARTMENT_CODE , DESCRIPTION) VALUES('CATEGORY_MANAGEMENT_AT', 'Category Management AT');
INSERT INTO dbo.FEEDBACK_DEPARTMENT (DEPARTMENT_CODE , DESCRIPTION) VALUES('DATA_CONNECT_TEAM', 'Data Connect Team');
INSERT INTO dbo.FEEDBACK_DEPARTMENT (DEPARTMENT_CODE , DESCRIPTION) VALUES('SERVICE_DESK_AT', 'Service Desk AT');

DECLARE @deptCategory INT = (SELECT ID FROM FEEDBACK_DEPARTMENT WHERE DEPARTMENT_CODE='CATEGORY_MANAGEMENT_AT');
DECLARE @deptData INT = (SELECT ID FROM FEEDBACK_DEPARTMENT WHERE DEPARTMENT_CODE='DATA_CONNECT_TEAM');
DECLARE @deptService INT = (SELECT ID FROM FEEDBACK_DEPARTMENT WHERE DEPARTMENT_CODE='SERVICE_DESK_AT');

DECLARE @topicPricing INT = (SELECT ID FROM FEEDBACK_TOPIC WHERE TOPIC_CODE='PRICING');
DECLARE @topicOrderAvai INT = (SELECT ID FROM FEEDBACK_TOPIC WHERE TOPIC_CODE='ORDERS_AVAILABILITY');
DECLARE @topicEaseOfUse INT = (SELECT ID FROM FEEDBACK_TOPIC WHERE TOPIC_CODE='EASE_OF_USE');
DECLARE @topicDataIssue INT = (SELECT ID FROM FEEDBACK_TOPIC WHERE TOPIC_CODE='MISSING_WRONG_DATA');
DECLARE @topicLicense INT = (SELECT ID FROM FEEDBACK_TOPIC WHERE TOPIC_CODE='LICENSING');
DECLARE @topicSystemBrowserInterface INT = (SELECT ID FROM FEEDBACK_TOPIC WHERE TOPIC_CODE='SYSTEM_BROWSER_INTERFACES');
DECLARE @topicProfileSetting INT = (SELECT ID FROM FEEDBACK_TOPIC WHERE TOPIC_CODE='PROFILE_SETTINGS');
DECLARE @topicOther INT = (SELECT ID FROM FEEDBACK_TOPIC WHERE TOPIC_CODE='OTHER');

TRUNCATE TABLE dbo.FEEDBACK_TOPIC_DEPARTMENT;
INSERT INTO dbo.FEEDBACK_TOPIC_DEPARTMENT (TOPIC_ID, DEPARTMENT_ID) VALUES(@topicPricing, @deptCategory);
INSERT INTO dbo.FEEDBACK_TOPIC_DEPARTMENT (TOPIC_ID, DEPARTMENT_ID) VALUES(@topicDataIssue, @deptData);
INSERT INTO dbo.FEEDBACK_TOPIC_DEPARTMENT (TOPIC_ID, DEPARTMENT_ID) VALUES(@topicOrderAvai, @deptService);
INSERT INTO dbo.FEEDBACK_TOPIC_DEPARTMENT (TOPIC_ID, DEPARTMENT_ID) VALUES(@topicEaseOfUse, @deptService);
INSERT INTO dbo.FEEDBACK_TOPIC_DEPARTMENT (TOPIC_ID, DEPARTMENT_ID) VALUES(@topicLicense, @deptService);
INSERT INTO dbo.FEEDBACK_TOPIC_DEPARTMENT (TOPIC_ID, DEPARTMENT_ID) VALUES(@topicSystemBrowserInterface, @deptService);
INSERT INTO dbo.FEEDBACK_TOPIC_DEPARTMENT (TOPIC_ID, DEPARTMENT_ID) VALUES(@topicProfileSetting, @deptService);
INSERT INTO dbo.FEEDBACK_TOPIC_DEPARTMENT (TOPIC_ID, DEPARTMENT_ID) VALUES(@topicOther, @deptService);


TRUNCATE TABLE dbo.FEEDBACK_DEPARTMENT_CONTACT;
INSERT INTO dbo.FEEDBACK_DEPARTMENT_CONTACT (DEPARTMENT_ID, [TYPE], VALUE) VALUES(@deptCategory, 'EMAIL', 'categorymanagement@sag-austria.at');
INSERT INTO dbo.FEEDBACK_DEPARTMENT_CONTACT (DEPARTMENT_ID, [TYPE], VALUE) VALUES(@deptData, 'EMAIL', 'dataconnect@sag-austria.at');
INSERT INTO dbo.FEEDBACK_DEPARTMENT_CONTACT (DEPARTMENT_ID, [TYPE], VALUE) VALUES(@deptService, 'EMAIL', 'servicedesk@sag-austria.at');


ALTER TABLE dbo.FEEDBACK ADD CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES dbo.ESHOP_USER (ID);
ALTER TABLE dbo.FEEDBACK ADD CONSTRAINT FK_SALES_ID FOREIGN KEY (SALES_ID) REFERENCES dbo.ESHOP_USER (ID);
ALTER TABLE dbo.FEEDBACK ADD CONSTRAINT FK_ORG_ID FOREIGN KEY (ORG_ID) REFERENCES dbo.ORGANISATION (ID);
ALTER TABLE dbo.FEEDBACK ADD CONSTRAINT FK_STATUS_ID FOREIGN KEY (STATUS_ID) REFERENCES dbo.FEEDBACK_STATUS (ID);
ALTER TABLE dbo.FEEDBACK ADD CONSTRAINT FK_TOPIC_ID FOREIGN KEY (TOPIC_ID) REFERENCES dbo.FEEDBACK_TOPIC (ID);
ALTER TABLE dbo.FEEDBACK_DEPARTMENT_CONTACT ADD CONSTRAINT FK_DEPARTMENT_ID FOREIGN KEY (DEPARTMENT_ID) REFERENCES dbo.FEEDBACK_DEPARTMENT (ID);

