
package com.sagag.services.stakis.erp.wsdl.tmconnect;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ITMConnectContract", targetNamespace = "http://topmotive.eu/TMConnect")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ITMConnectContract {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetVersion", action = "http://topmotive.eu/TMConnect/ITMConnectContract/GetVersion")
    @WebResult(name = "GetVersionResult", targetNamespace = "http://topmotive.eu/TMConnect")
    @RequestWrapper(localName = "GetVersion", targetNamespace = "http://topmotive.eu/TMConnect", className = "com.sagag.services.stakis.erp.wsdl.tmconnect.GetVersionRequestBody")
    @ResponseWrapper(localName = "GetVersionResponse", targetNamespace = "http://topmotive.eu/TMConnect", className = "com.sagag.services.stakis.erp.wsdl.tmconnect.GetVersionResponseBody")
    public String getVersion();

    /**
     * 
     * @param request
     * @return
     *     returns com.sagag.services.stakis.erp.wsdl.tmconnect.GetSessionReply
     */
    @WebMethod(operationName = "GetSession", action = "http://topmotive.eu/TMConnect/ITMConnectContract/GetSession")
    @WebResult(name = "GetSessionResult", targetNamespace = "http://topmotive.eu/TMConnect")
    @RequestWrapper(localName = "GetSession", targetNamespace = "http://topmotive.eu/TMConnect", className = "com.sagag.services.stakis.erp.wsdl.tmconnect.GetSessionRequestBody")
    @ResponseWrapper(localName = "GetSessionResponse", targetNamespace = "http://topmotive.eu/TMConnect", className = "com.sagag.services.stakis.erp.wsdl.tmconnect.GetSessionResponseBody")
    public GetSessionReply getSession(
        @WebParam(name = "request", targetNamespace = "http://topmotive.eu/TMConnect")
        BaseRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.sagag.services.stakis.erp.wsdl.tmconnect.BaseResponse
     */
    @WebMethod(operationName = "DeleteSession", action = "http://topmotive.eu/TMConnect/ITMConnectContract/DeleteSession")
    @WebResult(name = "DeleteSessionResult", targetNamespace = "http://topmotive.eu/TMConnect")
    @RequestWrapper(localName = "DeleteSession", targetNamespace = "http://topmotive.eu/TMConnect", className = "com.sagag.services.stakis.erp.wsdl.tmconnect.DeleteSessionRequestBody")
    @ResponseWrapper(localName = "DeleteSessionResponse", targetNamespace = "http://topmotive.eu/TMConnect", className = "com.sagag.services.stakis.erp.wsdl.tmconnect.DeleteSessionResponseBody")
    public BaseResponse deleteSession(
        @WebParam(name = "request", targetNamespace = "http://topmotive.eu/TMConnect")
        BaseRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.sagag.services.stakis.erp.wsdl.tmconnect.GetErpInformationReply
     */
    @WebMethod(operationName = "GetErpInformation", action = "http://topmotive.eu/TMConnect/ITMConnectContract/GetErpInformation")
    @WebResult(name = "GetErpInformationResult", targetNamespace = "http://topmotive.eu/TMConnect")
    @RequestWrapper(localName = "GetErpInformation", targetNamespace = "http://topmotive.eu/TMConnect", className = "com.sagag.services.stakis.erp.wsdl.tmconnect.GetErpInformationRequestBody")
    @ResponseWrapper(localName = "GetErpInformationResponse", targetNamespace = "http://topmotive.eu/TMConnect", className = "com.sagag.services.stakis.erp.wsdl.tmconnect.GetErpInformationResponseBody")
    public GetErpInformationReply getErpInformation(
        @WebParam(name = "request", targetNamespace = "http://topmotive.eu/TMConnect")
        GetErpInformationRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.sagag.services.stakis.erp.wsdl.tmconnect.SendOrderReply
     */
    @WebMethod(operationName = "SendOrder", action = "http://topmotive.eu/TMConnect/ITMConnectContract/SendOrder")
    @WebResult(name = "SendOrderResult", targetNamespace = "http://topmotive.eu/TMConnect")
    @RequestWrapper(localName = "SendOrder", targetNamespace = "http://topmotive.eu/TMConnect", className = "com.sagag.services.stakis.erp.wsdl.tmconnect.SendOrderRequestBody")
    @ResponseWrapper(localName = "SendOrderResponse", targetNamespace = "http://topmotive.eu/TMConnect", className = "com.sagag.services.stakis.erp.wsdl.tmconnect.SendOrderResponseBody")
    public SendOrderReply sendOrder(
        @WebParam(name = "request", targetNamespace = "http://topmotive.eu/TMConnect")
        SendOrderRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.sagag.services.stakis.erp.wsdl.tmconnect.BaseResponse
     */
    @WebMethod(operationName = "SendOrderDocument", action = "http://topmotive.eu/TMConnect/ITMConnectContract/SendOrderDocument")
    @WebResult(name = "SendOrderDocumentResult", targetNamespace = "http://topmotive.eu/TMConnect")
    @RequestWrapper(localName = "SendOrderDocument", targetNamespace = "http://topmotive.eu/TMConnect", className = "com.sagag.services.stakis.erp.wsdl.tmconnect.SendOrderDocumentRequestBody")
    @ResponseWrapper(localName = "SendOrderDocumentResponse", targetNamespace = "http://topmotive.eu/TMConnect", className = "com.sagag.services.stakis.erp.wsdl.tmconnect.SendOrderDocumentResponseBody")
    public BaseResponse sendOrderDocument(
        @WebParam(name = "request", targetNamespace = "http://topmotive.eu/TMConnect")
        SendOrderDocumentRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.sagag.services.stakis.erp.wsdl.tmconnect.FindItemsReply
     */
    @WebMethod(operationName = "FindItems", action = "http://topmotive.eu/TMConnect/ITMConnectContract/FindItems")
    @WebResult(name = "FindItemsResult", targetNamespace = "http://topmotive.eu/TMConnect")
    @RequestWrapper(localName = "FindItems", targetNamespace = "http://topmotive.eu/TMConnect", className = "com.sagag.services.stakis.erp.wsdl.tmconnect.FindItemsRequestBody")
    @ResponseWrapper(localName = "FindItemsResponse", targetNamespace = "http://topmotive.eu/TMConnect", className = "com.sagag.services.stakis.erp.wsdl.tmconnect.FindItemsResponseBody")
    public FindItemsReply findItems(
        @WebParam(name = "request", targetNamespace = "http://topmotive.eu/TMConnect")
        FindItemsRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.sagag.services.stakis.erp.wsdl.tmconnect.GetItemsCollectionReply
     */
    @WebMethod(operationName = "GetItemsCollections", action = "http://topmotive.eu/TMConnect/ITMConnectContract/GetItemsCollections")
    @WebResult(name = "GetItemsCollectionsResult", targetNamespace = "http://topmotive.eu/TMConnect")
    @RequestWrapper(localName = "GetItemsCollections", targetNamespace = "http://topmotive.eu/TMConnect", className = "com.sagag.services.stakis.erp.wsdl.tmconnect.GetItemsCollectionsRequestBody")
    @ResponseWrapper(localName = "GetItemsCollectionsResponse", targetNamespace = "http://topmotive.eu/TMConnect", className = "com.sagag.services.stakis.erp.wsdl.tmconnect.GetItemsCollectionsResponseBody")
    public GetItemsCollectionReply getItemsCollections(
        @WebParam(name = "request", targetNamespace = "http://topmotive.eu/TMConnect")
        GetItemsCollectionRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.sagag.services.stakis.erp.wsdl.tmconnect.GetNotificationReply
     */
    @WebMethod(operationName = "GetNotification", action = "http://topmotive.eu/TMConnect/ITMConnectContract/GetNotification")
    @WebResult(name = "GetNotificationResult", targetNamespace = "http://topmotive.eu/TMConnect")
    @RequestWrapper(localName = "GetNotification", targetNamespace = "http://topmotive.eu/TMConnect", className = "com.sagag.services.stakis.erp.wsdl.tmconnect.GetNotificationRequestBody")
    @ResponseWrapper(localName = "GetNotificationResponse", targetNamespace = "http://topmotive.eu/TMConnect", className = "com.sagag.services.stakis.erp.wsdl.tmconnect.GetNotificationResponseBody")
    public GetNotificationReply getNotification(
        @WebParam(name = "request", targetNamespace = "http://topmotive.eu/TMConnect")
        GetNotificationRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.sagag.services.stakis.erp.wsdl.tmconnect.GetAccountInformationReply
     */
    @WebMethod(operationName = "GetAccountData", action = "http://topmotive.eu/TMConnect/ITMConnectContract/GetAccountData")
    @WebResult(name = "GetAccountDataResult", targetNamespace = "http://topmotive.eu/TMConnect")
    @RequestWrapper(localName = "GetAccountData", targetNamespace = "http://topmotive.eu/TMConnect", className = "com.sagag.services.stakis.erp.wsdl.tmconnect.GetAccountDataRequestBody")
    @ResponseWrapper(localName = "GetAccountDataResponse", targetNamespace = "http://topmotive.eu/TMConnect", className = "com.sagag.services.stakis.erp.wsdl.tmconnect.GetAccountDataResponseBody")
    public GetAccountInformationReply getAccountData(
        @WebParam(name = "request", targetNamespace = "http://topmotive.eu/TMConnect")
        BaseRequest request);

}
