
package com.sagag.services.stakis.erp.wsdl.tmconnect;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TMConnect", targetNamespace = "http://tempuri.org/", wsdlLocation = "file:/C:/dev/soap/SOAP_UI_STAKIS/TmConnect.wsdl")
public class TMConnect
    extends Service
{

    private final static URL TMCONNECT_WSDL_LOCATION;
    private final static WebServiceException TMCONNECT_EXCEPTION;
    private final static QName TMCONNECT_QNAME = new QName("http://tempuri.org/", "TMConnect");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/dev/soap/SOAP_UI_STAKIS/TmConnect.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TMCONNECT_WSDL_LOCATION = url;
        TMCONNECT_EXCEPTION = e;
    }

    public TMConnect() {
        super(__getWsdlLocation(), TMCONNECT_QNAME);
    }

    public TMConnect(WebServiceFeature... features) {
        super(__getWsdlLocation(), TMCONNECT_QNAME, features);
    }

    public TMConnect(URL wsdlLocation) {
        super(wsdlLocation, TMCONNECT_QNAME);
    }

    public TMConnect(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TMCONNECT_QNAME, features);
    }

    public TMConnect(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TMConnect(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ITMConnectContract
     */
    @WebEndpoint(name = "BasicHttpBinding_dvse")
    public ITMConnectContract getBasicHttpBindingDvse() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_dvse"), ITMConnectContract.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ITMConnectContract
     */
    @WebEndpoint(name = "BasicHttpBinding_dvse")
    public ITMConnectContract getBasicHttpBindingDvse(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_dvse"), ITMConnectContract.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TMCONNECT_EXCEPTION!= null) {
            throw TMCONNECT_EXCEPTION;
        }
        return TMCONNECT_WSDL_LOCATION;
    }

}
