-- Init data for WORKING_DAY table
INSERT INTO [dbo].[WORKING_DAY] (CODE) VALUES ('WORKING_DAY');
INSERT INTO [dbo].[WORKING_DAY] (CODE) VALUES ('NON_WORKING_DAY');
INSERT INTO [dbo].[WORKING_DAY] (CODE) VALUES ('PUBLIC_HOLIDAY');