endpoints.jmx.domain: restatax

server:
  port: 9001
  sessionTimeout: 30
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %X{User} %X{requestID} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.springframework: INFO
    com.sagag.services: DEBUG
    org.hibernate.SQL: INFO
#Log for elasticsearch
    org.elasticsearch.index.search.slowlog.query: INFO

# MSSQL database configuration
spring:
  profiles.active:
    ax-pre-https,
    incentive-dev,
    hp-normal-at,
    hpback-at-dev,
    gtmotive-at-dev,
    mdm-pre,
    oates-pre-ch,
    mail-dev,
    elasticsearch-dev,
    db-at,
    executor-pool,
    no-liquibase,
    country-at,
    no-proxy,
    thule-pre

---
#Authorization server to manage and verify tokens
sag:
  security:
    auth:
      # host: http://localhost:9002
      host: https://at.bbv-demo.ch/auth-server
      tokenUrl: /oauth/token
      checkTokenUrl: /oauth/check_token
      clientId: eshop-web
      clientSecret: eshop-web-yztAhGpFW

