
DECLARE @dd_at INT = (SELECT ID FROM ORGANISATION WHERE SHORTNAME='derendinger-at');
INSERT INTO ORGANISATION_SETTINGS(NAME,ORGANISATION_ID,SETTING_KEY,SETTING_VALUE) VALUES('Derendinger-Austria',@dd_at,'setting_locale','de_DE');

DECLARE @matik_at INT = (SELECT ID FROM ORGANISATION WHERE SHORTNAME='matik-at');
INSERT INTO ORGANISATION_SETTINGS(NAME,ORGANISATION_ID,SETTING_KEY,SETTING_VALUE) VALUES('Matik-Austria',@matik_at,'setting_locale','de_DE');
