INSERT INTO axtest.dbo.PAYMENT_METHOD (PAY_METHOD, DESC_CODE, DESCRIPTION) VALUES ('Rechnung', 'CREDIT', 'Rechnung');
INSERT INTO axtest.dbo.PAYMENT_METHOD (PAY_METHOD, DESC_CODE, DESCRIPTION) VALUES ('Barzahlung', 'CASH', 'Barzahlung');
INSERT INTO axtest.dbo.PAYMENT_METHOD (PAY_METHOD, DESC_CODE, DESCRIPTION) VALUES ('Kartenzahlung', 'CARD', 'Kartenzahlung');
INSERT INTO axtest.dbo.PAYMENT_METHOD (PAY_METHOD, DESC_CODE, DESCRIPTION) VALUES ('Sofortrechnung', 'DIRECT_INVOICE', 'Sofortrechnung');