INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('ABW', 'Aruba', 'Aruba', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('AFG', 'Afghanistan', 'Afghanistan', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('AGO', 'Angola', 'Angola', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('AIA', 'Anguilla', 'Anguilla', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('ALA', 'Åland Islands', 'Åland Islands', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('ALB', 'Albania', 'Albania', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('AND', 'Andorra', 'Andorra', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('ANT', 'Netherlands Antilles', 'Netherlands Antilles', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('ARE', 'United Arab Emirates', 'United Arab Emirates', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('ARG', 'Argentina', 'Argentina', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('ARM', 'Armenia', 'Armenia', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('ASM', 'American Samoa', 'American Samoa', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('ATA', 'Antarctica', 'Antarctica', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('ATF', 'French Southern and Antarctic Lands', 'French Southern and Antarctic Lands', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('ATG', 'Antigua and Barbuda', 'Antigua and Barbuda', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('AUS', 'Australia', 'Australia', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('AUT', 'Austria', 'Austria', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('AZE', 'Azerbaijan', 'Azerbaijan', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('BDI', 'Burundi', 'Burundi', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('BEL', 'Belgium', 'Belgium', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('BEN', 'Benin', 'Benin', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('BFA', 'Burkina Faso', 'Burkina Faso', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('BGD', 'Bangladesh', 'Bangladesh', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('BGR', 'Bulgaria', 'Bulgaria', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('BHR', 'Bahrain', 'Bahrain', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('BHS', 'Bahamas', 'Bahamas', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('BIH', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('BLM', 'Saint Barthélemy', 'Saint Barthélemy', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('BLR', 'Belarus', 'Belarus', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('BLZ', 'Belize', 'Belize', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('BMU', 'Bermuda', 'Bermuda', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('BOL', 'Bolivia', 'Bolivia', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('BRA', 'Brazil', 'Brazil', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('BRB', 'Barbados', 'Barbados', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('BRN', 'Brunei', 'Brunei', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('BTN', 'Bhutan', 'Bhutan', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('BVT', 'Bouvet Island', 'Bouvet Island', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('BWA', 'Botswana', 'Botswana', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('CAF', 'Central African Republic', 'Central African Republic', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('CAN', 'Canada', 'Canada', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('CCK', 'Cocos (Keeling) Islands', 'Cocos (Keeling) Islands', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('CHE', 'Switzerland', 'Switzerland', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('CHL', 'Chile', 'Chile', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('CHN', 'China', 'China', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('CIV', 'Côte d’Ivoire', 'Côte d’Ivoire', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('CMR', 'Cameroon', 'Cameroon', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('COD', 'Congo (DRC)', 'Congo (DRC)', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('COG', 'Congo', 'Congo', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('COK', 'Cook Islands', 'Cook Islands', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('COL', 'Colombia', 'Colombia', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('COM', 'Comoros', 'Comoros', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('CPV', 'Cape Verde', 'Cape Verde', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('CRI', 'Costa Rica', 'Costa Rica', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('CUB', 'Cuba', 'Cuba', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('CXR', 'Christmas Island', 'Christmas Island', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('CYM', 'Cayman Islands', 'Cayman Islands', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('CYP', 'Cyprus', 'Cyprus', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('CZE', 'Czech Republic', 'Czech Republic', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('DEU', 'Germany', 'Germany', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('DJI', 'Djibouti', 'Djibouti', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('DMA', 'Dominica', 'Dominica', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('DNK', 'Denmark', 'Denmark', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('DOM', 'Dominican Republic', 'Dominican Republic', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('DZA', 'Algeria', 'Algeria', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('ECU', 'Ecuador', 'Ecuador', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('EGY', 'Egypt', 'Egypt', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('ERI', 'Eritrea', 'Eritrea', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('ESP', 'Spain', 'Spain', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('EST', 'Estonia', 'Estonia', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('ETH', 'Ethiopia', 'Ethiopia', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('FIN', 'Finland', 'Finland', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('FJI', 'Fiji', 'Fiji', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('FLK', 'Falkland Islands (Islas Malvinas)', 'Falkland Islands (Islas Malvinas)', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('FRA', 'France', 'France', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('FRO', 'Faroe Islands', 'Faroe Islands', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('FSM', 'Micronesia', 'Micronesia', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('GAB', 'Gabon', 'Gabon', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('GBR', 'United Kingdom', 'United Kingdom', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('GEO', 'Georgia', 'Georgia', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('GGY', 'Guernsey', 'Guernsey', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('GHA', 'Ghana', 'Ghana', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('GIB', 'Gibraltar', 'Gibraltar', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('GIN', 'Guinea', 'Guinea', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('GLP', 'Guadeloupe', 'Guadeloupe', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('GMB', 'Gambia', 'Gambia', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('GNB', 'Guinea-Bissau', 'Guinea-Bissau', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('GNQ', 'Equatorial Guinea', 'Equatorial Guinea', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('GRC', 'Greece', 'Greece', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('GRD', 'Grenada', 'Grenada', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('GRL', 'Greenland', 'Greenland', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('GTM', 'Guatemala', 'Guatemala', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('GUF', 'French Guiana', 'French Guiana', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('GUM', 'Guam', 'Guam', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('GUY', 'Guyana', 'Guyana', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('HKG', 'Hong Kong SAR', 'Hong Kong SAR', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('HMD', 'Heard Island and McDonald Islands', 'Heard Island and McDonald Islands', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('HND', 'Honduras', 'Honduras', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('HRV', 'Croatia', 'Croatia', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('HTI', 'Haiti', 'Haiti', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('HUN', 'Hungary', 'Hungary', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('IDN', 'Indonesia', 'Indonesia', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('IMN', 'Isle of Man', 'Isle of Man', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('IND', 'India', 'India', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('IOT', 'British Indian Ocean Territory', 'British Indian Ocean Territory', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('IRL', 'Ireland', 'Ireland', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('IRN', 'Iran', 'Iran', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('IRQ', 'Iraq', 'Iraq', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('ISL', 'Iceland', 'Iceland', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('ISR', 'Israel', 'Israel', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('ITA', 'Italy', 'Italy', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('JAM', 'Jamaica', 'Jamaica', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('JEY', 'Jersey', 'Jersey', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('JOR', 'Jordan', 'Jordan', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('JPN', 'Japan', 'Japan', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('KAZ', 'Kazakhstan', 'Kazakhstan', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('KEN', 'Kenya', 'Kenya', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('KGZ', 'Kyrgyzstan', 'Kyrgyzstan', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('KHM', 'Cambodia', 'Cambodia', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('KIR', 'Kiribati', 'Kiribati', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('KNA', 'Saint Kitts and Nevis', 'Saint Kitts and Nevis', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('KOR', 'Korea', 'Korea', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('KWT', 'Kuwait', 'Kuwait', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('LAO', 'Laos', 'Laos', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('LBN', 'Lebanon', 'Lebanon', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('LBR', 'Liberia', 'Liberia', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('LBY', 'Libya', 'Libya', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('LCA', 'Saint Lucia', 'Saint Lucia', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('LIE', 'Liechtenstein', 'Liechtenstein', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('LKA', 'Sri Lanka', 'Sri Lanka', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('LSO', 'Lesotho', 'Lesotho', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('LTU', 'Lithuania', 'Lithuania', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('LUX', 'Luxembourg', 'Luxembourg', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('LVA', 'Latvia', 'Latvia', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('MAC', 'Macao SAR', 'Macao SAR', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('MAF', 'Saint Martin', 'Saint Martin', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('MAR', 'Morocco', 'Morocco', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('MCO', 'Monaco', 'Monaco', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('MDA', 'Moldova', 'Moldova', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('MDG', 'Madagascar', 'Madagascar', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('MDV', 'Maldives', 'Maldives', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('MEX', 'Mexico', 'Mexico', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('MHL', 'Marshall Islands', 'Marshall Islands', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('MKD', 'Macedonia', 'Macedonia', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('MLI', 'Mali', 'Mali', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('MLT', 'Malta', 'Malta', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('MMR', 'Myanmar', 'Myanmar', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('MNE', 'Montenegro', 'Montenegro', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('MNG', 'Mongolia', 'Mongolia', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('MNP', 'Northern Mariana Islands', 'Northern Mariana Islands', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('MOZ', 'Mozambique', 'Mozambique', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('MRT', 'Mauritania', 'Mauritania', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('MSR', 'Montserrat', 'Montserrat', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('MTQ', 'Martinique', 'Martinique', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('MUS', 'Mauritius', 'Mauritius', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('MWI', 'Malawi', 'Malawi', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('MYS', 'Malaysia', 'Malaysia', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('MYT', 'Mayotte', 'Mayotte', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('NAM', 'Namibia', 'Namibia', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('NCL', 'New Caledonia', 'New Caledonia', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('NER', 'Niger', 'Niger', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('NFK', 'Norfolk Island', 'Norfolk Island', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('NGA', 'Nigeria', 'Nigeria', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('NIC', 'Nicaragua', 'Nicaragua', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('NIU', 'Niue', 'Niue', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('NLD', 'Netherlands', 'Netherlands', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('NOR', 'Norway', 'Norway', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('NPL', 'Nepal', 'Nepal', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('NRU', 'Nauru', 'Nauru', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('NZL', 'New Zealand', 'New Zealand', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('OMN', 'Oman', 'Oman', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('PAK', 'Pakistan', 'Pakistan', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('PAN', 'Panama', 'Panama', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('PCN', 'Pitcairn Islands', 'Pitcairn Islands', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('PER', 'Peru', 'Peru', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('PHL', 'Philippines', 'Philippines', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('PLW', 'Palau', 'Palau', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('PNG', 'Papua New Guinea', 'Papua New Guinea', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('POL', 'Poland', 'Poland', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('PRI', 'Puerto Rico', 'Puerto Rico', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('PRK', 'North Korea', 'North Korea', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('PRT', 'Portugal', 'Portugal', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('PRY', 'Paraguay', 'Paraguay', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('PSE', 'Palestinian Authority', 'Palestinian Authority', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('PYF', 'French Polynesia', 'French Polynesia', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('QAT', 'Qatar', 'Qatar', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('REU', 'Reunion', 'Reunion', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('ROU', 'Romania', 'Romania', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('RUS', 'Russia', 'Russia', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('RWA', 'Rwanda', 'Rwanda', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('SAU', 'Saudi Arabia', 'Saudi Arabia', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('SDN', 'Sudan', 'Sudan', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('SEN', 'Senegal', 'Senegal', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('SGP', 'Singapore', 'Singapore', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('SGS', 'South Georgia and the South Sandwich Islands', 'South Georgia and the South Sandwich Islands', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('SHN', 'Saint Helena', 'Saint Helena', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('SJM', 'Svalbard and Jan Mayen Island', 'Svalbard and Jan Mayen Island', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('SLB', 'Solomon Islands', 'Solomon Islands', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('SLE', 'Sierra Leone', 'Sierra Leone', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('SLV', 'El Salvador', 'El Salvador', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('SMR', 'San Marino', 'San Marino', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('SOM', 'Somalia', 'Somalia', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('SPM', 'Saint Pierre and Miquelon', 'Saint Pierre and Miquelon', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('SRB', 'Serbia', 'Serbia', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('STP', 'São Tomé and Príncipe', 'São Tomé and Príncipe', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('SUR', 'Suriname', 'Suriname', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('SVK', 'Slovakia', 'Slovakia', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('SVN', 'Slovenia', 'Slovenia', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('SWE', 'Sweden', 'Sweden', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('SWZ', 'Swaziland', 'Swaziland', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('SYC', 'Seychelles', 'Seychelles', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('SYR', 'Syria', 'Syria', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('TCA', 'Turks and Caicos Islands', 'Turks and Caicos Islands', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('TCD', 'Chad', 'Chad', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('TGO', 'Togo', 'Togo', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('THA', 'Thailand', 'Thailand', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('TJK', 'Tajikistan', 'Tajikistan', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('TKL', 'Tokelau', 'Tokelau', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('TKM', 'Turkmenistan', 'Turkmenistan', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('TLS', 'Timor-Leste', 'Timor-Leste', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('TON', 'Tonga', 'Tonga', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('TTO', 'Trinidad and Tobago', 'Trinidad and Tobago', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('TUN', 'Tunisia', 'Tunisia', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('TUR', 'Turkey', 'Turkey', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('TUV', 'Tuvalu', 'Tuvalu', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('TWN', 'Taiwan', 'Taiwan', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('TZA', 'Tanzania', 'Tanzania', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('UGA', 'Uganda', 'Uganda', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('UKR', 'Ukraine', 'Ukraine', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('UMI', 'U.S. Minor Outlying Islands', 'U.S. Minor Outlying Islands', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('URY', 'Uruguay', 'Uruguay', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('USA', 'United States', 'United States', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('UZB', 'Uzbekistan', 'Uzbekistan', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('VAT', 'Vatican City', 'Vatican City', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('VCT', 'Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('VEN', 'Venezuela', 'Venezuela', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('VGB', 'British Virgin Islands', 'British Virgin Islands', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('VIR', 'Virgin Islands', 'Virgin Islands', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('VNM', 'Vietnam', 'Vietnam', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('VUT', 'Vanuatu', 'Vanuatu', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('WLF', 'Wallis and Futuna', 'Wallis and Futuna', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('WSM', 'Samoa', 'Samoa', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('YEM', 'Yemen', 'Yemen', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('ZAF', 'South Africa', 'South Africa', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('ZMB', 'Zambia', 'Zambia', null, null);
INSERT INTO axtest.dbo.COUNTRY (CODE, SHORT_NAME, FULL_NAME, fullName, shortName) VALUES ('ZWE', 'Zimbabwe', 'Zimbabwe', null, null);