INSERT INTO axtest.dbo.LANGUAGES (LANGCODE, LANGISO, DESCRIPTION) VALUES ('LANG_DE', 'DE', 'German');
INSERT INTO axtest.dbo.LANGUAGES (LANGCODE, LANGISO, DESCRIPTION) VALUES ('LANG_FR', 'FR', 'French');
INSERT INTO axtest.dbo.LANGUAGES (LANGCODE, LANGISO, DESCRIPTION) VALUES ('LANG_IT', 'IT', 'Italian');