INSERT INTO axtest.dbo.PAYMENT_TYPE (CODE, DESCRIPTION) VALUES ('Bar', 'Barzahlung, petty cash');
INSERT INTO axtest.dbo.PAYMENT_TYPE (CODE, DESCRIPTION) VALUES ('Betreibung', 'Betreibung, operation');
INSERT INTO axtest.dbo.PAYMENT_TYPE (CODE, DESCRIPTION) VALUES ('Fin', 'Finanzierung, financing');
INSERT INTO axtest.dbo.PAYMENT_TYPE (CODE, DESCRIPTION) VALUES ('Karte', 'Kartenzahlung, card payment');
INSERT INTO axtest.dbo.PAYMENT_TYPE (CODE, DESCRIPTION) VALUES ('Keine', 'Keine, none');
INSERT INTO axtest.dbo.PAYMENT_TYPE (CODE, DESCRIPTION) VALUES ('Sak', 'Schuldanerkennung, acknowledgment of debt');
INSERT INTO axtest.dbo.PAYMENT_TYPE (CODE, DESCRIPTION) VALUES ('Selbstzahl', 'Selbstzahler, self-payer');
INSERT INTO axtest.dbo.PAYMENT_TYPE (CODE, DESCRIPTION) VALUES ('Sepa B Fin', 'Sepa B Finanzierung, financing');
INSERT INTO axtest.dbo.PAYMENT_TYPE (CODE, DESCRIPTION) VALUES ('Sepa B Sak', 'Sepa B Schuldanerkennung, acknowledgment of debt');
INSERT INTO axtest.dbo.PAYMENT_TYPE (CODE, DESCRIPTION) VALUES ('Sepa B2B', 'Sepa B2B');
INSERT INTO axtest.dbo.PAYMENT_TYPE (CODE, DESCRIPTION) VALUES ('Sepa C Fin', 'Sepa C Finanzierung, financing');
INSERT INTO axtest.dbo.PAYMENT_TYPE (CODE, DESCRIPTION) VALUES ('Sepa C Sak', 'Sepa C Schuldanerkennung, acknowledgment of debt');
INSERT INTO axtest.dbo.PAYMENT_TYPE (CODE, DESCRIPTION) VALUES ('Sepa Core', 'Sepa Core (inkl. Cor1)');
INSERT INTO axtest.dbo.PAYMENT_TYPE (CODE, DESCRIPTION) VALUES ('Sofort', 'Sofort fällige Rechnung, immediate due invoice');
INSERT INTO axtest.dbo.PAYMENT_TYPE (CODE, DESCRIPTION) VALUES ('Bar', 'Barzahlung, petty cash');
INSERT INTO axtest.dbo.PAYMENT_TYPE (CODE, DESCRIPTION) VALUES ('Betreibung', 'Betreibung, operation');
INSERT INTO axtest.dbo.PAYMENT_TYPE (CODE, DESCRIPTION) VALUES ('Fin', 'Finanzierung, financing');
INSERT INTO axtest.dbo.PAYMENT_TYPE (CODE, DESCRIPTION) VALUES ('Karte', 'Kartenzahlung, card payment');
INSERT INTO axtest.dbo.PAYMENT_TYPE (CODE, DESCRIPTION) VALUES ('Keine', 'Keine, none');
INSERT INTO axtest.dbo.PAYMENT_TYPE (CODE, DESCRIPTION) VALUES ('Sak', 'Schuldanerkennung, acknowledgment of debt');
INSERT INTO axtest.dbo.PAYMENT_TYPE (CODE, DESCRIPTION) VALUES ('Selbstzahl', 'Selbstzahler, self-payer');
INSERT INTO axtest.dbo.PAYMENT_TYPE (CODE, DESCRIPTION) VALUES ('Sepa B Fin', 'Sepa B Finanzierung, financing');
INSERT INTO axtest.dbo.PAYMENT_TYPE (CODE, DESCRIPTION) VALUES ('Sepa B Sak', 'Sepa B Schuldanerkennung, acknowledgment of debt');
INSERT INTO axtest.dbo.PAYMENT_TYPE (CODE, DESCRIPTION) VALUES ('Sepa B2B', 'Sepa B2B');
INSERT INTO axtest.dbo.PAYMENT_TYPE (CODE, DESCRIPTION) VALUES ('Sepa C Fin', 'Sepa C Finanzierung, financing');
INSERT INTO axtest.dbo.PAYMENT_TYPE (CODE, DESCRIPTION) VALUES ('Sepa C Sak', 'Sepa C Schuldanerkennung, acknowledgment of debt');
INSERT INTO axtest.dbo.PAYMENT_TYPE (CODE, DESCRIPTION) VALUES ('Sepa Core', 'Sepa Core (inkl. Cor1)');
INSERT INTO axtest.dbo.PAYMENT_TYPE (CODE, DESCRIPTION) VALUES ('Sofort', 'Sofort fällige Rechnung, immediate due invoice');