INSERT INTO axtest.dbo.GROUP_PERMISSION (GROUP_ID, PERM_ID, ALLOWED) VALUES (16, 16, 1);
INSERT INTO axtest.dbo.GROUP_PERMISSION (GROUP_ID, PERM_ID, ALLOWED) VALUES (27, 16, 1);
INSERT INTO axtest.dbo.GROUP_PERMISSION (GROUP_ID, PERM_ID, ALLOWED) VALUES (28, 16, 1);