INSERT INTO axtest.dbo.ADDRESS_TYPE (TYPE, DESCRIPTION) VALUES ('DEFAULT', 'DEFAULT');
INSERT INTO axtest.dbo.ADDRESS_TYPE (TYPE, DESCRIPTION) VALUES ('OFFICE', 'Office');
INSERT INTO axtest.dbo.ADDRESS_TYPE (TYPE, DESCRIPTION) VALUES ('BRANCH', 'Branch');
INSERT INTO axtest.dbo.ADDRESS_TYPE (TYPE, DESCRIPTION) VALUES ('SHOWROOM', 'Showroom');
INSERT INTO axtest.dbo.ADDRESS_TYPE (TYPE, DESCRIPTION) VALUES ('GARAGE', 'Garage');