CREATE TABLE [dbo].[RETURN_ORDER_REASON](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [CODE] [varchar](50) NOT NULL,
    [NAME] [varchar](255) NULL,
    [AX_CODE] [varchar](50) NOT NULL,
    [IS_DEFAULT] [bit] NOT NULL DEFAULT 0
 CONSTRAINT [PK_RETURN_ORDER_REASON] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
