-- Master data for VIN-license
INSERT INTO [dbo].[RETURN_ORDER_REASON] (CODE, NAME, AX_CODE, IS_DEFAULT)
VALUES ('DEFECT', 'Defect', '1', 0);

INSERT INTO [dbo].[RETURN_ORDER_REASON] (CODE, NAME, AX_CODE, IS_DEFAULT)
VALUES ('INCORRECT_FEED_LINE', 'Incorrect Feed Line', '2', 0);

INSERT INTO [dbo].[RETURN_ORDER_REASON] (CODE, NAME, AX_CODE, IS_DEFAULT)
VALUES ('FALSE_ARTICLE', 'False Article', '3', 0);

INSERT INTO [dbo].[RETURN_ORDER_REASON] (CODE, NAME, AX_CODE, IS_DEFAULT)
VALUES ('WRONG_AMOUNT', 'Wrong Amount', '4', 0);

INSERT INTO [dbo].[RETURN_ORDER_REASON] (CODE, NAME, AX_CODE, IS_DEFAULT)
VALUES ('SELECTION', 'Selection', '5', 0);

INSERT INTO [dbo].[RETURN_ORDER_REASON] (CODE, NAME, AX_CODE, IS_DEFAULT)
VALUES ('NOT_USED', 'Not Used', '6', 1);

INSERT INTO [dbo].[RETURN_ORDER_REASON] (CODE, NAME, AX_CODE, IS_DEFAULT)
VALUES ('SUPPLIER_CALLBACK', 'Supplier Callback', '7', 0);

INSERT INTO [dbo].[RETURN_ORDER_REASON] (CODE, NAME, AX_CODE, IS_DEFAULT)
VALUES ('ALTERNATIVE', 'Alternative', '8', 0);

INSERT INTO [dbo].[RETURN_ORDER_REASON] (CODE, NAME, AX_CODE, IS_DEFAULT)
VALUES ('AIS_RETOUR', 'AIS Retour', '9', 0);
