package com.sagag.services.common.enums;

public enum SalutationEnum {
  SALUTATION_MR, 
  SALUTATION_MRS,
  SALUTATION_MS,
  SALUTATION_DR,
  SALUTATION_PROF,
  SALUTATION_SIR,
  SALUTATION_MADAM,
  SALUTATION_OTHER,
  GENERAL_SALUTATION_COMPANY,
  GENERAL_SALUTATION_MALE,
  GENERAL_SALUTATION_FEMALE;
}
