ALTER TABLE AAD_ACCOUNTS ALTER COLUMN PERSONAL_NUMBER [varchar](255) NULL;
ALTER TABLE AAD_ACCOUNTS ADD CREATED_DATE datetime NULL;
ALTER TABLE AAD_ACCOUNTS ADD DEFAULT (getdate()) FOR [CREATED_DATE];
